import type { ChallengeDay } from "./types";

export const challengeDataEN: ChallengeDay[] = [
  {
    day: 0,
    title: "This is not just an AI challenge. This is an upgrade to how you work.",
    subject: "It starts today. Here is how the challenge works.",
    preheader: "28 days, 5–7 minutes a day. One real shift in how you work.",
    concept: [
      "AI is everywhere right now. New tools, new features, new promises. And that is exactly why it is easy to end up just trying more and more things – without your work actually changing.",
      "This challenge was created to help you do the opposite.",
      "The goal is not to learn as many AI tools as possible. The goal is to start using AI practically, regularly, and in a way that genuinely makes your work easier. This is the AI-first mindset: the way you think matters more than any specific tool.",
      "Each day should take about 5–7 minutes. Each day, you should take away something useful:",
      ["a new perspective on your work", "one small practical step", "a concrete output or a simple improvement to something you already do"],
      "Step by step, you are not just \"playing with AI.\" You are building your own way of working – AI Adoption in practice. It operates on three levels: Mindset, Tools, and Superpowers. And that is exactly the order we will follow in this challenge.",
      "Here is the structure: the first seven days are about the way you think and fundamental approaches. Then we add systems for storing knowledge, your digital environment, and project work. At the end, we look at five superpowers that AI collaboration brings you.",
      "One more important thing: when you come across something you already know, that is fine. Actually, great. Every challenge can be deepened – adjust the prompt, improve the template, build it into real work.",
      "The point of this challenge is not to complete everything. The point is to move a little further every day. A little is enough. Five minutes. One idea. One step. That is what real change is made of.",
    ],
    taskIntro: "Write down 3 things you do repeatedly by hand in your work or daily routine. They do not have to be big things. Small recurring tasks are enough. We will come back to them throughout the challenge.",
    taskItems: [],
    taskType: "text",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "You are not paid for work – you are paid for outcomes. And that changes everything about how you work with AI.",
  },
  {
    day: 1,
    title: "You are not paid for work. You are paid for outcomes.",
    subject: "You are not paid for work. You are paid for outcomes.",
    preheader: "One shift in thinking that changes everything else.",
    concept: [
      "When work piles up, most people automatically focus on one thing: how to get everything done.",
      "But this is exactly where the difference between normal work mode and AI-first thinking starts to show.",
      "The point is not just to do things faster. First, you need to pause and ask yourself what outcome you are actually trying to achieve.",
      "You are not always paid for:",
      ["writing the email", "preparing the presentation", "creating the document", "or spending an hour doing research"],
      "You are paid for:",
      ["someone getting the right information", "a decision getting made", "a project moving forward", "or something being prepared clearly and effectively"],
      "And that is a big difference. As soon as you start thinking more about the outcome than about the task itself, it becomes much easier to see what can be simplified, what to hand to AI, what does not need to start from scratch – or what maybe does not need to be done at all.",
      "This is the foundation of the Leverage approach. Leverage does not mean doing more. It means doing the right things – and bringing AI in where it adds value, not just where it adds speed.",
      "Do not just ask: How do I do this? Ask first: What am I actually trying to achieve? This difference – activity vs. outcome – is the key. Without this shift, AI becomes just another tool for doing things faster. With this shift, it becomes a tool for doing the right things.",
    ],
    taskIntro: "Pick one task you are working on today and write down two things:",
    taskItems: ["How the task sounds right now", "What outcome you actually want from it"],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Anything you do for the second time should not start from scratch. The OHIO principle – and how it saves you energy.",
  },
  {
    day: 2,
    title: "Anything you do for the second time should not start from scratch.",
    subject: "If you are doing it twice, stop starting from scratch.",
    preheader: "Repetition is a signal – not a challenge to work faster, but to build a template.",
    concept: [
      "A lot of work does not look difficult at first. But small repeated tasks often drain the most energy.",
      "When something repeats, it is a signal. Not a signal that you need to work faster. A signal that the task should have a template, a process, a prompt, or at least a better starting point.",
      "This is where the OHIO principle comes in: Only Handle It Once. If you are doing something for the second time, set it up properly right now – a template, a prompt, a structure – and next time you start from a baseline, not from zero.",
      "There are three types of repeating work where OHIO makes the most sense:",
      ["Documents – reports, proposals, briefs, notes, summaries", "Communication – follow-ups, confirmations, replies to frequent questions, intro emails", "Decisions – recurring choices where you always weigh the same criteria"],
      "AI is strongest exactly where work repeats. Not because it will do everything perfectly. But because it helps you stop starting over every single time.",
      "A concrete prompt for creating a template works like this: Create a template for [document type]. The template should contain: [sections]. Output in [format]. Try it now on one of your recurring documents.",
      "The point of today is not to design a perfect system. The point is to find one recurring thing and take the first step toward making it easier next time.",
    ],
    taskIntro: "Choose one recurring task and write a template-creation prompt in this format:",
    taskItems: [
      "Create a template for [add the document or message type]",
      "The template should contain these sections: [add sections that always repeat]",
      "Output in format [add – list, table, paragraphs...]",
    ],
    taskType: "ul",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "AI is not just a search engine. It is a collaborator – and the key is the quality of your brief.",
  },
  {
    day: 3,
    title: "Quality of brief = quality of output.",
    subject: "Stop using AI as a search engine.",
    preheader: "The real shift comes when you stop asking AI and start assigning it work.",
    concept: [
      "Most people still use AI like a slightly smarter search engine. They ask something, get an answer, and that is where it ends.",
      "But the real shift begins when you stop treating AI like a place where you type something in and start treating it like someone you assign work to.",
      "This is the foundation of symbiosis with AI: you set the direction – what should be done, for whom, in what context – and AI helps with execution. The result depends directly on how clear the brief is.",
      "The key principle: quality of brief = quality of output. This equation is absolute. A vague question = vague output. A specific brief with context = a usable result.",
      "A good brief has four parts that AI really needs to know:",
      ["Who to be – what role or expertise to take in this brief (experienced salesperson, coach, analyst...)", "What exactly to do – write, summarize, analyze, suggest, rewrite...", "What it needs to know – context about the situation, product, target audience, tone and constraints", "What the result should look like – length, format, tone, structure"],
      "Example of the difference in practice. Vague prompt: Write me an email. Specific brief: You are an experienced business communicator. Write a follow-up email to a client who saw a proposal for HR software but did not reply. The goal is to get a meeting. Tone is friendly and direct, maximum 5 sentences.",
      "This is the change that most affects output quality. And it is a change you can make right now – without learning any new tools.",
      "Take one prompt from today's work and add all four parts to it. You will see the difference in quality immediately.",
    ],
    taskIntro: "Take one specific prompt you wrote earlier or plan to write today, and rework it so it contains all four parts of a good brief:",
    taskItems: [
      "Who AI should be – write the role (example: You are an experienced project manager with a background in IT projects)",
      "What exactly it should do – specific task (example: Write a concise status summary for the client)",
      "What it needs to know – context (example: The project is 2 weeks behind, the client does not yet know why)",
      "What the result should look like – format and scope (example: Max 5 sentences, professional tone, no technical jargon)",
    ],
    taskType: "ul",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "The Prompt Generator approach: ask for the key details first, then create. This changes output quality completely.",
  },
  {
    day: 4,
    title: "Ask first. Then create.",
    subject: "Your prompt is too vague. Here is how to fix it.",
    preheader: "Prompt Generator approach: AI fills in context first, then creates.",
    concept: [
      "A lot of people feel that being good at AI means knowing secret formulas or complicated tricks. In reality, one much simpler thing often matters more: give AI space to fill in context first – and then create.",
      "This is called the Prompt Generator approach. Instead of jumping straight to the final prompt, you tell AI: ask me the key details you need to know, and then create the result.",
      "Why does it work? Because AI has no intuition or experience with you and your situation. Asking questions replaces what an experienced colleague would learn through an informal conversation.",
      "A good prompt generally has five components:",
      [
        "Role – who AI should be (expert, coach, copywriter, analyst...)",
        "Goal – what it should exactly do (write, analyze, rewrite, suggest, summarize)",
        "Context – what it needs to know about the project, situation, target audience, or requirements",
        "Constraints – what it should not do, how it should write, what the maximum scope is",
        "Output format – paragraphs, numbered list, table, headings, short text",
      ],
      "And there is one more approach that works brilliantly – add this sentence at the end of your prompt: Before you begin, ask me 3 clarifying questions that will improve the result. AI will ask for what it is missing. And by answering, you give it better context. The result will be noticeably better.",
      "An example of a full prompt: You are an experienced marketing strategist. You will write 3 variants of a subject line for an email announcing a new feature in a productivity app. The target audience is project managers in companies with 50+ people. The tone is friendly and direct, no corporate phrases. Each variant max 8 words. Before you begin, ask me 3 clarifying questions.",
      "The most important thing is to start. Take one old prompt – one where the output was not ideal – and apply the five components plus the clarifying questions sentence. You will see the difference immediately.",
    ],
    taskIntro: "Take one prompt where the output was not ideal and rewrite it with the five components. Then add the sentence: Before you begin, ask me 3 clarifying questions that will improve the result.",
    taskItems: [
      "Role – who AI should be",
      "Goal – what exactly it should do",
      "Context – what it needs to know",
      "Constraints – what it should not do or how to limit the scope",
      "Output format – what the result should look like",
    ],
    taskType: "ul",
    taskPrompt: `Before you begin, ask me 3 clarifying questions that will improve the result.`,
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "The most important question is not: how do I do this faster? It is: does this need to be done manually at all?",
  },
  {
    day: 5,
    title: "Do not optimize speed. Optimize leverage.",
    subject: "Forget speed. Optimize this instead.",
    preheader: "Leverage matrix: what only you can do, what is better with AI, what AI can mostly handle.",
    concept: [
      "The most important question is not: How can I do this faster? It is: Does this need to be done manually?",
      "Leverage means thinking about what should stay with you, where AI should help, and what should not pass through manually from beginning to end.",
      "There is a simple Leverage matrix that helps sort work into three groups:",
      [
        "Only me – work that requires your experience, relationships, values, creativity, or decision-making authority",
        "Me + AI – collaboration where you set the direction, context, and priorities, and AI helps with execution",
        "Mostly AI – repetitive or predictable tasks that AI can handle with minimal oversight",
      ],
      "Examples for each category: Only me includes leading people, strategic decisions, personal client relationships, or ethical judgements. Me + AI includes writing reports, preparing presentations, analyzing data, or research. Mostly AI includes formatting, summarizing, transcriptions, recurring emails, or generating variants.",
      "The key question that will change how you see your work: Do I need to do this myself, or do I just need to make sure it gets done?",
      "This is not about laziness. It is about being smarter about where attention is invested. The most valuable thing you have is focused time – and that is worth saving for work where it truly matters who is doing it.",
      "When you look at your day through this lens, you see it differently. You see where the real added value is – and where you are just spending energy on things that someone or something else could handle.",
    ],
    taskIntro: "Take your task list for today or tomorrow and sort each task into one of the three groups from the Leverage matrix:",
    taskItems: [
      "Only me – I need to be personally here, cannot be delegated even to AI (write at least 2 examples)",
      "Me + AI – I set the direction and context, AI helps with execution (write at least 2 examples)",
      "Mostly AI – predictable, AI can handle it with minimal oversight (write at least 2 examples)",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Why perfection kills automation – and how a first version changes everything.",
  },
  {
    day: 6,
    title: "V1 is always better than no version.",
    subject: "Perfection is slowing you down. Let's fix that today.",
    preheader: "You do not need a perfect system. You need a first usable version.",
    concept: [
      "Waiting for the perfect moment is one of the most common reasons why automation never actually gets started in practice.",
      "There is always something slightly unfinished. It could always be done better. There is always one more step, one template, one tool missing. And so nothing begins.",
      "The key principle that changes this: V1 > 0. The first version is always better than no version. This equation is the foundation of iteration with AI.",
      "How to iterate with AI: you do not need to start with a perfect brief. Just start like this:",
      [
        "Write a draft – tell AI the intention and let it write the first version, even if it is not perfect",
        "Let AI improve – give it specific feedback: what is too long, what is missing, what to change in tone",
        "Edit – add your perspective, experience, or context that AI does not have",
        "Finalize – quick review, small adjustments, done",
      ],
      "Concrete workflow for creating a template for a recurring document: Step 1 – give AI one example of a document you wrote manually. Step 2 – ask it to extract the structure and variable parts. Step 3 – let it create a template with blank spaces to fill in. Step 4 – test the template on the next document.",
      "This whole process takes less than 15 minutes. And the result is a template that exists – not a perfect template that has not been created yet.",
      "Maybe it will just be a simple template, one saved prompt, a short outline, a basic process, or a working version of something you will improve over time.",
      "The goal is not to have everything perfect today. The goal is to make sure tomorrow something does not have to be created from scratch again. Start small. Improve over time. That is how it works.",
    ],
    taskIntro: "Choose one recurring thing – a document, email, or process – and go through today's 4-step iteration workflow:",
    taskItems: [
      "Tell AI the intention and let it write the first version (do not edit anything yet)",
      "Give AI specific feedback: what to improve, what to shorten, what to change",
      "Add your context or perspective that AI cannot know",
      "Save the result as a template or reusable base for next time",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Today you will build your first mini workflow – a simple system where the steps connect.",
  },
  {
    day: 7,
    title: "Your first mini AI workflow.",
    subject: "Today you will build your first mini AI system.",
    preheader: "3 steps, one output, zero chaos. This is how it works.",
    concept: [
      "AI is strongest when it becomes part of a small workflow – not just a one-off tool.",
      "A mini AI workflow is not complicated. It is a chain of 2–3 steps where each step follows from the previous one and AI helps with at least one of them.",
      "Three examples of working mini AI workflows:",
      [
        "Call notes → AI summary → follow-up email: Write rough notes, let AI create a structured summary with action items, from that generate a follow-up email for the client",
        "Idea → outline → draft: Write a 2–3 sentence intention, let AI create an outline with main points, from the outline let AI write the first draft",
        "Briefing → assignment → follow-up: Paste a client briefing or assignment, let AI extract key requirements and questions, from that create a structured assignment for the team",
      ],
      "Each of these chains replaces 20–40 minutes of manual work. And once you set it up, it keeps working.",
      "The key is that you are not thinking about individual steps separately. You are thinking about the whole flow: what is the input, what does AI do with it, what is the output. That is a different way of thinking about work – the foundation of symbiosis with AI, where you set the direction and AI helps with execution.",
      "You do not have to start complex. Even a three-step chain that saves five minutes a day has big value over a month – that is over 2 hours back every month.",
      "Choose one chain that makes sense for your work and write it down. Input, what AI does, output. Three steps. Try it once.",
    ],
    taskIntro: "Choose one activity with at least 2–3 connected steps and describe your first mini AI workflow:",
    taskItems: [
      "What the input is – what you receive or what is the starting material",
      "What AI does with it – what you assign it and what it should prepare",
      "What the final output is – what you send, save, or pass on",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "There are 5 levels of AI tools – and most people stay at the first. Let's look at what is beyond it.",
  },
  {
    day: 8,
    title: "5 levels of AI tools – where are you?",
    subject: "Chatbots are just the beginning. Here is what comes next.",
    preheader: "From chatbots to agents: 5 levels of AI tools and where to start.",
    concept: [
      "Most people know AI as a chatbot. But a chatbot is just the first of five levels on which AI tools operate.",
      "Each level delivers a different type of value – and each requires a different approach, different briefs, and a different level of oversight.",
      "5 levels of AI tools:",
      [
        "Chatbots – conversational AI where you write a prompt and get a response. Examples: ChatGPT, Claude, Gemini. Value: quick answers, brainstorming, first drafts.",
        "Assistants – AI set up for a specific role, tone, or knowledge base. Has instructions, style, and context. Value: more consistent outputs, less repeating context.",
        "Scripts – automated sequences of steps without code. Templates in AI, fixed workflows. Value: repeatability without manual input.",
        "Automation – connecting tools where AI is part of the flow (e.g. Zapier, Make). Input triggers an action, AI processes it, output moves on. Value: work happens without active involvement.",
        "Agents – AI that independently plans steps, calls tools, and completes complex tasks. Value: highest leverage, but requires setup and oversight.",
      ],
      "Where to start? Most added value hides at levels 1–3. Agents are powerful but complex – and their time comes once the foundations are solid.",
      "The most important question of the day: At which level are you working most often right now? And what would be a natural next step?",
      "You do not have to jump straight to level 5. But it is good to know what exists – and understand what each level is for.",
    ],
    taskIntro: "Go through the 5 levels of AI tools and for each one write an example from your own work or an idea where that level would make sense:",
    taskItems: [
      "Chatbot – where you use it now or where it would help",
      "Assistant – for what role or situation would it make sense to have your own assistant",
      "Scripts / templates – what could be automated as a repeating sequence",
      "Automation – where information is repeatedly retyped or forwarded manually",
      "Agents – where it would make sense to let AI solve a complex task independently (even just as an idea)",
    ],
    taskType: "ul",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "AI speaks your language – if you teach it. Tomorrow you will set up your own Tone of Voice.",
  },
  {
    day: 9,
    title: "AI speaks your language – if you teach it.",
    subject: "How to set AI to your style.",
    preheader: "Tone of Voice: how to stop AI from writing generically and start writing like you.",
    concept: [
      "AI outputs have one common weakness: at first they sound generic. Accurate, but without personality. Correct, but without tone.",
      "The solution is to set your Tone of Voice for AI – your communication style, which AI then reflects in its outputs.",
      "Tone of Voice is not just formality or informality. It is a combination of several things:",
      ["How you speak to people – friendly, direct, expert, conversational", "What must not appear in outputs – corporate phrases, clichés, empty adjectives", "What words or turns of phrase are typically yours", "What length and structure you prefer"],
      "How to teach AI your style: the simplest way is to give it a sample text you wrote yourself. It could be an email, a LinkedIn post, a message to a colleague, or a piece of a document. Then say: Analyze my writing style and describe it to me. What is typical about my style? Then for the next brief, say: Write in the style you analyzed.",
      "Prompt for setting up Tone of Voice: Here is a sample text I wrote: [paste text]. Analyze my style: 1) How I write – tone, rhythm, sentence length. 2) What is typical about my style. 3) What is not in my style – phrases or expressions I do not use. Save this style and use it for future tasks.",
      "Once AI knows your style, outputs will stop sounding generic. They will be closer to what you would write yourself – just faster.",
      "This setup is worth doing properly once. Then add it as part of prompts wherever tone matters – emails, LinkedIn, customer-facing texts.",
    ],
    taskIntro: "Write your first Tone of Voice prompt. Here is how:",
    taskItems: [
      "Take one text you wrote that feels typical of your style",
      "Paste it into AI with the style analysis prompt from today",
      "Let AI describe your style – what is typical, what is not there, what is the tone",
      "Save the resulting description as a base for future prompts",
    ],
    taskType: "ol",
    taskPrompt: `Here is a sample text I wrote: [paste text]

Analyze my writing style:
1) How I write – tone, rhythm, sentence length
2) What is typical about my style
3) What is not in my style – phrases or expressions I do not use

Save this style and use it for future tasks.`,
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "The second brain – why you need a knowledge system and what it is all for.",
  },
  {
    day: 10,
    title: "The second brain: why you need a knowledge system.",
    subject: "Why AI will help you more when you have a second brain.",
    preheader: "A second brain is not an app. It is a system – and AI can significantly strengthen it.",
    concept: [
      "Information pours in from all directions today. Articles, notes, emails, ideas, feedback, sources. And most of it disappears before we can process it.",
      "A second brain is a knowledge storage system – an external system where thoughts, materials, and insights are captured so they remain usable a week, a month, or a year later.",
      "Why does it work with AI? Because AI is strongest when it has something to process. The more stored materials, context, and background, the more precise and relevant AI's outputs become.",
      "A second brain serves three functions:",
      ["Captures – thoughts, sources, feedback, and decisions are not lost", "Processes – raw material is turned into usable knowledge", "Connects – older insights are linked to new context and work"],
      "Without a system, information piles up and is not available at the right moment. With a second brain, it becomes an asset – something that can be pulled out, added to, or passed to AI at any time.",
      "A second brain does not have to be complex. One place where you regularly save what is worth keeping is enough – even if it is just one document or folder.",
      "Over the next three days we will go through the concrete 3C framework – Capture, Clean, Connect – which gives the second brain structure and works brilliantly alongside AI.",
    ],
    taskIntro: "Think about where you currently store information and knowledge. Write down your answers to these questions:",
    taskItems: [
      "Where do you currently capture ideas, notes, and sources (nowhere, in your head, an app, a notebook...)",
      "What gets lost most often – what type of information or context would you need to have on hand",
      "What one place would make sense as the foundation of your second brain",
    ],
    taskType: "ul",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Capture: the first step toward a second brain – how to capture information so it does not get lost.",
  },
  {
    day: 11,
    title: "3C framework: Capture – catch what is worth keeping.",
    subject: "How to capture information so it does not get lost.",
    preheader: "Capture is the first step of the 3C framework. This is the foundation of the second brain.",
    concept: [
      "Capture is the first step of the 3C framework – Capture, Clean, Connect. The idea is to catch information the moment it arrives, without unnecessary sorting or editing.",
      "The biggest mistake when building a second brain is waiting for the right moment. The right moment never comes. Only one thing works: capture immediately.",
      "What is worth capturing? Four basic types:",
      ["Ideas – what occurred to you, what could be improved, what you want to try", "Sources – an article, video, podcast, quote that you want to use or return to", "Decisions and context – what was decided, why, and under what conditions", "Feedback – what customers and colleagues say, what worked and what did not"],
      "How to capture: the simplest system is one inbox – one place where everything goes without sorting. It can be an app, a document, or a notebook. The important thing is not where, but that it gets captured.",
      "AI helps in the Capture phase by being able to process even rough, unstructured input. Just write: Here are my rough notes: [paste]. Pull out the key thoughts and give them structure.",
      "Good capturing saves a lot of work during processing. Information that is in the system even in raw form is always better than perfect information that has disappeared.",
      "Today, do not focus on how to sort information. Just focus on whether it gets captured. Clean and Connect come in the next two days.",
    ],
    taskIntro: "Set up your Capture system. Go through three steps:",
    taskItems: [
      "Choose one inbox location – where you will capture everything without sorting (app, document, folder)",
      "Capture at least 3 things today – ideas, sources, or notes that would otherwise disappear",
      "Try throwing one set of rough notes into AI and letting it pull out the key thoughts",
    ],
    taskType: "ol",
    taskPrompt: `Here are my rough notes: [paste]

Please pull out:
1. Key thoughts (max 5 points)
2. What follows from this or what I should do
3. What I want to remember
4. Questions that arise from this`,
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Capturing is not enough. How to turn raw material into usable knowledge – that is Clean.",
  },
  {
    day: 12,
    title: "3C framework: Clean – process what you captured.",
    subject: "Capturing is not enough. How to turn raw material into knowledge.",
    preheader: "Clean is the second step of the 3C framework. This is where information becomes knowledge.",
    concept: [
      "Capture without Clean is just a pile of notes. Clean is the step that turns raw material into usable knowledge.",
      "Clean does not mean perfect or exhaustive processing. It means sufficient – such that the information is usable at the right moment.",
      "Three levels of Clean processing:",
      ["Minimal – read, mark what is important, add a short comment about what it means", "Medium – summarize key ideas, remove what is unnecessary, give it structure", "Deeper – connect with other material, draw conclusions, write your own perspective"],
      "AI is strongest in the Clean phase. From raw material it can quickly create a structured output – a summary, key points, action steps, or questions for further reflection.",
      "Working prompt for Clean: Here are my rough notes or material: [paste]. Process this as follows: 1) Main ideas in max 5 points. 2) What follows from this or what I should do. 3) What I want to remember. 4) Questions that arise from this.",
      "When to Clean? It is not enough to do Capture and hope that processing will happen on its own. Clean works best as a small routine – a short block once a day or week, going through the inbox and processing what is sitting there.",
      "An unprocessed inbox is just digital chaos. A processed second brain is an asset that grows with time.",
    ],
    taskIntro: "Take material you have captured in recent days and run it through the Clean process:",
    taskItems: [
      "Choose 2–3 items from your inbox or captured notes",
      "For each one, use the AI prompt for processing – let it pull out main ideas and what follows",
      "Save the result somewhere you will find it again (document, folder, app)",
    ],
    taskType: "ol",
    taskPrompt: `Here are my notes from a meeting or call:
[paste text]

Please create:
1. A short summary (3–5 sentences)
2. Key decisions made
3. Concrete next steps: who, what, by when
4. A short follow-up I can send to participants`,
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Connect: how to link knowledge so AI can truly work with your context.",
  },
  {
    day: 13,
    title: "3C framework: Connect – link knowledge to your work.",
    subject: "A second brain is complete only when you connect knowledge to your work.",
    preheader: "Connect is the third step of the 3C framework. This is where the second brain becomes an asset.",
    concept: [
      "Capture captures. Clean processes. Connect links – and that is what makes the second brain a real asset.",
      "Connect means linking knowledge to current work, projects, and decisions. Information that sits stored without connection has no added value. Information that connects at the right moment with what you are currently working on – that is a different category.",
      "How Connect works in practice:",
      ["When starting a project, review what you have saved on similar topics", "When writing a text, give AI context from previously captured sources or decisions", "When making a decision, pull up notes from past situations or feedback", "When preparing for a client, use summaries from past calls or materials"],
      "Connect with AI looks like this: give AI your processed material from the second brain as context – and then ask or assign work. AI then works with your context, not with general knowledge.",
      "Prompt for Connect: Here is context from my second brain on this topic: [paste processed material]. Use this context for: [specific task].",
      "In this way, the second brain becomes a productive partner for AI collaboration. Not only do you not lose information – you actively incorporate it into outputs.",
      "The 3C framework – Capture, Clean, Connect – is a system, not a one-time action. It works best when it becomes a routine: Capture continuously, Clean periodically, Connect at every relevant opportunity.",
    ],
    taskIntro: "Try today's Connect step in practice:",
    taskItems: [
      "Choose one current project or task you are working on",
      "Look through what you have in your second brain on a similar topic – notes, summaries, sources",
      "Paste relevant material into AI as context and give it a specific task with this context",
      "Compare the result with what AI would produce without this context",
    ],
    taskType: "ol",
    taskPrompt: `Here is context from my second brain on this topic:
[paste processed material]

On this basis please:
[paste your specific task or question]`,
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Halfway checkpoint – what you have, what you are building next, and how the second half of the challenge depends on it.",
  },
  {
    day: 14,
    title: "Halfway checkpoint: what you have and what you are building next.",
    subject: "Halfway through. What you are taking with you and what comes next.",
    preheader: "Day 14 of 28. Time to stop, assess, and set course for the second half.",
    concept: [
      "You are halfway. 14 days behind you, 14 days ahead. Time to stop and look at what you actually have.",
      "The first 14 days were about the fundamentals: AI-first mindset, Leverage matrix, OHIO principle, quality of brief, Prompt Generator approach, V1 and iteration, first workflow, 5 levels of AI tools, Tone of Voice, and the 3C framework for a second brain.",
      "These are not just concepts. They are tools you can use right now – and most of them become stronger the more they are connected together.",
      "Stopping has three purposes:",
      ["Assess what has genuinely been built into your work – what you use, what you just know", "Name what makes sense to develop further – where is the biggest potential for the rest of the challenge", "Prepare for the second half – which will be about systems, tools, and superpowers"],
      "The second half of the challenge will bring the PACT framework for your digital work environment, WBS for project work, the Human-in-the-loop approach, and five Superpowers that AI collaboration brings.",
      "These concepts make the most sense when you layer them onto what you built in the first half: mindset, prompts, templates, workflows, and a second brain.",
      "A checkpoint is not an assessment. It is an opportunity to consciously choose what to focus on next – and what from the first 14 days to truly carry with you.",
    ],
    taskIntro: "Go through a short halfway checkpoint. Write down answers to four questions:",
    taskItems: [
      "What from the first 14 days are you actually using or has helped you – specific examples",
      "What gave you the biggest shift in how you think about work and AI",
      "What have you not tried yet but want to – what are you putting off",
      "What do you want to focus on in the second half of the challenge",
    ],
    taskType: "ul",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "PACT framework: how to think about your digital work environment – starting with Projects.",
  },
  {
    day: 15,
    title: "PACT: Projects – AI in project management.",
    subject: "How to bring AI into everyday project work.",
    preheader: "The PACT framework starts with projects. Here is how AI changes the way they are managed.",
    concept: [
      "The PACT framework describes the digital work environment in four layers: Projects, Agents, Context, and Tools. We start with Projects.",
      "Projects in PACT are not just a list of tasks. They are structured units with an intention, milestones, context, and outputs. And this is exactly where AI adds tremendous value.",
      "How AI helps in project work:",
      ["Breaking a project into steps – turns a big intention into clear phases and tasks", "Preparing briefings and assignments – creates a clear brief for the team from rough inputs", "Tracking progress – summarizes project status from notes or updates", "Identifying risks – what can get stuck, what is missing, what is most critical"],
      "Working prompt for starting a project: I am working on a project [name]. The goal is [what we want to achieve]. The deadline is [date]. The main stakeholders are [who]. Resources we have: [what is available]. Break the project into logical phases and key tasks. Identify the top 3 risks.",
      "A project without a clear structure gets stuck before it begins. AI helps create the structure quickly – and then keep it current.",
      "The strongest use of AI in projects is not on a single task. It is on the overview: what is the status, what is the priority, what is stuck, and what needs to be decided. AI can pull this from rough notes in minutes.",
    ],
    taskIntro: "Take one project you are currently working on or planning, and run it through AI:",
    taskItems: [
      "Write the project intention – what is the goal and what counts as success",
      "Let AI break the project into phases and key steps",
      "Ask AI to identify the top 3 risks or uncertainties",
      "From the result, put together a project status overview in 5 sentences",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "PACT: Agents – AI agents and assistants in practice. What they are, what they are for, and where to start.",
  },
  {
    day: 16,
    title: "PACT: Agents – AI assistants and agents in practice.",
    subject: "What are AI agents and assistants – and how to use them.",
    preheader: "Agents is the second layer of the PACT framework. This is where AI gets a specific role.",
    concept: [
      "Agents in the PACT framework are AI tools that have been assigned a specific role, instructions, and context – and consistently operate in that role.",
      "The difference between a chatbot and an agent: a chatbot answers questions. An agent has a role, style, instructions, and context – and consistently operates in that role without repeating the basic setup.",
      "Two types of agents you work with most often:",
      ["Assistants – AI with an assigned role and style that you collaborate with repeatedly (examples: AI for writing content, AI for summarizing, AI for data analysis)", "Agents – AI that independently plans steps and calls different tools to complete a complex task (still evolving, but growing fast)"],
      "How to set up your own assistant: the simplest way is to create a system instruction – a short text that tells AI who it is, how it works, what it does, and what it does not do. You then paste this instruction into each new chat or set it up in custom instructions.",
      "Example system instruction: You are my personal communication assistant. You write in my style – [paste tone description]. Always ask for context before writing. Avoid [specific phrase or approach]. Output is always in [format].",
      "The better the agent is set up, the less you repeat context in each new brief. And the faster you get usable outputs.",
      "In the PACT framework, Agents are a key element – they are collaborators, not just tools. And like collaborators, they need clear instructions, a role, and a way of working together.",
    ],
    taskIntro: "Create your first personal AI assistant. Go through three steps:",
    taskItems: [
      "Choose a role – what do you need the assistant for most often (writing, analysis, summarizing, communication)",
      "Write a system instruction – who it is, how it works, what it does and does not do, what tone it has",
      "Test it on one specific task – compare the result with a regular chatbot without an instruction",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "PACT: Context – why context changes output quality more than any tool.",
  },
  {
    day: 17,
    title: "PACT: Context – context changes everything.",
    subject: "Why context changes AI output quality more than any tool.",
    preheader: "Context is the third layer of PACT. Without context, even the best AI produces average outputs.",
    concept: [
      "Context is the third layer of the PACT framework – and it is possibly the most underestimated. Without good context, even the best AI tool produces average outputs.",
      "Context is not just information. It is the set of what AI needs to know in order to work precisely – for you, for your situation, for your output.",
      "Four types of context that most change output quality:",
      ["Personal context – who you are, how you work, what your style is and what you prefer", "Project context – what the intention is, who the stakeholders are, what was decided, what is in the background", "Situational context – who the output is for, in what situation it will be used, what the goal is", "Negative context – what the output should not contain, what approaches or formats do not work"],
      "How to pass context efficiently: the strongest approach is to have prepared context blocks for recurring situations – shorter texts that you add to the beginning of a prompt. You do not need to write context from scratch each time.",
      "A prompt with a context block looks like this: [CONTEXT: I work as... on a project... for a client... in a situation where...] [TASK: Now I need...]",
      "Connected with the second brain (3C framework), Context is especially powerful: material captured and processed in the second brain becomes a context block for AI. You do not need to re-explain each time – you paste the prepared context and get to work.",
      "People who get the best outputs from AI do not use better tools. They use better context.",
    ],
    taskIntro: "Create your first context block for your most common situation:",
    taskItems: [
      "Choose one recurring situation where you regularly use AI (writing, analysis, summarizing...)",
      "Write a short context block – who you are, what the intention is, for whom, in what context",
      "Add negative context – what the output should not contain or what approach does not work",
      "Test a prompt with this context block and compare the result with what you get without it",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "PACT: Tools – how to choose the right tools and not drown in their volume.",
  },
  {
    day: 18,
    title: "PACT: Tools – choosing the right tool.",
    subject: "How to choose AI tools and not drown in their volume.",
    preheader: "Tools is the fourth layer of PACT. A tool is always the fourth step, not the first.",
    concept: [
      "Tools are the fourth – and final – layer of the PACT framework. And they are intentionally in fourth place. Because a tool is always the fourth step.",
      "Most people do it backwards: they see a tool, want to use it, and look for a problem. The result is a pile of tools that go unused.",
      "The right order in PACT: first define your projects and their needs. Then think about what agents or assistants would help. Then figure out what context you need to have prepared. And only then choose the tool – the one that will support all of this.",
      "How to evaluate an AI tool before you start using it:",
      ["What specific problem it solves – what cannot be done or is harder without it", "How much time it costs in setup versus how much it returns – V1 calculation", "How well it integrates with what you already have and use", "How quickly you can tell if it works – when you will see the first result"],
      "Three categories of tools that make sense for most work environments:",
      ["Conversational AI – for creation, analysis, summarizing, and brainstorming (ChatGPT, Claude, Gemini)", "Specialized assistants – AI with an assigned role and context for a specific area", "Automation – connecting tools where AI processes inputs without manual involvement"],
      "The strongest set of tools is not the largest. It is the most used. Two or three tools you know well and have context and workflows prepared for are worth more than ten tools you occasionally try.",
    ],
    taskIntro: "Review your current AI toolkit and assess it:",
    taskItems: [
      "Which tools do you actually use every week – and which only occasionally or not at all",
      "Where in your work is there an unsolved need for which you have no good tool",
      "What one tool would be worth exploring more deeply or setting up better",
    ],
    taskType: "ul",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "WBS – how to break a project into steps with the help of AI. Larger projects without chaos.",
  },
  {
    day: 19,
    title: "WBS: break a project into steps.",
    subject: "How to break a large project into steps that make sense.",
    preheader: "AI-WBS: Work Breakdown Structure with the help of AI. Larger projects without chaos.",
    concept: [
      "Large projects get stuck not because they are too big. But because they are not broken down enough into smaller, concrete steps.",
      "WBS – Work Breakdown Structure – is a tool that solves this problem. A project is broken into phases, phases into milestones, and milestones into concrete tasks. The result is an overview from which you can clearly see what needs to be done and in what order.",
      "AI-WBS combines the traditional WBS approach with the power of AI: instead of hours of thinking about structure, you write the project intention and AI suggests a breakdown that you then adjust to reality.",
      "Four steps of AI-WBS:",
      ["Project intention – what is the goal, what counts as success, what is the deadline", "Phases – logical units the project goes through (preparation, execution, finalization...)", "Milestones – key outputs or decisions in each phase", "Tasks – concrete actions with an owner and estimated scope"],
      "Working prompt for AI-WBS: I am working on a project [name]. The goal is [what we want to achieve]. The deadline is [date]. Team or resources: [what we have]. Create a WBS structure: 1) Project phases. 2) Main milestones in each phase. 3) Key tasks for each phase. 4) What are the biggest risks or unknowns.",
      "AI-WBS is not a replacement for project management. It is a quick way to get structure from a blank page – and then refine it according to reality.",
      "The biggest value is in seeing the project as a whole, not just today's task. And that changes how you prioritize, delegate, and communicate about progress.",
    ],
    taskIntro: "Take one larger project or intention and run it through AI-WBS:",
    taskItems: [
      "Write the project intention – what is the goal, what is success, what is the deadline",
      "Let AI suggest the phases and key milestones",
      "For each phase, let AI suggest 3–5 concrete tasks",
      "Identify with AI the top 3 risks or key unknowns",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Human-in-the-loop: AI does 90%, the human checks the result. How to set this up correctly.",
  },
  {
    day: 20,
    title: "Human-in-the-loop: AI does 90%, the human checks.",
    subject: "Where you need to step into AI outputs – and where you do not.",
    preheader: "Human-in-the-loop is a principle, not a limitation. Here is how to apply it.",
    concept: [
      "AI can do an enormous amount of work. But not everything AI prepares is ready to be sent or used directly.",
      "Human-in-the-loop is an approach that says: AI does 90% of the work, the human steps in at the key moments where human judgement, relationship, or responsibility matters.",
      "Where Human-in-the-loop is most important:",
      ["Outputs going to a customer or partner – tone, accuracy, and relationship are too important", "Decisions with impact – where a mistake has real consequences", "Sensitive information – where AI may have processed inaccurately or incompletely", "Creative or strategic outputs – where personality or specific context is missing"],
      "Where Human-in-the-loop is not needed – or a quick glance is enough: internal documents and notes, first drafts intended for further processing, summaries for personal use, recurring texts with a standardized structure.",
      "Practical approach: for every AI output, ask yourself one question – If it turns out this is wrong, who does it affect and how much? The higher the impact of an error, the greater the human oversight needs to be.",
      "Human-in-the-loop does not mean checking everything. It means knowing where checking adds real value – and where it is just unnecessary friction that slows down work.",
      "The goal is not to distrust AI. The goal is to distribute responsibility sensibly so AI does what it can handle, and you step in where it truly matters.",
    ],
    taskIntro: "Review your current AI use and write down where Human-in-the-loop is critical and where it is not:",
    taskItems: [
      "Outputs where you always need to check before using – and why",
      "Outputs where a quick glance is enough or they can be used directly",
      "One situation where you used an AI output without checking and it would be worth reconsidering",
    ],
    taskType: "ul",
    taskPrompt: `Here is my data or text:
[paste input]

Please answer:
- What is repeating or most frequent here?
- What is most important or most significant?
- What is surprising or unexpected?
- What do you recommend doing next based on this information?`,
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Superpowers: the first of five abilities that AI collaboration brings – Perception.",
  },
  {
    day: 21,
    title: "Superpowers: Perception – see more.",
    subject: "AI will help you see more than you can see alone.",
    preheader: "Perception is the first of 5 Superpowers. How AI expands what you perceive.",
    concept: [
      "Superpowers are five abilities that AI collaboration brings when you consciously develop them. It is not about what AI can do – it is about what you can do with AI.",
      "The first superpower is Perception: the ability to see more, notice more, and have a wider range of information and perspectives than would be possible without AI.",
      "How Perception works in practice:",
      ["Quick topic overview – in minutes you can orient yourself in an area where you are not an expert", "Alternative perspectives – AI shows how different people, customers, or experts would look at the situation", "Signals in feedback – AI pulls patterns from a large volume of comments or responses", "Blind spots – AI points out what you forgot, overlooked, or underestimated"],
      "Perception prompt: Look at this situation from the perspective of [different roles: customer, critic, expert]. What does each of them perceive differently? What would each of them see as the main problem or opportunity?",
      "Perception is valuable precisely because everyone has natural blind spots – areas where we see less because they are outside our experience or perspective. AI can expand this range.",
      "This superpower does not mean AI always sees correctly. It means that with AI you see more options, perspectives, and signals – and then you make better decisions.",
      "Consciously developed Perception changes how you approach problems and opportunities. You stop looking from just one angle and naturally start considering the wider picture.",
    ],
    taskIntro: "Practice Perception on one current situation or challenge:",
    taskItems: [
      "Choose one current problem or decision you are working on",
      "Ask AI to look at it from three different perspectives – customer, critic, expert from another field",
      "Write down what surprised you in the result or what you had not seen",
    ],
    taskType: "ul",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Superpowers: Intelligence – how AI helps you analyze better and faster.",
  },
  {
    day: 22,
    title: "Superpowers: Intelligence – analyze better.",
    subject: "How AI helps you analyze better and faster.",
    preheader: "Intelligence is the second of 5 Superpowers. How AI expands analytical ability.",
    concept: [
      "The second superpower is Intelligence: the ability to analyze, evaluate, and find patterns faster and more accurately than is possible without AI.",
      "Intelligence does not mean AI thinks for you. It means AI helps you process a greater amount of information, identify patterns, and draw conclusions – faster than you could alone.",
      "Where Intelligence adds the most value:",
      ["Feedback at scale – AI pulls themes, recurring patterns, and key points from large volumes", "Comparing options – AI evaluates pros and cons of possibilities according to given criteria", "Analyzing text or data – structured overview from unstructured input", "Identifying anomalies – what in the data or situation does not fit the pattern"],
      "Intelligence prompt: Here are [data / feedback / texts / information]: [paste input]. Analyze and: 1) Identify the main patterns or recurring themes. 2) What is most important or most critical. 3) What is unexpected or does not fit the pattern. 4) What follows from this for next steps.",
      "The key difference between Intelligence and mere searching: Intelligence is not about getting an answer. It is about getting a structured analysis that helps you better understand the situation and make better decisions.",
      "Intelligence as a superpower grows as you improve the quality of input – the better the context and data, the more precise the analysis. This again refers back to the second brain and 3C framework: captured and processed materials are excellent input for Intelligence.",
    ],
    taskIntro: "Practice Intelligence on one real input:",
    taskItems: [
      "Choose an input you need to analyze – feedback, data, a list of things, texts",
      "Give it to AI with the Intelligence prompt from today",
      "From the result, draw one concrete conclusion or decision",
    ],
    taskType: "ul",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Superpowers: Memory – how AI helps you remember more and better use what you know.",
  },
  {
    day: 23,
    title: "Superpowers: Memory – remember more.",
    subject: "How AI helps you remember more and better use your knowledge.",
    preheader: "Memory is the third of 5 Superpowers. How AI expands what you remember and use.",
    concept: [
      "The third superpower is Memory: the ability to have access to more context, knowledge, and history than any one person can remember.",
      "Memory as a superpower is not just about storing information. It is about the ability to retrieve it at the right moment and connect it with current work.",
      "AI expands Memory in three ways:",
      ["Externalizing context – everything important is saved and can be reused, not just remembered", "Quick retrieval and connection – older material becomes relevant in a new context", "Consistency – AI remembers the context you give it and works with it consistently within a conversation"],
      "The Memory superpower works best connected with the second brain (3C framework): captured and processed materials are exactly what can be passed to AI as context – and in this way AI expands your Memory.",
      "Where Memory as a superpower helps most: before a client meeting (what was discussed, what was decided, what is the context), when continuing a project after a break (what was where, what is still missing), when onboarding a new person (documented context and decisions).",
      "Memory prompt: Here is context and history on this topic: [paste material from second brain]. On this basis: [specific task or question].",
      "When you connect your second brain with AI Memory, you stop losing context. Every project, every client, every decision has its history – and it is available at the right moment.",
    ],
    taskIntro: "Practice the Memory superpower on one situation where context matters:",
    taskItems: [
      "Choose a situation where context or history is important – a project, client, or topic",
      "Put together a short context block from what you know or have saved about the situation",
      "Paste the context into AI and give it a specific task or question on that basis",
      "Compare the result with what AI would produce without this context",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Superpowers: Creation – how to create faster and with greater variety of outputs.",
  },
  {
    day: 24,
    title: "Superpowers: Creation – create faster.",
    subject: "How AI helps you create faster and with greater variety.",
    preheader: "Creation is the fourth of 5 Superpowers. Creating without waiting for inspiration.",
    concept: [
      "The fourth superpower is Creation: the ability to create more, faster, and with greater variety of outputs – without waiting for the right moment or a blank page.",
      "Creation as a superpower does not mean AI creates for you. It means you add a co-creator who never has a creative block, produces variants on demand, and does not stop at the first version.",
      "Where Creation adds the most value:",
      ["Overcoming the blank page – the first draft of anything is produced in minutes, not hours", "Variants – instead of one version you get three, from which you assemble a better result", "Repurposing – one piece of content is transformed into multiple formats for different situations", "Iteration – quick reworking based on feedback without losing energy"],
      "Creation workflow: 1) Intention – what you want to create and why. 2) Context – for whom, in what tone, in what format. 3) Variants – ask for 2–3 different approaches. 4) Selection – take the best elements from each variant. 5) Finalization – add your voice and detail.",
      "V1 > 0 is strongest exactly here: Creation with AI removes the most painful part of making things – the beginning. Once you have a first version, work becomes concrete and manageable.",
      "The Creation superpower grows as you get better at passing context and Tone of Voice. The outputs you get are only as good as the brief – and you already know that well from the previous days.",
    ],
    taskIntro: "Practice the Creation superpower on one piece of content or output:",
    taskItems: [
      "Choose one text, document, or content you need to create",
      "Ask AI for 3 variants with different approaches or tones",
      "From the three variants, take the best elements and put together the final version",
      "Save the resulting prompt as a template for the next similar task",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Superpowers: Connection – how AI helps you communicate better and achieve more.",
  },
  {
    day: 25,
    title: "Superpowers: Connection – communicate better.",
    subject: "How AI helps you communicate better and achieve more.",
    preheader: "Connection is the fifth of 5 Superpowers. Communication that works better.",
    concept: [
      "The fifth superpower is Connection: the ability to communicate better, formulate more persuasively, and build stronger relationships – with the help of AI as a communication partner.",
      "Connection does not mean AI communicates for you. It means it helps prepare communication that is clearer, more precise, and better tailored to a specific person or situation.",
      "Where Connection adds the most value:",
      ["Preparing an important message – AI helps you formulate what you want to say so it is heard", "Adapting tone – the same content formulated differently for different recipients", "Empathy and perspective – how the recipient perceives the message and what they might hear differently", "Difficult situations – feedback, escalation, rejection, or persuasion"],
      "Connection prompt: I want to convey [content or intention] to [recipient]. This person is [description or context about the recipient]. The goal of the communication is [what we want to achieve]. Suggest: 1) How to formulate it clearly and understandably. 2) What might be perceived badly and how to prevent that. 3) How to close the message so the next step is clear.",
      "Connection as a superpower also includes Tone of Voice (day 9): when AI knows your style, communication remains personal – it is just better prepared.",
      "The strongest communication is not the longest or most formal. It is the one that says exactly what it needs to say – and says it in a way the recipient hears. And AI can significantly help with that.",
    ],
    taskIntro: "Practice the Connection superpower on one communication situation:",
    taskItems: [
      "Choose one important message, email, or conversation you need to prepare",
      "Use the Connection prompt – describe the recipient, intention, and communication goal",
      "Let AI suggest the wording and assess what might be perceived differently",
      "Finalize the message with your own tone and send it or use it",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "AI Adoption: how to connect it all – Mindset, Tools, and Superpowers as a whole.",
  },
  {
    day: 26,
    title: "AI Adoption: Mindset, Tools, and Superpowers as a whole.",
    subject: "How to connect it all and continue after the challenge.",
    preheader: "AI Adoption trilogy: Mindset, Tools, Superpowers. Here is how they work together.",
    concept: [
      "On the last day before the finale, it is worth looking at the whole challenge as a unit.",
      "AI Adoption works in three layers that build on each other: Mindset, Tools, and Superpowers.",
      "Mindset is the foundation. Without an AI-first way of thinking, tools are just toys. Mindset includes everything from the first week: AI-first approach, Leverage matrix, OHIO principle, quality of brief, Prompt Generator approach, V1 > 0, and iteration.",
      "Tools are the means. The right tools in the right context amplify what Mindset made possible. The PACT framework, 5 levels of AI tools, the second brain, and workflows are the Tools layer – the way to organize work and systematically bring in AI.",
      "Superpowers are the result. Perception, Intelligence, Memory, Creation, and Connection are not AI's abilities – they are human abilities that AI collaboration expands. They develop gradually as Mindset and Tools strengthen.",
      "How to continue after the challenge:",
      ["Maintain Mindset – regularly ask yourself about outcome vs. activity, leverage vs. speed", "Develop Tools – build the second brain, PACT environment, and workflows not all at once, but gradually", "Consciously develop Superpowers – each week choose one and focus on it"],
      "AI Adoption is not a one-time project. It is a gradual change in the way you work. And the change that began with this challenge continues – in the next 90 days, the next year, and every day you consciously choose to work smarter.",
      "The biggest shift does not come from one tool or one prompt. It comes from Mindset, Tools, and Superpowers starting to work as a whole.",
    ],
    taskIntro: "Assess your AI Adoption journey through the challenge across three layers:",
    taskItems: [
      "Mindset – what has changed in how you think about work and AI collaboration",
      "Tools – what tools, systems, or workflows you are taking with you and want to develop further",
      "Superpowers – which of the five abilities feels most relevant and you want to consciously develop",
    ],
    taskType: "ul",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Second to last day. How to transfer the system into practice – and make it work even without active thinking.",
  },
  {
    day: 27,
    title: "The system that works for you.",
    subject: "You are not collecting tips anymore. You are building a system.",
    preheader: "Tomorrow is the last day of the challenge. Today you put together what you are taking with you.",
    concept: [
      "A real AI system is not one tool. It is a way of working where more things come together at once.",
      "It is a combination of how you think about tasks, what you delegate to AI, what you save and reuse, how you build your second brain, and where you keep Human-in-the-loop oversight.",
      "After 27 days of the challenge, you have enough experience for putting together your own system to make sense. It is not theory – it is an overview of what worked and what you want to keep.",
      "A good AI system has six components:",
      [
        "Mindset – how you think about work: outcomes vs. activities, Leverage vs. speed",
        "Prompts – a saved set of prompts for the most common situations (Tone of Voice, templates, Prompt Generator)",
        "Workflow – connected chains of steps where AI helps automatically",
        "Second brain – where knowledge, materials, and reusable assets are stored (3C framework)",
        "PACT environment – Projects, Agents, Context, Tools set up for your work",
        "Rules – where Human-in-the-loop is needed and what not to put into AI",
      ],
      "The first version does not have to be perfect. But it has to exist – otherwise it stays just an idea.",
      "Put it together today. Search through notes from the challenge, what you learned, what you saved, what you tried. Put it all together. It will be the foundation you build from in the next 90 days.",
    ],
    taskIntro: "Write the first version of your AI system. Go through all six components:",
    taskItems: [
      "What I use AI for most often and where it genuinely helps me",
      "Which prompts or templates I want to save and always have on hand",
      "Which workflows or chains of steps make sense to me and I want to keep",
      "Where I store materials, knowledge, and resources from the challenge (second brain)",
      "Where I need Human-in-the-loop – what I will never send or use without verification",
      "What I no longer want to do from scratch manually",
    ],
    taskType: "ul",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "The last day of the challenge. And the beginning of everything that comes after.",
  },
  {
    day: 28,
    title: "Real change starts now.",
    subject: "28 days done. Real change starts now.",
    preheader: "Finishing the challenge is not the goal. It is the beginning. Here is what comes next.",
    concept: [
      "Finishing the challenge is not the goal. It is the beginning.",
      "The point is not to go through 28 days and try 28 things. The point is what remains in your everyday work afterward. What changes in how you think, how you brief work, how you look at what has to be done manually and what does not.",
      "The strongest change does not come from one big leap. It comes from a small step repeated every day. And that is exactly what you have been doing for the last 28 days.",
      "What you know now that you did not know or realize before the challenge:",
      [
        "that you are paid for outcomes, not activity – and that AI is strongest when you work with that consciously",
        "that repetition is a signal for OHIO and a template, not a challenge to work faster",
        "that quality of brief = quality of output – always",
        "that V1 > 0 – the first version is always better than the perfect system that has not been created yet",
        "that Leverage matters more than speed",
        "that Mindset, Tools, and Superpowers work best as a whole",
      ],
      "What is next. The challenge is over, but work on the system is not. The next 90 days are critical – that is the window when new habits either take root or get lost.",
      "A plan for the next 90 days can be summarized in four steps: Keep – what I definitely want to keep. Build – what I want to continue developing or building. Share – what I want to share with others. Measure – how I will know this is actually helping me.",
      "A little is enough. Five minutes a day. One prompt. One saved step. And that is what real change is made of – the kind that stays.",
    ],
    taskIntro: "Write a short plan for the next 90 days. Go through the four steps:",
    taskItems: [
      "Keep – what I definitely want to keep (min. 3 concrete things from the challenge)",
      "Build – what I want to continue developing or building (min. 1 concrete goal)",
      "Share – what I want to share with others (with whom and what specifically I will show)",
      "Measure – how I will know this is actually helping me (concrete metric or feeling)",
    ],
    taskType: "ul",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "",
  },
];
