import type { ChallengeDay } from "./types";

export const challengeDataAdvancedCZ: ChallengeDay[] = [
  {
    day: 0,
    title: "Základy máš. Teď přichází systém.",
    subject: "Advanced start: 3C, PACT, Superpowers.",
    preheader: "Pro ty, kdo mají základy. Teď jde o to posunout se výš.",
    concept: [
      "Jsi tady, protože základy máš. Víš, jak zadat AI úkol. Možná ji používáš každý den. A přesto cítíš, že tam je víc — že z AI dostáváš zlomek toho, co by mohla nabídnout.",
      "Přesně proto existuje tato verze challenge.",
      "Nezačínáme od toho, co je AI a jak ji použít. Začínáme od otázky: jak postavit systém, který funguje — i když nejsi u toho?",
      "Tahle challenge má tři vrstvy:",
      [
        "3C framework — Capture, Clean, Connect: jak z chaosu znalostí vznikne něco, co lze skutečně použít",
        "PACT framework — Projects, Agents, Context, Tools: jak přemýšlet o AI jako o systému, ne sadě triků",
        "Superpowers — pět schopností, které AI spoluprací skutečně získáváš: Perception, Intelligence, Memory, Creation, Connection",
      ],
      "A čtvrtá vrstva, která to celé uzavírá: Scale — jak vše vybudované převést na systém, který pracuje za tebe.",
      "Každý den trvá 5–10 minut. Teorie jsou kratší a konkrétnější. Praxe je zaměřena na věci, které budeš moci použít hned.",
      "Prvním krokem: zamysli se nad tím, kde ti AI zatím nestačí. Ne obecně — ale konkrétně. Kde musíš výstup přepsat? Kde s AI ztrácíš čas místo aby ho ušetřila? Kde AI naráží?",
      "Tohle je výchozí bod. Nejde o sebekritiku — jde o mapování terénu. Příštích 28 dní bude konkrétnější, pokud víš, kde začínáš.",
    ],
    taskIntro: "Napiš 3 věci, kde ti AI zatím nestačí nebo kde chceš jít výrazně hlouběji. Buď konkrétní:",
    taskItems: [],
    taskType: "text",
    taskFallback: `Pokud nevíš, kde začít, odpověz si na tři otázky:
– Kde musím výstup z AI vždy výrazně přepracovat?
– Co dělám opakovaně a AI mi s tím nepomáhá tak, jak by bylo potřeba?
– Kde mám pocit, že ostatní z AI dostávají víc než já?

Příklady z praxe:
→ Výstupy pro klienty jsou obecné — musím je přepsat do kontextu projektu.
→ Nevím, jak AI zapojit do strategického plánování bez povrchních výsledků.
→ Používám AI pro obsah, ale chybí mi systém pro uchování toho, co funguje.`,
    taskExample: `Vstup: "Kde mi AI zatím nestačí?"

Tři konkrétní záznamy:
1. Příprava nabídek: AI navrhne strukturu, ale nezná kontext klienta — výsledek vždy přepisuji ze 60 %.
2. Projektové retrospektivy: nevím, jak systematicky zachycovat poznatky a dávat je AI jako kontext.
3. Delegování v týmu: AI sice funguje individuálně, ale nevím, jak zavést systém pro celý tým.`,
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra si ukážeme 3C framework — a proč chaos ve znalostech brzdí i dobré prompty.",
  },
  {
    day: 1,
    title: "3C framework: Capture, Clean, Connect jako jeden systém.",
    subject: "Proč chaos ve znalostech brzdí i dobré prompty.",
    preheader: "Znalosti bez systému nejsou znalosti. Jsou to jen data.",
    concept: [
      "Jeden z nejčastějších důvodů, proč AI výstupy jsou průměrné, nemá nic společného s promptem samotným.",
      "Má co do činění se vstupem. S tím, co AI dáš k dispozici.",
      "Pokud pracuješ s chaosem — poznámky všude, nápady nenapsané, poučení z projektů ztracená v emailech — pak i ten nejlepší prompt produkuje průměrné výsledky. Garbage in, garbage out platí s AI dvojnásobně.",
      "3C framework je systém pro práci se znalostmi v kontextu AI. Tři kroky, jeden systém:",
      [
        "Capture — zachycení hodnotných věcí: co stojí za uchování a co ne. Filtrování je schopnost, ne jen zvyk.",
        "Clean — zpracování surového materiálu do použitelné znalosti. Tohle je krok, který většina lidí přeskakuje.",
        "Connect — propojení starých znalostí s aktuální prací. Starý poznatek může odemknout nové řešení.",
      ],
      "Tři kroky fungují pouze jako celek:",
      [
        "Capture bez Clean = hromada poznámek, které nikdy nepoužiješ",
        "Clean bez Connect = izolované znalosti bez kontextu",
        "Connect bez Capture = propojuješ věci, které nebyly nikdy zachyceny",
      ],
      "V následujících dnech si každý krok rozložíme do teorie i praxe. Ale dnes je důležitější jeden poznatek: nejkvalitnější výstupy z AI nevznikají z nejchytřejších promptů. Vznikají z nejlepšího kontextu. A kontext pochází ze systému.",
    ],
    taskIntro: "Zamysli se, jak v současnosti pracuješ se znalostmi ze své práce. Odpověz si na tři otázky:",
    taskItems: [
      "Kam zachycuješ poznatky, nápady a důležité informace z práce? (jedno místo, nebo chaos?)",
      "Jak zpracováváš surový materiál — poznámky, transkripty, hrubé drafty — do něčeho použitelného?",
      "Jak se k starým znalostem a poznatkům vracíš, když řešíš nový problém?",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra si ukážeme první krok — Capture: co stojí za zachycení a co ne.",
  },
  {
    day: 2,
    title: "Capture: ne vše stojí za zachycení.",
    subject: "Filtrování je schopnost, ne jen zvyk.",
    preheader: "Zachytit vše je stejně špatné jako nezachytit nic.",
    concept: [
      "Prvním krokem 3C systému je Capture — zachycení hodnotných informací z práce.",
      "Jenže tady je problém, do kterého padne většina lidí: snaží se zachytit vše. A výsledek je hromada poznámek, ze které nikdy nic nevytáhnou.",
      "Capture není o maximálním zachycení. Je o filtrování. Dobrý filtr tě naučí vidět, co má trvalou hodnotu — a co je jen momentální hluk.",
      "Principy filtru — co stojí za zachycení:",
      [
        "Poznatky z praxe: co fungovalo, co nefungovalo, co by si příště zasloužilo jiný přístup",
        "Opakující se vzorce: co se děje pravidelně — v projektech, v komunikaci, v rozhodnutích",
        "Kontext pro AI: informace, které budeš chtít AI dát jako kontext — o klientovi, projektu, sobě",
        "Rozhodnutí a jejich důvody: ne jen co bylo rozhodnuto, ale proč",
      ],
      "Co naopak zachycovat nemusíš:",
      [
        "Obecné informace, které jsou snadno dohledatelné kdykoli",
        "Fakta bez kontextu nebo bez vazby na tvou konkrétní práci",
        "Věci, které se pravděpodobně nevrátí a nejsou přenositelné",
      ],
      "Praktický test: pokud si za tři týdny přečteš zachycenou poznámku — bude stále relevantní? Pokud ano, zachyť. Pokud ne, přeskoč.",
      "Cíl dnešního dne: pochopit svůj filtr a zachytit pět věcí z aktuálního týdne, které skutečně mají trvalou hodnotu.",
    ],
    taskIntro: "Zachyť 5 věcí z tohoto pracovního týdne, které stojí za uchování. Ke každé věci napiš jednu větu: proč to stojí za uchování.",
    taskItems: [],
    taskType: "text",
    taskFallback: `Pokud nevíš, co zachytit, použij tento prompt:

"Pomoč mi zachytit klíčové věci z tohoto pracovního týdne. Zeptej se mě na 5 otázek zaměřených na: co fungovalo, co nefungovalo, jaká rozhodnutí padla a proč, co překvapilo a co by šlo příště udělat jinak."

Odpověz na otázky — máš základ pro 5 zachycených věcí.`,
    taskExample: `Vstup (surový materiál z týdne, zadaný do AI):
"Tento týden: schůzka s klientem ohledně prodloužení smlouvy, draft reportu, interní retrospektiva projektu, nový dodavatel — první call, zamítnutý rozpočet pro Q2."

AI výstup — 5 věcí hodných zachycení:
1. Klient — schůzka: jaké konkrétní námitky zazněly a jak na ně zazněla reakce. (Proč: příště mít připravené odpovědi)
2. Retrospektiva: tři věci, které by tým udělal jinak. (Proč: vzorce, které se opakují)
3. Nový dodavatel: první dojem, klíčové parametry spolupráce. (Proč: kontext pro budoucí jednání)
4. Zamítnutý rozpočet: jaký byl skutečný důvod zamítnutí. (Proč: vzorec pro budoucí žádosti)
5. Draft reportu: co fungovalo ve struktuře, co bylo nejasné. (Proč: základ pro šablonu)`,
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Capture v praxi — jak zachycování zabudovat do pracovního dne bez přetížení.",
  },
  {
    day: 3,
    title: "Capture v praxi: systém, který nezabere více než 2 minuty.",
    subject: "Jak zachycování zabudovat do práce bez přetížení.",
    preheader: "Nejlepší systém je ten, který skutečně používáš.",
    concept: [
      "Teorie Capture je jasná. Praxe je jiná věc — protože většina lidí začne zachycovat, vydrží dva týdny a pak přestane. Ne proto, že by nechtěla. Ale proto, že systém byl příliš složitý.",
      "Pravidlo: nejlepší Capture systém je ten nejjednodušší, který ti opravdu vyhovuje. Jeden inbox. Jedno místo. Dvě minuty.",
      "Tři vzorce Capture, které v praxi fungují:",
      [
        "End-of-day zápis: 3 věty na konci pracovního dne — co se stalo, jaké plyne poučení, co udělat jinak",
        "Meeting capture: hned po schůzce — dvě minuty, tři věci: co bylo rozhodnuto, co mám udělat, co překvapilo",
        "Inbox first: jedno místo pro vše — Notion, Apple Notes nebo papír — a jednou týdně zpracuješ",
      ],
      "Jak AI pomáhá s Capture: nemusíš psát hned v čistém. Hoď do AI hrubé poznámky — nesourodé věty, zkratky, proud myšlenek. AI to zpracuje do struktury. Tím se Capture stane rychlejší a méně náročné.",
      "Ukázkový Capture prompt: Mám tyto hrubé poznámky ze schůzky: [vlož poznámky]. Vyextrahuj: 1) co bylo rozhodnuto, 2) co mám udělat a do kdy, 3) co je nejdůležitější poznatek.",
      "Klíčová chyba: mít příliš mnoho míst pro Capture. Každé místo navíc je místo, kde informace zmizí. Jedno místo, konzistentně. Týden stačí ke zjištění, zda to funguje.",
    ],
    taskIntro: "Nastav si svůj Capture systém — konkrétně, ne obecně:",
    taskItems: [
      "Vyber jedno místo, kam budeš zachycovat — Notion, Apple Notes, Google Docs, papír (jedno, ne více)",
      "Vyber svůj vzorec: end-of-day zápis, meeting capture nebo weekly inbox — co ti lépe sedí?",
      "Hned teď zachyť 3 věci z dnešního nebo včerejšího dne — otestuj svůj systém ještě dnes",
    ],
    taskType: "ol",
    taskPrompt: "Mám tyto hrubé poznámky ze schůzky nebo dne: [vlož poznámky]. Vyextrahuj: 1) co bylo rozhodnuto nebo co je klíčový závěr, 2) co mám udělat a do kdy, 3) nejdůležitější poznatek, který stojí za uchování.",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Clean — proč uložení poznámky a zpracování poznámky jsou dvě různé věci.",
  },
  {
    day: 4,
    title: "Clean: zpracování není totéž co uložení.",
    subject: "Clean — surový materiál se stane znalostí až po zpracování.",
    preheader: "Hromada poznámek není znalostní systém. Je to jen hromada.",
    concept: [
      "Druhý krok 3C systému je Clean — zpracování surového materiálu do použitelné znalosti.",
      "Tady je největší díra ve většině systémů: lidé zachycují, ale nečistí. A výsledek je hromada surového materiálu, ze které nelze nic efektivně vytáhnout.",
      "Rozdíl mezi uložením a zpracováním:",
      [
        "Uložení: transkript schůzky zkopírovaný do Notion",
        "Zpracování: z transkriptu vyextrahovaná tři klíčová rozhodnutí, dva úkoly s termíny a jeden strategický poznatek — vše otagované pro snadné hledání",
      ],
      "Proč je Clean klíčové: AI potřebuje strukturovaný kontext, ne surový chaos. Čím lépe je vstupní materiál zpracovaný, tím relevantnější je výstup.",
      "Jak Clean funguje v praxi:",
      [
        "Extrakce: z dlouhého materiálu vytáhni klíčové body — rozhodnutí, úkoly, poznatky",
        "Formátování: přepiš surový materiál do konzistentní struktury, kterou si příště rychle přečteš",
        "Tagování: přidej kategorii nebo klíčové slovo — aby šlo rychle najít",
        "Komprese: z hodiny zápisků udělej pět odrážek — co skutečně potřebuješ",
      ],
      "AI jako Clean asistent: vlož surový materiál, zadej instrukci Clean, dostaneš strukturovaný výstup. Pak jen ověříš a uložíš. Clean s AI trvá 3 minuty místo 20.",
      "Cíl dnešního dne: vzít surový materiál z D2 nebo D3 a projít ho celým Clean procesem.",
    ],
    taskIntro: "Vezmi surový materiál ze svého Capture systému a proveď Clean:",
    taskItems: [
      "Otevři surový materiál — poznámky ze schůzky, zápis z dne, nebo cokoli z D2/D3",
      "Zadej AI instrukci Clean (viz prompt níže) nebo proveď ručně: extrahuj klíčové body, zformátuj, přidej kontext",
      "Výsledek ulož jako čistý záznam — tak, aby bylo za měsíc čitelné a srozumitelné na první pohled",
    ],
    taskType: "ol",
    taskPrompt: "Vlož tento surový materiál: [vlož poznámky nebo transkript]. Proveď Clean: 1) extrahuj klíčová rozhodnutí a závěry, 2) vypiš úkoly s termíny, 3) identifikuj nejdůležitější poznatek nebo vzorec, 4) napiš jednověté shrnutí. Výstup ve strukturovaném formátu.",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Clean v praxi — jak ho zabudovat do rutiny tak, aby fungoval i v náročných týdnech.",
  },
  {
    day: 5,
    title: "Clean v praxi: rutina, která funguje i pod tlakem.",
    subject: "Jak zpracovávat pravidelně — bez přetížení.",
    preheader: "Clean jako návyk: jednou týdně, strukturovaně, 20 minut.",
    concept: [
      "Teorie Clean je jasná. Praxe je o tom, kdy a jak to zařadíš do pracovního týdne — ne jako extra práci, ale jako součást rutiny.",
      "Nejčastější chyba: snaha o Clean v reálném čase. Clean každého záznamu hned po zachycení je příliš náročné. Výsledkem je přetížení a pak opuštění celého systému.",
      "Lepší přístup: dávkový Clean. Jednou týdně, třicet minut, vše najednou. Nebo každodenní mini Clean: pět minut na konci dne na tři záznamy z dnešního dne.",
      "Dvě funkční rutiny:",
      [
        "Weekly Clean (pátek, 20–30 min): projdi celý inbox z týdne, zpracuj vše najednou, archivuj",
        "Daily mini Clean (konec dne, 5 min): tři nejdůležitější věci z dnešního dne, rychlá extrakce",
      ],
      "Jak AI urychlí weekly Clean: vlož všechny surové záznamy z týdne do jedné konverzace s AI a zadej: 'Zpracuj tyto záznamy z týdne. Pro každý: extrahuj klíčové body, identifikuj opakující se vzorce přes více záznamů a navrhni prioritu zpracování.' Za 10 minut máš strukturu, co by jinak trvalo hodinu.",
      "Klíčový poznatek: pravidelný Clean je cennější než dokonalý Clean. Dokonalý systém, který nefunguje pravidelně, nepřinese nic. Nedokonalý systém, který funguje každý týden, přinese mnoho.",
      "Po dnešní praxi budeš mít Capture i Clean zabudované. Zítra přidáme třetí krok: Connect.",
    ],
    taskIntro: "Nastav svůj Clean rytmus a proveď první weekly Clean:",
    taskItems: [
      "Rozhodni: weekly Clean nebo daily mini Clean — co lépe sedí tvé práci?",
      "Nastav si opakující se slot v kalendáři — konkrétní den a čas",
      "Proveď první Clean hned teď: vezmi vše z Capture inboxu a zpracuj pomocí AI promptu",
    ],
    taskType: "ol",
    taskPrompt: "Tady jsou surové záznamy z mého pracovního týdne: [vlož záznamy]. Zpracuj je: 1) pro každý záznam vyextrahuj klíčové body, 2) identifikuj opakující se vzorce nebo témata přes více záznamů, 3) navrhni, co je prioritní pro budoucí práci.",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Connect — jak propojovat starý poznatek s novým problémem, aby vzniklo skutečné řešení.",
  },
  {
    day: 6,
    title: "Connect: starý poznatek, nové řešení.",
    subject: "Connect — propojení znalostí jako nejcennější část 3C systému.",
    preheader: "Nejcennější znalost je ta, kterou máš — a dovede tě k novému řešení.",
    concept: [
      "Třetí krok 3C systému je Connect — propojování zachycených a zpracovaných znalostí s aktuální prací.",
      "Capture a Clean jsou příprava. Connect je místo, kde se hodnota skutečně projeví.",
      "Co Connect znamená v praxi: když řešíš nový problém, projekt nebo rozhodnutí, nevytváříš znalost od nuly. Vracíš se k tomu, co bylo zachyceno a zpracováno — a propojuješ to s aktuální situací.",
      "Tři způsoby, jak Connect funguje:",
      [
        "Analogie: 'Řeším teď X. V minulosti šlo o podobnou situaci Y. Co se tehdy osvědčilo?'",
        "Vzorce: 'V tomto projektu se opakuje problém Z. Tentýž problém se vyskytl ve třech předchozích projektech. Co byl společný jmenovatel?'",
        "Kontextový vstup: 'Mám vytvořit nabídku pro klienta A. Mám záznamy o podobném klientovi B — dám je AI jako kontext.'",
      ],
      "Jak AI pomáhá s Connect: vlož zpracované záznamy z Capture/Clean jako kontext a zadej AI: 'Řeším aktuálně tuto situaci: [popis]. Z mých předchozích záznamů je toto relevantní: [záznamy]. Jaké vzorce vidíš? Co z předchozích zkušeností je aplikovatelné?'",
      "Klíčový poznatek: lidé, kteří z AI dostávají nejlepší výstupy, nepíší nejlepší prompty. Mají nejlepší kontext. A kontext pochází z fungujícího Capture, Clean, Connect systému.",
      "Po dnešním dni máš celý 3C systém — alespoň jako teorii. Zítra uděláme review: kde systém funguje, kde jsou díry a co z toho vezmeš dál.",
    ],
    taskIntro: "Vezmi aktuální problém nebo projekt, který řešíš, a proveď Connect:",
    taskItems: [
      "Vyber aktuální problém nebo rozhodnutí, které teď řešíš",
      "Projdi svůj Capture/Clean systém: co z předchozích záznamů je relevantní?",
      "Zadej AI aktuální problém + relevantní záznamy jako kontext a požádej o analýzu vzorců a doporučení",
    ],
    taskType: "ol",
    taskPrompt: "Řeším aktuálně tuto situaci: [popis situace nebo problému]. Z mých předchozích záznamů je toto relevantní: [vlož záznamy]. Jaké vzorce vidíš? Co z předchozích zkušeností nebo poznatků lze aplikovat na aktuální situaci?",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: 3C reflexe — kde systém funguje, kde jsou díry a co z prvního týdne vezmeš dál.",
  },
  {
    day: 7,
    title: "3C reflexe: kde systém funguje a kde jsou díry.",
    subject: "Týden jedna za námi — co si z 3C bereš dál.",
    preheader: "Systém funguje jen tehdy, pokud ho skutečně používáš.",
    concept: [
      "Celý první týden byl o 3C frameworku. Dnes je čas se zastavit a zhodnotit — ne jako teorii, ale jako praxi.",
      "Reflexe není hodnocení toho, zda vše šlo správně. Je to mapování reality: kde systém funguje a kde naráží. Tohle je nejcennější informace pro to, aby systém zůstal a zlepšoval se.",
      "Tři otázky pro 3C reflexi:",
      [
        "Capture: zachycuješ pravidelně? Je inbox přeplněný nebo prázdný? Co je největší překážka?",
        "Clean: zpracováváš záznamy nebo se hromadí? Pomáhá ti AI s Clean nebo ho ještě nepoužíváš?",
        "Connect: přišlo v tomto týdnu k návratu ke starému záznamu a jeho použití? Co to přineslo nebo co chybí?",
      ],
      "Co s výsledky reflexe: pokud Capture nefunguje — zjednodušíš systém (jedno místo, jeden vzorec). Pokud Clean je přetěžující — přejdeš na weekly Clean. Pokud Connect chybí — začneš každý projekt nebo problém nejdřív spojovat s archivem záznamů.",
      "Klíčový poznatek prvního týdne: 3C není o dokonalosti. Je o konzistenci. Nedokonalý systém, který používáš každý týden, je cennější než dokonalý systém, který opustíš za dva týdny.",
      "Příští týden přejdeme na PACT framework — a začneme přemýšlet o AI jako o systému pro projektovou práci.",
    ],
    taskIntro: "Proveď 3C reflexi — stručně a konkrétně:",
    taskItems: [
      "Capture: funguje? Co je největší třecí plocha?",
      "Clean: zpracováváš pravidelně nebo se materiál hromadí?",
      "Connect: byl tento týden použit starý záznam ze systému? Co to přineslo nebo co chybí?",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden: PACT framework — Projects, Agents, Context, Tools. Systémový přístup k AI v projektové práci.",
  },
  {
    day: 8,
    title: "PACT framework: Projects, Agents, Context, Tools.",
    subject: "Proč framework místo náhodného výběru nástrojů.",
    preheader: "Bez struktury se AI stane dalším nástrojem, který přidává zmatek.",
    concept: [
      "Druhý týden challenge je o PACT frameworku — způsobu, jak přemýšlet o AI v pracovním kontextu systematicky.",
      "PACT stojí na čtyřech prvcích. Každý prvek je jiná vrstva, jiná otázka:",
      [
        "Projects — jak AI zapojit do reálných projektů s jasnou strukturou a výstupy",
        "Agents — kdy dávají smysl AI agenti a multi-step workflow, kdy jsou zbytečně složití",
        "Context — proč kontext rozhoduje o kvalitě výstupu víc než samotný prompt",
        "Tools — jak vybírat nástroje funkčně, ne na základě hype",
      ],
      "Proč framework místo náhodného výběru: bez struktury se AI stane dalším nástrojem, ke kterému se chodí ad hoc. S frameworkem se stane součástí způsobu práce.",
      "Rozdíl v praxi: bez PACT se ptáš 'Jaký AI nástroj mám vyzkoušet?' nebo 'Jak napsat lepší prompt?'. S PACT se ptáš 'Jaký výsledek chci dosáhnout a jak mi AI může systematicky pomoct?' — a to je jiná otázka.",
      "PACT není rigidní metodologie. Je to způsob myšlení — čtyři otázky, které si kladeš, když přemýšlíš o zapojení AI:",
      [
        "Je to projekt s jasnou strukturou, nebo jednorázový úkol?",
        "Jde o opakující se složitý úkol, kde by pomohl agent nebo workflow?",
        "Mám dost kontextu, aby výstup byl kvalitní?",
        "Jaký nástroj je pro tuto situaci skutečně vhodný?",
      ],
      "Tento týden si každý prvek PACT rozložíme. Cíl: na konci týdne mít jasno v tom, jak AI zapojit systematicky do svého pracovního kontextu.",
    ],
    taskIntro: "Zamysli se nad svou aktuální prací a odpověz si na čtyři PACT otázky:",
    taskItems: [
      "Projects: Který aktuální projekt by mohl mít jasnou AI-asistovanou strukturu?",
      "Agents: Máš složitý opakující se úkol, kde by mohl fungovat multi-step workflow?",
      "Context: Jaký kontext o sobě, své roli nebo práci AI nemá, a přitom by výstupy výrazně zlepšil?",
      "Tools: Které AI nástroje používáš a proč — nebo je používáš náhodně bez jasného důvodu?",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Projects — jak naplánovat reálný projekt s AI pomocí WBS.",
  },
  {
    day: 9,
    title: "Projects: naplánuj reálný projekt s AI pomocí WBS.",
    subject: "AI jako spolupracovník na struktuře projektu.",
    preheader: "AI nezná tvůj projekt. Ale pokud jí ho popíšeš, pomůže ti ho rozložit.",
    concept: [
      "První prvek PACT frameworku jsou Projects — způsob, jak AI zapojit do reálné projektové práce.",
      "Nejčastější chyba: AI se používá na jednotlivé části projektu (napsat email, shrnout dokument), ale ne na projekt jako celek. Výsledek je fragmentovaná pomoc bez přidané hodnoty na úrovni celku.",
      "Work Breakdown Structure (WBS) je technika, která projekt rozloží na přehledné vrstvy výstupů a kroků. S AI ji lze vytvořit rychle — a výsledek slouží jako základ pro celý projekt, komunikaci se stakeholdery i delegování.",
      "Jak WBS s AI funguje: popíšeš projekt — cíl, scope, klíčová omezení — a AI ti pomůže:",
      [
        "Identifikovat hlavní fáze a výstupy v každé fázi",
        "Rozložit fáze na konkrétní kroky a zodpovědnosti",
        "Upozornit na závislosti a rizika",
        "Navrhnout rámcový časový odhad",
      ],
      "Kdy AI v Projects opravdu pomáhá: když máš projekt, který je komplexní nebo nový, kde nemáš jasno v rozsahu, nebo kde potřebuješ rychle strukturu pro komunikaci se stakeholdery.",
      "WBS s AI není finální plán — je to výchozí bod. Rychlý přehled, který pak upravuješ dle reality. Ale vytvořit ho trvá 10 minut místo 3 hodin.",
    ],
    taskIntro: "Vyber si jeden aktuální projekt a nech si vytvořit WBS s AI:",
    taskItems: [
      "Napiš popis projektu: co je cíl, co je v scope, kdo je zapojen, jaký je rámcový termín",
      "Zadej AI instrukci pro WBS (viz prompt níže)",
      "Projdi výsledek a uprav dle reality — přidej co AI vynechala, odeber co nedává smysl",
    ],
    taskType: "ol",
    taskPrompt: "Vytvoř WBS pro tento projekt: [popis projektu — cíl, scope, zapojení lidé, termín]. Rozlož ho na: 1) hlavní fáze s výstupy, 2) konkrétní kroky v každé fázi, 3) závislosti mezi fázemi, 4) potenciální rizika. Výstup ve strukturovaném formátu.",
    taskFallback: `Pokud nemáš vhodný projekt, použij cvičné zadání:
"Projekt: Zavedení nového onboarding procesu pro nové zaměstnance. Cíl: zkrátit dobu potřebnou k plné produktivitě z 3 měsíců na 6 týdnů. Zapojeni: HR, přímý nadřízený, IT. Termín: Q3."`,
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Agents — co jsou AI agenti, kdy dávají smysl a kdy jsou zbytečně složití.",
  },
  {
    day: 10,
    title: "Agents: kdy dávají smysl a kdy jsou zbytečně složití.",
    subject: "Co jsou AI agenti a jak o nich přemýšlet.",
    preheader: "Agent není magic. Je to workflow. A workflow musí mít smysl.",
    concept: [
      "Druhý prvek PACT frameworku jsou Agents — AI agenti a automatizované workflow.",
      "Co je AI agent: zjednodušeně jde o AI, která neprovádí jen jeden úkol, ale sérii kroků — reaguje na výsledek předchozího kroku, rozhoduje se co udělat dál, a může volat nástroje nebo jiné modely.",
      "Kdy agenti dávají smysl:",
      [
        "Opakující se složitý úkol, kde je jasná sekvence kroků a každý krok závisí na výstupu předchozího",
        "Zpracování velkého objemu vstupů — agent prochází data, kategorizuje, filtruje",
        "Paralelní zpracování — agent spouští více úkolů najednou a kombinuje výstupy",
        "Monitoring nebo alerting — agent sleduje stav a upozorní, když nastane podmínka",
      ],
      "Kdy agenti nepomáhají nebo komplikují:",
      [
        "Jednorázové nebo jednoduché úkoly — přidávají složitost bez hodnoty",
        "Kreativní práce s vysokou mírou lidského úsudku — agent nenahradí rozhodování",
        "Úkoly, kde je vstup pokaždé velmi odlišný — agent potřebuje konzistentní strukturu vstupu",
      ],
      "Praktický test pro agenty: má tento úkol jasný spouštěč, jasné kroky a jasný výstup? Opakuje se pravidelně? Pokud ano na obě — je kandidát na agenta. Pokud ne — stačí dobrý prompt.",
      "Pro tuhle challenge se soustředíme na jednodušší multi-step workflow — sérii promptů, kde výstup jednoho kroku je vstup druhého. Agenti v technickém slova smyslu jsou pokročilejší téma.",
    ],
    taskIntro: "Identifikuj jeden opakující se složitý úkol ze své práce a zhodnoť:",
    taskItems: [
      "Má jasný spouštěč a předvídatelné kroky? (podmínka pro workflow)",
      "Opakuje se pravidelně ve stejné nebo podobné struktuře?",
      "Navrhni: jak by vypadal jako tříkrokový workflow — co je vstup, co jsou kroky, co je výstup",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Agents v praxi — sestavíš multi-step workflow pro jeden reálný úkol.",
  },
  {
    day: 11,
    title: "Agents v praxi: multi-step workflow pro složitý úkol.",
    subject: "Postav workflow, kde každý krok staví na předchozím.",
    preheader: "Jeden složitý úkol. Tři kroky. Každý navazuje na předchozí.",
    concept: [
      "Teorie agentů je za námi. Dnes jde o praxi: postavíš multi-step workflow pro jeden opakující se úkol.",
      "Multi-step workflow s AI je sekvence promptů, kde výstup jednoho kroku je vstup dalšího. Nepoužíváš nástroj automatizace — pracuješ v jedné konverzaci nebo v sérii konverzací, ale s jasnou strukturou.",
      "Ukázka multi-step workflow pro přípravu klientské nabídky:",
      [
        "Krok 1 — Analýza kontextu: 'Tady jsou informace o klientovi a jeho situaci. Identifikuj klíčové potřeby a potenciální námitky.'",
        "Krok 2 — Struktura nabídky: 'Na základě analýzy z kroku 1 navrhni strukturu nabídky — sekce, klíčové argumenty pro každou sekci, co zdůraznit první.'",
        "Krok 3 — Draft: 'Napiš draft nabídky podle struktury z kroku 2. Tón: profesionální ale přátelský. Délka: max 1 strana A4.'",
      ],
      "Proč je tato struktura silnější než jeden prompt: každý krok zpřesňuje vstup pro následující. Výsledek je relevantní pro konkrétní situaci, ne generický.",
      "Kde multi-step workflow přidává hodnotu: složité výstupy (nabídky, reporty, strategie), kde je potřeba nejdřív analyzovat a pak tvořit. Jednoduchý email nebo shrnutí nepotřebuje workflow.",
      "Cíl dnešního dne: vzít úkol z D10 a postavit pro něj konkrétní tříkrokový workflow. Pak ho otestovat.",
    ],
    taskIntro: "Vezmi úkol z D10 a postav tříkrokový workflow:",
    taskItems: [
      "Krok 1: Co je vstup a co má AI analyzovat nebo zjistit?",
      "Krok 2: Co staví na výstupu kroku 1 a co má AI navrhnout nebo strukturovat?",
      "Krok 3: Co je finální výstup a jak má vypadat?",
    ],
    taskType: "ol",
    taskPrompt: "Krok 1: [instrukce pro analýzu vstupu]. \nKrok 2: Na základě výstupu kroku 1, [instrukce pro strukturu nebo návrh]. \nKrok 3: Na základě výstupu kroku 2, [instrukce pro finální výstup — formát, tón, délka].",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Context — proč kontext rozhoduje víc než samotný prompt.",
  },
  {
    day: 12,
    title: "Context: proč kontext rozhoduje víc než prompt.",
    subject: "Nejdůležitější část PACT frameworku — a proč ji většina lidí přehlíží.",
    preheader: "Stejný prompt, jiný kontext — zcela jiný výsledek.",
    concept: [
      "Třetí prvek PACT frameworku je Context — a je to pravděpodobně nejdůležitější ze čtyř.",
      "Experiment: vezmi libovolný prompt a zadej ho dvakrát — jednou bez kontextu a jednou s detailním kontextem. Výsledky budou tak odlišné, jako by to bylo od jiné AI.",
      "Proč kontext rozhoduje: AI zpracovává tvůj vstup a generuje pravděpodobnostní výstup na základě toho, co ví. Bez kontextu ví obecné věci. S kontextem ví tvoji situaci. A výstup odpovídá tomu, co ví.",
      "Tři typy kontextu, které mají největší vliv:",
      [
        "Kontext role a osoby: kdo jsi, co děláš, pro koho a s jakými omezeními — to nastaví celý tón a relevanci",
        "Kontext situace: co se konkrétně děje, co je v sázce, co je cílem, jaká jsou fakta",
        "Kontext výstupu: pro koho je výsledek, co o tématu ví, jaká je jejich perspektiva",
      ],
      "Největší chyba v práci s kontextem: myslet si, že kontext je jen o délce. Kontext může být jedna věta — pokud je to správná věta. 'Píšu nabídku pro konzervativní finanční klientelu' změní výstup dramatičtěji než tři odstavce irelevantního kontextu.",
      "System prompt jako nástroj kontextu: system prompt je způsob, jak dát AI trvalý kontext pro celou konverzaci nebo pro opakované použití. Je to jako nástup nového zaměstnance — jednou dobře briefuješ, a pak to nemusíš opakovat.",
      "Zítra si napíšeš svůj vlastní system prompt — kontext, který budeš používat opakovaně.",
    ],
    taskIntro: "Proveď experiment s kontextem — uvidíš rozdíl okamžitě:",
    taskItems: [
      "Vezmi libovolný prompt, který plánuješ nebo běžně používáš",
      "Zadej ho nejprve bez kontextu — ulož výsledek",
      "Přidej detailní kontext (kdo jsi, jaká je situace, pro koho je výstup) a zadej znovu",
      "Porovnej oba výstupy — zapiš si konkrétní rozdíl",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: napíšeš svůj pracovní system prompt — kontext, který použiješ znovu a znovu.",
  },
  {
    day: 13,
    title: "Context v praxi: napiš svůj pracovní system prompt.",
    subject: "Jednou napsat. Použít stokrát.",
    preheader: "System prompt je tvůj stálý briefing pro AI.",
    concept: [
      "Teorie kontextu je za námi. Dnes tvoříš: napíšeš svůj pracovní system prompt.",
      "System prompt je dokument nebo pasáž, která AI okamžitě dává kontext o tobě, tvé roli a tvých preferovaných způsobech spolupráce. Přidáš ho na začátek každé nové konverzace — nebo ho nastavíš v Custom Instructions v ChatGPT nebo v Project Settings v Claudovi.",
      "Co dobrý system prompt obsahuje:",
      [
        "Kdo jsi: role, obor, typ organizace, délka praxe",
        "Co děláš: 3–5 typických úkolů, pro koho výstupy tvoříš",
        "Jak pracuješ: preferovaný tón, délka výstupů, co nechceš",
        "Kontext organizace nebo oboru: co je specifické pro tvůj kontext — terminologie, kultura, omezení",
        "Preferovaný formát: odrážky nebo odstavce, strukturované nebo volné",
      ],
      "Jak system prompt použít: zkopíruj ho na začátek každé nové konverzace s AI. Nebo ulož do Custom Instructions / Project Settings. AI pak okamžitě 'ví', s kým mluví — a výstupy budou relevantnější bez opakovaného briefingu.",
      "Nejdůležitější vlastnost system promptu: není dokonalý napoprvé. Napiš první verzi dnes, otestuj ji tento týden a uprav co nesedí. System prompt je živý dokument.",
    ],
    taskIntro: "Napiš svůj pracovní system prompt — v 5 sekcích:",
    taskItems: [
      "Kdo jsem a co dělám: role, obor, typické výstupy",
      "Pro koho pracuji: interní tým, klienti, vedení — a co o mé práci vědí",
      "Jak preferuji komunikovat: tón, délka, formát",
      "Co AI nesmí dělat nebo předpokládat: omezení, citlivé oblasti",
      "Kontext organizace nebo oboru: co je specifické, co AI bez vysvětlení neví",
    ],
    taskType: "ol",
    taskPrompt: "Pracuji jako [role] v [typ organizace/obor]. Moje typické úkoly jsou: [3–5 konkrétních věcí]. Výstupy tvoříme pro [kdo]. Preferovaný tón: [přátelský/formální/přímý]. Preferovaná délka výstupů: [krátká/střední/podrobná]. Formát: [odrážky/odstavce]. Co nechci: [co AI nemá dělat]. Specifický kontext: [co je pro mou práci nebo obor důležité vědět].",
    taskTip: "System prompt ulož do svého knowledge base z předchozích dní — a přidej ho jako Custom Instructions v ChatGPT nebo Project Instructions v Claudovi.",
    teaser: "Zítra: PACT checkpoint — co z frameworku skutečně používáš a co ti přináší hodnotu.",
  },
  {
    day: 14,
    title: "PACT checkpoint: co z frameworku skutečně používáš.",
    subject: "Polovina Advanced challenge — čas zmapovat, kde jsi.",
    preheader: "Framework bez reflexe je jen teorie.",
    concept: [
      "Čtrnáct dní je za námi. Celý 3C framework a celý PACT framework jsou za sebou. Dnes je reflexe — ne test, ale mapování reality.",
      "Nejužitečnější otázka dne: které části 3C a PACT opravdu používám a které zůstaly jen jako teorie?",
      [
        "3C — Capture: zachytuji pravidelně? Funguje mi filtr? Nebo pořád zachycuji příliš mnoho nebo příliš málo?",
        "3C — Clean: zpracovávám záznamy nebo se hromadí? Pomáhá mi AI s Clean?",
        "3C — Connect: vracím se ke starým znalostem nebo je ignoruji?",
        "PACT — Projects: byl v praxi použit WBS nebo strukturovaný přístup k projektu?",
        "PACT — Agents: mám nějaký workflow, který funguje opakovaně?",
        "PACT — Context: je system prompt nastavený a v pravidelném používání?",
        "PACT — Tools: mám jasno, proč používám které nástroje?",
      ],
      "Klíčový poznatek: není problém, pokud část frameworku nepoužíváš. Problém nastane, pokud to nevíš. Reflexe ti ukáže, kde je příležitost.",
      "Druhá polovina Advanced challenge se zaměří na Superpowers — pět schopností, které AI spoluprací skutečně získáváš. A pak na Scale — jak to celé převést na systém, který pracuje za tebe.",
    ],
    taskIntro: "PACT checkpoint — projdi každý prvek a zhodnoť:",
    taskItems: [
      "Capture, Clean, Connect: pro každý napiš jednu větu — funguje, nebo kde jsou díry?",
      "Projects, Agents, Context, Tools: pro každý napiš jednu větu — používáš, nebo zůstalo jen jako teorie?",
      "Jedno konkrétní zlepšení: co z výše uvedeného chceš příštích 14 dní aktivně zlepšit?",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden: Superpowers — pět schopností, které AI spoluprací získáváš.",
  },
  {
    day: 15,
    title: "Pět superschopností, které AI spoluprací skutečně získáváš.",
    subject: "Perception, Intelligence, Memory, Creation, Connection.",
    preheader: "Nejcennější věci, které AI spolupráce přinese, nejsou výstupy. Jsou to schopnosti.",
    concept: [
      "Třetí týden challenge je o Superpowers — pěti schopnostech, které AI spoluprací skutečně získáváš.",
      "Tento pohled je odlišný od toho, co většina lidí o AI slyší. Většina diskuze je o tom, co AI udělá za tebe. Ale ještě cennější je to, co tě AI spolupráce naučí — schopnosti, které si pak neseš i bez AI.",
      "Pět superschopností:",
      [
        "Perception — schopnost vidět vzorce a strukturu tam, kde jiní vidí chaos",
        "Intelligence — schopnost lépe rozhodovat díky strukturovanému dialogu s AI jako myšlenkovým partnerem",
        "Memory — schopnost pracovat s informacemi a znalostmi systematicky, ne se spoléhat jen na paměť",
        "Creation — schopnost rychle vytvářet kvalitní první verze a iterovat — bez paralýzy prázdné stránky",
        "Connection — schopnost propojovat myšlenky, lidi a zdroje způsoby, které by bez AI trvaly mnohem déle",
      ],
      "Proč jsou to superschopnosti, ne jen funkce AI: pokud AI zítra přestane existovat, tyto schopnosti ti zůstanou. Vědomí o vzorcích, systematická práce s pamětí, iterativní tvorba — to jsou způsoby myšlení, které AI trénování posiluje.",
      "Tento týden si každou superschopnost rozložíme do teorie a praxe. Dnes je přehled — zítra jdeme do hloubky s první: Perception.",
    ],
    taskIntro: "Zamysli se nad pěti superschopnostmi a odpověz si:",
    taskItems: [
      "Která z pěti ti přijde jako tvoje přirozeně silnější stránka?",
      "Která je tvoje největší příležitost — kde cítíš, že AI spolupráce může přidat nejvíc?",
      "Zapiš si jednu konkrétní situaci z práce, kde by každá z superschopností mohla pomoci",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Perception — jak AI spoluprací trénuješ schopnost vidět vzorce a strukturu.",
  },
  {
    day: 16,
    title: "Perception: vidíš vzorce, které by ti jinak unikly.",
    subject: "Jak AI spoluprací trénuješ schopnost vidět strukturu v chaosu.",
    preheader: "Nejcennější věc není rychlejší výstup. Je to jiný způsob vidění.",
    concept: [
      "První superschopnost je Perception — schopnost vidět vzorce, strukturu a souvislosti tam, kde jiní vidí chaos nebo nesouvisející informace.",
      "Jak AI spolupráce trénuje Perception: AI velmi rychle nachází strukturu ve velkém množství textu nebo dat. Pokud s AI pracuješ pravidelně, začneš přebírat tento způsob pohledu — hledáš vzorce dřív, než začneš tvořit. Vidíš strukturu dřív, než ji pojmenuješ.",
      "Tři cvičení, která Perception posilují:",
      [
        "Pattern recognition: vlož AI velký objem materiálu a zeptej se — 'Jaké vzorce vidíš? Co se opakuje? Co vypadá neobvykle?' Pak zkus příště tentýž pohled udělat bez AI.",
        "Structure first: před každým novým úkolem se zeptej — 'Jaká je základní struktura tohoto problému? Co jsou klíčové proměnné?' Dříve než začneš tvořit.",
        "Anomaly detection: v jakémkoli datovém vstupu (reporty, zpětná vazba, zákaznické odpovědi) se zeptej AI — 'Co tady vypadá neobvykle nebo neočekávaně?' Trénuje tě vidět výjimky.",
      ],
      "Perception v kontextu 3C: Clean proces posiluje Perception — zpracování surového materiálu tě nutí hledat klíčové body a vzorce. Po měsíci Clean rutiny tě tenhle způsob pohledu začne přicházet automaticky.",
      "Klíčový poznatek: Perception nelze natrénovat čtením. Trénuje se praxí — opakovaným hledáním vzorců ve vlastní práci. AI je tvůj tréninkový partner.",
    ],
    taskIntro: "Perception cvičení — vezmi velký kus materiálu ze své práce:",
    taskItems: [
      "Vyber materiál: transkripty schůzek, zákaznická zpětná vazba, projektové poznámky, nebo data z reportu",
      "Vlož AI a zadej: 'Jaké vzorce vidíš? Co se opakuje? Co je neobvyklé nebo překvapivé?'",
      "Porovnej výstup s vlastním pohledem — co AI viděla jinak, co tě překvapilo?",
    ],
    taskType: "ol",
    taskPrompt: "Tady je [typ materiálu]: [vlož materiál]. Proveď Perception analýzu: 1) Jaké vzorce nebo opakující se témata vidíš? 2) Co se zdá neobvyklé nebo překvapivé? 3) Jaká je základní struktura nebo logika tohoto materiálu?",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Intelligence — jak AI spoluprací trénuješ schopnost lépe rozhodovat.",
  },
  {
    day: 17,
    title: "Intelligence: lepší rozhodnutí s AI jako myšlenkovým partnerem.",
    subject: "Jak AI spoluprací trénuješ schopnost lépe rozhodovat.",
    preheader: "AI nerozhodne za tebe. Ale pomůže ti udělat lepší rozhodnutí.",
    concept: [
      "Druhá superschopnost je Intelligence — schopnost lépe rozhodovat díky strukturovanému dialogu s AI jako myšlenkovým partnerem.",
      "AI nerozhoduje za tebe. Ale může ti pomoci strukturovat rozhodnutí způsobem, který odhalí slepé skvrny, zpochybní předpoklady a ukáže alternativy.",
      "Čtyři způsoby, jak AI pomáhá s rozhodováním:",
      [
        "Devil's advocate: 'Tady je moje rozhodnutí. Hraj ďáblova advokáta — jaké jsou nejsilnější argumenty proti?'",
        "Předpoklady: 'Tady je moje uvažování. Jaké předpoklady toto rozhodnutí vyžaduje? Které z nich jsou nejriskantnější?'",
        "Pre-mortem: 'Představ si, že toto rozhodnutí za rok selže. Co pravděpodobně způsobilo selhání?'",
        "Alternativy: 'Jaké jsou tři alternativní přístupy k tomuto problému, které v dosavadním uvažování nezazněly?'",
      ],
      "Proč to trénuje Intelligence: každé z těchto cvičení tě nutí rozdělit rozhodnutí na části a zkoumat ho strukturovaně. Pokud tuto metodu opakuješ, začneš ji aplikovat automaticky — i bez AI.",
      "Důležitá hranice: AI je myšlenkový partner, ne rozhodovací nástroj. Konečné rozhodnutí je vždy na tobě. AI ti dá šíři pohledu — ty dáš odborný úsudek a odpovědnost.",
      "Klíčová chyba: ptát se AI 'co mám udělat?' místo 'pomoz mi promyslet tuto situaci'. První otázka vypíná tvoje myšlení. Druhá ho zapíná.",
    ],
    taskIntro: "Vyber jedno rozhodnutí, které aktuálně řešíš, a projdi ho těmito čtyřmi kroky:",
    taskItems: [
      "Napiš své aktuální uvažování — proč se klonit k té možnosti, kterou teď preferuješ",
      "Požádej AI o devil's advocate — nejsilnější argumenty proti tvé preferované volbě",
      "Požádej AI o pre-mortem — co by za rok mohlo způsobit selhání",
      "Zapoj výstupy do svého rozhodování — co to změnilo nebo potvrdilo?",
    ],
    taskType: "ol",
    taskPrompt: "Řeším toto rozhodnutí: [popis situace a tvé aktuální uvažování]. \n1) Hraj ďáblova advokáta — jaké jsou nejsilnější argumenty proti mé preferované volbě? \n2) Jaké předpoklady moje uvažování vyžaduje? Které jsou nejriskantnější? \n3) Pre-mortem: pokud toto rozhodnutí za rok selže, co pravděpodobně způsobilo selhání?",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Intelligence v praxi — analyzuješ reálné rozhodnutí, které teď řešíš.",
  },
  {
    day: 18,
    title: "Intelligence v praxi: analyzuj rozhodnutí, které teď řešíš.",
    subject: "Structured decision-making s AI — od uvažování k akci.",
    preheader: "Teorie rozhodování je jedna věc. Praxe je jiná.",
    concept: [
      "Teorie Intelligence je za námi. Dnes jde o praxi — vezmeš reálné rozhodnutí ze svého pracovního kontextu a projdeš ho celým procesem.",
      "Proč je praxe obtížnější než teorie: reálná rozhodnutí mají nejistotu, emoční složku a politický kontext. AI ti pomůže s analytickou složkou — ale emoční a politická složka je na tobě.",
      "Tři typy rozhodnutí, kde AI Intelligence přidává nejvíc:",
      [
        "Strategická rozhodnutí s nejasným outcome: kde volba závisí na předpokladech o budoucnosti",
        "Mezioborová rozhodnutí: kde je potřeba integrovat více perspektiv najednou",
        "Rozhodnutí pod časovým tlakem: kde AI rychle strukturuje to, co by jinak trvalo hodiny debatování",
      ],
      "Jak zvládnout rozhodnutí s vysokou emoční náloží: nejdřív napiš AI, jak se na situaci cítíš — bez filtrů. Pak požádej o strukturovanou analýzu. Oddělení emocí a analýzy ti dá jasnost, která v přímé diskuzi přijde obtížně.",
      "Klíčový poznatek: AI vidí tvoji situaci bez emocí a bez politiky. To je výhoda i limit. Výhoda: jasnost a šíře pohledu. Limit: AI nezná kontext, který nikdy nenapíšeš.",
    ],
    taskIntro: "Vezmi reálné rozhodnutí ze svého pracovního kontextu a projdi ho structured decision-making procesem:",
    taskItems: [
      "Napiš situaci: co řešíš, jaké jsou možnosti, co tě drží v nerozhodnosti",
      "Projdi čtyři Intelligence kroky z D17: devil's advocate, předpoklady, pre-mortem, alternativy",
      "Zapiš: co tě AI výstup překvapil nebo změnil? Co potvrdil? Co uděláš jinak díky tomuto procesu?",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: zbývající tři superschopnosti — Memory, Creation, Connection.",
  },
  {
    day: 19,
    title: "Memory, Creation, Connection: zbývající tři superschopnosti.",
    subject: "Tři superschopnosti, které dokončují obraz.",
    preheader: "Paměť, tvorba, propojení — a jak je AI spoluprací rozvíjíš.",
    concept: [
      "Perception a Intelligence máme za sebou. Dnes přidáme zbývající tři superschopnosti — a spojíme to celé.",
      "Memory — schopnost pracovat s informacemi systematicky, bez spoléhání na přirozenou paměť:",
      [
        "AI spolupráce tě nutí zachycovat a zpracovávat (viz 3C) — a tím posiluje schopnost pracovat s externím systémem paměti",
        "V praxi: system prompt, knowledge base, opakující se kontext — to jsou nástroje externalizované paměti",
        "Superschopnost: přestáváš spoléhat na to, co si pamatuješ — a začínáš budovat systém, který funguje i bez tebe",
      ],
      "Creation — schopnost rychle vytvářet první verze a iterovat bez paralýzy:",
      [
        "AI spolupráce trénuje tě k iterativní tvorbě — první draft je základ, ne finální produkt",
        "Superschopnost: překonávání prázdné stránky. Kdykoli nevíš, jak začít, máš způsob — požádej AI o první verzi",
        "V praxi: komplexní výstupy (nabídky, strategie, prezentace) vznikají rychleji a ve vyšší kvalitě",
      ],
      "Connection — schopnost propojovat myšlenky, lidi a zdroje:",
      [
        "AI spolupráce tě vystavuje širšímu kontextu — AI vidí souvislosti, které by trvalo roky zkušeností identifikovat",
        "V praxi: mezioborové myšlení, propojování zdánlivě nesouvisejících věcí, identifikace expertů nebo zdrojů",
        "Superschopnost: naučíš se klást otázku 'kdo nebo co jiného tohle řeší?' — a hledat inspiraci mimo vlastní obor",
      ],
      "Pět superschopností dohromady: Perception vidí vzorce. Intelligence strukturuje rozhodnutí. Memory uchovává a zpřístupňuje. Creation realizuje. Connection propojuje. Spolupráce s AI je posiluje — ale jsou tvoje.",
    ],
    taskIntro: "Pro každou ze tří zbývajících superschopností napiš jeden konkrétní příklad z tvé práce:",
    taskItems: [
      "Memory: kde spoléháš na paměť, ale systém by fungoval líp? Kde by externalizovaná paměť přidala hodnotu?",
      "Creation: kde tě blokuje prázdná stránka nebo začátek? Kde by AI draft pomohl překonat začátek?",
      "Connection: kde by propojení s jinou oblastí, oborem nebo člověkem přineslo nový pohled?",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Creation v praxi — komplexní výstup od nuly, s iterací.",
  },
  {
    day: 20,
    title: "Creation: komplexní výstup od nuly s iterací.",
    subject: "Postav komplexní výstup v šesti krocích.",
    preheader: "Paralýza prázdné stránky přestane existovat, když máš proces.",
    concept: [
      "Creation superschopnost je dnes na řadě v praxi. Vezmeš komplexní výstup — takový, který by ti normálně trval hodiny — a projdeš ho celým iterativním procesem s AI.",
      "Co je komplexní výstup: ne jeden email nebo krátké shrnutí. Ale strategie, prezentace, nabídka, analýza, konzultační doporučení, nebo jakýkoli výstup, kde je prázdná stránka největší překážka.",
      "Šest kroků pro Creation s AI:",
      [
        "Define: Napiš přesně, co chceš vytvořit — pro koho, proč, v jakém formátu, jaký je cíl",
        "Structure: Požádej AI o strukturu — přehled sekcí a logiku toku, ne samotný obsah",
        "Draft sections: Pro každou sekci zvlášť napiš prompt — tak dostaneš relevantnější obsah než v jednom velkém promptu",
        "Synthesize: Zkombinuj sekce, projdi celý výstup — co chybí, co je přebytečné, co špatně sedí",
        "Refine: Iteruj — konkrétní instrukce pro každou slabou část",
        "Final review: Projdi z pohledu čtenáře — je to srozumitelné, přesvědčivé, použitelné?",
      ],
      "Proč sekce zvlášť fungují líp než jeden velký prompt: každá sekce má jiný cíl, jiný tón, jiná omezení. Jeden prompt pro celý výstup generuje průměr. Prompty pro sekce generují optimum.",
      "Dnes budeš pracovat déle než obvyklých 5–10 minut. Creation práce si zaslouží 20–30 minut. Ale výstup, který dostaneš, bude stát za to.",
    ],
    taskIntro: "Vyber si komplexní výstup ze své práce a proveď ho šestikrokovým procesem Creation:",
    taskItems: [
      "Define: co tvoříš, pro koho, proč a v jakém formátu",
      "Structure: nech AI navrhnout strukturu — pak uprav dle reality",
      "Draft: proveď každou sekci jako samostatný prompt, zkombinuj",
      "Refine: iteruj slabé části, finalizuj",
    ],
    taskType: "ol",
    taskPrompt: "Tvoříme [typ výstupu] pro [příjemce/publikum]. Cíl: [co má výstup dosáhnout]. Kontext: [relevantní info]. \nKrok 1: Navrhni strukturu — přehled sekcí s jednovětným popisem každé. \nKrok 2 (pro každou sekci zvlášť): Napiš sekci [název sekce] v délce [délka] v tónu [tón].",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: reflexe Superpowers — která ti sedí a kterou chceš dál rozvíjet.",
  },
  {
    day: 21,
    title: "Tvoje AI superschopnosti: která ti sedí, kterou chceš rozvíjet?",
    subject: "Reflexe Superpowers týdne — a tvůj osobní profil.",
    preheader: "Nejlepší systém rozvoje je ten, který vychází z tebe.",
    concept: [
      "Třetí týden je za námi. Všech pět superschopností — Perception, Intelligence, Memory, Creation, Connection — je v teorii i praxi za sebou.",
      "Dnes je reflexe: ne co proběhlo, ale co z toho jde dál.",
      "Proč je reflexe Superpowers důležitá: každý člověk pracuje s AI jinak. Každý má jiné přirozené silné stránky. A každý má jiné oblasti, kde je AI spolupráce největší příležitost. Znát svůj profil ti pomůže investovat energii tam, kde efekt bude největší.",
      "Pět otázek pro Superpowers reflexi:",
      [
        "Perception: Používáš AI pro hledání vzorců pravidelně? Nebo jde stále o jednorázové experimenty?",
        "Intelligence: Byl AI structured decision-making vyzkoušen v reálné situaci? Co to přineslo?",
        "Memory: Funguje ti 3C systém jako externalizovaná paměť? Nebo stále spoléháš hlavně na hlavu?",
        "Creation: Překonala AI spolupráce paralýzu prázdné stránky? Iteruješ nebo stále čekáš na dokonalý první draft?",
        "Connection: Hledáš aktivně propojení a analogie z jiných oborů? Nebo zůstáváš v úzkém kontextu?",
      ],
      "Tvůj Superpowers profil není dokonalý obraz — je to výchozí bod pro další rozvoj. Čtvrtý týden se zaměří na Scale: jak vše vybudované převést na systém, který pracuje za tebe.",
    ],
    taskIntro: "Napiš svůj Superpowers profil — stručně a konkrétně:",
    taskItems: [
      "Tvoje přirozeně silnější superschopnosti (1–2): kde ti přijde AI spolupráce nejpřirozenější",
      "Tvoje největší příležitost (1): kde je největší potenciál pro zlepšení",
      "Jeden konkrétní krok pro čtvrtý týden: co budeš aktivně dělat jinak",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden: Scale — Human-in-the-loop, workflow s checkpointy, AI adoption v týmu a systém, který pracuje za tebe.",
  },
  {
    day: 22,
    title: "Human-in-the-loop: kde jsi ty v AI procesu.",
    subject: "Jak navrhnout systém, kde AI pracuje, ale ty kontroluješ.",
    preheader: "Nejlepší AI systém není ten, kde AI dělá vše. Je to ten, kde ví, kde jsi potřeba.",
    concept: [
      "Čtvrtý týden je o Scale — jak vše vybudované převést na systémy, které pracují za tebe. A první otázka, na kterou musíš odpovědět: kde jsi v procesu ty?",
      "Human-in-the-loop (HITL) je princip návrhu AI systémů: AI dělá to, co dělá dobře, ale člověk je zapojen v klíčových rozhodovacích bodech.",
      "Proč HITL záleží: plně automatizovaný systém bez lidské kontroly funguje skvěle — dokud selže. A pak selže katastrofálně. HITL systémy jsou robustnější, protože člověk zachytí chyby, které AI nevidí.",
      "Tři typy zapojení člověka:",
      [
        "Human-before: člověk definuje vstup, kontext a cíl — AI pak provede",
        "Human-in: člověk schvaluje nebo opravuje v klíčových krocích workflow",
        "Human-after: AI provede celý úkol, člověk zkontroluje a schválí výsledek",
      ],
      "Jak rozhodnout, kde být v procesu:",
      [
        "Vysoké riziko selhání nebo velký dopad: human-before nebo human-in",
        "Nízké riziko a opakující se strukturovaný úkol: human-after",
        "Kreativní nebo vysoce personalizovaný výstup: human-before, silný kontext",
      ],
      "Dnešní cíl: zmapovat jeden ze svých opakujících se úkolů a rozhodnout, kde je správné místo pro lidský vstup.",
    ],
    taskIntro: "Vezmi jeden opakující se úkol ze svého pracovního kontextu a navrhni HITL strukturu:",
    taskItems: [
      "Popiš úkol: co je vstup, co jsou kroky, co je výstup",
      "Rozhodni: human-before, human-in nebo human-after — kde je tvoje přidaná hodnota?",
      "Napiš konkrétně: co AI dělá a kde přesně vstupuješ ty — co kontroluješ, co schvaluješ, co upravuješ",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: nakresli svůj workflow — kde jsi ty, kde pracuje AI, kde jsou checkpointy.",
  },
  {
    day: 23,
    title: "Nakresli svůj workflow: kde jsi ty, kde pracuje AI.",
    subject: "Workflow s checkpointy — vizualizace systému.",
    preheader: "Systém, který nevidíš, nemůžeš optimalizovat.",
    concept: [
      "Včerejší den vyjasnil, kde v procesu stojíš. Dnes to vizualizuješ — nakreslíš (nebo napíšeš) svůj workflow.",
      "Proč vizualizace záleží: workflow, který máš jen v hlavě, je workflow, který nemůžeš sdílet, optimalizovat ani delegovat. Jakmile ho nakreslíš nebo popíšeš, vidíš ho jinak.",
      "Jak popsat workflow — čtyři prvky:",
      [
        "Spouštěč: co spustí proces? (nová žádost klienta, týden, konkrétní událost)",
        "Kroky: co se stane v jakém pořadí? (kdo nebo co — ty nebo AI)",
        "Checkpointy: kde jsou body lidské kontroly?",
        "Výstup: co je finální výsledek a komu slouží?",
      ],
      "Jak AI pomáhá s návrhem workflow: popis svého současného procesu zadej AI a požádej: 'Identifikuj kroky, kde by AI mohla pomoct, a navrhni kde jsou správné checkpointy pro lidskou kontrolu.' AI ti vrátí strukturovaný pohled, který pak uprav.",
      "Cíl dnešního dne: mít popsaný workflow pro jeden konkrétní opakující se proces — tak, aby ho mohl sledovat i někdo jiný. To je základ pro delegování nebo zdokonalování.",
    ],
    taskIntro: "Napiš nebo nakresli workflow pro jeden ze svých opakujících se procesů:",
    taskItems: [
      "Spouštěč: co spustí tento proces?",
      "Kroky v pořadí: co se stane, kdo to dělá (ty nebo AI), co je výstup každého kroku",
      "Checkpointy: kde vstupuješ ty — co kontroluješ nebo schvaluješ",
      "Finální výstup: co vznikne a komu slouží",
    ],
    taskType: "ol",
    taskPrompt: "Tady je popis mého procesu pro [název procesu]: [popis současného procesu]. Identifikuj: 1) kde by AI mohla převzít nebo asistovat, 2) kde jsou správné checkpointy pro lidskou kontrolu, 3) jak by vypadal optimalizovaný workflow. Výstup jako strukturovaný přehled kroků.",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: AI adoption v týmu — jak sdílet znalost bez hype a bez odporu.",
  },
  {
    day: 24,
    title: "AI adoption v týmu: jak sdílet znalost bez hype a bez odporu.",
    subject: "Jak přenést AI práci na kolegy bez tlaku a bez technologie pro technologii.",
    preheader: "Nejlepší AI champion v týmu je ten, kdo ukazuje výsledky, ne evangelizuje.",
    concept: [
      "Jednou z největších příležitostí AI není to, čeho je možné s AI dosáhnout individuálně. Je to, co dokáže tým, když jsou sdílené znalosti, prompty a workflow.",
      "Ale AI adoption v týmu je jiná výzva než osobní AI adoption. Lidé mají různé technické zázemí, různý přístup k novým nástrojům a různé obavy. Přístup 'vyzkoušej, je to skvělé' nestačí.",
      "Tři přístupy k AI adoption v týmu, které fungují:",
      [
        "Show, don't tell: ukaž konkrétní výsledek ze své práce — čas, kvalita, jednoduchý proces. Výsledky přesvědčují více než argumenty.",
        "Start small: jeden prompt pro jeden opakující se úkol, který tým dělá pravidelně. Žádný velký projekt, žádný nový nástroj navíc.",
        "Build shared library: začni sdílenou sbírku promptů, šablon a workflow. Každý přispívá tím, co mu funguje. Systém roste organicky.",
      ],
      "Co adoption brzdí:",
      [
        "Přílišný hype: 'AI změní vše' vytváří odpor u skeptiků a zklamání u nadšenců, protože realita nikdy nedorovná hype",
        "Technická složitost: pokud vyžaduje adoption nový nástroj nebo velkou investici, většina lidí to odloží",
        "Bez jasného přínosu: pokud není jasné, co to ulehčí konkrétně tobě, nemáš důvod to zkusit",
      ],
      "Tvoje role v adoption: nejsi AI evangelista. Jsi někdo, kdo má výsledky — a je ochoten je sdílet. To je dostatečně silný příspěvek.",
    ],
    taskIntro: "Připrav adoption příspěvek pro svůj tým:",
    taskItems: [
      "Vyber jeden konkrétní výsledek nebo workflow, který ti z challenge funguje",
      "Napiš jednovětý popis: co to je, kolik to trvá a co to přinese kolegovi",
      "Sdílej ho s jedním kolegou — ústně, v chatu nebo jako dokument",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: nauč kolegu jeden AI trick — nebo ho zapiš jako mini guide.",
  },
  {
    day: 25,
    title: "Nauč kolegu jeden AI trick — nebo ho zapiš jako mini guide.",
    subject: "Znalost sdílená je znalost zdvojená.",
    preheader: "Nejlepší test, jestli něco chápeš: dokážeš to vysvětlit jednoduše.",
    concept: [
      "Jeden z nejlepších způsobů, jak prohloubit vlastní znalost, je učit ostatní. Pokud dokážeš vysvětlit, jak AI prompt funguje, jednoduše a bez žargonu — skutečně tomu rozumíš.",
      "Dnešní úkol má dvě varianty: nauč kolegu jeden trick osobně nebo ho zapiš jako mini guide.",
      "Osobní výuka (5–10 minut): vyber jeden konkrétní AI trick ze svého repertoáru, přejdi s kolegou přes jeden reálný příklad a nech ho zkusit samostatně. Cíl: kolega odejde s jedním použitelným promptem.",
      "Mini guide (alternativa): napiš dokument, který vysvětlí jeden AI trick nebo workflow. Obsah:",
      [
        "Co to je: jednovětý popis",
        "Proč to funguje: základní princip (jednoduše, bez teorie)",
        "Jak to udělat: krok za krokem, s konkrétním promptem",
        "Příklad výstupu: co dostaneš, pokud to uděláš správně",
      ],
      "Proč mini guide funguje lépe než sdílení linku nebo tooltipu: guide je kontextualizovaný pro váš tým a vaši práci. Obecný tutorial pokrývá obecné situace. Tvůj guide pokrývá váš kontext.",
      "Bonus: pokud kolega mini guide použije a vrátí ti zpětnou vazbu — co bylo nejasné, co funguje jinak — to přinese víc než hodina strávená na dalším tutorialu.",
    ],
    taskIntro: "Vyber si variantu a proveď ji dnes:",
    taskItems: [
      "Varianta A: Nauč kolegu jeden trick osobně — konkrétní prompt, reálný příklad, nech ho zkusit",
      "Varianta B: Napiš mini guide pro jeden AI trick nebo workflow ze své practice",
      "Po dokončení: zapiš si, co tě překvapilo — buď v odpovědích kolegy nebo v procesu psaní guide",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: leverage na úrovni systému — nástroj vs. způsob práce.",
  },
  {
    day: 26,
    title: "Leverage na úrovni systému: nástroj vs. způsob práce.",
    subject: "Rozdíl mezi 'používám AI' a 'AI je součást mého systému práce'.",
    preheader: "Největší leverage není v jednom skvělém promptu. Je v systému.",
    concept: [
      "Předposlední téma Advanced challenge se vrací k začátku — ale jinak.",
      "Na začátku challenge byl leverage definován jako: dosáhnout výsledku, který by jinak nebyl možný. Nebo by trvalo desetkrát déle. Leverage na úrovni jednotlivce.",
      "Leverage na úrovni systému je jiná věc: AI je zabudovaná do způsobu práce tak, že funguje za tebe — i když aktivně nepromýšlíš 'jak použít AI'. Stává se součástí procesu, ne nástrojem, který vědomě vytahuješ.",
      "Jak to vypadá v praxi:",
      [
        "Každé zahájení projektu automaticky zahrnuje WBS s AI — ne jako extra krok, ale jako součást startu projektu",
        "Každý týden je Clean rutina zabudovaná — pátek, 20 minut, Capture inbox zpracován",
        "System prompt je nastaven a přidává se automaticky — žádné manuální briefování",
        "Sdílená knihovna promptů v týmu roste organicky — každý přidá co mu funguje",
      ],
      "Systémový leverage vzniká z návyků a procesů, ne z motivace. Pokud si každé pondělí musíš připomínat 'dnes použiji AI', ještě nemáš systémový leverage. Pokud AI je prostě součástí toho, jak věci děláš — máš ho.",
      "Dnešní otázka: co z toho, co za 26 dní vzniklo, se stalo součástí systému práce? A co ještě není?",
    ],
    taskIntro: "Zmapuj svůj aktuální systémový leverage:",
    taskItems: [
      "Co z challenge se stalo rutinou nebo součástí způsobu práce? (konkrétní věci, ne obecné)",
      "Co stále vyžaduje vědomou snahu nebo připomínání?",
      "Jedno konkrétní rozhodnutí: co zabuduju do svého systému práce jako pravidelný krok — s konkrétním termínem",
    ],
    taskType: "ol",
    taskTip: "Pracuj přímo v Claude, ChatGPT nebo Gemini – výsledek si ulož do Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: postavíš end-to-end mini AI systém — na jeden ze svých klíčových procesů.",
  },
  {
    day: 27,
    title: "Postav end-to-end mini AI systém.",
    subject: "Jeden klíčový proces — od vstupu po výstup — s AI na každém kroku.",
    preheader: "Systém, který pracuje za tebe, začíná jako jeden dobře navržený proces.",
    concept: [
      "Předposlední den challenge. Dnes tvoříš — a tvoříš největší věc v celé challenge.",
      "End-to-end mini AI systém je jeden konkrétní proces ze tvé práce — od vstupu po výstup — navržený s AI na každém relevantním kroku, s jasnou HITL strukturou a dokumentovaný tak, aby ho mohl sledovat nebo použít i někdo jiný.",
      "Pět prvků dobrého mini AI systému:",
      [
        "Spouštěč: co spustí proces a jak poznám, že je čas ho spustit",
        "Vstup: co vkládám — data, kontext, materiál",
        "Kroky s AI: co dělá AI v každém kroku a s jakým promptem",
        "HITL checkpointy: kde vstupuji já — co kontroluji, schvaluji nebo upravuji",
        "Výstup: co vznikne a komu slouží",
      ],
      "Příklady mini AI systémů ze světa práce:",
      [
        "Týdenní reporting: Spouštěč: pátek 14h. Vstup: data z týdne. AI: strukturuje shrnutí, navrhuje klíčová čísla. HITL: ověřuji přesnost čísel, přidám kontext. Výstup: report pro vedení.",
        "Client onboarding: Spouštěč: nový klient podepsal. Vstup: informace o klientovi. AI: draft onboarding emailové sekvence. HITL: zkontroluji tón, personalizuji. Výstup: odeslané emaily.",
        "Projektová retrospektiva: Spouštěč: konec projektu. Vstup: zápisky, feedback, data. AI: strukturuje retrospektivu. HITL: doplním kontext, rozhodnu o prioritách. Výstup: retrospektivní záznam v Capture systému.",
      ],
      "Cíl dnešního dne je mít jeden fungující mini AI systém zdokumentovaný tak, aby ho mohl přečíst kolega a pochopit, jak ho spustit.",
    ],
    taskIntro: "Postav svůj end-to-end mini AI systém — dokumentovaný v pěti prvcích:",
    taskItems: [
      "Vyber proces: opakující se, komplexní a hodnotný — kde AI přidává nejvíc",
      "Dokumentuj pět prvků: spouštěč, vstup, AI kroky s prompty, HITL checkpointy, výstup",
      "Otestuj ho jedenkrát — projdi celý systém na reálném příkladu a zapiš co upravit",
    ],
    taskType: "ol",
    taskTip: "Systém ulož do svého knowledge base — tak aby byl dostupný tobě i kolegům.",
    teaser: "Zítra je závěr. 28 dní. Co za tu dobu vzniklo — a co přichází dál.",
  },
  {
    day: 28,
    title: "Systém je postaven. A teď pracuje za tebe.",
    subject: "Závěr Advanced challenge — a co přichází dál.",
    preheader: "Konec challenge. Začátek systému.",
    concept: [
      "Dvacet osm dní je za námi.",
      "Celá challenge šla přes čtyři vrstvy. 3C framework — Capture, Clean, Connect — základ pro práci se znalostmi v kontextu AI. PACT framework — Projects, Agents, Context, Tools — systematické přemýšlení o AI, ne sada triků. Superpowers — pět schopností, které AI spoluprací posiluješ. A Scale — Human-in-the-loop, workflow design, AI adoption v týmu, systémový leverage.",
      "Co si bereš z Advanced challenge:",
      [
        "3C systém jako základ práce se znalostmi — Capture, Clean, Connect jako rutina",
        "PACT jako způsob myšlení o AI v projektovém a pracovním kontextu",
        "Pět superschopností jako vědomý cíl rozvoje — co trénovat, kde je příležitost",
        "HITL jako princip návrhu AI workflow — kde jsi ty, kde pracuje AI",
        "Alespoň jeden dokumentovaný end-to-end mini AI systém",
      ],
      "Co přichází dál: tato challenge je konec kurzu, ne konec cesty. Vybudované systémy se zlepšují s každým týdnem používání. 3C systém bude za měsíc lepší, než je dnes. Navržený workflow se vyladí po prvním měsíci provozu.",
      "Jedna poslední otázka: co je jedno konkrétní rozhodnutí, které uděláš příštích 30 dní — jedno, které posune tvůj AI systém dál?",
      "Ber si to s sebou.",
    ],
    taskIntro: "Závěrečná reflexe Advanced challenge:",
    taskItems: [
      "Tři největší poznatky z celé challenge — konkrétní, ne obecné",
      "Jedno místo, kde AI změnila způsob, jak pracuješ — systémově, ne jen jednorázově",
      "Jedno konkrétní rozhodnutí pro příštích 30 dní — co zabuduju nebo zlepším",
    ],
    taskType: "ol",
    taskTip: "Závěrečnou reflexi ulož do svého knowledge base — za 3 měsíce si ji přečti a uvidíš, jak daleko jsi.",
    teaser: "Systém je postavený. Teď ho používej. Výsledky přijdou — ne z motivace, ale z konzistence.",
  },
];
