import type { ChallengeDay } from "./types";

export const challengeDataBasicCZ: ChallengeDay[] = [
  {
    day: 0,
    title: "Tohle není kurz. Je to nový způsob práce.",
    subject: "Začínáme. Takhle funguje challenge.",
    preheader: "28 dní, 5–7 minut denně. Jeden opravdový posun.",
    concept: [
      "AI je dnes všude. Každý týden nové nástroje, nové funkce, nové sliby. A právě proto je snadné skončit u toho, že člověk něco vyzkouší, nedostane co čekal, a zavře záložku.",
      "Tahle challenge vznikla proto, aby se tohle nestalo.",
      "Nejde o to naučit se co nejvíc AI nástrojů. Jde o to začít AI používat pravidelně a tak, aby opravdu ulehčovala práci. Tohle je AI-first přístup: způsob přemýšlení o práci, který změní to, jak ji děláš — bez ohledu na to, který konkrétní nástroj zrovna používáš.",
      "Každý den ti zabere přibližně 5–7 minut. Každý den si odneseš něco konkrétního:",
      ["nový pohled na práci s AI", "malý praktický krok", "konkrétní výstup nebo drobné zlepšení něčeho, co už děláš"],
      "Tato verze challenge — Basic — se zaměřuje na základy. Na to, jak AI přemýšlí, co od ní realisticky čekat, jak psát zadání, která fungují, a jak AI zapojit do věcí, které děláš každý den.",
      "Každou výzvu lze prohloubit. Pokud na něco narazíš, co už znáš, nevadí — každý den se dá udělat hlouběji. Upravit prompt, vylepšit výstup, zabudovat do reálné práce. Smyslem není stihnout všechno. Smyslem je posouvat se každý den o kousek dál.",
      "Stačí málo. Pět minut. Jedna věc. Jeden krok. Z toho nakonec vzniká skutečná změna.",
    ],
    taskIntro: "Než začneme, jeden jednoduchý úkol. Zamysli se a zapiš si:",
    taskItems: [
      "3 věci, které v práci nebo v běžném dni děláš opakovaně — každý týden nebo každý den",
      "Klidně i banální věci: odpovídání na emaily, příprava schůzek, psaní textů, reporty, shrnutí",
      "Zapiš si je kamkoli — Notion, Google Docs, Apple Notes nebo papír. Budeme se k nim vracet.",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra se podíváme na to, proč AI není jen rychlejší Google — a proč na tom záleží.",
  },
  {
    day: 1,
    title: "AI není rychlejší Google. Je to leverage.",
    subject: "Jeden posun v myšlení, který změní výsledky.",
    preheader: "Rychlost je vedlejší efekt. Leverage je cíl.",
    concept: [
      "Většina lidí používá AI tak, jako by to byl trochu chytřejší vyhledávač: napíše otázku, dostane odpověď, jde dál. To funguje — ale využívá zlomek toho, co AI skutečně umí.",
      "Je to jako mít Ferrari a jezdit s ním jenom na nákup.",
      "Klíčový posun v myšlení: AI není nástroj pro rychlost. Je to nástroj pro leverage — pro zásadní rozdíl ve výsledku při stejném nebo menším úsilí. Rychlost je vedlejší efekt, ne cíl.",
      "Jak to vypadá v praxi? Rychlost znamená: napíšu email za 5 minut místo 20. Leverage znamená: napíšu email, který by bez AI nikdy nevznikl takto — protože jsem s AI promyslela, co ten klient skutečně potřebuje slyšet, jak to formulovat, a ve třech variantách.",
      "Dobrá analogie: digitální fotoaparát dal lidem rychlost. Ale Photoshop dal fotografům leverage — výsledky, které fotoaparát sám nikdy neprodukoval. AI je tvůj Photoshop na práci s textem, myšlením a strukturou.",
      [
        "Rychlost: udělám totéž, ale rychleji",
        "Leverage: dosáhnu výsledku, který by jinak nebyl možný — nebo by trval deset krát déle",
        "Mindset: AI jako spolupracovník, ne jako zkratka",
        "Praxe: ptej se 'jak dosáhnout lepšího výsledku', ne jen 'jak to udělat rychleji'",
      ],
      "Toto přeskočení — mindsetové části — je důvod, proč většina lidí AI 'vyzkouší a pak nechá'. Nevidí leverage. Vidí jen, že výsledek není dost dobrý napoprvé. A mají pravdu — napoprvé nikdy není. Ale leverage přichází ve druhém a třetím kole.",
      "Dnešní úkol tě donutí myslet právě tímto způsobem.",
    ],
    taskIntro: "Vezmi jeden úkol ze svého včerejšího seznamu a zkus se zamyslet ze dvou úhlů:",
    taskItems: [
      "Jak by mi AI pomohla udělat tento úkol rychleji? (rychlost)",
      "Jakého výsledku bych s AI dosáhla, který by jinak vůbec nebyl možný — nebo by trval moc dlouho? (leverage)",
      "Zapiš si obě odpovědi. Nemusí být dokonalé — jde o způsob přemýšlení.",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra si nakreslíme realistickou mapu AI: co umí skvěle, kde selhává — a proč je to důležité vědět dřív než začneš.",
  },
  {
    day: 2,
    title: "AI je skvělá asistentka. Ale horší kouzelník.",
    subject: "Realistická mapa AI — co umí a co ne.",
    preheader: "Přehnané očekávání a přílišná skepse vedou na stejné místo.",
    concept: [
      "Jedna z největších chyb při práci s AI je přehnané očekávání. Nebo naopak — přílišná skepse. Obojí vede ke stejnému výsledku: člověk AI nepoužívá efektivně, protože buď čeká zázraky, nebo věří, že mu nepomůže.",
      "Realistická mapa je víc než žádná mapa.",
      "Co AI skutečně umí dobře — a kde je nejsilnější:",
      [
        "Strukturovat a přepisovat text rychle a konzistentně",
        "Generovat varianty, nápady a návrhy — dát ti pět možností místo jedné",
        "Shrnovat dlouhé dokumenty — 10 stran do 5 vět",
        "Vysvětlovat složité věci jednoduše — pro různá publika, různou úroveň detailu",
        "Asistovat při opakujících se úkolech — šablony, drafty, struktury",
        "Pracovat rychle s velkým množstvím textu — co by trvalo hodiny, zvládne za minuty",
      ],
      "Co AI neumí nebo dělá nespolehlivě — a kde je potřeba kontrola:",
      [
        "Přistupovat k internetu v reálném čase (bez speciálních nástrojů nebo záložek)",
        "Pamatovat si minulé konverzace, pokud to nenastavíš nebo nezopakuješ kontext",
        "Vždy říkat pravdu — AI může s přesvědčením vymýšlet fakta, čísla i reference",
        "Rozumět tvé specifické situaci, pokud mu ji neposkytneš jako kontext",
        "Nahradit odborný úsudek v kritických rozhodnutích — lékařství, právo, finance",
      ],
      "Nejzrádnější past je, že AI neumí říct 'nevím' přesvědčivě. Vygeneruje odpověď, která zní skvěle — ale může být špatně. Ověřuj fakta a konkrétní čísla vždy externě, zejména v situacích, kde na přesnosti záleží.",
      "Klíčový princip: AI je nejlepší spolupracovník, když víš, co od ní chceš — a ověříš, co ti dá. Tento princip ti zůstane platný po celých 28 dní.",
    ],
    taskIntro: "Zamysli se nad jedním úkolem, kde si nejsi jistá, jestli by AI pomohla. Zkus to otestovat:",
    taskItems: [
      "Vyber úkol, kde jsi skeptická — nebo kde se ti AI dosud neosvědčila",
      "Napiš AI jednoduchý prompt a zjisti, co dostaneš",
      "Zhodnoť: bylo to užitečné? Kde AI selhala? Co by jí pomohlo?",
    ],
    taskType: "ol",
    taskPrompt: "Potřebuji pomoc s [úkol]. Mám k dispozici [co máš k dispozici]. Výsledek by měl být [co potřebuješ].",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra to bude praktické — napíšeš AI, co přesně děláš, a necháš ji navrhnout, kde může pomoci.",
  },
  {
    day: 3,
    title: "AI o tobě nic neví. Změň to za 5 minut.",
    subject: "Napiš co děláš — dostaneš návrh jak pomoci.",
    preheader: "Generický vstup = generický výstup. Kontext mění vše.",
    concept: [
      "AI bez kontextu je jako nový kolega v první den práce. Technicky schopný, ale ještě neví, pro koho pracuje, co je důležité, ani jak věci fungují.",
      "Přesně tak se AI chová, dokud jí nedáš kontext. A právě to je dnešní úkol.",
      "Proč je to tak důležité? Zkus zadat 'pomoz mi s prací' a uvidíš, co dostaneš. Pak zkus 'pracuji jako produktová manažerka v B2B SaaS firmě, moje největší každodenní bolest je příprava týdenních statusů pro vedení, které mají vždy stejnou strukturu' — a výsledek bude zásadně jiný.",
      "Kontext funguje jako briefing pro spolupracovníka. Čím lepší briefing, tím lépe bude pracovat hned od prvního slova. AI si nic nepamatuje z minulých konverzací — takže briefing dáváš vždy. Ale nemusí to trvat dlouho.",
      "Co do kontextu patří:",
      [
        "Kdo jsi — tvoje role nebo obor, ve kterém pracuješ",
        "Co konkrétně děláš — 3–5 typických úkolů, ne obecná náplň práce",
        "Pro koho pracuješ — interní tým, klienti, zákazníci, management",
        "Jaké jsou tvé největší bolesti nebo opakující se práce",
      ],
      "Tenhle úkol má dvě části: nejdřív napíšeš AI o sobě, pak se jí zeptáš, kde může pomoci. Neočekávej dokonalý výsledek — jde o první mapování. Výstup si ulož, budeme se k němu v challenge vracet.",
      "Nejčastější chyba: být příliš obecný. 'Pracuji v marketingu' je příliš málo. 'Připravuji kampaňové reporty pro e-commerce klienty, každý týden, v PowerPointu, a vždy mi zabere 3–4 hodiny shánění dat' je použitelné.",
    ],
    taskIntro: "Použij tento postup — zabere ti 5–7 minut:",
    taskItems: [
      "Otevři Claude, ChatGPT nebo Gemini",
      "Napiš AI prompt podle šablony níže",
      "Výstup si ulož — konkrétní oblasti, kde AI navrhla pomoci",
    ],
    taskType: "ol",
    taskPrompt: "Pracuji jako [tvoje role nebo obor]. Moje typické úkoly jsou: [vypiš 3–5 konkrétních věcí]. Největší opakující se práce, která mi zabere čas, je [dopiš]. Navrh mi 5 konkrétních způsobů, jak by mi AI mohla pomoci — ne obecně, ale přímo na moje úkoly.",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra se podíváme na to, co dělá největší rozdíl mezi dobrým a špatným promptem — a proč je to proveditelné hned.",
  },
  {
    day: 4,
    title: "Dobrý prompt nebo špatný — záleží na jednom.",
    subject: "Co dělá největší rozdíl mezi výsledkem a odpadem.",
    preheader: "Vágní vstup = vágní výstup. Platí vždy.",
    concept: [
      "Špatný výsledek z AI má ve většině případů jednu příčinu: špatné zadání. Ne špatnou AI. To je zpráva, která osvobozuje — protože zadání můžeš zlepšit ty.",
      "Prompt je v podstatě pracovní zadání. A zadání, které dáš novému kolegovi, určuje kvalitu jeho práce. 'Napiš mi email' je jako říct kolegovi 'udělej mi tu věc' — ani jeden z nich neví, kde začít.",
      "Co dělá prompt špatným:",
      [
        "Je příliš vágní: 'napiš mi email'",
        "Chybí kontext: AI neví, pro koho, proč, v jakém tónu",
        "Chybí formát: AI neví, jak dlouhý, jak strukturovaný má výsledek být",
        "Chybí cíl: AI neví, čeho má výstup dosáhnout — informovat, přesvědčit, domluvit schůzku",
      ],
      "Co dělá prompt dobrým:",
      [
        "Je konkrétní: 'napiš follow-up email pro klienta, který viděl nabídku, ale neodpověděl'",
        "Má kontext: 'klient je malá výrobní firma, jednám s majitelem, nabídka byla na systém řízení skladu'",
        "Má formát: 'krátký, max 5 vět, přátelský a přímý tón'",
        "Má cíl: 'chci dostat odpověď — ať kladnou nebo zápornou'",
      ],
      "Nejčastější chyba: čekat, že AI 'pochopí, co chceš'. AI vždy pochopí doslova to, co napíšeš — ne to, co jsi měla na mysli. Vágní vstup, vágní výstup. Platí to pokaždé.",
      "Pravidlo palce: čím víc si dokážeš přesně představit výsledek, který chceš — tím přesnější prompt napíšeš. Pomůže, když si před psaním promptu položíš otázku: kdybych dostala tohle jako zadání od šéfa, věděla bych přesně, co udělat? Pokud ne, přidej víc.",
    ],
    taskIntro: "Porovnej tyto dva prompty a zkus oba v AI — uvidíš rozdíl okamžitě:",
    taskItems: [
      "Špatný: 'Napiš mi email.'",
      "Lepší: 'Napiš follow-up email klientovi, který viděl cenovou nabídku na software, ale neodpověděl. Tón přátelský a přímý, max 5 vět. Cíl: dostat odpověď — kladnou nebo zápornou.'",
      "Zapiš si, jak se liší výstupy — kvalitou, použitelností, délkou. Tenhle rozdíl je přesně to, s čím budeme pracovat dál.",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra si procvičíš přepisování špatných promptů — na třech reálných příkladech.",
  },
  {
    day: 5,
    title: "Přepisování promptů je sval. Dnes ho posílíš.",
    subject: "Praxe: z vágního na konkrétní, třikrát za sebou.",
    preheader: "Tohle je dovednost, ne znalost. Musíš si ji zkoušet.",
    concept: [
      "Přepisování promptů je jako editace textu — první verze nikdy není nejlepší. A stejně jako u textu: nemusíš začínat od nuly. Musíš vědět, co přidat nebo odebrat.",
      "Prompting je dovednost, ne znalost. To znamená, že čtení o tom nestačí — musíš si to zkoušet na vlastních příkladech. Dnes máš tři konkrétní prompty k přepsání. Tvůj úkol: oprav je tak, aby dávaly lepší výstup. Pak obě verze otestuj v AI a porovnej.",
      "Co typicky chybí ve špatných promptech:",
      [
        "Cílová skupina nebo příjemce — kdo to bude číst nebo slyšet?",
        "Tón nebo styl komunikace — formální, přátelský, odborný, přímý?",
        "Požadovaný formát nebo délka — odrážky, odstavec, tři věty, tabulka?",
        "Kontext situace nebo cíl výstupu — proč to píšeš a co má příjemce udělat?",
      ],
      "Proč je tohle cvičení tak efektivní: naučíš se rozpoznat, co v promptu chybí — ne jako teorii, ale jako instinkt. Za pár týdnů budeš psát prompty, které fungují napoprvé, protože si automaticky budeš klást správné otázky ještě před napsáním.",
      "Tip: zkopíruj špatný i přepsaný prompt do AI a podívej se na oba výstupy vedle sebe. Rozdíl bývá okamžitě viditelný. Takhle se buduje intuice pro dobrý prompting — ne čtením, ale porovnáváním.",
      "Tenhle den je jeden z nejpraktičtějších v celém prvním týdnu. Nejde o pochopení — jde o zkoušení.",
    ],
    taskIntro: "Přepiš tyto 3 prompty a otestuj je v AI:",
    taskItems: [
      "'Napiš mi text na LinkedIn.' → přidej: pro koho, na jaké téma, jaký cíl, jaký tón, jak dlouhý",
      "'Pomoz mi s prezentací.' → přidej: na jaké téma, pro jaké publikum, kolik slidů, jaký výstup chceš",
      "'Napiš odpověď na email.' → přidej: co email obsahoval, co chceš sdělit, jaký tón, jak dlouhá odpověď",
    ],
    taskType: "ol",
    taskPrompt: "Přepiš tento prompt tak, aby byl konkrétnější: [vlož původní prompt]. Přidej kontext, cíl, tón a požadovaný formát výstupu.",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: proč je první výsledek z AI vždy jen začátek — a jak z toho dostat mnohem víc.",
  },
  {
    day: 6,
    title: "První výsledek je základ. Ne finální produkt.",
    subject: "Iterace — jak z AI dostat mnohem víc.",
    preheader: "Nejlepší výstup vzniká ve druhém nebo třetím kole.",
    concept: [
      "Největší chyba při práci s AI: napsat prompt, dostat výsledek, a buď ho přijmout nebo zahodit. Obojí je špatně — a obojí přichází o největší hodnotu, kterou AI nabízí.",
      "AI funguje nejlépe jako iterativní spolupracovník. První výstup je základ — ne finální produkt. Přesně tak funguje spolupráce s dobrým kolegou: dáš mu zadání, on navrhne draft, vy to společně dotáhnete. AI je v tomhle procesu neúnavná — může iterovat donekonečna.",
      "Proč lidé iteraci přeskakují? Buď nemají čas (ale iterace trvá 30 vteřin), nebo nevědí, co říct AI. Proto máš níže konkrétní instrukce. Nebo jsou jednoduše zklamaní z výsledku — a zklamání je zpráva. Řekni AI přesně, co nesedí.",
      "Jak iterovat efektivně — konkrétní fráze:",
      [
        "Pokud je výsledek moc obecný: 'přidej konkrétní příklad z [tvoje oblast]'",
        "Pokud je výsledek moc dlouhý: 'zkrať to na 3 věty, zachovej klíčové body'",
        "Pokud tón nesedí: 'přepiš to formálněji' nebo 'udělej to méně korporátní, více lidsky'",
        "Pokud chybí detail: 'rozveď bod číslo 2 — přidej konkrétní příklad'",
        "Pokud je špatná struktura: 'přepiš jako odrážkový seznam' nebo 'rozděl do tří sekcí s nadpisy'",
      ],
      "Klíčový princip: nemusíš začínat znovu. Pokračuj v konverzaci — AI pamatuje celé vlákno. Každá instrukce navazuje na předchozí výstup. Tím se konverzace s AI liší od Googlu: je to dialog, ne série samostatných dotazů.",
      "Jedno varování: iterace neznamená přepsat vše do nekonečna. Tři až čtyři kola zpravidla stačí. Pokud po pěti iteracích stále nejsi spokojená, problém je nejspíš v původním zadání — vrať se k promptu a upřesni ho od začátku.",
    ],
    taskIntro: "Vezmi libovolný výstup z minulých dnů a proveď s ním 3 iterace za sebou:",
    taskItems: [
      "Iterace 1: zkrať nebo prodluž výstup — upřesni délku a hustotu informace",
      "Iterace 2: změň tón — formálnější nebo přátelštější, podle toho co ti nesedí",
      "Iterace 3: přidej nebo odeber konkrétní informaci — upřesni obsah",
    ],
    taskType: "ol",
    taskPrompt: "Přepiš předchozí výstup takto: [konkrétní instrukce — co zkrátit, co přepsat, co přidat].",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra je reflexe prvního týdne — zapíšeš si, co fungovalo, co ne, a co z toho vezmeš dál.",
  },
  {
    day: 7,
    title: "Týden za námi. Co ses vlastně naučila?",
    subject: "Reflexe prvního týdne — tři věci, které zůstávají.",
    preheader: "Znalost zapomeneš. Zapsaný poznatek ti zůstane.",
    concept: [
      "První týden je za námi. Šest témat, šest krátkých cvičení. A teď přichází možná nejdůležitější den ze všech — reflexe.",
      "Proč je reflexe tak důležitá? Protože bez ní mizí poznatky stejně rychle, jak přišly. Mozek si pamatuje to, co zpracuje — ne to, co jen přijme. Napsat si tři věci, které ti utkvěly, je víc než přečíst deset dalších článků o AI.",
      "Reflexe není test. Nejde o to, jestli jsi všechno 'udělala správně'. Jde o to přijít na to, co ti z prvního týdne opravdu zůstalo — a co z toho chceš vzít do týdne druhého.",
      "Tři otázky pro reflexi:",
      [
        "Co ti z prvního týdne utkvělo nejvíc? (jedna konkrétní věc, ne seznam)",
        "Kde jsi s AI dostala výsledek, který tě překvapil pozitivně?",
        "Co ti nefungovalo — a co bys příště zkusila jinak?",
      ],
      "Nejčastější chyba při reflexi: být příliš obecný. 'Naučila jsem se o AI' není reflexe. 'Zjistila jsem, že výsledky se zásadně zlepší, když zadám konkrétní formát výstupu' je reflexe — protože to je použitelný poznatek.",
      "Týden druhý bude stavět na tom, co ses naučila. Budeme se věnovat struktuře promptu, kontextu a tomu, jak AI použít na opravdové úkoly z tvé práce. Základ, který sis vybudovala tento týden, teď začne dávat smysl.",
    ],
    taskIntro: "Zapiš si tři věci — konkrétně a stručně:",
    taskItems: [
      "Jedno největší zjištění z prvního týdne (jedna věta, konkrétní)",
      "Jeden výstup z AI, který byl lepší, než jsi čekala — co na promptu fungovalo?",
      "Jedna věc, která nefungovala — a jak bys ji příště přistoupila jinak",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden jdeme hlouběji: struktura promptu, kontext a první opravdový AI výstup z tvé práce.",
  },
  {
    day: 8,
    title: "Dobré prompty mají strukturu. Tady je ta tvoje.",
    subject: "Anatomie dobrého promptu — čtyři části, které vždy fungují.",
    preheader: "Roli, úkol, kontext, formát. V tomhle pořadí.",
    concept: [
      "Minulý týden jsme rozlišili dobrý a špatný prompt. Teď jdeme o krok dál: naučíme se, co přesně dobrý prompt obsahuje — a v jakém pořadí to dát.",
      "Existují čtyři části, které má každý dobrý prompt. Nemusíš je použít vždy všechny — ale čím víc z nich zadáš, tím lepší výstup dostaneš.",
      "Čtyři části dobrého promptu:",
      [
        "Role: kým má AI být? Zkušený obchodník, kouč, analytik, copywriter — role dává AI způsob uvažování",
        "Úkol: co přesně má udělat? Napsat, shrnout, analyzovat, přepsat, navrhnout, vysvětlit",
        "Kontext: co potřebuje vědět? Informace o situaci, cílové skupině, produktu, omezeních",
        "Formát: jak má výstup vypadat? Délka, struktura, tón, odrážky nebo odstavce",
      ],
      "Proč role funguje? Protože AI je trénovaná na obrovském množství textu z různých perspektiv. Když zadáš roli, přepneš AI do způsobu uvažování, který k té roli patří. 'Jsi zkušený HR manažer' dá AI jiný přístup než 'jsi junior recruiter'.",
      "Ukázka strukturovaného promptu: Jsi zkušený obchodní konzultant s praxí v B2B. Napiš krátký follow-up email klientovi, který viděl naši nabídku ale neodpověděl 5 dní. Kontext: klient je malá výrobní firma, já jsem obchodní ředitel, nabídka byla na ERP systém. Formát: max 5 vět, přátelský ale přímý tón, bez obecných frází.",
      "Nemusí to být vždy takto obsáhlé. Kratší prompty fungují pro jednodušší úkoly. Ale jakmile chceš výstup, který opravdu použiješ — tato čtyřdílná struktura tě dostane tam mnohem spolehlivěji.",
      "Dnes si tuto strukturu zkusíš na vlastním promptu — a uvidíš rozdíl oproti tomu, co jsi psala minulý týden.",
    ],
    taskIntro: "Vezmi jeden úkol z tvé práce a napiš prompt podle čtyřdílné struktury:",
    taskItems: [
      "Role: kým má AI být? (dopiš konkrétní roli nebo odbornost)",
      "Úkol: co přesně má udělat? (konkrétní instrukce — napsat, shrnout, navrhnout...)",
      "Kontext: co AI potřebuje vědět o situaci, cílové skupině, omezeních",
      "Formát: délka, tón, struktura výstupu",
    ],
    taskType: "ol",
    taskPrompt: "Jsi [role]. [Konkrétní úkol]. Kontext: [co AI potřebuje vědět]. Formát výstupu: [délka, tón, struktura].",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: proč je kontext tvůj nejsilnější nástroj — a jak ho použít tak, aby AI pracovala přesně pro tebe.",
  },
  {
    day: 9,
    title: "AI neví, co ty víš. Kontext je tvůj nejsilnější nástroj.",
    subject: "Kontext je klíč — jak ho dát správně.",
    preheader: "Čím víc AI ví, tím víc se chová jako někdo, kdo zná tvoji práci.",
    concept: [
      "Proč dvě osoby se stejným promptem dostávají naprosto různé výsledky? Kontext.",
      "AI nemá přístup k tvé práci, tvým klientům, tvým omezeným zdrojům ani tvé historii projektů. Ví jen to, co jsi napsala v aktuální konverzaci. To není omezení — to je pravidlo hry, které lze využít ve svůj prospěch.",
      "Dobrý kontext není paragraf textu. Je to výběr toho nejdůležitějšího, co AI potřebuje vědět, aby výstup dával smysl pro tvoji situaci — ne pro průměrnou situaci.",
      "Co do kontextu patří nejvíc:",
      [
        "Kdo je příjemce výstupu — zkušený odborník, laik, zákazník, manažer",
        "Jaká je situace — co se děje, co je v sázce, co se stalo dřív",
        "Jaká jsou omezení — co AI nemá dělat, co je citlivé, co je dané",
        "Jaký je tvůj cíl — informovat, přesvědčit, získat zpětnou vazbu, domluvit schůzku",
      ],
      "Příklad bez kontextu: 'Napiš shrnutí projektu.' AI napíše obecné shrnutí, které lze použít na cokoliv — a tím pádem na nic konkrétního.",
      "Příklad s kontextem: 'Napiš shrnutí projektu pro výbor vedení firmy. Projekt je v prodlení 3 týdny. Vedení o prodlení ví, ale nezná důvody. Tón klidný a věcný, bez omluv, s návrhem dalšího kroku. Max 150 slov.' To je výstup, který okamžitě použiješ.",
      "Klíčová otázka, kterou si klásti před každým promptem: co by si o mé situaci myslel moudrý kolega, který mi chce pomoci — co by potřeboval vědět, aby poradil dobře? To je tvůj kontext.",
    ],
    taskIntro: "Vezmi prompt z minulého dne a vylepši ho přidáním kontextu:",
    taskItems: [
      "Vyber prompt z D8 nebo libovolný, který ti dal průměrný výstup",
      "Přidej: kdo je příjemce, jaká je situace, jaká jsou omezení, jaký je cíl",
      "Porovnej výstup s původním — zapiš si konkrétní rozdíl",
    ],
    taskType: "ol",
    taskPrompt: "Kontext: [kdo jsem, jaká je situace, co je cílem]. Příjemce: [kdo to bude číst a co o tématu ví]. Omezení: [co nemá výstup obsahovat nebo dělat]. Úkol: [konkrétní instrukce].",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra si napíšeš prompt pro opravdový úkol ze své práce — a dostaneš výstup, který okamžitě použiješ.",
  },
  {
    day: 10,
    title: "Dnes tvoříš pro sebe. Prompt z tvé reálné práce.",
    subject: "Žádné cvičení — opravdový úkol, opravdový výstup.",
    preheader: "Tady se teorie mění na praxi.",
    concept: [
      "Prvních devět dní bylo příprava. Dnes je výsledek.",
      "Nejlepší způsob, jak otestovat, co ses naučila, je vzít opravdový úkol z tvé práce a projít celým procesem: kontext, role, zadání, formát. A pak iterovat, dokud výstup není použitelný.",
      "Proč je tohle důležité? Protože reálný úkol je vždy těžší než cvičný příklad. Máš méně ideální informace, výstup musí sedět konkrétním lidem, a záleží ti na výsledku. Právě proto je to nejlepší test.",
      "Úkoly, které na dnešní den fungují dobře:",
      [
        "Text, který budeš brzy potřebovat — email, zpráva, shrnutí, post",
        "Dokument, který připravuješ opakovaně — agenda schůzky, týdenní status, report",
        "Odpověď na otázku, kterou řešíš — návrh řešení, analýza situace, porovnání možností",
        "Výstup, který jinak děláš manuálně — přepis poznámek, strukturování informací, překlad",
      ],
      "Dobrý výsledek dnes není dokonalý výstup. Dobrý výsledek je výstup, který ti ušetří čas nebo dá základ, který dál dopracuješ. To je cíl.",
      "Pamatuj na iteraci: pokud první výstup není dobrý, nereklamuj to u AI — upřesni prompt. Přidej kontext, upřesni formát, změň roli. Tři kola zpravidla stačí.",
      "Výstup dnešního dne si ulož. V den 12 se k němu vrátíme a výstup společně vylepšíme na základě toho, co se naučíš mezitím.",
    ],
    taskIntro: "Vyber reálný úkol ze své práce a projdi celým procesem:",
    taskItems: [
      "Zapiš si úkol a co přesně potřebuješ jako výstup",
      "Napiš prompt podle čtyřdílné struktury z D8 — role, úkol, kontext, formát",
      "Zkus ho v AI, výsledek zkontroluj a udělej aspoň jednu iteraci",
      "Výstup ulož — vrátíme se k němu ve středu",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: co dělat, když výstup nesedí — konkrétní techniky pro opravu špatného výstupu.",
  },
  {
    day: 11,
    title: "Výstup nesedí? Tady jak ho zachránit.",
    subject: "Jak opravit špatný výstup — bez začínání od nuly.",
    preheader: "Zklamání z výsledku je informace. Víš, co říct dál.",
    concept: [
      "Špatný výstup z AI je frustrace. Ale je to také informace — říká ti přesně, co chybí v zadání.",
      "Nejhorší reakce: smazat výstup a začít znovu od prázdné stránky. Nebo AI opustit a dělat to ručně. Obojí je zbytečné — a oba kroky vyhodíš to, co AI pro tebe udělala.",
      "Správná reakce: napiš AI přesně, co nesedí. Ne vágně ('toto je špatně'), ale konkrétně ('tento odstavec je příliš obecný, přepiš ho s konkrétním příkladem z HR prostředí').",
      "Pět technik pro opravu špatného výstupu:",
      [
        "Upřesni požadavek: 'Výsledek je příliš obecný. Přidej konkrétní příklad pro [situaci].'",
        "Změň tón: 'Přepiš to méně formálně, více jako by to psal člověk, ne korporátní dokument.'",
        "Omeč rozsah: 'Zkrať na 3 klíčové body — zbytek odstraň.'",
        "Požádej o varianty: 'Napiš to ještě třemi různými způsoby — hledám jiný úhel pohledu.'",
        "Vysvětli, proč to nefunguje: 'Příjemce zprávy nezná náš kontext — přepiš bez předpokladu, že čtenář ví o projektu.'",
      ],
      "Jedna věc, na kterou si dát pozor: AI si pamatuje kontext celé konverzace. Pokud iteruješ moc dlouho a výsledky se zhoršují, někdy pomůže začít novou konverzaci — s lepším výchozím promptem, který zahrnuje, co ses v předchozí konverzaci naučila.",
      "Dnešní cvičení tě naučí rozlišovat mezi 'špatným promptem' a 'špatným výstupem' — protože oprava je jiná.",
    ],
    taskIntro: "Vezmi výstup z D10 nebo jakýkoli výstup, který ti nesedí, a zkus tyto kroky:",
    taskItems: [
      "Identifikuj konkrétně, co nesedí — tón, délka, obsah, nebo struktura",
      "Napiš AI instrukci opravy — konkrétně, ne obecně",
      "Porovnej původní a opravený výstup — co se změnilo?",
    ],
    taskType: "ol",
    taskPrompt: "Tento výstup nesedí, protože [konkrétní důvod]. Přepiš ho tak, aby [konkrétní požadavek na opravu].",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: vrátíme se k promptu z D10 a výstup vylepšíme pomocí technik z dnešního dne.",
  },
  {
    day: 12,
    title: "Vrátíme se k pondělnímu výstupu. Teď ho dotáhneme.",
    subject: "Iterace v praxi — lepší výstup z toho, co máš.",
    preheader: "Dobrý výsledek nevznikne napoprvé. Vznikne napotřetí.",
    concept: [
      "Dnes je den, kdy se vše dá dohromady.",
      "Máš prompt a výstup z D10. Máš techniky z D11. Teď je čas je spojit — a dotáhnout výstup na úroveň, kterou bys opravdu použila.",
      "Proč je návrat k předchozímu výstupu tak cenný? Protože vidíš ho s odstupem. Co se ti tehdy zdálo použitelné, teď může vypadat jinak. A co ses naučila v D11, ti dá konkrétní nápady, co zlepšit.",
      "Proces dnešního dne:",
      [
        "Otevři výstup z D10 — přečti ho znovu s čerstvým pohledem",
        "Identifikuj tři věci, které by šlo zlepšit — tón, délka, konkrétnost, struktura",
        "Napiš opravnou instrukci pro každou z nich",
        "Výsledné výstupy porovnej s originálem",
      ],
      "Nepotřebuješ opravit vše. Zaměř se na jednu nebo dvě největší slabiny. Perfekcionismus v iteraci je past — lepší je výstup, který je o 80 % dobrý a ušetřil ti hodinu, než dokonalý výstup, na který jsi strávila dvě hodiny iterací.",
      "Klíčový poznatek: iterace s AI není slabina. Je to způsob práce. Nejlepší pracovníci s AI nedostávají dokonalé výsledky napoprvé — dostávají je po dvou nebo třech iteracích. To je norma, ne výjimka.",
    ],
    taskIntro: "Vrať se k výstupu z D10 a proveď tři cílené iterace:",
    taskItems: [
      "Iterace 1: upřesni obsah — co přidat nebo odebrat, aby výstup lépe odpovídal skutečné situaci",
      "Iterace 2: uprav tón nebo délku — dle výstupu z D11",
      "Iterace 3: přidej konkrétní příklad nebo detail, který výstup zpřesní",
    ],
    taskType: "ol",
    taskPrompt: "Vezmi předchozí výstup a vylepši ho takto: 1. [co konkrétně přidat nebo změnit]. 2. [co zkrátit nebo odstranit]. 3. [jak upravit tón nebo strukturu].",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: kdy AI pomáhá a kdy to celé jenom zkomplikuje — upřímný přehled.",
  },
  {
    day: 13,
    title: "AI není správná volba vždy. Tady kdy.",
    subject: "Kdy AI pomáhá a kdy přidává práci.",
    preheader: "Nejlepší nástroj pro každý úkol — to někdy není AI.",
    concept: [
      "Nejsofistikovanější AI uživatelé nevyužívají AI na vše. Vědí přesně, kdy AI použít — a kdy je rychlejší, lepší nebo spolehlivější udělat to bez ní.",
      "Tohle je pohled, který v tutoriálech o AI málokdy uslyšíš. Ale je to pohled, který tě posune nejvíc.",
      "Kdy AI pomáhá nejvíce:",
      [
        "Úkol má jasnou strukturu — email, shrnutí, agenda, analýza, vysvětlení",
        "Potřebuješ varianty nebo nápady rychle — brainstorming, možnosti, alternativy",
        "Text je dlouhý a potřebuješ ho zkrátit nebo přestrukturovat",
        "Děláš to opakovaně — šablona nebo prompt ti každé příští kolo ušetří čas",
        "Potřebuješ začít — draft, osnova, první verze, od které se odrazíš",
      ],
      "Kdy AI přidává práci nebo komplikuje:",
      [
        "Potřebuješ přesná fakta, čísla nebo aktuální informace — AI může vymýšlet",
        "Rozhodnutí vyžaduje tvůj odborný úsudek nebo znalost konkrétního kontextu",
        "Výstup potřebuje být zcela osobní — AI neudrží tvůj autentický hlas bez velké práce",
        "Zadání je složité formulovat — pokud nevíš, co přesně chceš, AI to za tebe nevymyslí",
        "Krátký jednoduchý úkol — napsat jednu větu nebo odškrtnout jednu položku je rychlejší ručně",
      ],
      "Praktický test: pokud ti trvá napsat prompt déle, než by trvalo udělat úkol ručně — přeskoč AI. Pokud se jedná o opakující se typ úkolu, investuj do dobrého promptu nyní, abys ho příště použila za 30 vteřin.",
      "Tohle není kritika AI. Je to realistický pohled na to, jak ji používat s rozumem — ne z nadšení.",
    ],
    taskIntro: "Projdi svůj typický pracovní den a roztřiď úkoly do dvou skupin:",
    taskItems: [
      "Úkoly, kde AI pomáhá — strukturované, opakující se, kde potřebuješ varianty nebo drafty",
      "Úkoly, kde je lepší bez AI — krátké jednorázové věci, kde potřebuješ přesnost nebo osobní hlas",
      "Zapiš si po třech příkladech do každé skupiny",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra je checkpoint — polovina challenge je za námi a zapíšeš si svůj osobní prompt checklist.",
  },
  {
    day: 14,
    title: "Polovina za námi. Čas se zastavit a podívat dozadu.",
    subject: "Checkpoint — co ti z první poloviny zůstalo.",
    preheader: "Nejlepší investice 5 minut: vědět, co si vezmeš dál.",
    concept: [
      "Čtrnáct dní. Čtrnáct témat. A teď přichází jeden z nejdůležitějších dnů challenge — ne protože bys dnes dělala novou věc, ale protože se zastavíš a zpracuješ, co ses naučila.",
      "Zapsaný poznatek funguje jinak než přečtená informace. Když si napíšeš, co ti opravdu funguje, vytvoříš si osobní checklist — přesně na míru tvé práci a tvým situacím.",
      "Tři věci, na které se zaměříme:",
      [
        "Co z první poloviny challenge si vezmeš a budeš aktivně používat?",
        "Co ti nefungovalo — a proč?",
        "Jaký je tvůj aktuální osobní prompt checklist?",
      ],
      "Osobní prompt checklist je jednoduše seznam věcí, které si ověříš před tím, než prompt odešleš. Nemusí být dlouhý — tři až pět bodů stačí. Ale musí být tvůj, ne zkopírovaný. Co funguje pro tebe konkrétně.",
      "Příklad checklistu (ne šablona — příklad):",
      [
        "Mám roli? Zadal/a jsem AI, kým má být?",
        "Mám kontext? Ví AI dost o situaci a příjemci?",
        "Mám formát? Ví AI, jak má výsledek vypadat?",
        "Mám cíl? Ví AI, čeho má výstup dosáhnout?",
      ],
      "Druhá polovina challenge bude stavět na základech, které sis vybudovala. Půjdeme do šablon, opakující se práce, AI nástrojů v kontextu celého pracovního dne — a nakonec k tomu, jak si vybudovat návyk, který ti zůstane i po skončení challenge.",
    ],
    taskIntro: "Zapiš si tři věci — stačí odrážky, stačí pár slov:",
    taskItems: [
      "Tři poznatky z první poloviny challenge, které ti opravdu zůstaly (konkrétní, ne obecné)",
      "Tvůj osobní prompt checklist — 3–5 věcí, které si ověříš před odesláním každého promptu",
      "Jeden konkrétní cíl pro druhou polovinu challenge",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden: opakující se práce jako signál, šablony a workflows — a jak ušetřit hodinu týdně na věcech, které děláš pořád znovu.",
  },
  {
    day: 15,
    title: "Opakující se práce je nejdražší práce, co máš.",
    subject: "Identifikuj, co děláš každý týden znovu — to je signál.",
    preheader: "Ne každá opakující se práce je nutná. Ale každá stojí za pozornost.",
    concept: [
      "Spousta práce nevypadá na první pohled drahá. Jeden email tady, jedno shrnutí tam, agenda schůzky ve čtvrtek. Každá věc zvlášť trvá deset minut.",
      "Ale deset věcí každý týden je hodina. A hodina každý týden je dva a půl týdne ročně. Na jedné kategorii práce.",
      "Opakující se práce je signál. Ne signál, že máš být rychlejší. Signál, že by tato práce měla mít šablonu, prompt nebo workflow — aby příště nezačínala od nuly.",
      "Tři typy opakující se práce, kde AI pomáhá nejvíc:",
      [
        "Dokumenty — reporty, shrnutí, zápisky, briefy, agendy, nabídky",
        "Komunikace — follow-upy, odpovědi na časté dotazy, potvrzení, interní updaty",
        "Strukturování — přepis poznámek, organizace informací, příprava podkladů pro rozhodnutí",
      ],
      "Nejčastější chyba: podceňovat drobnosti. 'Trvá mi to jen deset minut' zní jako argument pro to, nic neměnit. Ale deset minut opakujících se úkolů každý den je za rok dva plné pracovní týdny.",
      "Dnešní úkol je průzkum — bez nátlaku měnit cokoliv hned. Cílem je vidět mapu opakující se práce. Co trvá? Co se vrací? Co tě stojí nejvíc energie? To bude základ pro šablony a prompty, které si vytvoříš v dalších dnech.",
    ],
    taskIntro: "Zamysli se nad svým pracovním týdnem a zapiš si:",
    taskItems: [
      "5 věcí, které děláš opakovaně — každý týden nebo každý druhý týden",
      "U každé: přibližně jak dlouho trvá a jak moc tě to stojí energie",
      "Označ hvězdičkou tu, u které je ztráta času nebo energie největší",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: z tohoto seznamu sestavíš svoji osobní leverage matici — kde AI může přidat nejvíc.",
  },
  {
    day: 16,
    title: "Sestavíš svůj osobní seznam AI kandidátů.",
    subject: "Top 5 opakujících se úkolů, kde AI může ušetřit nejvíc.",
    preheader: "Leverage matice: co předat AI, co vylepšit, co zautomatizovat.",
    concept: [
      "Včera jsi identifikovala opakující se práci. Dnes ji roztřídíš — a rozhodneš, kde AI přinese nejvíc.",
      "Ne každá opakující se práce je stejný typ příležitosti. Pomáhá ji rozdělit do tří kategorií:",
      [
        "Předat AI: AI může udělat první verzi nebo celý výstup — ty jen zkontroluj a pošli",
        "Vylepšit s AI: ty máš vstup a strukturu, AI pomáhá s formulací, délkou nebo formátem",
        "Zautomatizovat šablonou: prompt jednou dobře nastavíš, pak ho používáš opakovaně za 30 vteřin",
      ],
      "Jak rozlišit, do které kategorie věc patří: úkoly, které mají jasnou strukturu a výstup (email, shrnutí, report), jsou kandidáti pro 'předat' nebo 'šablona'. Úkoly, kde vstup je složitý nebo osobní (koučovací rozhovor, kreativní návrh), jsou spíše pro 'vylepšit s AI'.",
      "Ukázka leverage matice v praxi:",
      [
        "Týdenní status pro vedení → předat AI (zadám data, dostanu draft)",
        "Odpovědi na opakující se dotazy klientů → šablona (jednou napíšu prompt, opakuji)",
        "Příprava agendy schůzky → vylepšit s AI (já mám témata, AI strukturuje)",
        "Strategická prezentace pro board → vylepšit s AI (obsah je můj, AI pomáhá s formulací)",
      ],
      "Cílem dnešního dne není udělat vše najednou. Cílem je vybrat jeden nebo dva úkoly, kde začneš — a kde bude efekt nejviditelnější.",
    ],
    taskIntro: "Vezmi seznam z D15 a projdi ho tímto filtrem:",
    taskItems: [
      "U každého úkolu rozhodni: předat AI, vylepšit s AI, nebo zautomatizovat šablonou",
      "Vyber jeden úkol v kategorii 'předat AI' nebo 'šablona' — ten je nejjednodušší na začátek",
      "Zapiš si konkrétně, jak by tam AI pomohla — co by byl vstup a co výstup",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: rozdíl mezi šablonou a workflowem — a proč na tom záleží, když chceš systém, ne jen pomůcku.",
  },
  {
    day: 17,
    title: "Šablona řeší jeden úkol. Workflow řeší celý proces.",
    subject: "Šablona vs. workflow — a kdy použít co.",
    preheader: "Šablona je odpověď. Workflow je systém.",
    concept: [
      "Šablona a workflow zní podobně. Ale jsou to dvě různé věci — a záměna je příčinou toho, proč někdo 'má šablonu', ale stále tráví stejně času.",
      "Šablona je předpřipravený výstup nebo prompt pro jeden opakující se úkol. Např.: mám prompt pro týdenní status — zadám data, dostanu draft. Šablona řeší jeden konkrétní krok.",
      "Workflow je posloupnost kroků, která zahrnuje více šablon a rozhodnutí. Např.: proces od schůzky k odeslání zápisku — zápis poznámek, strukturování do agendy, doplnění úkolů, odeslání. Každý krok má svoji šablonu, ale dohromady tvoří workflow.",
      "Kdy stačí šablona:",
      [
        "Opakující se výstup, který je vždy podobný — email, report, agenda, shrnutí",
        "Jednokrokový úkol, kde vstup je jasný a výstup je předvídatelný",
        "Začátek — první šablona je vždy nejdůležitější krok",
      ],
      "Kdy potřebuješ workflow:",
      [
        "Proces má více kroků, které na sebe navazují",
        "Různí lidé jsou zapojeni v různých fázích",
        "Chybí jeden krok → celý výsledek se zhorší",
      ],
      "Pro tuhle challenge se soustředíme hlavně na šablony — jsou rychlejší na vybudování a efekt je okamžitý. Workflow je pokročilejší téma, které si rozvedeme v Advanced verzi challenge.",
      "Důležité: dobrá šablona není dokument. Je to prompt, který je napsaný tak konkrétně, že ho můžeš zadat AI za 30 vteřin a dostat výstup, který přímo použiješ.",
    ],
    taskIntro: "Vyber si jeden opakující se úkol ze svého seznamu a rozhodni:",
    taskItems: [
      "Je to jeden krok (šablona) nebo více kroků (workflow)?",
      "Pokud šablona: napiš si, co by měl prompt obsahovat — vstup, výstup, tón, formát",
      "Pokud workflow: napiš si kroky procesu a označ, který z nich je nejdůležitější kandidát na šablonu",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: vytvoříš svoji první opravdovou šablonu — prompt, který budeš opakovaně používat.",
  },
  {
    day: 18,
    title: "Dnes postavíš šablonu, která ti ušetří hodinu týdně.",
    subject: "Vytvoř první opakovaně použitelný prompt.",
    preheader: "Jednou dobře. Pak za 30 vteřin pokaždé.",
    concept: [
      "Dobré šablony se nepíší na jeden zátah. Vyvíjejí se — první verze funguje na 70 %, druhá verze na 85 %, třetí je ta, kterou pak používáš roky.",
      "Ale někdy začít. A začít znamená napsat první verzi — i nedokonalou.",
      "Co dělá šablonu dobrou? Tři věci:",
      [
        "Je konkrétní — ne 'napiš email', ale 'napiš follow-up email klientovi, který neodpověděl na nabídku po 5 dnech'",
        "Má proměnné — místa, kde dosadíš konkrétní hodnoty: [jméno klienta], [typ nabídky], [datum]",
        "Dává konzistentní výstup — každé použití produkuje výsledek, který je na stejné kvalitativní úrovni",
      ],
      "Jak šablonu vytvořit:",
      [
        "Vyber opakující se úkol — nejlépe takový, kde výstup bývá vždy podobný",
        "Napiš prompt, který přesně popisuje, co výstup má obsahovat, v jakém tónu a formátu",
        "Přidej proměnné — místa v promptu, kde dosadíš konkrétní detaily",
        "Otestuj šablonu na dvou různých situacích a uprav, co nesedí",
        "Ulož ji na místo, odkud ji příště rychle dostaneš — Notion, Google Docs, Apple Notes",
      ],
      "Jedna šablona týdně. Za čtyři týdny máš čtyři šablony — a každá ti ušetří 20–30 minut. To je hodina a půl týdně na věcech, které jsi dřív dělala od nuly.",
      "Dnešní úkol není dokonalý. Je to první verze. A to je přesně, co potřebuješ.",
    ],
    taskIntro: "Postav svoji první šablonu — krok za krokem:",
    taskItems: [
      "Vyber opakující se úkol — nejlépe ten, který jsi označila hvězdičkou v D15",
      "Napiš prompt: role, úkol, kontext (jako proměnné), formát výstupu",
      "Otestuj ho na jednom konkrétním příkladu — funguje? Co upravit?",
      "Ulož šablonu do Notion, Google Docs nebo Apple Notes jako 'Moje AI šablony'",
    ],
    taskType: "ol",
    taskPrompt: "Jsi [role]. [Konkrétní úkol]. Kontext: [jméno/situace/specifika — dosadíš pokaždé]. Formát výstupu: [délka, tón, struktura].",
    taskTip: "Šablonu ulož jako dokument do Notion, Google Docs nebo Apple Notes — ať ji máš rychle po ruce.",
    teaser: "Zítra: empirický pohled na čas — kde AI skutečně ušetří a kde ho paradoxně přidá.",
  },
  {
    day: 19,
    title: "Kde AI šetří čas a kde ho přidává — upřímný přehled.",
    subject: "Měření, ne pocit. Kde AI přidává hodnotu a kde ne.",
    preheader: "Nejlepší AI workflow je ten, který opravdu ušetří čas.",
    concept: [
      "Říká se, že AI šetří čas. Ale 'AI mi šetří čas' je pocit. Kde konkrétně, jak moc, a při jakém typu úkolů — to je data. A data jsou mnohem užitečnější.",
      "Proč to záleží? Protože bez měření jdeš buď do nadšení (AI pomáhá vždy) nebo do skepse (AI nepomáhá nikdy). Upřímný pohled na to, kde AI skutečně přidává hodnotu, ti pomůže ji nasadit tam, kde to dává smysl.",
      "Kde AI typicky šetří čas:",
      [
        "První draft textu — psaní od nuly je nejnákladnější; AI draft trvá sekunda, úprava minuty",
        "Strukturování — přepis poznámek nebo neuspořádaných informací do přehledné formy",
        "Variace — místo tvorby jedné možnosti dostaneš tři; výběr je rychlejší než tvorba",
        "Přeformátování — z bulletů na odstavce, z textu na tabulku, z formálního na přátelský",
      ],
      "Kde AI čas nepřidává nebo přidává práci:",
      [
        "Krátké jednoduché věci — napsat jednu větu ručně je rychlejší než formulovat prompt",
        "Vysoce specifický kontext — pokud musíš napsat víc textu jako kontext než je výstup, nedává to smysl",
        "Ověřování faktů — AI výstup, který musíš doslova každou větu zkontrolovat, ušetří málo",
      ],
      "Praktický test: pokud ti tvorba dobrého promptu trvá déle než 2 minuty a výstup bude kratší než stránka — zvažte, jestli je AI opravdu rychlejší. Pokud ano, jděte do šablony.",
      "Cílem dne není odpovědět 'AI mi šetří čas'. Cílem je vědět konkrétně: kde ano, jak moc a proč.",
    ],
    taskIntro: "Projdi svůj minulý týden a udělej malý experiment:",
    taskItems: [
      "Vyber 3 různé úkoly, které jsi dělala — s AI nebo bez ní",
      "Odhadni: kolik minut trvaly vs. kolik by trvaly s/bez AI",
      "Zapiš si, kde byl rozdíl největší — a proč",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: celý den s AI jako vedlejším nástrojem — jak to vypadá v praxi.",
  },
  {
    day: 20,
    title: "Jeden vědomý den s AI vedlejší.",
    subject: "Reálný den s AI — ne experiment, ale způsob práce.",
    preheader: "AI jako tichý spolupracovník po celý den.",
    concept: [
      "Největší posun nenastane v jednom dokonalém AI promptu. Nastane ve chvíli, kdy AI přestane být 'věc, kterou někdy zkouším', a stane se tichým nástrojem, který je přítomný celý den.",
      "To neznamená AI zapojit do každého úkolu. Znamená to být v průběhu dne pozorná na chvíle, kde by AI mohla pomoci — a ve vybraných z nich ji opravdu použít.",
      "Jak může vypadat den s AI vedlejší:",
      [
        "Ráno: rychlé shrnutí agendy nebo priorit pro dnešek — zadám AI, co mám naplánováno, dostanu přehled",
        "Před schůzkou: draft agendy nebo připravené otázky — za 2 minuty namísto 10",
        "Po schůzce: zápis z poznámek — vložím, co jsem si napsala, dostanu čistý zápis",
        "Uprostřed dne: email, který trvá — místo 20 minut iteruju s AI draft za 5",
        "Na konci dne: krátký zápis toho, co se stalo — základ pro report nebo osobní přehled",
      ],
      "Nejdůležitější věc: nevynucovat. Pokud v jeden den AI nepoužiješ vůbec, nic se neděje. Pokud ji použiješ na tři věci a jedna z nich funguje skvěle — to je výsledek.",
      "Tohle je cíl: ne zvyk používat AI vždy, ale reflex — 'tady by AI mohla pomoci' — a schopnost to za 30 vteřin otestovat.",
    ],
    taskIntro: "Dnešní úkol je na celý den, ne jen na 5 minut:",
    taskItems: [
      "Vyber 2–3 konkrétní úkoly, u kterých dnes AI použiješ — předem si je zapiš",
      "U každého zapiš: prompt, výsledek, co jsi upravila",
      "Na konci dne napiš tři věty: co fungoval, co ne, co příště změníš",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: jaký je tvůj AI styl — a proč každý pracuje s AI jinak.",
  },
  {
    day: 21,
    title: "Každý používá AI jinak. Jaký je tvůj styl?",
    subject: "Tvůj AI styl — silné stránky, preference, způsob práce.",
    preheader: "Nejlepší AI workflow je ten, který sedí tobě.",
    concept: [
      "Dva lidé se stejnými AI nástroji mohou mít zcela odlišné výsledky. Jeden je skvělý ve psaní promptů, druhý v iteraci. Jeden používá AI pro texty, druhý pro strukturování a analýzu. Jeden preferuje krátké konverzace, druhý delší dialog.",
      "Tohle není problém. Je to realita — a čím dřív to přijmeš, tím lépe budeš vědět, jak AI nasadit.",
      "Tři dimenze AI stylu:",
      [
        "Typ úkolů: kde ti AI pomáhá nejvíc — texty, strukturování, brainstorming, analýza, kódování?",
        "Způsob iterace: preferuješ dostat jednu dobrou odpověď napoprvé, nebo rychlý draft a pak opravovat?",
        "Frekvence: AI jako každodenní nástroj nebo na vybrané opakující se úkoly?",
      ],
      "Není správný nebo špatný AI styl. Jsou jen styly, které fungují lépe nebo hůř pro konkrétní práci a konkrétního člověka.",
      "Proč je tohle důležité vědět: pokud budeš AI používat způsobem, který ti nevyhovuje, přestaneš ji používat. Pokud si nastavíš AI do módu, který sedí tvé práci a tvému tempu — zůstane ti.",
      "Třetí týden je za námi. V tomhle týdnu sis postavila první šablonu, identifikovala opakující se práci a prošla první reálným dnem s AI. Teď přichází čtvrtý týden — a jde o to, jak to udělat trvalým.",
    ],
    taskIntro: "Zapiš si svůj AI styl — tři věty, konkrétně:",
    taskItems: [
      "Kde mi AI pomáhá nejvíce — jaký typ úkolů (být konkrétní, ne obecný)",
      "Jak preferuji iterovat — jeden dobrý draft, nebo rychlý základ a pak opravuji?",
      "Jak chci AI do práce zapojit — denně na vybrané věci, nebo situačně?",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden: jak si vybudovat druhý mozek s AI — kde ukládat výstupy a jak je opakovaně používat.",
  },
  {
    day: 22,
    title: "AI si nic nepamatuje. Ale ty si to zařídit můžeš.",
    subject: "Druhý mozek — kde ukládat AI výstupy, aby se nestratily.",
    preheader: "Výstup bez uložení je polovina hodnoty.",
    concept: [
      "Každý AI výstup, který si neuložíš, je pryč. Příští konverzace s AI nezačíná tam, kde jsi skončila — začíná od nuly. To je vlastnost AI, ne chyba. A lze ji kompenzovat.",
      "Druhý mozek je jednoduché místo, kde ukládáš věci, které se vrátí. AI výstupy, šablony, dobré prompty, poznatky, zápisy. Ne proto, aby to bylo hezky seřazené — ale proto, aby ses k tomu mohla vrátit.",
      "Proč to nestačí pamatovat si to v hlavě? Protože mozek je špatný úložiště pro opakující se informace a dobré úložiště pro kontext a rozhodování. Druhý mozek — digitální — přebírá ukládání. Mozek zůstane na přemýšlení.",
      "Co do druhého mozku patří:",
      [
        "Šablony a dobré prompty — ty, které opakovaně fungují",
        "AI výstupy, které chceš použít nebo na ně navázat",
        "Zápisy ze schůzek nebo dnů — připravené AI pro rychlý přístup",
        "Poznatky a nápady — krátké záznamy, které ti přišly v průběhu práce",
      ],
      "Nejdůležitější vlastnost druhého mozku: musí být rychle dostupný. Pokud se k tomu dostaneš za 10 vteřin, použiješ to. Pokud za 3 minuty hledání, nepoužiješ to nikdy.",
      "Dnes si nastavíš základ — jedno místo, kam všechno půjde. Nemusí být dokonalé. Musí existovat.",
    ],
    taskIntro: "Vyber místo pro svůj druhý mozek a nastav základ:",
    taskItems: [
      "Vyber nástroj: Notion, Google Docs, Apple Notes, Obsidian — jakýkoli, který já denně otevírám",
      "Vytvoř dokument nebo stránku nazvanou 'AI — šablony a výstupy'",
      "Vlož tam tři věci z challenge: jednu šablonu, jeden dobrý prompt, jeden výstup, který chceš znovu použít",
    ],
    taskType: "ol",
    taskTip: "Cíl: jedno místo, rychle dostupné. Není třeba složitá struktura — složitá struktura brání používání.",
    teaser: "Zítra: postavíš základ svého mini knowledge base — tak, aby výstupy z AI nezmizely.",
  },
  {
    day: 23,
    title: "Jeden dokument, který změní, jak pracuješ s AI.",
    subject: "Mini knowledge base — kontext, který používáš znovu a znovu.",
    preheader: "Jednou napsat. Použít stokrát.",
    concept: [
      "Je jedna věc, kterou AI znovu a znovu potřebuje, a ty ji znovu a znovu opakuješ: kontext o tobě a tvé práci.",
      "Kdo jsi, co děláš, pro koho, jak komunikuješ, jaká jsou tvoje typická témata. Každý nový chat začíná od nuly — a bez kontextu dostáváš generické výstupy.",
      "Řešení je jednoduché: napiš si jednou dobře svůj pracovní kontext. Uloži ho. A příště ho jen zkopíruj na začátek konverzace. Za 10 vteřin máš AI, která 'zná' tebe.",
      "Co do pracovního kontextu patří:",
      [
        "Tvoje role a obor — konkrétně, ne obecně ('produktová manažerka v B2B SaaS' ne 'pracuji v IT')",
        "Tvoje typické úkoly — 3–5 věcí, které děláš pravidelně",
        "Tvoje cílová skupina — komu výstupy slouží (klienti, tým, vedení...)",
        "Preferovaný tón komunikace — formální, přátelský, technický, přímý",
        "Co AI nesmí dělat — co je v tvojí práci citlivé nebo co nechceš v výstupech",
      ],
      "Druhá část mini knowledge base: opakující se prompty. Každý prompt, který sis za challenge napsala a fungoval, ulož. Příště ho dostaneš za 10 vteřin. Tak se buduje osobní nástroj, ne jen znalost.",
      "Cílem dnešního dne je mít dokument, který existuje a funguje. Ne dokonalou databázi — jen použitelný základ.",
    ],
    taskIntro: "Napiš svůj pracovní kontext — základ mini knowledge base:",
    taskItems: [
      "Role a obor: kdo jsi a v jakém kontextu pracuješ (2–3 věty)",
      "Typické úkoly: 3–5 věcí, které děláš pravidelně",
      "Tón a omezení: jak chceš, aby AI komunikovala — a co nesmí dělat",
      "Ulož jako první dokument do svého druhého mozku z D22",
    ],
    taskType: "ol",
    taskPrompt: "Pracuji jako [role] v [obor nebo typ firmy]. Moje typické úkoly jsou: [3–5 úkolů]. Výstupy tvoří pro [koho]. Preferovaný tón: [přátelský/formální/přímý]. Nechci v výstupech: [co nechceš].",
    taskTip: "Tento dokument zkopíruj vždy na začátek konverzace s AI — okamžitě dostaneš relevantnější výstupy.",
    teaser: "Zítra: jak poznat, že AI ti skutečně pomáhá — ne pocitem, ale konkrétně.",
  },
  {
    day: 24,
    title: "Cítíš to, ale neumíš to změřit. Tady jak.",
    subject: "Jak poznat, že AI ti skutečně pomáhá.",
    preheader: "Ne 'AI mi pomáhá'. Ale proč, kde a o kolik.",
    concept: [
      "Říkat 'AI mi pomáhá' je jako říkat 'sport mi dělá dobře'. Je to pravda — ale bez konkrétnějšího pohledu nevíš, co zopakovat a co změnit.",
      "Čtyři signály, že AI ti opravdu přidává hodnotu:",
      [
        "Výstup, který by bez AI vznikl těžce nebo vůbec — ne jen rychleji",
        "Opakující se úkol, který teď trvá výrazně méně a výsledek je stejně dobrý",
        "Iterace, která přinesla výsledek, co by jinak trval hodinu ručního přepisování",
        "Nový pohled nebo nápad, ke kterému by ses sama nedostala rychle",
      ],
      "Čtyři signály, že AI ti práci přidává nebo neutralizuje:",
      [
        "Kontrola každé věty výstupu — pokud kontroluješ 100 %, ušetříš jen 'psaní, ne přemýšlení'",
        "Opravuješ výstup víc, než trvalo napsat ho ručně",
        "Výsledek vyžaduje tak velký kontext v promptu, že je celý proces pomalejší",
        "Stres ze zadávání AI místo radosti ze spolupráce",
      ],
      "Jak měřit (jednoduše, ne složitě): jednou za týden napiš tři věci, kde AI přidala hodnotu — konkrétní výstup, konkrétní úspora, konkrétní zlepšení. Tenhle malý záznam ti za dva týdny ukáže jasný vzorec.",
      "Proč na tom záleží? Protože bez zpětné vazby se zvyk nezvyšuje — kolísá. A cílem challenge není vědět víc o AI, ale pracovat s ní líp. Zpětná vazba je klíč.",
    ],
    taskIntro: "Retrospektiva: projdi minulé tři dny a zapiš si:",
    taskItems: [
      "Jeden konkrétní případ, kde AI přidala skutečnou hodnotu — co to bylo a čím to bylo jiné",
      "Jeden případ, kde AI práci nepomohla nebo ji zkomplikovala — proč si myslíš, že to tak bylo",
      "Co z toho bys příště udělala jinak",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: porovnáš minulý týden s AI s hypotetickým týdnem bez ní — a uvidíš, co se změnilo.",
  },
  {
    day: 25,
    title: "Jak vypadal tento týden bez AI?",
    subject: "Zpětné srovnání — s AI vs. bez AI.",
    preheader: "Nejlepší způsob vidět pokrok: imaginární porovnání.",
    concept: [
      "Nemusíš celý týden žít bez AI, abys věděla, co změnila. Stačí si ho představit.",
      "Zpětné porovnání je myšlenkový experiment: vezmi jeden konkrétní výstup nebo proces z minulého týdne a přemýšlej — jak by vypadal, kdybys AI nepoužila? Jak dlouho by trvalo? Jak by vypadal výsledek? Kolik energie by stál?",
      "Proč je tohle cvičení tak silné: mozek si lépe pamatuje změny, pokud je porovnává s alternativou. Ne 'co se zlepšilo', ale 'jak by to bylo jinak'.",
      "Tři typy porovnání:",
      [
        "Čas: tento výstup trval 15 minut s AI. Bez AI by byl 45 minut — nebo bych ho neudělala vůbec.",
        "Kvalita: výstup, který jsem dostala po 2 iteracích, by ručně trval hodinu nebo by byl horší.",
        "Energie: tento týden jsem se na opakující se věci nedostala do stresu — protože jsem věděla, že je zvládnu rychle.",
      ],
      "Tohle není bragging o AI. Je to způsob, jak vybudovat motivaci pro pokračování — na základě skutečných dat, ne náhodného nadšení.",
      "Čtvrtý týden se blíží ke konci. Zbývají tři dny — a jsou to dny, které rozhodnou o tom, jestli to, cos se naučila, zůstane nebo zmizí.",
    ],
    taskIntro: "Vyber tři věci z minulého týdne a pro každou si napiš:",
    taskItems: [
      "Co jsi udělala s AI — konkrétní výstup nebo úspora",
      "Jak by to vypadalo bez AI — čas, kvalita nebo energie",
      "Jeden poznatek: co z tohoto porovnání si vezmeš dál",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: jak si vybudovat AI návyk, který přežije motivaci.",
  },
  {
    day: 26,
    title: "Vědět nestačí. Návyk je jiná věc.",
    subject: "Budování AI návyku — jak ho zabudovat do dne.",
    preheader: "Motivace přijde a odejde. Návyk zůstane.",
    concept: [
      "Po 25 dnech víš o AI víc, než věděla většina lidí po měsících zkoušení. Ale vědomosti zmizí, pokud za nimi nestojí návyk. A návyk nevznikne z motivace — motivace kolísá. Návyk vzniká z rutiny.",
      "Věda o návycích říká, že tři prvky dělají chování trvalým: spouštěč (cue), rutina (routine), a odměna (reward). To platí přesně i pro AI.",
      [
        "Spouštěč: konkrétní moment, který ti připomene, že AI může pomoci — ráno při otevření počítače, před schůzkou, při začátku psaní",
        "Rutina: konkrétní akce, ne obecný cíl — 'otevřu AI a napíšu prompt pro dnešní report' ne 'budu víc používat AI'",
        "Odměna: výstup, který opravdu použiješ — konkrétní hodnota, ne jen 'byl jsem produktivní'",
      ],
      "Nejčastější chyba: velký ambiciózní plán. 'Budu každý den používat AI na deset věcí' nevydrží. 'Každé pondělí ráno napíšu týdenní priority s AI' vydrží.",
      "Dobrý AI návyk je malý, konkrétní a vázaný na věc, kterou děláš tak jako tak. Přidej AI k něčemu, co děláš každý týden — a nemusíš budovat novou rutinu od nuly.",
      "Klíčová otázka: co děláš každý týden, co se dá s AI udělat lépe? Najdi tu jednu věc. Přidej k ní AI. Opakuj čtyři týdny. Pak přidej druhou věc.",
    ],
    taskIntro: "Navrhni svůj AI návyk pro příští měsíc:",
    taskItems: [
      "Vyber jednu věc, kterou děláš každý týden — a kde by AI pomohla",
      "Napiš konkrétní rutinu: kdy, co uděláš, jaký prompt použiješ",
      "Nastav si připomínku — kalendář, sticky note nebo cokoli, co ti připomene první tři týdny",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Předposlední den: nastavíš si svůj denní AI rituál — pět minut ráno, které změní celý den.",
  },
  {
    day: 27,
    title: "Pět minut ráno, které změní celý den.",
    subject: "Nastav si svůj denní AI rituál.",
    preheader: "Jeden moment každý den je víc než hodina jednou za týden.",
    concept: [
      "Nejsilnější AI návyky nejsou velké. Jsou malé, pravidelné a vázané na začátek dne.",
      "Ranní AI rituál — pět minut ráno — dokáže nastavit kontext pro celý den, identifikovat priority, a zahájit nejdůležitější práci dřív, než se roztrhne vak emailů a notifikací.",
      "Jak může vypadat pětiminutový ranní AI rituál:",
      [
        "Agenda dne: 'Mám naplánováno toto. Napiš mi tři priority a co připravit pro každou schůzku.'",
        "Psaní: 'Dnes potřebuji napsat [text]. Napiš mi draft, začnu od toho.'",
        "Příprava: 'Dnes mám schůzku s [klientem] o [tématu]. Napiš mi 5 otázek.'",
        "Reflexe: 'Co jsem udělala včera? [krátký přehled] Napiš mi jedno doporučení na dnešek.'",
      ],
      "Rituál nemusí dělat vše. Stačí jedna věc — ta, která ti dává největší return na 5 minut. Za měsíc je to 20 rituálů. Za rok 240 klidných a připravených ráno.",
      "Neboj se ho upravovat. Rituál, který perfektně funguje v pondělí, nemusí fungovat ve čtvrtek. Dobrý rituál je flexibilní — má pevnou strukturu, ale proměnlivý obsah.",
      "Tohle je předposlední den challenge. Zítra bude závěr. Dnes si nastavíš věc, která ti zůstane — i po skončení challenge.",
    ],
    taskIntro: "Nastavení ranního AI rituálu — konkrétně:",
    taskItems: [
      "Vyber jednu věc, pro které chceš AI každé ráno použít — agenda, psaní, příprava nebo reflexe",
      "Napiš si konkrétní prompt, který budeš opakovat (ulož do svého druhého mozku z D22)",
      "Nastav si připomínku na 5–7 minut ráno po dobu příštích dvou týdnů — první tři týdny jsou klíčové",
    ],
    taskType: "ol",
    taskPrompt: "Dnes mám naplánováno: [krátký přehled]. Největší priorita je: [co je nejdůležitější]. Napiš mi: 1) tři prioritní úkoly pro dnešek, 2) co připravit pro nejdůležitější schůzku nebo úkol.",
    taskTip: "Prompt si ulož do svého druhého mozku — a nastav si ho jako 'ranní rituál'.",
    teaser: "Zítra je poslední den. Závěr, reflexe — a co tě čeká dál.",
  },
  {
    day: 28,
    title: "28 dní. Co ses naučila — a co tě čeká dál.",
    subject: "Závěr Basic challenge. Tady co si vezmeš.",
    preheader: "Konec základů. Začátek systémů.",
    concept: [
      "Dvacet osm dní je za námi.",
      "Prošla jsi základy: AI jako leverage, ne jen rychlost. Anatomii dobrého promptu. Práci s kontextem. Iteraci. Šablony. Opakující se práci. Denní rituál. A — nejdůležitější — způsob přemýšlení o práci, který se změní, i když AI přestaneš používat.",
      "Co ses naučila v Basic challenge:",
      [
        "Dobrý prompt = role + úkol + kontext + formát — a proč každá část záleží",
        "Iterace jako způsob práce — první výstup je základ, ne finální produkt",
        "Opakující se práce jako signál pro šablonu nebo workflow",
        "Druhý mozek — kde ukládat výstupy, aby nezmizely",
        "AI návyk jako rutina, ne motivace — malý, pravidelný, vázaný na den",
      ],
      "Co přichází v Advanced verzi challenge:",
      [
        "3C framework: Capture, Clean, Connect — systém pro práci s informacemi a znalostmi",
        "PACT framework: Projects, Agents, Context, Tools — jak AI zapojit do projektové práce",
        "Pět superschopností, které AI spoluprací získáváš — Perception, Intelligence, Memory, Creation, Connection",
        "Leverage na úrovni systému — workflow, týmové nasazení, end-to-end procesy",
      ],
      "Basic challenge tě postavila na nohy. Advanced challenge tě naučí běžet.",
      "Ale teď — oslav, co ses naučila. 28 dní, 5–7 minut denně. To není samozřejmost. Většina lidí to nikdy nedodělá.",
    ],
    taskIntro: "Poslední úkol challenge — závěrečná reflexe:",
    taskItems: [
      "Tři největší poznatky z celé challenge — konkrétní, ne obecné",
      "Jedno místo, kde AI změnila způsob, jak pracuješ — konkrétní výstup nebo rutina",
      "Jeden cíl pro příštích 30 dní — co budeš dělat jinak s AI, specificky",
    ],
    taskType: "ol",
    taskTip: "Závěrečnou reflexi ulož do svého druhého mozku — za 3 měsíce si to přečti a uvidíš, jak daleko jsi.",
    teaser: "Advanced challenge: 3C, PACT, Superschopnosti — a systémy, které pracují za tebe.",
  },
];
