import type { ChallengeDay } from "./types";

export const challengeDataCZ: ChallengeDay[] = [
  {
    day: 0,
    title: "Tohle není jen AI challenge. Tohle je upgrade způsobu práce.",
    subject: "Začínáme. Takhle bude challenge fungovat.",
    preheader: "28 dní, 5–7 minut denně. Jeden opravdový posun.",
    concept: [
      "AI je dnes všude. Nové nástroje, nové funkce, nové sliby. A právě proto je snadné skončit u toho, že člověk jen zkouší další a další věci — ale ve skutečnosti se jeho práce moc nemění.",
      "Tahle challenge vznikla proto, aby ti pomohla udělat pravý opak.",
      "Nejde o to naučit se co nejvíc AI nástrojů. Jde o to začít AI používat prakticky, pravidelně a tak, aby ti opravdu ulehčovala práci.",
      "Každý den ti zabere přibližně 5–7 minut. Každý den si odneseš něco použitelného:",
      ["nový pohled na práci", "malý praktický krok", "konkrétní výstup", "nebo drobné zlepšení něčeho, co už děláš"],
      "Postupně si tak nebudeš jen hrát s AI, ale začneš si budovat:",
      ["lepší návyky", "menší tření v práci", "vlastní prompty, šablony a workflow", "a hlavně nový způsob přemýšlení o tom, co opravdu musíš dělat ručně"],
      "A ještě jedna důležitá věc: když během challenge narazíš na něco, co už znáš, vůbec to nevadí. Naopak. To je dobře.",
      "Můžeš:",
      ["vrátit se k některé z předchozích výzev", "rozšířit si to, co už používáš", "vylepšit si existující prompt nebo workflow", "nebo si prostě dát 5 minut cíleného tréninku něčeho, co už chceš dostat víc do praxe"],
      "Smyslem téhle challenge není stihnout všechno. Smyslem je posouvat se každý den o kousek dál.",
      "Stačí málo. Pět až sedm minut denně. Jedna myšlenka. Jeden krok. Jedno malé zlepšení.",
      "A právě z toho nakonec vzniká skutečná změna.",
    ],
    taskIntro: "Sepiš si 3 věci, které ve své práci nebo běžném dni děláš opakovaně ručně. Nemusí to být nic velkého. Stačí drobnosti, které se vracejí znovu a znovu.",
    taskItems: [],
    taskType: "text",
    teaser: "V práci se nečeká odměna za samotnou práci, ale za výsledek — a co to mění v tom, jak se zadávají AI úkoly.",
  },
  {
    day: 1,
    title: "V práci se neplatí za práci. Platí se za výsledek.",
    subject: "V práci se neplatí za práci. Platí se za výsledek.",
    preheader: "Jeden posun v myšlení, který mění všechno ostatní.",
    concept: [
      "Když je toho hodně, většinou automaticky řešíme jednu věc: jak všechno stihnout.",
      "Jenže právě tady se často láme rozdíl mezi běžným fungováním a AI-first přístupem.",
      "Nejde totiž jen o to udělat věci rychleji. Nejdřív je potřeba se zastavit a podívat se, co je vlastně skutečný výsledek, kterého chceš dosáhnout.",
      "Ne vždy se platí za to, že:",
      ["napíšeš email", "připravíš prezentaci", "vytvoříš dokument", "nebo strávíš hodinu rešerší"],
      "Platí se za to, že:",
      ["někdo dostane jasnou informaci", "vznikne rozhodnutí", "posune se projekt", "nebo se něco kvalitně připraví"],
      "A v tom je velký rozdíl.",
      "Jakmile začneš víc přemýšlet o výsledku než o samotném úkolu, začneš mnohem snáz vidět, co:",
      ["můžeš udělat jednodušeji", "můžeš zadat AI", "nemusí začínat od nuly", "nebo možná ani nemusíš dělat vůbec"],
      "Tohle je jeden z nejdůležitějších návyků celé challenge. Neptat se jen: Jak to udělám? Ale nejdřív: Čeho tím vlastně chci dosáhnout?",
    ],
    taskIntro: "Vyber si jeden úkol, který dnes řešíš, a napiš si k němu dvě věci:",
    taskItems: ["Jak ten úkol zní teď", "Jaký je skutečný výsledek, kterého chceš dosáhnout"],
    taskType: "ol",
    teaser: "Cokoliv děláš podruhé, by nemělo začínat od nuly. Ukážeme si, jak na to.",
  },
  {
    day: 2,
    title: "Cokoliv děláš podruhé, už by to nemělo začínat od nuly.",
    subject: "Co děláš podruhé, přestaň psát od nuly.",
    preheader: "Opakování je signál — ne výzva pracovat rychleji, ale postavit šablonu.",
    concept: [
      "Spousta práce nevypadá na první pohled složitě. Ale právě ty malé opakující se věci často berou nejvíc energie.",
      "Když něco děláš opakovaně, je to signál. Ne signál, že máš být rychlejší. Ale signál, že by to mělo mít šablonu, postup, prompt nebo aspoň jednodušší výchozí bod.",
      "AI je nejsilnější právě tam, kde se něco opakuje. Ne proto, že všechno udělá dokonale. Ale proto, že pomůže přestat začínat pokaždé znovu.",
      "Když si jednou vytvoříš základ — šablonu, prompt nebo jednoduchý postup — příště se začíná z toho, ne od prázdné stránky. A to je velký rozdíl v energii i čase.",
    ],
    taskIntro: "Vyber si jednu opakující se činnost a zkus si k ní napsat:",
    taskItems: ["Co se na ní opakuje?", "Co je pokaždé skoro stejné?", "Co by šlo připravit dopředu?"],
    taskType: "ul",
    teaser: "Přestaň používat AI jako vyhledávač. Je to spolupracovník — a tohle je klíčový rozdíl.",
  },
  {
    day: 3,
    title: "AI není nástroj. AI je spolupracovník.",
    subject: "Přestaň AI používat jako vyhledávač.",
    preheader: "Největší posun nastane, když přestaneš AI ptát a začneš jí zadávat práci.",
    concept: [
      "Většina lidí pořád používá AI tak, jako by to byl trochu chytřejší vyhledávač. Něco se zeptají, dostanou odpověď a tím to skončí.",
      "Jenže největší posun nastane ve chvíli, kdy AI přestaneš brát jako místo, kam něco napíšeš, a začneš ji brát jako někoho, komu zadáváš práci.",
      "Když položíš otázku, dostaneš odpověď. Když zadáš práci, můžeš dostat výsledek.",
      "Rozdíl je v tom, jak formuluješ vstup. Otázka je pasivní — čeká, co AI řekne. Zadání je aktivní — definuješ, co má AI udělat, v jakém formátu, pro koho a proč.",
      "Tohle je změna, která nejvíc mění kvalitu výstupů. A je to změna, kterou můžeš udělat hned — bez učení se nových nástrojů.",
    ],
    taskIntro: "Přepiš jeden běžný prompt do struktury:",
    taskItems: ["Role — kým má AI být", "Úkol — co přesně má udělat", "Kontext — co potřebuje vědět", "Výstup — jak má vypadat výsledek"],
    taskType: "ul",
    teaser: "Prompt není otázka. Je to zadání práce — a tenhle rozdíl mění kvalitu výstupu zásadně.",
  },
  {
    day: 4,
    title: "Prompt není otázka. Je to zadání práce.",
    subject: "Tvůj prompt je příliš vágní. Tady je jak ho opravit.",
    preheader: "Stejný princip jako u delegování práce člověku. Čím jasnější zadání, tím lepší výstup.",
    concept: [
      "Spousta lidí má pocit, že umět AI znamená znát nějaké tajné formulky nebo složité promptovací triky. Ve skutečnosti často stačí jedna jednodušší věc: umět dobře zadat práci.",
      "Stejně jako u člověka. Když někomu řekneš jen: napiš mi něco na LinkedIn — pravděpodobně dostaneš něco neurčitého. Když ale řekneš, kdo je cílovka, co má být hlavní myšlenka, jaký má být tón a jak má výstup vypadat, výsledek bude úplně jiný.",
      "Dobrý prompt má zpravidla pět složek:",
      ["Roli — kým má AI být (expert, kouč, copywriter...)", "Cíl — co má přesně udělat", "Kontext — co potřebuje vědět o projektu nebo situaci", "Omezení — co nemá dělat, jak má psát, jaký je rozsah", "Formát výstupu — odstavce, seznam, tabulka, krátký text..."],
      "A je tu ještě jedna technika, která funguje skvěle: přidej větu 'Než začneš, polož mi 3 doplňující otázky, které zlepší výstup.' AI se zeptá na to, co jí chybí — a poskytnutím lepšího kontextu bude výsledek znatelně lepší.",
    ],
    taskIntro: "Vezmi si jeden starý prompt a doplň:",
    taskItems: ["roli", "cíl", "kontext", "omezení", "formát výstupu"],
    taskType: "ul",
    teaser: "Nejdůležitější otázka není: jak to udělám rychleji? Ale: musí tohle být uděláno ručně?",
  },
  {
    day: 5,
    title: "Neřeš rychlost. Řeš leverage.",
    subject: "Zapomeň na rychlost. Řeš tohle místo toho.",
    preheader: "Leverage = přemýšlet, co musí být uděláno ručně — a co ne.",
    concept: [
      "Nejdůležitější otázka není: Jak to udělám rychleji? Ale: Musí tohle být uděláno ručně?",
      "Leverage znamená, že se nedělá všechno jen proto, že to jde. Přemýšlíš, co má zůstat na tobě, kde má pomáhat AI a co už by vůbec nemělo projít ručně od začátku do konce.",
      "Když se díváš na svůj den touhle optikou, vidíš ho jinak. Vidíš, kde je opravdová přidaná hodnota — a kde se jen spotřebuje energie na věci, které by mohl někdo (nebo něco) udělat jinak.",
      "Tohle není o lenosti. Je to o tom být chytřejší v tom, kam se investuje pozornost.",
    ],
    taskIntro: "Vezmi si dnešní seznam úkolů a rozděl si ho do 3 skupin:",
    taskItems: ["Jen já — vyžaduje moje myšlení, zkušenosti nebo rozhodování", "Já + AI — spolupráce, kde já říkám směr a AI pomáhá s exekucí", "Hlavně AI — opakující se, předvídatelné, AI to zvládne bez velkého dohledu"],
    taskType: "ol",
    teaser: "Proč dokonalost zabíjí automatizaci — a jak přestat čekat na správný moment.",
  },
  {
    day: 6,
    title: "Dokonalost zabíjí automatizaci.",
    subject: "Dokonalost tě brzdí. Dnes to změníme.",
    preheader: "Nepotřebuješ dokonalý systém. Potřebuješ první použitelnou verzi.",
    concept: [
      "Nepotřebuješ hned dokonalý systém. Potřebuješ první použitelnou verzi.",
      "Možná to bude jen jednoduchá šablona, jeden uložený prompt, krátká osnova, základní postup nebo pracovní verze něčeho, co ještě časem upravíš.",
      "Cílem není mít dnes všechno perfektní. Cílem je, aby zítra něco nemuselo vznikat znovu od nuly.",
      "Čekání na dokonalý moment je jedna z nejčastějších příčin, proč automatizace v praxi nikdy nezačne. Vždy je něco málo nedodělané, vždy by to šlo udělat lépe. Ale první použitelná verze, která funguje dnes, je vždy lepší než dokonalý systém, který vzniká půl roku.",
      "Začni málo. Uprav časem. Tak to funguje.",
    ],
    taskIntro: "Vyber si jednu opakující se věc a vytvoř si k ní první verzi něčeho použitelného:",
    taskItems: ["šablonu", "prompt", "strukturu", "nebo jednoduchý pracovní postup"],
    taskType: "ul",
    teaser: "Dnes si postavíš svůj úplně první mini AI systém. Je jednodušší, než se zdá.",
  },
  {
    day: 7,
    title: "Tvůj první mini AI systém.",
    subject: "Dnes si postavíš svůj první mini AI systém.",
    preheader: "3 kroky, jeden výstup, nulový chaos. Takhle to funguje.",
    concept: [
      "AI je nejsilnější ve chvíli, kdy se stane součástí malého workflow.",
      "Například:",
      ["poznámky z hovoru => shrnutí => follow-up email", "nápad => osnova => draft textu", "seznam úkolů => priority => plán dne"],
      "Když tyto kroky propojíš, přestaneš řešit každý krok zvlášť a začínáš myslet v celých procesech. To je změna, která ušetří nejvíc času — ne jeden rychlejší prompt, ale celý řetězec, který běží sám.",
      "Začít nemusíš složitě. I trojkrokový řetězec, který ušetří pět minut denně, má za měsíc velkou hodnotu.",
    ],
    taskIntro: "Vyber si jednu činnost, která má aspoň 2–3 navazující kroky, a napiš si:",
    taskItems: ["Co je vstup", "Co s tím může udělat AI", "Co je finální výstup"],
    taskType: "ol",
    teaser: "Prázdná stránka? AI napíše první verzi čehokoliv — bez přemýšlení, kde začít.",
  },
  {
    day: 8,
    title: "AI jako copywriter.",
    subject: "Prázdná stránka? Nikdy víc.",
    preheader: "AI napíše první verzi. Ty ji jen dotáhneš. Takhle funguje psaní s AI.",
    concept: [
      "Jedna z nejrychlejších úlev, kterou AI může přinést, je psaní. Ne proto, že by měla všechno napsat bez přemýšlení. Ale proto, že už není potřeba začínat od prázdné stránky.",
      "Stačí dodat záměr, kontext, hlavní myšlenku a tón. AI připraví první verzi, varianty nebo strukturu, od které se odpíchneš.",
      "Prázdná stránka bere energii. První verze — i ta horší — dá něco, od čeho se odpíchneš. A to je obrovská změna v tom, jak psaní probíhá.",
      "Pilit na druhé verzi je vždy rychlejší než začínat od nuly.",
    ],
    taskIntro: "Vezmi si jeden text, který dnes potřebuješ napsat, a nech si od AI připravit 3 verze:",
    taskItems: ["stručnou", "přesvědčivější", "přirozenější"],
    taskType: "ul",
    teaser: "Research nemusí být vyčerpávající. Ukážeme si, jak z AI udělat první vrstvu orientace.",
  },
  {
    day: 9,
    title: "AI jako research assistant.",
    subject: "Jak se přestat topit v researchi.",
    preheader: "Moc zdrojů, moc variant, nevíš kde začít? AI ti udělá první orientaci.",
    concept: [
      "Research umí být překvapivě vyčerpávající. Často ne proto, že je složitý problém, ale proto, že je moc zdrojů, moc variant a člověk neví, kde začít.",
      "AI umí pomoct jako první vrstva orientace:",
      ["rozdělit téma na důležité oblasti", "navrhnout rámec porovnání", "vytáhnout klíčové otázky", "nebo připravit stručné shrnutí"],
      "Tohle není záměna za hloubkový research. Je to rychlý start, který ukazuje, kde má smysl pokračovat a co si ověřit zvlášť.",
      "Místo hodiny prokousávání se weby můžeš za pět minut získat ucelenou orientaci — a pak jít do hloubky tam, kde to opravdu potřebuješ.",
    ],
    taskIntro: "Vyber si jedno téma a nech si od AI připravit:",
    taskItems: ["hlavní oblasti, které sledovat", "rámec porovnání", "otázky, které si položit", "co si máš ověřit zvlášť"],
    taskType: "ul",
    teaser: "Chaos v hlavě není problém s kapacitou. Je to problém se strukturou. AI s tím umí pomoct.",
  },
  {
    day: 10,
    title: "AI jako thinking partner.",
    subject: "Máš chaos v hlavě? Tohle zkus.",
    preheader: "AI jako partner pro přemýšlení — ne jen pro hledání odpovědí.",
    concept: [
      "Někdy člověk nesedí nad konkrétním výstupem, ale nad chaosem v hlavě. A právě v těchto chvílích může být AI překvapivě užitečná.",
      "Ne jako expert, který řekne jedinou správnou odpověď. Ale jako partner, který pomůže roztřídit myšlenky, pojmenovat problém, oddělit důležité od méně důležitého a navrhnout další rozumný krok.",
      "Zkus to takhle: místo přemýšlení o samotě vysyp chaos do AI. Napiš: 'Mám chaos v této věci, pomozte mi to roztřídit.' A pak jen odpovídej na jejich otázky.",
      "Často zjistíš, že sám proces vysypání objasní více než hodina přemýšlení o samotě.",
    ],
    taskIntro: "Vezmi si jedno téma, které teď nosíš v hlavě a ještě v něm nemáš jasno. Vysyp ho do AI a nech ji, ať ti pomůže:",
    taskItems: ["rozdělit to do bloků", "pojmenovat hlavní problém", "navrhnout 2–3 možné směry", "určit nejlepší další krok"],
    taskType: "ul",
    teaser: "Rozhodování je náročné. AI s ním umí pomoct — ne tím, že rozhodne za tebe, ale tím, že uvidíš možnosti čistěji.",
  },
  {
    day: 11,
    title: "AI jako decision partner.",
    subject: "Jak se líp rozhodovat s pomocí AI.",
    preheader: "AI nerozhoduje za tebe. Pomáhá ti vidět možnosti čistěji.",
    concept: [
      "Spousta práce není o tom něco vytvořit. Spousta práce je o tom rozhodnout se.",
      "AI nerozhoduje za tebe. Pomáhá ti vidět možnosti čistěji:",
      ["zpřehlednit varianty", "pojmenovat plusy a mínusy", "ukázat trade-offy", "upozornit na rizika"],
      "Když člověk rozhoduje sám, je těžké vidět všechno najednou. Dochází k přemýšlení v kruzích, resetování na známá řešení nebo ignorování aspektů, které jsou nepříjemné.",
      "AI pomůže rozložit rozhodnutí na části, které se dají porovnat. Není to náhrada za vlastní úhel pohledu — ale je to spolehlivý způsob, jak nic nedoohlat.",
    ],
    taskIntro: "Vyber si jedno skutečné rozhodnutí. Dej AI:",
    taskItems: ["možnosti, mezi kterými vybíráš", "čeho chceš dosáhnout", "co tě omezuje", "čeho se obáváš"],
    taskType: "ul",
    teaser: "Co by se stalo, kdyby každý meeting měl automatické shrnutí a jasné next steps?",
  },
  {
    day: 12,
    title: "AI jako meeting assistant.",
    subject: "Co by se stalo, kdyby každý meeting měl automatické shrnutí?",
    preheader: "Meetingy berou energii. Chybějící shrnutí a next steps berou čas navíc. AI to řeší.",
    concept: [
      "Meetingy často neberou nejvíc času. Berou nejvíc energie. A největší problém bývá, že po nich chybí stručné shrnutí, jasné rozhodnutí a další kroky.",
      "AI umí z poznámek nebo přepisu rychle vytvořit:",
      ["přehledné shrnutí", "seznam úkolů", "otevřené otázky", "a follow-up zprávu"],
      "To znamená, že už není potřeba po každém meetingu sedět další půlhodinu nad zápisem. Stačí mít hrubé poznámky — a AI z nich vytvoří strukturovaný výstup za pár minut.",
    ],
    taskIntro: "Vezmi si poslední meeting, call nebo poznámky z rozhovoru a nech AI vytvořit:",
    taskItems: ["stručné shrnutí", "hlavní rozhodnutí", "další kroky", "krátký follow-up"],
    taskType: "ul",
    teaser: "Příliš mnoho úkolů, příliš málo jasna. Jak AI pomůže nastavit priority.",
  },
  {
    day: 13,
    title: "AI jako personal productivity coach.",
    subject: "Moc úkolů, málo jasna. AI ti pomůže nastavit priority.",
    preheader: "Přetlak není o nástrojích. Je o prioritách. A s těmi AI umí pomoct.",
    concept: [
      "Produktivita dnes často nevypadá jako nedostatek nástrojů. Spíš jako přetlak: moc úkolů, moc věcí v hlavě, moc rozhodování.",
      "AI může fungovat jako vnější mozek, který pomůže:",
      ["ujasnit si priority", "zmenšit chaos", "odložit méně důležité věci", "a udělat plán, který je reálně proveditelný"],
      "Nejde o to mít dokonalý time management systém. Jde o to vidět jasně, co je dnes opravdu důležité — a co může počkat.",
      "Když AI řekneš, kolik je času, co je na listě a co je opravdu náročné, pomůže sestavit den, který není jen seznam — ale je realistický.",
    ],
    taskIntro: "Vezmi si dnešní nebo zítřejší seznam úkolů, přidej k němu:",
    taskItems: ["kolik máš času", "jakou máš kapacitu", "co je opravdu důležité", "co je spíš: bylo by fajn"],
    taskType: "ul",
    teaser: "Sestavíš si svůj vlastní AI copilot — první verzi toho, jak budeš s AI pracovat každý den.",
  },
  {
    day: 14,
    title: "Tvůj osobní AI copilot.",
    subject: "Tvůj osobní AI copilot — první verze.",
    preheader: "Dnes si složíš, jak chceš s AI pracovat každý den. Je to jednodušší, než zní.",
    concept: [
      "Jednotlivé role AI jsou užitečné. Ale skutečný posun přichází ve chvíli, kdy si z toho začneš skládat vlastní systém.",
      "Na začátek stačí, když si ujasníš:",
      ["na co AI používáš nejčastěji", "kde ti opravdu šetří čas", "kde ti pomáhá líp přemýšlet", "a které prompty nebo postupy si chceš uložit"],
      "AI copilot není appka. Je to způsob práce. Je to sada návyků, promptů a rutin, která funguje pro tebe — a která denně ulehčuje práci.",
      "První verze nemusí být dokonalá. Stačí, že existuje. Buduj ji postupně.",
    ],
    taskIntro: "Sepiš si svou první verzi osobního AI copilot setupu:",
    taskItems: ["Na co AI používám nejčastěji?", "Kde mi nejvíc šetří čas?", "Kde mi pomáhá dělat lepší práci?", "Jaké 3–5 promptů nebo postupů si chci uložit?", "Co chci, aby byl defaultní způsob práce s AI?"],
    taskType: "ul",
    teaser: "Neautomatizuj všechno — ale tohle automatizuj určitě. Jak najít správné kandidáty.",
  },
  {
    day: 15,
    title: "Neautomatizuj všechno. Automatizuj to, co má největší dopad.",
    subject: "Neautomatizuj všechno. Automatizuj tyhle věci.",
    preheader: "Nejde o to automatizovat co nejvíc. Jde o to vybrat to, co vrátí nejvíc.",
    concept: [
      "Nejde o to automatizovat co nejvíc. Jde o to automatizovat to, co vrátí nejvíc času, energie nebo pozornosti.",
      "Nejlepší kandidáti bývají věci, které jsou:",
      ["opakující se", "předvídatelné", "trochu otravné", "časově náročné", "a mají poměrně jasný vstup i výstup"],
      "Naopak nestojí za to automatizovat věci, které jsou vždy jiné, vyžadují osobní úhel pohledu nebo které jsou tak jednoduché, že je rychlejší je udělat ručně než nastavovat.",
      "Automatizace má smysl tam, kde se čas navrátí. Ne všude.",
    ],
    taskIntro: "Podívej se na činnosti, které se během challenge opakovaly nejčastěji. U každé si zkus říct:",
    taskItems: ["Jak často se děje?", "Kolik času bere?", "Jak moc mentálně vyčerpává?", "Jak moc je předvídatelná?"],
    taskType: "ul",
    teaser: "Zapomeň na appky. Nejdřív musíš pochopit samotný tok práce — a pak teprve vybírat nástroje.",
  },
  {
    day: 16,
    title: "Začni přemýšlet v logice workflow, ne nástrojů.",
    subject: "Zapomeň na appky. Nejdřív pochop workflow.",
    preheader: "Výběr nástroje je až druhý krok. Tady je, co přijde první.",
    concept: [
      "Dřív než vybírat appku, je potřeba pochopit samotný tok práce:",
      ["co je spouštěč", "co je vstup", "co má udělat AI nebo systém", "a co je výstup"],
      "Tohle je no-code mindset.",
      "Když si tohle nejdřív napíšeš na papír, vybereš nástroj mnohem lépe. A často zjistíš, že ani nepotřebuješ nový nástroj — že stačí lepší použití toho, co už máš.",
    ],
    taskIntro: "Vyber si jednu opakující se činnost a popiš si ji v této struktuře:",
    taskItems: ["Spouštěč — co spouští tento proces?", "Vstup — co je zdrojový materiál?", "Zpracování — co s tím dělá AI nebo systém?", "Výstup — co je finální výsledek?"],
    taskType: "ul",
    teaser: "Komunikace, která se nemusí pokaždé psát od začátku. AI-first přístup k opakujícím se zprávám.",
  },
  {
    day: 17,
    title: "Komunikace nemusí pokaždé začínat od nuly.",
    subject: "Přestaň psát podobné zprávy pokaždé od začátku.",
    preheader: "Reusable struktura + lidská finalizace. Takhle vypadá AI-first komunikace.",
    concept: [
      "Velká část komunikace v práci je opakující se. Podobné odpovědi, follow-upy, potvrzení, shrnutí.",
      "AI-first komunikace není robotická komunikace. Je to reusable struktura plus lidská finalizace.",
      "Principem je jednoduchý: mít základ, který můžeš vzít, upravit za dvě minuty a odeslat — místo že každý email vzniká znovu od nuly.",
      "Časem si z toho můžeš sestavit celou sadu šablon pro nejčastější typy zpráv. A když dojde na něco konkrétního, jen doplníš detaily.",
    ],
    taskIntro: "Vyber si jeden typ zprávy, který píšeš často, a vytvoř si k němu první reusable základ:",
    taskItems: ["osnovu", "šablonu", "nebo prompt"],
    taskType: "ul",
    teaser: "Jedna myšlenka, tři výstupy. Takhle vypadá obsah s leverage.",
  },
  {
    day: 18,
    title: "Jedna myšlenka nemusí skončit v jednom výstupu.",
    subject: "Jedna myšlenka, tři výstupy. Takhle funguje leverage obsahu.",
    preheader: "Přestaň vymýšlet nové věci. Začni víc těžit z toho, co už máš.",
    concept: [
      "Jedna dobrá myšlenka může být post, krátký newsletter, část webového textu, FAQ, osnova videa nebo základ pro další obsah.",
      "AI pomůže přepnout z režimu: zase něco nového vymyslet — do režimu: jak z toho, co už mám, vytěžit víc.",
      "Tohle je jeden z nejsilnějších AI use cases pro tvorbu obsahu. Nepotřebuješ mít víc nápadů — stačí mít lepší leverage z těch, které už existují.",
      "Místo jednoho postu za týden mohou být tři výstupy z jednoho nápadu — a každý v jiné formě a cílící na jiný kontext.",
    ],
    taskIntro: "Vezmi si jeden existující obsahový vstup (článek, poznámky, email, záznam...) a nech si z něj pomocí AI vytvořit aspoň 3 různé výstupy.",
    taskItems: [],
    taskType: "text",
    teaser: "Největší chaos nevzniká v práci. Vzniká mezi kroky. A s tím si AI umí poradit.",
  },
  {
    day: 19,
    title: "Nejvíc chaosu často nevzniká v práci. Ale mezi kroky.",
    subject: "Kde vzniká chaos, který tě brzdí — a jak ho zmenšit.",
    preheader: "Problém nebývá v samotné práci. Je v předávání, v mezerách, v přechodech.",
    concept: [
      "Neefektivita často nevzniká v samotné práci, ale mezi ní: mezi meetingem a exekucí, mezi člověkem a systémem, mezi nápadem a výstupem.",
      "AI může pomoct zlepšit strukturu předání:",
      ["co se má shrnout", "co se má zapsat", "co je další krok", "a kdo ho má udělat"],
      "Když si tohle ujasníš a nastavíš, přestaneš ztrácet informace mezi kroky. A to je často to místo, kde se práce nejvíc zadrhává.",
    ],
    taskIntro: "Vyber si jedno místo, kde se často ztrácí informace, a napiš si:",
    taskItems: ["Co se má vždy předat?", "Co by mělo být stručně shrnuté?", "Co by se mělo zapsat do systému?", "Co je jasný další krok?"],
    taskType: "ul",
    teaser: "Data sama o sobě nestačí. Pomáhá až to, co z nich pochopíš — a AI ti s tím pomůže.",
  },
  {
    day: 20,
    title: "Data sama o sobě nepomáhají. Pomáhá až to, co z nich pochopíš.",
    subject: "Jak z dat dostat to, co opravdu potřebuješ vědět.",
    preheader: "Data bez interpretace jsou jen hluk. AI ti pomůže najít vzorec.",
    concept: [
      "Data pomáhají až ve chvíli, kdy z nich vznikne vzorec, insight, rozhodnutí nebo další krok.",
      "AI ti může pomoct:",
      ["vytáhnout opakující se témata", "pojmenovat, co je důležité", "odhalit, co je překvapivé", "a navrhnout, co z toho dává smysl udělat dál"],
      "Není potřeba umět pracovat s tabulkami ani vidět v číslech. Stačí dát AI kontext — a ona pomůže najít, co v těch datech opravdu je.",
    ],
    taskIntro: "Vezmi si jeden skutečný datový nebo textový vstup a nech AI odpovědět:",
    taskItems: ["Co se tu opakuje?", "Co je tu nejdůležitější?", "Co by z toho mělo následovat dál?"],
    taskType: "ul",
    teaser: "Propojené kroky mění všechno. Dnes si ukážeme, jak je popsat a začít stavět.",
  },
  {
    day: 21,
    title: "Skutečný posun přichází ve chvíli, kdy propojíš jednotlivé kroky.",
    subject: "Propojené kroky mění všechno. Tady je jak na to.",
    preheader: "Jeden dobrý prompt nestačí. Skutečná úleva přijde, když kroky začnou navazovat.",
    concept: [
      "Největší úleva často nepřichází z jednoho dobrého promptu. Přichází ve chvíli, kdy na sebe začnou navazovat jednotlivé kroky tak, že už není potřeba všechno držet v hlavě a posouvat ručně.",
      "Například: meeting skončí, poznámky jdou do AI, AI vytvoří shrnutí + úkoly, úkoly jdou do taskmanageru, follow-up email odešleš za minutu.",
      "Každý krok sám o sobě je malý. Propojené dohromady ušetří desítky minut týdně.",
      "Tohle je AI-first způsob práce: ne používat AI nárazově, ale mít málo propojených řetězců, které fungují stále.",
    ],
    taskIntro: "Vyber si jednu oblast a popiš si jednoduchý řetězec:",
    taskItems: ["Co je vstup?", "Co udělá AI?", "Co se kam uloží?", "Kde zůstává kontrola na člověku?", "Co je finální výstup?"],
    taskType: "ul",
    teaser: "AI transformace ve firmě nezačíná u nástroje. Začíná u práce. A tam je i správné místo začít.",
  },
  {
    day: 22,
    title: "AI ve firmě nezačíná u nástroje. Začíná u práce.",
    subject: "AI ve firmě nezačíná u nástroje.",
    preheader: "Kde opravdu začít AI transformaci — a kde se většina firem mýlí.",
    concept: [
      "AI transformace nezačíná u technologie. Začíná u práce samotné.",
      "U toho, kde ve firmě vzniká:",
      ["opakující se ruční činnost", "zbytečné přeposílání informací", "ztráta know-how", "pomalé rozhodování", "nebo práce s nízkou přidanou hodnotou"],
      "Teprve když toto vidíš jasně, má smysl ptát se: kde by AI mohla pomoct nejrychleji a s největší přidanou hodnotou?",
      "Firmy, které začnou od nástroje, často skončí u toho, že nový nástroj zůstane nevyužívaný. Firmy, které začnou od práce, najdou místa, kde je změna opravdu cítit.",
    ],
    taskIntro: "Vyber si jeden tým, oddělení nebo část firmy a zkus si pojmenovat:",
    taskItems: ["Kde vzniká nejvíc opakující se ruční práce?", "Kde se ztrácí kontext nebo know-how?", "Kde lidé tráví čas něčím, co nemá nejvyšší hodnotu?", "Kde by menší změna mohla přinést rychlý dopad?"],
    taskType: "ul",
    teaser: "Každý tým potřebuje jiné AI use cases. Jak je najít a jak začít tam, kde to dává smysl.",
  },
  {
    day: 23,
    title: "Každý tým potřebuje jiné AI use cases.",
    subject: "Každý tým potřebuje jiné AI use cases. Tady je jak na to.",
    preheader: "Jedno řešení pro všechny nefunguje. AI adopce musí vycházet z konkrétní práce.",
    concept: [
      "Každý tým pracuje jinak. Má jiné cíle, jiné tření, jiné tempo i jiné typy úkolů. Proto dává větší smysl hledat AI use cases podle konkrétní role a konkrétní práce.",
      "Use cases se často dají rozdělit do tří skupin:",
      ["AI něco draftuje — připravuje první verze textu, emailu, dokumentu", "AI něco shrnuje — z hovoru, meetingu, dat, zpětné vazby", "AI je součástí workflow — zpracovává vstup a předává dál"],
      "Pro každý tým je pak správná otázka: kde se tráví nejvíc času na věcech s nízkou přidanou hodnotou? Právě tam je nejlepší začít.",
    ],
    taskIntro: "Vyber si jeden konkrétní tým a napiš si:",
    taskItems: ["Co dělají často?", "Co je nejvíc zdržuje?", "Co se opakuje?", "Co by AI mohla připravovat, shrnovat nebo zrychlovat?"],
    taskType: "ul",
    teaser: "Lidi nepřesvědčí technologie. Přesvědčí je přínos. Jak mluvit o AI jazykem, který funguje.",
  },
  {
    day: 24,
    title: "Lidi nepřesvědčí technologie. Přesvědčí je přínos.",
    subject: "Jak přesvědčit lidi, kteří AI zatím nepotřebují.",
    preheader: "Přestaň mluvit o AI jako o technologii. Mluv o ní jako o práci.",
    concept: [
      "Většina lidí nepotřebuje slyšet, že AI je budoucnost. Potřebuje pochopit, co jim konkrétně ulehčí už teď.",
      "Proto je důležité mluvit o AI jazykem práce, ne jazykem nástrojů.",
      "Místo: 'Tohle umí generovat text pomocí large language modelu' říkej: 'Tohle ti ušetří hodinu psaní draftu týdně.'",
      "Lidé změní chování, když vidí, že jim to něco konkrétního ulehčí. Ne když slyší, že to je cool technologie.",
    ],
    taskIntro: "Vyber si jednu konkrétní roli nebo člověka a zkus si napsat:",
    taskItems: ["Čeho se ten člověk může obávat?", "Co ho v práci nejvíc zdržuje?", "Kde by mu AI mohla dát rychlý a viditelný přínos?", "Jak by vypadal malý quick win, který by dával smysl ukázat jako první?"],
    taskType: "ul",
    teaser: "Pár jednoduchých pravidel AI governance — která ušetří problémy a dají lidem jistotu.",
  },
  {
    day: 25,
    title: "Bez pravidel vzniká chaos. S příliš mnoha pravidly nevznikne nic.",
    subject: "AI governance: pár pravidel, která ti ušetří problémy.",
    preheader: "Dobrá governance lidi neodrazuje. Dává jim jistotu, že to dělají správně.",
    concept: [
      "Dobrá governance nemá lidi odradit. Má jim pomoct používat AI bezpečněji, rozumněji a s větší jistotou.",
      "Na začátek často stačí pár jednoduchých a srozumitelných pravidel:",
      ["co je bezpečné používat", "co anonymizovat", "co musí vidět člověk", "a kde je potřeba větší opatrnost"],
      "Příliš málo pravidel vede k chaosu — někdo sdílí co by nemělo jít ven, někdo spoléhá na výstup, který by měl kontrolovat. Příliš mnoho pravidel lidi od AI odrazuje.",
      "Cíl je jednoduchý: dát lidem jasný rámec, ve kterém se můžou pohybovat bez strachu, že něco pokazí.",
    ],
    taskIntro: "Sepiš si první jednoduchou verzi AI pravidel pro sebe nebo svůj tým:",
    taskItems: ["Co je v pořádku dávat do AI?", "Co by bylo lepší anonymizovat nebo tam nedávat vůbec?", "Které výstupy by nikdy neměly být bez lidské kontroly?", "U jakých typů práce je potřeba větší opatrnost?"],
    taskType: "ul",
    teaser: "Jak AI adopci rozšířit přes celou firmu — a ne jen u pár nadšenců.",
  },
  {
    day: 26,
    title: "AI adopce se neškáluje přístupem. Škáluje se tím, co se dá sdílet a znovu použít.",
    subject: "Jak rozšířit AI adopci přes celou firmu.",
    preheader: "Pokud to zůstane jen u pár lidí, adopce se nikam neposune. Tady je jak dál.",
    concept: [
      "Pokud všechno zůstane jen u několika jednotlivců, adopce se dál neposune. Know-how zůstane rozptýlené a výsledky budou nekonzistentní.",
      "Skutečné škálování začíná ve chvíli, kdy se úspěch dá sdílet:",
      ["prompt library", "seznam use cases", "ukázky toho, co funguje", "jednoduché standardy", "malá knowledge base"],
      "Tohle je moment, kdy AI přestává být projektem jednotlivců a stává se součástí toho, jak firma pracuje.",
      "Začni málo: jeden sdílený dokument s prompty, jeden příklad toho, co funguje — a to postačí jako začátek.",
    ],
    taskIntro: "Podívej se na to, co už funguje, a napiš si:",
    taskItems: ["Co by stálo za to sdílet dál?", "Co by šlo uložit jako prompt, šablonu nebo příklad?", "Co by pomohlo ostatním začít rychleji?", "Co by mohlo být základem malého AI adoption kitu?"],
    taskType: "ul",
    teaser: "Teď už neskládáš tipy. Skládáš svůj vlastní AI systém. Předposlední den.",
  },
  {
    day: 27,
    title: "Teď už neskládáš tipy. Skládáš svůj vlastní AI systém.",
    subject: "Teď už neskládáš tipy. Skládáš systém.",
    preheader: "Zítra je poslední den challenge. Dnes si sestavíš, co si odnášíš.",
    concept: [
      "Skutečný AI systém není jeden nástroj. Je to způsob práce, ve kterém se potkává:",
      ["jak přemýšlíš o úkolech", "co deleguješ AI", "co si ukládáš", "co znovu používáš", "jak si buduješ knowledge base", "a kde si necháváš lidskou kontrolu"],
      "Teď, po 27 dnech, už není těžké tohle sestavit. Máš dostatek zkušeností, aby ti to dávalo smysl.",
      "První verze AI systému nemusí být dokonalá. Ale musí existovat — jinak to zůstane jen u nápadu.",
    ],
    taskIntro: "Sepiš si první verzi svého AI systému:",
    taskItems: ["Na co AI používám nejčastěji", "Jaké prompty nebo šablony si chci uložit", "Jaké workflow už mi dávají smysl", "Kde mám své poznámky, podklady a reusable assets", "Kde potřebuji lidskou kontrolu", "Co už nechci příště dělat od nuly ručně"],
    taskType: "ul",
    teaser: "Poslední den challenge. A zároveň začátek toho, co přijde po ní.",
  },
  {
    day: 28,
    title: "Skutečná změna začíná až teď.",
    subject: "28 dní za tebou. Skutečná změna začíná teď.",
    preheader: "Dokončení challenge není cíl. Je to začátek. Tady je co dál.",
    concept: [
      "Dokončení challenge není cíl. Je to začátek.",
      "Nejde o to projít 28 dní a vyzkoušet 28 věcí. Jde o to, co z toho zůstane v běžné práci i potom.",
      "Nejsilnější změna nevzniká z jednoho velkého skoku. Vzniká z malého kroku opakovaného každý den.",
      "Za sebou je 28 kroků. Teď jde jen o jedno: udržet rytmus.",
    ],
    taskIntro: "Sepiš si krátký plán na dalších 90 dní ve 4 bodech:",
    taskItems: ["Keep — co si chci určitě udržet", "Build — co chci dál rozvíjet nebo postavit", "Share — co chci sdílet s ostatními", "Measure — podle čeho poznám, že mi to opravdu pomáhá"],
    taskType: "ul",
    teaser: "",
  },
];
