import type { ChallengeDay } from "./types";

export const challengeDataCZ: ChallengeDay[] = [
  {
    day: 0,
    title: "Tohle není AI challenge. Tohle je upgrade způsobu práce.",
    subject: "Začínáme. Takhle bude challenge fungovat.",
    preheader: "28 dní, 5-7 minut denně. Jeden opravdový posun.",
    concept: [
      "AI je dnes všude. Nové nástroje, nové funkce, nové sliby. A právě proto je snadné skončit u toho, že člověk jen zkouší další a další věci — ale ve skutečnosti se jeho práce moc nemění.",
      "Tahle challenge vznikla proto, aby ti pomohla udělat pravý opak.",
      "Nejde o to naučit se co nejvíc AI nástrojů. Jde o to začít AI používat prakticky, pravidelně a tak, aby ti opravdu ulehčovala práci.",
      "Každý den ti zabere přibližně 5-7 minut. Každý den si odneseš něco použitelného: nový pohled na práci, malý praktický krok, konkrétní výstup, nebo drobné zlepšení něčeho, co už děláš.",
      "Postupně si tak nebudeš jen hrát s AI, ale začneš si budovat lepší návyky, menší tření v práci, vlastní prompty, šablony a workflow — a hlavně nový způsob přemýšlení o tom, co opravdu musíš dělat ručně.",
      "Smyslem téhle challenge není stihnout všechno. Smyslem je posouvat se každý den o kousek dál.",
    ],
    taskIntro: "Sepiš si 3 věci, které ve své práci nebo běžném dni děláš opakovaně ručně.",
    taskItems: [],
    taskType: "text",
    teaser: "Proč nejsi placená za práci, ale za výsledek — a co to mění v tom, jak zadáváš AI úkoly.",
  },
  {
    day: 1,
    title: "Nejsi placená za práci. Jsi placená za výsledek.",
    subject: "Nejsi placená za práci. Jsi placená za výsledek.",
    preheader: "Jeden posun v myšlení, který mění všechno ostatní.",
    concept: [
      "Když máme hodně práce, většinou automaticky řešíme jednu věc: jak všechno stihnout.",
      "Jenže právě tady se často láme rozdíl mezi běžným fungováním a AI-first přístupem.",
      "Nejde totiž jen o to udělat věci rychleji. Nejdřív je potřeba se zastavit a podívat se, co je vlastně skutečný výsledek, kterého chceš dosáhnout.",
      "Někdy nejsi placená za to, že napíšeš email, připravíš prezentaci, vytvoříš dokument nebo strávíš hodinu rešerší. Jsi placená za to, že někdo dostane jasnou informaci, vznikne rozhodnutí, posune se projekt, nebo se něco kvalitně připraví.",
      "Jakmile začneš víc přemýšlet o výsledku než o samotném úkolu, začneš mnohem snáz vidět, co můžeš udělat jednodušeji, co můžeš zadat AI, co nemusíš dělat od nuly, nebo co možná ani nemusíš dělat vůbec.",
    ],
    taskIntro: "Vyber si jeden úkol, který dnes řešíš, a napiš si:",
    taskItems: ["Jak ten úkol zní teď", "Jaký je skutečný výsledek, kterého chceš dosáhnout"],
    taskType: "ol",
    teaser: "Cokoliv děláš podruhé, by nemělo začínat od nuly. Ukážeme si, jak na to.",
  },
  {
    day: 2,
    title: "Cokoliv děláš podruhé, už bys neměla dělat od nuly.",
    subject: "Co děláš podruhé, přestaň psát od nuly.",
    preheader: "Opakování je signál — ne výzva pracovat rychleji, ale postavit šablonu.",
    concept: [
      "Spousta práce nevypadá na první pohled složitě. Ale právě ty malé opakující se věci často berou nejvíc energie.",
      "Když něco děláš opakovaně, je to signál. Ne signál, že máš být rychlejší. Ale signál, že by to mělo mít šablonu, postup, prompt nebo aspoň jednodušší výchozí bod.",
      "AI je nejsilnější právě tam, kde se něco opakuje. Ne proto, že všechno udělá dokonale. Ale proto, že ti pomůže přestat začínat pokaždé znovu.",
    ],
    taskIntro: "Vyber si jednu opakující se činnost a zkus si k ní napsat:",
    taskItems: ["Co se na ní opakuje?", "Co je pokaždé skoro stejné?", "Co by šlo připravit dopředu?"],
    taskType: "ul",
    teaser: "Přestaň používat AI jako vyhledávač. Je to spolupracovník — a tohle je klíčový rozdíl.",
  },
  {
    day: 3,
    title: "AI není nástroj. AI je spolupracovník.",
    subject: "Přestaň AI používat jako vyhledávač.",
    preheader: "Největší posun nastane, když AI přestaneš ptát a začneš jí zadávat práci.",
    concept: [
      "Většina lidí pořád používá AI tak, jako by to byl trochu chytřejší vyhledávač. Něco se zeptají, dostanou odpověď a tím to skončí.",
      "Jenže největší posun nastane ve chvíli, kdy AI přestaneš brát jako místo, kam něco napíšeš, a začneš ji brát jako někoho, komu zadáváš práci.",
      "Když položíš otázku, dostaneš odpověď. Když zadáš práci, můžeš dostat výsledek.",
    ],
    taskIntro: "Přepiš jeden běžný prompt do struktury:",
    taskItems: ["Role", "Úkol", "Kontext", "Výstup"],
    taskType: "ul",
    teaser: "Prompt není otázka. Je to zadání práce — a tenhle rozdíl mění kvalitu výstupu zásadně.",
  },
  {
    day: 4,
    title: "Prompt není otázka. Je to zadání práce.",
    subject: "Tvůj prompt je příliš vágní. Tady je jak ho opravit.",
    preheader: "Stejný princip jako u delegování práce člověku. Čím jasnější zadání, tím lepší výstup.",
    concept: [
      "Spousta lidí má pocit, že umět AI znamená znát nějaké tajné formulky nebo složité promptovací triky. Ve skutečnosti často stačí jedna jednodušší věc: umět dobře zadat práci.",
      "Stejně jako u člověka. Když někomu řekneš jen: napiš mi něco na LinkedIn — pravděpodobně dostaneš něco neurčitého. Když ale řekneš, kdo je cílovka, co má být hlavní myšlenka, jaký má být tón a jak má výstup vypadat, výsledek bude úplně jiný.",
    ],
    taskIntro: "Vezmi si jeden starý prompt a doplň:",
    taskItems: ["roli", "cíl", "kontext", "omezení", "formát výstupu"],
    taskType: "ul",
    teaser: "Nejdůležitější otázka není: jak to udělám rychleji? Ale: musím tohle dělat já?",
  },
  {
    day: 5,
    title: "Neřeš rychlost. Řeš leverage.",
    subject: "Zapomeň na rychlost. Řeš tohle místo toho.",
    preheader: "Leverage = přemýšlíš, co musíš dělat ty — a co ne.",
    concept: [
      "Nejdůležitější otázka není: Jak to udělám rychleji? Ale: Musím tohle dělat já?",
      "Leverage znamená, že neděláš všechno sama jen proto, že to udělat umíš. Ale přemýšlíš, co má zůstat na tobě, kde ti má pomáhat AI a co už by vůbec nemělo projít ručně od začátku do konce.",
    ],
    taskIntro: "Vezmi si dnešní seznam úkolů a rozděl si ho do 3 skupin:",
    taskItems: ["Jen já", "Já + AI", "Hlavně AI"],
    taskType: "ol",
    teaser: "Proč dokonalost zabíjí automatizaci — a jak přestat čekat na správný moment.",
  },
  {
    day: 6,
    title: "Dokonalost zabíjí automatizaci.",
    subject: "Dokonalost tě brzdí. Dnes to změníme.",
    preheader: "Nepotřebuješ dokonalý systém. Potřebuješ první použitelnou verzi.",
    concept: [
      "Nepotřebuješ hned dokonalý systém. Potřebuješ první použitelnou verzi.",
      "Možná to bude jen jednoduchá šablona, jeden uložený prompt, krátká osnova, základní postup nebo pracovní verze něčeho, co ještě časem upravíš.",
      "Cílem není mít dnes všechno perfektní. Cílem je, aby zítra něco nemuselo vznikat znovu od nuly.",
    ],
    taskIntro: "Vyber si jednu opakující se věc a vytvoř si k ní první verzi něčeho použitelného:",
    taskItems: ["šablonu", "prompt", "strukturu", "nebo jednoduchý pracovní postup"],
    taskType: "ul",
    teaser: "Dnes si postavíš svůj úplně první mini AI systém. Je jednodušší, než si myslíš.",
  },
  {
    day: 7,
    title: "Tvůj první mini AI systém.",
    subject: "Dnes si postavíš svůj první mini AI systém.",
    preheader: "3 kroky, jeden výstup, nulový chaos. Takhle to funguje.",
    concept: [
      "AI je nejsilnější ve chvíli, kdy se stane součástí malého workflow.",
      "Například: poznámky z hovoru → shrnutí → follow-up email. Nebo: nápad → osnova → draft textu. Nebo: seznam úkolů → priority → plán dne.",
    ],
    taskIntro: "Vyber si jednu činnost, která má aspoň 2-3 navazující kroky, a napiš si:",
    taskItems: ["Co je vstup", "Co s tím může udělat AI", "Co je finální výstup"],
    taskType: "ol",
    teaser: "Prázdná stránka? AI ti napíše první verzi čehokoliv — bez přemýšlení, kde začít.",
  },
  {
    day: 8,
    title: "AI jako copywriter.",
    subject: "Prázdná stránka? Nikdy víc.",
    preheader: "AI ti napíše první verzi. Ty ji jen dotáhneš. Takhle funguje psaní s AI.",
    concept: [
      "Jedna z nejrychlejších úlev, kterou AI může přinést, je psaní. Ne proto, že by za tebe měla všechno napsat bez přemýšlení. Ale proto, že už nemusíš začínat od prázdné stránky.",
      "Ty dodáš záměr, kontext, hlavní myšlenku a tón. AI ti připraví první verzi, varianty nebo strukturu, od které se odpíchneš.",
    ],
    taskIntro: "Vezmi si jeden text, který dnes potřebuješ napsat, a nech si od AI připravit 3 verze:",
    taskItems: ["stručnou", "přesvědčivější", "přirozenější"],
    taskType: "ul",
    teaser: "Research nemusí být vyčerpávající. Ukážeme si, jak z AI udělat první vrstvu orientace.",
  },
  {
    day: 9,
    title: "AI jako research assistant.",
    subject: "Jak se přestat topit v researchi.",
    preheader: "Moc zdrojů, moc variant, nevíš kde začít? AI ti udělá první orientaci.",
    concept: [
      "Research umí být překvapivě vyčerpávající. Často ne proto, že je složitý problém, ale proto, že je moc zdrojů, moc variant a člověk neví, kde začít.",
      "AI umí pomoct jako první vrstva orientace: rozdělit téma na důležité oblasti, navrhnout rámec porovnání, vytáhnout klíčové otázky, nebo připravit stručné shrnutí.",
    ],
    taskIntro: "Vyber si jedno téma a nech si od AI připravit:",
    taskItems: ["hlavní oblasti, které sledovat", "rámec porovnání", "otázky, které si položit", "co si máš ověřit zvlášť"],
    taskType: "ul",
    teaser: "Chaos v hlavě není problém s kapacitou. Je to problém se strukturou. AI s tím umí pomoct.",
  },
  {
    day: 10,
    title: "AI jako thinking partner.",
    subject: "Máš chaos v hlavě? Tohle zkus.",
    preheader: "AI jako partner pro přemýšlení — ne jen pro hledání odpovědí.",
    concept: [
      "Někdy člověk nesedí nad konkrétním výstupem, ale nad chaosem v hlavě. A právě v těchto chvílích může být AI překvapivě užitečná.",
      "Ne jako expert, který ti řekne jedinou správnou odpověď. Ale jako partner, který ti pomůže roztřídit myšlenky, pojmenovat problém, oddělit důležité od nedůležitého a navrhnout další rozumný krok.",
    ],
    taskIntro: "Vezmi si jedno téma, které teď nosíš v hlavě a ještě v něm nemáš jasno. Vysyp ho do AI a nech ji, ať ti pomůže:",
    taskItems: ["rozdělit to do bloků", "pojmenovat hlavní problém", "navrhnout 2-3 možné směry", "určit nejlepší další krok"],
    taskType: "ul",
    teaser: "Rozhodování je náročné. AI ti s ním umí pomoct — ne tím, že rozhodne za tebe, ale tím, že uvidíš možnosti čistěji.",
  },
  {
    day: 11,
    title: "AI jako decision partner.",
    subject: "Jak se líp rozhodovat s pomocí AI.",
    preheader: "AI nerozhoduje za tebe. Pomáhá ti vidět možnosti čistěji.",
    concept: [
      "Spousta práce není o tom něco vytvořit. Spousta práce je o tom rozhodnout se.",
      "AI nerozhoduje za tebe. Pomáhá ti vidět možnosti čistěji: zpřehlednit varianty, pojmenovat plusy a mínusy, ukázat trade-offy, upozornit na rizika.",
    ],
    taskIntro: "Vyber si jedno skutečné rozhodnutí. Dej AI:",
    taskItems: ["možnosti, mezi kterými vybíráš", "čeho chceš dosáhnout", "co tě omezuje", "čeho se obáváš"],
    taskType: "ul",
    teaser: "Co by se stalo, kdyby každý meeting měl automatické shrnutí a jasné next steps?",
  },
  {
    day: 12,
    title: "AI jako meeting assistant.",
    subject: "Co by se stalo, kdyby každý meeting měl automatické shrnutí?",
    preheader: "Meetingy berou energii. Chybějící shrnutí a next steps berou čas navíc. AI to řeší.",
    concept: [
      "Meetingy často neberou nejvíc času. Berou nejvíc energie. A největší problém bývá, že po nich chybí stručné shrnutí, jasné rozhodnutí a další kroky.",
      "AI umí z poznámek nebo přepisu rychle vytvořit: přehledné shrnutí, seznam úkolů, otevřené otázky, a follow-up zprávu.",
    ],
    taskIntro: "Vezmi si poslední meeting, call nebo poznámky z rozhovoru a nech AI vytvořit:",
    taskItems: ["stručné shrnutí", "hlavní rozhodnutí", "další kroky", "krátký follow-up"],
    taskType: "ul",
    teaser: "Příliš mnoho úkolů, příliš málo jasna. Jak ti AI pomůže nastavit priority.",
  },
  {
    day: 13,
    title: "AI jako personal productivity coach.",
    subject: "Moc úkolů, málo jasna. AI ti pomůže nastavit priority.",
    preheader: "Přetlak není o nástrojích. Je o prioritách. A s těmi AI umí pomoct.",
    concept: [
      "Produktivita dnes často nevypadá jako nedostatek nástrojů. Spíš jako přetlak: moc úkolů, moc věcí v hlavě, moc rozhodování.",
      "AI může fungovat jako vnější mozek, který ti pomůže ujasnit si priority, zmenšit chaos, odložit méně důležité věci, a udělat plán, který je reálně proveditelný.",
    ],
    taskIntro: "Vezmi si dnešní nebo zítřejší seznam úkolů, přidej k němu:",
    taskItems: ["kolik máš času", "jakou máš kapacitu", "co je opravdu důležité", "co je spíš: bylo by fajn"],
    taskType: "ul",
    teaser: "Sestavíš si svůj vlastní AI copilot — první verzi toho, jak budeš s AI pracovat každý den.",
  },
  {
    day: 14,
    title: "Tvůj osobní AI copilot.",
    subject: "Tvůj osobní AI copilot — první verze.",
    preheader: "Dnes si složíš, jak chceš s AI pracovat každý den. Je to jednodušší, než zní.",
    concept: [
      "Jednotlivé role AI jsou užitečné. Ale skutečný posun přichází ve chvíli, kdy si z toho začneš skládat vlastní systém.",
      "Na začátek stačí, když si ujasníš: na co AI používáš nejčastěji, kde ti opravdu šetří čas, kde ti pomáhá líp přemýšlet, a které prompty nebo postupy si chceš uložit.",
    ],
    taskIntro: "Sepiš si svou první verzi osobního AI copilot setupu:",
    taskItems: ["Na co AI používám nejčastěji?", "Kde mi nejvíc šetří čas?", "Kde mi pomáhá dělat lepší práci?", "Jaké 3-5 promptů nebo postupů si chci uložit?", "Co chci, aby byl můj defaultní způsob práce s AI?"],
    taskType: "ul",
    teaser: "Neautomatizuj všechno — ale tohle automatizuj určitě. Jak najít správné kandidáty.",
  },
  {
    day: 15,
    title: "Neautomatizuj všechno. Automatizuj to, co má největší dopad.",
    subject: "Neautomatizuj všechno. Automatizuj tyhle věci.",
    preheader: "Nejde o to automatizovat co nejvíc. Jde o to vybrat to, co vrátí nejvíc.",
    concept: [
      "Nejde o to automatizovat co nejvíc. Jde o to automatizovat to, co ti vrátí nejvíc času, energie nebo pozornosti.",
      "Nejlepší kandidáti bývají věci, které jsou opakující se, předvídatelné, trochu otravné, časově náročné, a mají poměrně jasný vstup i výstup.",
    ],
    taskIntro: "Podívej se na činnosti, které se ti během challenge opakovaly nejčastěji. U každé si zkus říct:",
    taskItems: ["Jak často se děje?", "Kolik času bere?", "Jak moc tě mentálně vyčerpává?", "Jak moc je předvídatelná?"],
    taskType: "ul",
    teaser: "Zapomeň na appky. Nejdřív musíš pochopit samotný tok práce — a pak teprve vybírat nástroje.",
  },
  {
    day: 16,
    title: "Začni přemýšlet v logice workflow, ne nástrojů.",
    subject: "Zapomeň na appky. Nejdřív pochop workflow.",
    preheader: "Výběr nástroje je až druhý krok. Tady je, co přijde první.",
    concept: [
      "Dřív než vybírat appku, je potřeba pochopit samotný tok práce: co je spouštěč, co je vstup, co má udělat AI nebo systém, a co je výstup.",
      "Tohle je no-code mindset.",
    ],
    taskIntro: "Vyber si jednu opakující se činnost a popiš si ji v této struktuře:",
    taskItems: ["Spouštěč", "Vstup", "Zpracování", "Výstup"],
    taskType: "ul",
    teaser: "Komunikace, která se nemusí pokaždé psát od začátku. AI-first přístup k opakujícím se zprávám.",
  },
  {
    day: 17,
    title: "Komunikace nemusí pokaždé začínat od nuly.",
    subject: "Přestaň psát podobné zprávy pokaždé od začátku.",
    preheader: "Reusable struktura + lidská finalizace. Takhle vypadá AI-first komunikace.",
    concept: [
      "Velká část komunikace v práci je opakující se. Podobné odpovědi, follow-upy, potvrzení, shrnutí.",
      "AI-first komunikace není robotická komunikace. Je to reusable struktura plus lidská finalizace.",
    ],
    taskIntro: "Vyber si jeden typ zprávy, který píšeš často, a vytvoř si k němu první reusable základ:",
    taskItems: ["osnovu", "šablonu", "nebo prompt"],
    taskType: "ul",
    teaser: "Jedna myšlenka, tři výstupy. Takhle vypadá obsah s leverage.",
  },
  {
    day: 18,
    title: "Jedna myšlenka nemusí skončit v jednom výstupu.",
    subject: "Jedna myšlenka, tři výstupy. Takhle funguje leverage obsahu.",
    preheader: "Přestaň vymýšlet nové věci. Začni víc těžit z toho, co už máš.",
    concept: [
      "Jedna dobrá myšlenka může být post, krátký newsletter, část webového textu, FAQ, osnova videa nebo základ pro další obsah.",
      "AI ti pomůže přepnout z režimu: zase něco nového vymyslet — do režimu: jak z toho, co už mám, vytěžit víc.",
    ],
    taskIntro: "Vezmi si jeden existující obsahový vstup a nech si z něj pomocí AI vytvořit alespoň 3 různé výstupy.",
    taskItems: [],
    taskType: "text",
    teaser: "Největší chaos nevzniká v práci. Vzniká mezi kroky. A s tím si AI umí poradit.",
  },
  {
    day: 19,
    title: "Nejvíc chaosu často nevzniká v práci. Ale mezi kroky.",
    subject: "Kde vzniká chaos, který tě brzdí — a jak ho zmenšit.",
    preheader: "Problém nebývá v samotné práci. Je v předávání, v mezerách, v přechodech.",
    concept: [
      "Neefektivita často nevzniká v samotné práci, ale mezi ní: mezi meetingem a exekucí, mezi člověkem a systémem, mezi nápadem a výstupem.",
      "AI může pomoct zlepšit strukturu předání: co se má shrnout, co se má zapsat, co je další krok, a kdo ho má udělat.",
    ],
    taskIntro: "Vyber si jedno místo, kde se často ztrácí informace, a napiš si:",
    taskItems: ["Co se má vždy předat?", "Co by mělo být stručně shrnuté?", "Co by se mělo zapsat do systému?", "Co je jasný další krok?"],
    taskType: "ul",
    teaser: "Data sama o sobě nestačí. Pomáhá až to, co z nich pochopíš — a AI ti s tím pomůže.",
  },
  {
    day: 20,
    title: "Data sama o sobě nepomáhají. Pomáhá až to, co z nich pochopíš.",
    subject: "Jak z dat dostat to, co opravdu potřebuješ vědět.",
    preheader: "Data bez interpretace jsou jen hluk. AI ti pomůže najít vzorec.",
    concept: [
      "Data pomáhají až ve chvíli, kdy z nich vznikne vzorec, insight, rozhodnutí nebo další krok.",
      "AI ti může pomoct vytáhnout opakující se témata, pojmenovat, co je důležité, odhalit, co je překvapivé, a navrhnout, co z toho dává smysl udělat dál.",
    ],
    taskIntro: "Vezmi si jeden skutečný datový nebo textový vstup a nech AI odpovědět:",
    taskItems: ["Co se tu opakuje?", "Co je tu nejdůležitější?", "Co bych z toho měla udělat dál?"],
    taskType: "ul",
    teaser: "Propojené kroky mění všechno. Dnes si ukážeme, jak je popsat a začít stavět.",
  },
  {
    day: 21,
    title: "Skutečný posun přichází ve chvíli, kdy propojíš jednotlivé kroky.",
    subject: "Propojené kroky mění všechno. Tady je jak na to.",
    preheader: "Jeden dobrý prompt nestačí. Skutečná úleva přijde, když kroky začnou navazovat.",
    concept: [
      "Největší úleva často nepřichází z jednoho dobrého promptu. Přichází ve chvíli, kdy na sebe začnou navazovat jednotlivé kroky tak, že už nemusíš všechno držet v hlavě a posouvat ručně.",
    ],
    taskIntro: "Vyber si jednu oblast a popiš si jednoduchý řetězec:",
    taskItems: ["Co je vstup?", "Co udělá AI?", "Co se kam uloží?", "Kde zůstává kontrola na člověku?", "Co je finální výstup?"],
    taskType: "ul",
    teaser: "AI transformace ve firmě nezačíná u nástroje. Začíná u práce. A tam je i správné místo začít.",
  },
  {
    day: 22,
    title: "AI ve firmě nezačíná u nástroje. Začíná u práce.",
    subject: "AI ve firmě nezačíná u nástroje.",
    preheader: "Kde opravdu začít AI transformaci — a kde se většina firem mýlí.",
    concept: [
      "AI transformace nezačíná u technologie. Začíná u práce samotné.",
      "U toho, kde ve firmě vzniká opakující se ruční činnost, zbytečné přeposílání informací, ztráta know-how, pomalé rozhodování, nebo práce s nízkou přidanou hodnotou.",
    ],
    taskIntro: "Vyber si jeden tým, oddělení nebo část firmy a zkus si pojmenovat:",
    taskItems: ["Kde vzniká nejvíc opakující se ruční práce?", "Kde se ztrácí kontext nebo know-how?", "Kde lidé tráví čas něčím, co nemá nejvyšší hodnotu?", "Kde by menší změna mohla přinést rychlý dopad?"],
    taskType: "ul",
    teaser: "Každý tým potřebuje jiné AI use cases. Jak je najít a jak začít tam, kde to dává smysl.",
  },
  {
    day: 23,
    title: "Každý tým potřebuje jiné AI use cases.",
    subject: "Každý tým potřebuje jiné AI use cases. Tady je jak na to.",
    preheader: "Jedno řešení pro všechny nefunguje. AI adopce musí vycházet z konkrétní práce.",
    concept: [
      "Každý tým pracuje jinak. Má jiné cíle, jiné tření, jiné tempo i jiné typy úkolů. Proto dává větší smysl hledat AI use cases podle konkrétní role a konkrétní práce.",
      "Use cases se často dají rozdělit do tří skupin: AI něco draftuje, AI něco shrnuje, AI je součástí workflow.",
    ],
    taskIntro: "Vyber si jeden konkrétní tým a napiš si:",
    taskItems: ["Co dělají často?", "Co je nejvíc zdržuje?", "Co se opakuje?", "Co by AI mohla připravovat, shrnovat nebo zrychlovat?"],
    taskType: "ul",
    teaser: "Lidi nepřesvědčí technologie. Přesvědčí je přínos. Jak mluvit o AI jazykem, který funguje.",
  },
  {
    day: 24,
    title: "Lidi nepřesvědčí technologie. Přesvědčí je přínos.",
    subject: "Jak přesvědčit lidi, kteří AI zatím nepotřebují.",
    preheader: "Přestaň mluvit o AI jako o technologii. Mluv o ní jako o práci.",
    concept: [
      "Většina lidí nepotřebuje slyšet, že AI je budoucnost. Potřebuje pochopit, co jim konkrétně ulehčí už teď.",
      "Proto je důležité mluvit o AI jazykem práce, ne jazykem nástrojů.",
    ],
    taskIntro: "Vyber si jednu konkrétní roli nebo člověka a zkus si napsat:",
    taskItems: ["Čeho se ten člověk může obávat?", "Co ho v práci nejvíc zdržuje?", "Kde by mu AI mohla dát rychlý a viditelný přínos?", "Jak by vypadal malý quick win, který by dával smysl ukázat jako první?"],
    taskType: "ul",
    teaser: "Pár jednoduchých pravidel AI governance — která ušetří problémy a dají lidem jistotu.",
  },
  {
    day: 25,
    title: "Bez pravidel vzniká chaos. S příliš mnoha pravidly nevznikne nic.",
    subject: "AI governance: pár pravidel, která ti ušetří problémy.",
    preheader: "Dobrá governance lidi neodrazuje. Dává jim jistotu, že to dělají správně.",
    concept: [
      "Dobrá governance nemá lidi odradit. Má jim pomoct používat AI bezpečněji, rozumněji a s větší jistotou.",
      "Na začátek často stačí pár jednoduchých a srozumitelných pravidel: co je bezpečné používat, co anonymizovat, co musí vidět člověk, a kde je potřeba větší opatrnost.",
    ],
    taskIntro: "Sepiš si první jednoduchou verzi AI pravidel pro sebe nebo svůj tým:",
    taskItems: ["Co je v pořádku dávat do AI?", "Co bych radši anonymizovala nebo tam nedávala vůbec?", "Které výstupy bych nikdy nenechala bez lidské kontroly?", "U jakých typů práce je potřeba větší opatrnost?"],
    taskType: "ul",
    teaser: "Jak AI adopci rozšířit přes celou firmu — a ne jen u pár nadšenců.",
  },
  {
    day: 26,
    title: "AI adopce se neškáluje přístupem. Škáluje se tím, co se dá sdílet a znovu použít.",
    subject: "Jak rozšířit AI adopci přes celou firmu.",
    preheader: "Pokud to zůstane jen u pár lidí, adopce se nikam neposune. Tady je jak dál.",
    concept: [
      "Pokud všechno zůstane jen u několika jednotlivců, adopce se dál neposune. Know-how zůstane rozptýlené a výsledky budou nekonzistentní.",
      "Skutečné škálování začíná ve chvíli, kdy se úspěch dá sdílet: prompt library, seznam use cases, ukázky toho, co funguje, jednoduché standardy, malá knowledge base.",
    ],
    taskIntro: "Podívej se na to, co už funguje, a napiš si:",
    taskItems: ["Co by stálo za to sdílet dál?", "Co by šlo uložit jako prompt, šablonu nebo příklad?", "Co by pomohlo ostatním začít rychleji?", "Co by mohlo být základem malého AI adoption kitu?"],
    taskType: "ul",
    teaser: "Teď už neskládáš tipy. Skládáš svůj vlastní AI systém. Předposlední den.",
  },
  {
    day: 27,
    title: "Teď už neskládáš tipy. Skládáš svůj vlastní AI systém.",
    subject: "Teď už neskládáš tipy. Skládáš systém.",
    preheader: "Zítra je poslední den challenge. Dnes si sestavíš, co si odnášíš.",
    concept: [
      "Skutečný AI systém není jeden nástroj. Je to způsob práce, ve kterém se potkává: jak přemýšlíš o úkolech, co deleguješ AI, co si ukládáš, co znovu používáš, jak si buduješ knowledge base, a kde si necháváš lidskou kontrolu.",
    ],
    taskIntro: "Sepiš si první verzi svého AI systému:",
    taskItems: ["Na co AI používám nejčastěji", "Jaké prompty nebo šablony si chci uložit", "Jaké workflow už mi dávají smysl", "Kde mám své poznámky, podklady a reusable assets", "Kde potřebuju lidskou kontrolu", "Co už nechci příště dělat od nuly ručně"],
    taskType: "ul",
    teaser: "Poslední den challenge. A zároveň začátek toho, co přijde po ní.",
  },
  {
    day: 28,
    title: "Skutečná změna začíná až teď.",
    subject: "28 dní za tebou. Skutečná změna začíná teď.",
    preheader: "Dokončení challenge není cíl. Je to začátek. Tady je co dál.",
    concept: [
      "Dokončení challenge není cíl. Je to začátek.",
      "Nejde o to projít 28 dní a vyzkoušet 28 věcí. Jde o to, co z toho zůstane v běžné práci i potom.",
    ],
    taskIntro: "Sepiš si krátký plán na dalších 90 dní ve 4 bodech:",
    taskItems: ["Keep – co si chci určitě udržet", "Build – co chci dál rozvíjet nebo postavit", "Share – co chci sdílet s ostatními", "Measure – podle čeho poznám, že mi to opravdu pomáhá"],
    taskType: "ul",
    teaser: "",
  },
];
