import type { ChallengeDay } from "./types";

export const challengeDataBasicCZ: ChallengeDay[] = [
  // ─── TÝDEN 1: Mindset + leverage (D0–D6) ──────────────────────────────────────

  {
    day: 0,
    title: "Tohle není kurz. Je to nový způsob práce.",
    subject: "Začínáme. Takhle funguje challenge.",
    preheader: "28 dní, 5–7 minut denně. Jeden opravdový posun.",
    teze: "Znalost o AI a zvyk s AI jsou dvě různé věci — tato challenge buduje to druhé.",
    concept: [
      "AI je dnes všude. Každý týden nové nástroje, nové funkce, nové sliby. A právě proto je snadné skončit u toho, že člověk něco vyzkouší, nedostane co čekal, a zavře záložku.",
      "Tahle challenge vznikla proto, aby se tohle nestalo.",
      "Nejde o to naučit se co nejvíc AI nástrojů. Jde o to začít AI používat pravidelně a tak, aby opravdu ulehčovala práci. Tohle je AI-first přístup: způsob přemýšlení o práci, který změní to, jak ji děláš — bez ohledu na to, který konkrétní nástroj zrovna používáš.",
      "Každý den ti zabere přibližně 5–7 minut. Každý den si odneseš něco konkrétního:",
      ["nový pohled na práci s AI", "malý praktický krok", "konkrétní výstup nebo drobné zlepšení něčeho, co už děláš"],
      "Tato verze challenge — Basic — se zaměřuje na základy. Na to, jak AI přemýšlí, co od ní realisticky čekat, jak psát zadání, která fungují, a jak AI zapojit do věcí, které děláš každý den.",
      "Každou výzvu lze prohloubit. Pokud na něco narazíš, co už znáš, nevadí — každý den se dá udělat hlouběji. Upravit prompt, vylepšit výstup, zabudovat do reálné práce. Smyslem není stihnout všechno. Smyslem je posouvat se každý den o kousek dál.",
      "Stačí málo. Pět minut. Jedna věc. Jeden krok. Z toho nakonec vzniká skutečná změna.",
    ],
    taskIntro: "Než začneme, jeden jednoduchý úkol. Zamysli se a zapiš si:",
    taskItems: [
      "3 věci, které v práci nebo v běžném dni děláš opakovaně — každý týden nebo každý den",
      "Klidně i banální věci: odpovídání na emaily, příprava schůzek, psaní textů, reporty, shrnutí",
      "Zapiš si je kamkoli — Notion, Google Docs, Apple Notes nebo papír. Budeme se k nim vracet.",
    ],
    taskType: "ol",
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Proč AI není jen rychlejší Google — a proč na tom záleží.",
  },

  {
    day: 1,
    title: "AI není rychlejší Google. Je to leverage.",
    subject: "Jeden posun v myšlení, který změní výsledky.",
    preheader: "Rychlost je vedlejší efekt. Leverage je cíl.",
    teze: "AI neurychlí práci — změní poměr vstupu a výstupu. Jeden prompt místo hodiny práce.",
    concept: [
      "Většina lidí používá AI tak, jako by to byl trochu chytřejší vyhledávač: napíše otázku, dostane odpověď, jde dál. To funguje — ale využívá zlomek toho, co AI skutečně umí.",
      "Je to jako mít Ferrari a jezdit s ním jenom na nákup.",
      "Klíčový posun v myšlení: AI není nástroj pro rychlost. Je to nástroj pro leverage — pro zásadní rozdíl ve výsledku při stejném nebo menším úsilí. Rychlost je vedlejší efekt, ne cíl.",
      "Jak to vypadá v praxi? Rychlost znamená: napíšu email za 5 minut místo 20. Leverage znamená: napíšu email, který by bez AI nevznikl — protože AI pomohla promyslet, co ten klient skutečně potřebuje slyšet, jak to formulovat, a ve třech variantách.",
      "Dobrá analogie: digitální fotoaparát dal lidem rychlost. Ale Photoshop dal fotografům leverage — výsledky, které fotoaparát sám nikdy neprodukoval. AI je tvůj Photoshop na práci s textem, myšlením a strukturou.",
      ["Rychlost: udělám totéž, ale rychleji", "Leverage: dosáhnu výsledku, který by jinak nebyl možný — nebo by trval desetkrát déle", "Mindset: AI jako spolupracovník, ne jako zkratka", "Praxe: ptej se \u201Ejak dosáhnout lepšího výsledku\", ne jen \u201Ejak to udělat rychleji\""],
      "Toto přeskočení — mindsetové části — je důvod, proč většina lidí AI \u201Evyzkouší a pak nechá\". Nevidí leverage. Vidí jen, že výsledek není dost dobrý napoprvé. A mají pravdu — napoprvé nikdy není. Ale leverage přichází ve druhém a třetím kole.",
    ],
    taskIntro: "Vezmi jeden úkol ze svého včerejšího seznamu a zkus se zamyslet ze dvou úhlů:",
    taskItems: [
      "Jak by mi AI pomohla udělat tento úkol rychleji? (rychlost)",
      "Jaký výsledek by s AI mohl vzniknout, který by jinak vůbec nebyl možný — nebo by trval moc dlouho? (leverage)",
      "Zapiš si obě odpovědi. Nemusí být dokonalé — jde o způsob přemýšlení.",
      "Vyber si jeden konkrétní moment v dnešním dni, kde AI zkusíš — například po prvním emailu ráno nebo před přípravou schůzky. Zapiš si ho.",
    ],
    taskType: "ol",
    taskTip: "Tento konkrétní moment — 'po prvním emailu otevřu AI' — je tvůj první kotevní bod. Návyk s AI neroste z motivace, ale z opakování ve stejný moment dne.",
    teaser: "Zítra: Nakreslíme si realistickou mapu AI: co umí skvěle, kde selhává — a proč je to důležité vědět dřív, než začneš.",
  },

  {
    day: 2,
    title: "AI je skvělá asistentka. Ale horší kouzelník.",
    subject: "Realistická mapa AI — co umí a co ne.",
    preheader: "Přehnané očekávání a přílišná skepse vedou na stejné místo.",
    teze: "AI dělá skvěle to, co jí přesně popíšeš — a selhává tam, kde čekáš, že odhadne zbytek.",
    concept: [
      "Jedna z největších chyb při práci s AI je přehnané očekávání. Nebo naopak — přílišná skepse. Obojí vede ke stejnému výsledku: člověk AI nepoužívá efektivně, protože buď čeká zázraky, nebo věří, že mu nepomůže.",
      "Realistická mapa je víc než žádná mapa.",
      "Co AI skutečně umí dobře — a kde je nejsilnější:",
      ["Strukturovat a přepisovat text rychle a konzistentně", "Generovat varianty, nápady a návrhy — dát ti pět možností místo jedné", "Shrnovat dlouhé dokumenty — 10 stran do 5 vět", "Vysvětlovat složité věci jednoduše — pro různá publika, různou úroveň detailu", "Asistovat při opakujících se úkolech — šablony, drafty, struktury", "Pracovat rychle s velkým množstvím textu — co by trvalo hodiny, zvládne za minuty"],
      "Co AI neumí nebo dělá nespolehlivě — a kde je potřeba kontrola:",
      ["Přistupovat k internetu v reálném čase (bez speciálních nástrojů nebo záložek)", "Pamatovat si minulé konverzace, pokud to nenastavíš nebo nezopakuješ kontext", "Vždy říkat pravdu — AI může s přesvědčením vymýšlet fakta, čísla i reference", "Rozumět tvé specifické situaci, pokud jí ji neposkytneš jako kontext", "Nahradit odborný úsudek v kritických rozhodnutích — lékařství, právo, finance"],
      "Nejzrádnější past je, že AI neumí říct \u201Enevím\" přesvědčivě. Vygeneruje odpověď, která zní skvěle — ale může být špatně. Ověřuj fakta a konkrétní čísla vždy externě, zejména v situacích, kde na přesnosti záleží.",
      "Klíčový princip: AI je nejlepší spolupracovník, když víš, co od ní chceš — a ověříš, co ti dá.",
    ],
    taskIntro: "Zamysli se nad jedním úkolem, kde nevíš, jestli by AI pomohla. Zkus to otestovat:",
    taskItems: [
      "Vyber úkol, kde AI dosud nepřinesla výsledek — nebo kde o jejím použití pochybuješ",
      "Napiš AI jednoduchý prompt a zjisti, co dostaneš",
      "Zhodnoť: bylo to užitečné? Kde AI selhala? Co by jí pomohlo?",
    ],
    taskType: "ol",
    taskPrompt: "Potřebuji pomoc s [úkol]. Mám k dispozici [co máš k dispozici]. Výsledek by měl být [co potřebuješ].",
    taskTip: "Funguje v ChatGPT, Claude i Gemini.",
    teaser: "Zítra: To bude praktické — napíšeš AI, co přesně děláš, a necháš ji navrhnout, kde může pomoci.",
  },

  {
    day: 3,
    title: "AI o tobě nic neví. Změň to za 5 minut.",
    subject: "Napiš, co děláš — dostaneš návrh, jak pomoci.",
    preheader: "Generický vstup = generický výstup. Kontext mění vše.",
    teze: "Generický vstup dostane generický výstup — 5 minut na popis kontextu změní vše.",
    concept: [
      "AI bez kontextu je jako nový kolega v první den práce. Technicky schopný, ale ještě neví, pro koho pracuje, co je důležité, ani jak věci fungují.",
      "Přesně tak se AI chová, dokud jí nedáš kontext. A právě to je dnešní úkol.",
      "Proč je to tak důležité? Zkus zadat \u201Epomoz mi s prací\" a uvidíš, co dostaneš. Pak zkus \u201Epracuji jako produktový manažer v B2B SaaS firmě, moje největší každodenní bolest je příprava týdenních statusů pro vedení, které mají vždy stejnou strukturu\" — a výsledek bude zásadně jiný.",
      "Kontext funguje jako briefing pro spolupracovníka. Čím lepší briefing, tím lépe bude pracovat hned od prvního slova. AI si nic nepamatuje z minulých konverzací — takže briefing dáváš vždy. Ale nemusí to trvat dlouho.",
      "Co do kontextu patří:",
      ["Kdo jsi — tvoje role nebo obor, ve kterém pracuješ", "Co konkrétně děláš — 3–5 typických úkolů, ne obecná náplň práce", "Pro koho pracuješ — interní tým, klienti, zákazníci, management", "Jaké jsou tvé největší bolesti nebo opakující se práce"],
      "Tenhle úkol má dvě části: nejdřív napíšeš AI o sobě, pak se jí zeptáš, kde může pomoci. Neočekávej dokonalý výsledek — jde o první mapování. Výstup si ulož, budeme se k němu v challenge vracet.",
      "Nejčastější chyba: být příliš obecný. \u201EPracuji v marketingu\" je příliš málo. \u201EPřipravuji kampaňové reporty pro e-commerce klienty, každý týden, v PowerPointu, a vždy mi zabere 3–4 hodiny shánění dat\" je použitelné.",
    ],
    taskIntro: "Použij tento postup — zabere ti 5–7 minut:",
    taskItems: [
      "Otevři Claude, ChatGPT nebo Gemini",
      "Napiš AI prompt podle šablony níže",
      "Výstup si ulož — konkrétní oblasti, kde AI navrhla pomoci",
    ],
    taskType: "ol",
    taskPrompt: "Pracuji jako [tvoje role nebo obor]. Moje typické úkoly jsou: [vypiš 3–5 konkrétních věcí]. Největší opakující se práce, která mi zabere čas, je [dopiš]. Navrh mi 5 konkrétních způsobů, jak by mi AI mohla pomoci — ne obecně, ale přímo na moje úkoly.",
    taskFallback: `Pokud nevíš, jak začít, zkus tento vyplněný příklad:
"Pracuji jako projektový koordinátor v marketingové agentuře. Moje typické úkoly jsou: příprava reportů pro klienty, koordinace termínů s grafiky a copywritery, komunikace s klienty, zadávání briefů a kontrola výstupů. Největší opakující se práce, která mi zabere čas, je příprava týdenního reportu — shromáždím data z různých míst a pak to sepisuji do přehledné zprávy. Navrh mi 5 konkrétních způsobů, jak by mi AI mohla pomoci."`,
    taskTip: "Funguje v ChatGPT, Claude i Gemini.",
    teaser: "Zítra: Co dělá největší rozdíl mezi dobrým a špatným promptem — a proč je to proveditelné hned.",
  },

  {
    day: 4,
    title: "Jeden detail dělí skvělý prompt od průměrného.",
    subject: "Co dělá největší rozdíl mezi výsledkem a odpadem.",
    preheader: "Vágní vstup = vágní výstup. Platí vždy.",
    teze: "Přesný záměr v promptu rozhoduje víc než délka nebo složitost — a jde se to naučit rychle.",
    concept: [
      "Špatný výsledek z AI má ve většině případů jednu příčinu: špatné zadání. Ne špatnou AI. To je zpráva, která osvobozuje — protože zadání můžeš zlepšit ty.",
      "Prompt je v podstatě pracovní zadání. A zadání, které dáš novému kolegovi, určuje kvalitu jeho práce. \u201ENapiš mi email\" je jako říct kolegovi \u201Eudělej mi tu věc\" — ani jeden z nich neví, kde začít.",
      "Co dělá prompt špatným:",
      ["Je příliš vágní: \u201Enapiš mi email\"", "Chybí kontext: AI neví, pro koho, proč, v jakém tónu", "Chybí formát: AI neví, jak dlouhý, jak strukturovaný má výsledek být", "Chybí cíl: AI neví, čeho má výstup dosáhnout — informovat, přesvědčit, domluvit schůzku"],
      "Co dělá prompt dobrým:",
      ["Je konkrétní: \u201Enapiš follow-up email pro klienta, který viděl nabídku, ale neodpověděl\"", "Má kontext: \u201Eklient je malá výrobní firma, jednám s majitelem, nabídka byla na systém řízení skladu\"", "Má formát: \u201Ekrátký, max 5 vět, přátelský a přímý tón\"", "Má cíl: \u201Echci dostat odpověď — ať kladnou nebo zápornou\""],
      "Nejčastější chyba: čekat, že AI \u201Epochopí, co chceš\". AI vždy pochopí doslova to, co napíšeš — ne to, co bylo zamýšleno. Vágní vstup, vágní výstup. Platí to pokaždé.",
      "Základní pravidlo: čím víc si dokážeš přesně představit výsledek, který chceš — tím přesnější prompt napíšeš. Pomůže položit si otázku: kdyby tohle přišlo jako zadání od šéfa, bylo by jasné, co přesně udělat? Pokud ne, přidej víc.",
    ],
    taskIntro: "Porovnej tyto dva prompty a zkus oba v AI — uvidíš rozdíl okamžitě:",
    taskItems: [
      "Špatný: \u201ENapiš mi email.\"",
      "Lepší: \u201ENapiš follow-up email klientovi, který viděl cenovou nabídku na software, ale neodpověděl. Tón přátelský a přímý, max 5 vět. Cíl: dostat odpověď — kladnou nebo zápornou.\"",
      "Zapiš si, jak se liší výstupy — kvalitou, použitelností, délkou. Tenhle rozdíl je přesně to, s čím budeme pracovat dál.",
    ],
    taskType: "ol",
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Přepisování špatných promptů — na třech reálných příkladech.",
  },

  {
    day: 5,
    title: "Přepisování promptů je sval. Dnes ho posílíš.",
    subject: "Praxe: z vágního na konkrétní, třikrát za sebou.",
    preheader: "Tohle je dovednost, ne znalost. Musíš si ji zkoušet.",
    teze: "Psaní promptů se nezlepší čtením o tom — jen tím, že přepíšeš špatné a pak lepší.",
    concept: [
      "Přepisování promptů je jako editace textu — první verze nikdy není nejlepší. A stejně jako u textu: nemusíš začínat od nuly. Musíš vědět, co přidat nebo odebrat.",
      "Prompting je dovednost, ne znalost. To znamená, že čtení o tom nestačí — musíš si to zkoušet na vlastních příkladech. Dnes máš tři konkrétní prompty k přepsání. Tvůj úkol: oprav je tak, aby dávaly lepší výstup. Pak obě verze otestuj v AI a porovnej.",
      "Co typicky chybí ve špatných promptech:",
      ["Cílová skupina nebo příjemce — kdo to bude číst nebo poslouchat?", "Tón nebo styl komunikace — formální, přátelský, odborný, přímý?", "Požadovaný formát nebo délka — odrážky, odstavec, tři věty, tabulka?", "Kontext situace nebo cíl výstupu — proč to píšeš a co má příjemce udělat?"],
      "Proč je tohle cvičení tak efektivní: naučíš se rozpoznat, co v promptu chybí — ne jako teorii, ale jako instinkt. Za pár týdnů budeš psát prompty, které fungují napoprvé, protože si automaticky budeš klást správné otázky ještě před napsáním.",
      "Tip: zkopíruj špatný i přepsaný prompt do AI a podívej se na oba výstupy vedle sebe. Rozdíl bývá okamžitě viditelný. Takhle se buduje intuice pro dobrý prompting — ne čtením, ale porovnáváním.",
      "Tenhle den je jeden z nejpraktičtějších v celém prvním týdnu. Nejde o pochopení — jde o zkoušení.",
    ],
    taskIntro: "Přepiš tyto 3 prompty a otestuj je v AI:",
    taskItems: [
      "\u201ENapiš mi text na LinkedIn.\" → přidej: pro koho, na jaké téma, jaký cíl, jaký tón, jak dlouhý",
      "\u201EPomoz mi s prezentací.\" → přidej: na jaké téma, pro jaké publikum, kolik slidů, jaký výstup chceš",
      "\u201ENapiš odpověď na email.\" → přidej: co email obsahoval, co chceš sdělit, jaký tón, jak dlouhá odpověď",
    ],
    taskType: "ol",
    taskPrompt: "Přepiš tento prompt tak, aby byl konkrétnější: [vlož původní prompt]. Přidej kontext, cíl, tón a požadovaný formát výstupu.",
    taskFallback: `Pokud nevíš, jak prompt přepsat, tady jsou příklady přepsaných verzí:
1. LinkedIn: "Napiš příspěvek na LinkedIn pro produktového manažera. Téma: jak jsme snížili churn klientů o 20 %. Tón: osobní, bez korporátního jazyka. Délka: 150–200 slov. Cíl: ukázat konkrétní postup, ne jen výsledek."
2. Prezentace: "Pomoz mi strukturovat 10minutovou prezentaci pro vedení o výsledcích Q3. Publikum: 5 manažerů, kteří vidí čísla poprvé. Výstup: osnova se 4–5 slidy a klíčovým sdělením každého."
3. Email: "Napiš odpověď na email klienta, který si stěžuje na zpoždění dodávky. Tón: empatický, ne obranný. Délka: max 5 vět. Cíl: zachovat vztah a navrhnout konkrétní řešení."`,
    taskTip: "Funguje v ChatGPT, Claude i Gemini.",
    teaser: "Zítra: Proč je první výsledek z AI vždy jen začátek — a jak z toho dostat mnohem víc.",
  },

  {
    day: 6,
    title: "První výsledek je základ. Ne finální produkt.",
    subject: "Iterace — jak z AI dostat mnohem víc.",
    preheader: "Nejlepší výstup vzniká ve druhém nebo třetím kole.",
    teze: "Iterace není oprava selhání — je to způsob práce, který z dobrého výstupu udělá skvělý.",
    concept: [
      "Největší chyba při práci s AI: napsat prompt, dostat výsledek, a buď ho přijmout nebo zahodit. Obojí je špatně — a obojí přichází o největší hodnotu, kterou AI nabízí.",
      "AI funguje nejlépe jako iterativní spolupracovník. První výstup je základ — ne finální produkt. Přesně tak funguje spolupráce s dobrým kolegou: dáš mu zadání, on navrhne draft, vy to společně dotáhnete. AI je v tomhle procesu neúnavná — může iterovat donekonečna.",
      "Proč lidé iteraci přeskakují? Buď nemají čas (ale iterace trvá 30 vteřin), nebo nevědí, co říct AI. Nebo jsou jednoduše zklamaní výsledkem. Má to ale jednoduché řešení — řekni AI přesně, co nesedí. Níže máš konkrétní instrukce.",
      "Jak iterovat efektivně — konkrétní fráze:",
      ["Pokud je výsledek moc obecný: \u201Epřidej konkrétní příklad z [tvoje oblast]\"", "Pokud je výsledek moc dlouhý: \u201Ezkrať to na 3 věty, zachovej klíčové body\"", "Pokud tón nesedí: \u201Epřepiš to formálněji\" nebo \u201Eudělej to méně korporátní, více lidsky\"", "Pokud chybí detail: \u201Erozveď bod číslo 2 — přidej konkrétní příklad\"", "Pokud je špatná struktura: \u201Epřepiš jako odrážkový seznam\" nebo \u201Erozděl do tří sekcí s nadpisy\""],
      "Klíčový princip: nemusíš začínat znovu. Pokračuj v konverzaci — AI pamatuje celé vlákno. Každá instrukce navazuje na předchozí výstup. Tím se konverzace s AI liší od Googlu: je to dialog, ne série samostatných dotazů.",
      "Jedno varování: iterace neznamená přepsat vše do nekonečna. Tři až čtyři kola zpravidla stačí. Pokud po pěti iteracích stále není výstup dobrý, problém je nejspíš v původním zadání — vrať se k promptu a upřesni ho od začátku.",
    ],
    taskIntro: "Vezmi libovolný výstup z minulých dnů a proveď s ním 3 iterace za sebou:",
    taskItems: [
      "Iterace 1: zkrať nebo prodluž výstup — upřesni délku a hustotu informace",
      "Iterace 2: změň tón — formálnější nebo přátelštější, podle toho co ti nesedí",
      "Iterace 3: přidej nebo odeber konkrétní informaci — upřesni obsah",
    ],
    taskType: "ol",
    taskPrompt: "Přepiš předchozí výstup takto: [konkrétní instrukce — co zkrátit, co přepsat, co přidat].",
    taskTip: "Funguje v ChatGPT, Claude i Gemini.",
    teaser: "Zítra: Reflexe prvního týdne — zapíšeš si, co fungovalo, co ne, a co z toho vezmeš dál.",
  },

  // ─── D7: Reflexe prvního týdne ────────────────────────────────────────────────

  {
    day: 7,
    title: "Týden za tebou. Co ti z něj zůstalo?",
    subject: "Reflexe prvního týdne — tři věci, které zůstávají.",
    preheader: "Znalost zapomeneš. Zapsaný poznatek ti zůstane.",
    teze: "Týden zkušeností bez zápisu zmizí jako týden přečtených knih bez poznámek.",
    concept: [
      "První týden je za tebou. Šest témat, šest krátkých cvičení. A teď přichází možná nejdůležitější den ze všech — reflexe.",
      "Proč je reflexe tak důležitá? Protože bez ní mizí poznatky stejně rychle, jak přišly. Mozek si pamatuje to, co zpracuje — ne to, co jen přijme. Napsat si tři věci, které ti utkvěly, je víc než přečíst deset dalších článků o AI.",
      "Reflexe není test. Nejde o to, jestli šlo všechno správně. Jde o to přijít na to, co ti z prvního týdne opravdu zůstalo — a co z toho chceš vzít do týdne druhého.",
      "Tři otázky pro reflexi:",
      ["Co ti z prvního týdne utkvělo nejvíc? (jedna konkrétní věc, ne seznam)", "Kde AI dala výsledek, který tě překvapil pozitivně?", "Co ti nefungovalo — a co by šlo příště zkusit jinak?"],
      "Nejčastější chyba při reflexi: být příliš obecný. \u201EVím víc o AI\" není reflexe. \u201EUkázalo se, že výsledky se zásadně zlepší, když zadám konkrétní formát výstupu\" je reflexe — protože to je použitelný poznatek.",
      "Týden druhý bude stavět na tom, co ti zůstalo. Budeme se věnovat struktuře promptu, kontextu a tomu, jak AI použít na opravdové úkoly z tvé práce. Základ z tohoto týdne teď začne dávat smysl.",
    ],
    taskIntro: "Zapiš si tři věci — konkrétně a stručně:",
    taskItems: [
      "Jedno největší zjištění z prvního týdne (jedna věta, konkrétní)",
      "Jeden výstup z AI, který byl lepší, než jsi čekal — co na promptu fungovalo?",
      "Jedna věc, která nefungovala — a jak by se k ní šlo příště přistoupit jinak",
    ],
    taskType: "ol",
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden: Jdeme hlouběji: struktura promptu, kontext a první opravdový AI výstup z tvé práce.",
  },

  // ─── TÝDEN 2: Anatomie promptu + iterace (D8–D14) ─────────────────────────────

  {
    day: 8,
    title: "Dobré prompty mají strukturu. Čtyři části, které fungují.",
    subject: "Anatomie dobrého promptu — čtyři části, které vždy fungují.",
    preheader: "Role, úkol, kontext, formát. V tomhle pořadí.",
    teze: "Role, úkol, kontext, formát — čtyři části fungují jako šablona pro každý prompt.",
    concept: [
      "Minulý týden jsme rozlišili dobrý a špatný prompt. Teď jdeme o krok dál: naučíme se, co přesně dobrý prompt obsahuje — a v jakém pořadí to dát.",
      "Existují čtyři části, které má každý dobrý prompt. Nemusíš je použít vždy všechny — ale čím víc z nich zadáš, tím lepší výstup dostaneš.",
      "Čtyři části dobrého promptu:",
      ["Role: kým má AI být? Zkušený obchodník, kouč, analytik, copywriter — role dává AI způsob uvažování", "Úkol: co přesně má udělat? Napsat, shrnout, analyzovat, přepsat, navrhnout, vysvětlit", "Kontext: co potřebuje vědět? Informace o situaci, cílové skupině, produktu, omezeních", "Formát: jak má výstup vypadat? Délka, struktura, tón, odrážky nebo odstavce"],
      "Proč role funguje? Protože AI je trénovaná na obrovském množství textu z různých perspektiv. Když zadáš roli, přepneš AI do způsobu uvažování, který k té roli patří. \u201EJsi zkušený HR manažer\" dá AI jiný přístup než \u201Ejsi junior recruiter\".",
      "Ukázka strukturovaného promptu: Jsi zkušený obchodní konzultant s praxí v B2B. Napiš krátký follow-up email klientovi, který viděl naši nabídku ale neodpověděl 5 dní. Kontext: klient je malá výrobní firma, já jsem obchodní ředitel, nabídka byla na ERP systém. Formát: max 5 vět, přátelský ale přímý tón, bez obecných frází.",
      "Nemusí to být vždy takto obsáhlé. Kratší prompty fungují pro jednodušší úkoly. Ale jakmile chceš výstup, který opravdu použiješ — tato čtyřdílná struktura tě dostane tam mnohem spolehlivěji.",
      "Dnes si tuto strukturu zkusíš na vlastním promptu — a uvidíš rozdíl oproti výstupům z prvního týdne.",
    ],
    taskIntro: "Vezmi jeden úkol z tvé práce a napiš prompt podle čtyřdílné struktury:",
    taskItems: [
      "Role: kým má AI být? (dopiš konkrétní roli nebo odbornost)",
      "Úkol: co přesně má udělat? (konkrétní instrukce — napsat, shrnout, navrhnout...)",
      "Kontext: co AI potřebuje vědět o situaci, cílové skupině, omezeních",
      "Formát: délka, tón, struktura výstupu",
    ],
    taskType: "ol",
    taskPrompt: "Jsi [role]. [Konkrétní úkol]. Kontext: [co AI potřebuje vědět]. Formát výstupu: [délka, tón, struktura].",
    taskTip: "Funguje v ChatGPT, Claude i Gemini.",
    teaser: "Zítra: Proč je kontext tvůj nejsilnější nástroj — a jak ho použít tak, aby AI pracovala přesně pro tebe.",
  },

  {
    day: 9,
    title: "AI neví, co ty víš. Kontext je tvůj nejsilnější nástroj.",
    subject: "Kontext je klíč — jak ho dát správně.",
    preheader: "Čím víc AI ví, tím víc se chová jako někdo, kdo zná tvoji práci.",
    teze: "Čím přesnější kontext zadáš, tím víc se AI chová jako někdo, kdo zná tvoji práci.",
    concept: [
      "Proč dvě osoby se stejným promptem dostávají naprosto různé výsledky? Kontext.",
      "AI nemá přístup k tvé práci, tvým klientům, tvým omezeným zdrojům ani tvé historii projektů. Ví jen to, co bylo napsáno v aktuální konverzaci. To není omezení — to je pravidlo hry, které lze využít ve svůj prospěch.",
      "Dobrý kontext není paragraf textu. Je to výběr toho nejdůležitějšího, co AI potřebuje vědět, aby výstup dával smysl pro tvoji situaci — ne pro průměrnou situaci.",
      "Co do kontextu patří nejvíc:",
      ["Kdo je příjemce výstupu — zkušený odborník, laik, zákazník, manažer", "Jaká je situace — co se děje, co je v sázce, co se stalo dřív", "Jaká jsou omezení — co AI nemá dělat, co je citlivé, co je dané", "Jaký je tvůj cíl — informovat, přesvědčit, získat zpětnou vazbu, domluvit schůzku"],
      "Příklad bez kontextu: \u201ENapiš shrnutí projektu.\" AI napíše obecné shrnutí, které lze použít na cokoliv — a tím pádem na nic konkrétního.",
      "Příklad s kontextem: \u201ENapiš shrnutí projektu pro výbor vedení firmy. Projekt je v prodlení 3 týdny. Vedení o prodlení ví, ale nezná důvody. Tón klidný a věcný, bez omluv, s návrhem dalšího kroku. Max 150 slov.\" To je výstup, který okamžitě použiješ.",
      "Klíčová otázka, kterou si klást před každým promptem: co by si o mé situaci myslel moudrý kolega, který mi chce pomoci — co by potřeboval vědět, aby poradil dobře? To je tvůj kontext.",
    ],
    taskIntro: "Vezmi prompt z minulého dne a vylepši ho přidáním kontextu:",
    taskItems: [
      "Vyber prompt z D8 nebo libovolný, který ti dal průměrný výstup",
      "Přidej: kdo je příjemce, jaká je situace, jaká jsou omezení, jaký je cíl",
      "Porovnej výstup s původním — zapiš si konkrétní rozdíl",
    ],
    taskType: "ol",
    taskPrompt: "Kontext: [kdo jsem, jaká je situace, co je cílem]. Příjemce: [kdo to bude číst a co o tématu ví]. Omezení: [co nemá výstup obsahovat nebo dělat]. Úkol: [konkrétní instrukce].",
    taskTip: "Funguje v ChatGPT, Claude i Gemini.",
    teaser: "Zítra: Napíšeš si prompt pro opravdový úkol ze své práce — a dostaneš výstup, který okamžitě použiješ.",
  },

  {
    day: 10,
    title: "Dnes to bude osobní. Prompt přímo z tvé práce.",
    subject: "Žádné cvičení — opravdový úkol, opravdový výstup.",
    preheader: "Tady se teorie mění na praxi.",
    teze: "Teorie se promění v praxi přesně ve chvíli, kdy ji použiješ na svůj vlastní úkol — dnes.",
    concept: [
      "Prvních devět dní bylo příprava. Dnes je výsledek.",
      "Nejlepší způsob, jak otestovat, co ti zůstalo, je vzít opravdový úkol z tvé práce a projít celým procesem: kontext, role, zadání, formát. A pak iterovat, dokud výstup není použitelný.",
      "Proč je tohle důležité? Protože reálný úkol je vždy těžší než cvičný příklad. Máš méně ideální informace, výstup musí sedět konkrétním lidem, a záleží ti na výsledku. Právě proto je to nejlepší test.",
      "Úkoly, které na dnešní den fungují dobře:",
      ["Text, který budeš brzy potřebovat — email, zpráva, shrnutí, post", "Dokument, který připravuješ opakovaně — agenda schůzky, týdenní status, report", "Odpověď na otázku, kterou řešíš — návrh řešení, analýza situace, porovnání možností", "Výstup, který jinak děláš manuálně — přepis poznámek, strukturování informací, překlad"],
      "Dobrý výsledek dnes není dokonalý výstup. Dobrý výsledek je výstup, který ti ušetří čas nebo dá základ, který dál dopracuješ. To je cíl.",
      "Pamatuj na iteraci: pokud první výstup není dobrý, nereklamuj to u AI — upřesni prompt. Přidej kontext, upřesni formát, změň roli. Tři kola zpravidla stačí.",
      "Výstup dnešního dne si ulož. V den 12 se k němu vrátíme a výstup společně vylepšíme na základě toho, co se naučíš mezitím.",
    ],
    taskIntro: "Vyber reálný úkol ze své práce a projdi celým procesem:",
    taskItems: [
      "Zapiš si úkol a co přesně potřebuješ jako výstup",
      "Napiš prompt podle čtyřdílné struktury z D8 — role, úkol, kontext, formát",
      "Zkus ho v AI, výsledek zkontroluj a udělej aspoň jednu iteraci",
      "Výstup ulož — vrátíme se k němu ve středu",
    ],
    taskType: "ol",
    taskFallback: `Pokud nevíš, jaký úkol vzít, zkus jeden z těchto startovacích promptů:
"Napiš shrnutí schůzky pro tým. Probrali jsme: [téma 1], [téma 2], [téma 3]. Výstup: odrážky, max 10 řádků, jasné akční body na konci."
"Napiš follow-up email pro klienta po úvodní schůzce. Tón: přátelský a konkrétní. Délka: max 5 vět. Cíl: potvrdit zájem a domluvit další krok."
"Napiš týdenní status pro vedení. Co jsme posunuli: [X]. Co čeká: [Y]. Blokery: [Z]. Formát: max 5 odrážek."`,
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Co dělat, když výstup nesedí — konkrétní techniky pro opravu špatného výstupu.",
  },

  {
    day: 11,
    title: "Výstup z AI nesedí? Pět technik, které ho zachrání.",
    subject: "Jak opravit špatný výstup — bez začínání od nuly.",
    preheader: "Zklamání z výsledku je informace. Víš, co říct dál.",
    teze: "Špatný výstup je informace, ne selhání — říká ti přesně, co v promptu chybí.",
    concept: [
      "Špatný výstup z AI je frustrace. Ale je to také informace — říká ti přesně, co chybí v zadání.",
      "Nejhorší reakce: smazat výstup a začít znovu od prázdné stránky. Nebo AI opustit a dělat to ručně. Obojí je zbytečné — a oba přístupy vyhodí práci, kterou AI odvedla.",
      "Správná reakce: napiš AI přesně, co nesedí. Ne vágně (\u201Etoto je špatně\"), ale konkrétně (\u201Etento odstavec je příliš obecný, přepiš ho s konkrétním příkladem z HR prostředí\").",
      "Pět technik pro opravu špatného výstupu:",
      ["Upřesni požadavek: \u201EVýsledek je příliš obecný. Přidej konkrétní příklad pro [situaci].\"", "Změň tón: \u201EPřepiš to méně formálně, více jako by to psal člověk, ne korporátní dokument.\"", "Omez rozsah: \u201EZkrať na 3 klíčové body — zbytek odstraň.\"", "Požádej o varianty: \u201ENapiš to ještě třemi různými způsoby — hledám jiný úhel pohledu.\"", "Vysvětli, proč to nefunguje: \u201EPříjemce zprávy nezná náš kontext — přepiš bez předpokladu, že čtenář ví o projektu.\""],
      "Jedna věc, na kterou si dát pozor: AI si pamatuje kontext celé konverzace. Pokud iteruješ moc dlouho a výsledky se zhoršují, někdy pomůže začít novou konverzaci — s lepším výchozím promptem, který zahrnuje, co ti předchozí konverzace přinesla.",
      "Dnešní cvičení tě naučí rozlišovat mezi \u201Ešpatným promptem\" a \u201Ešpatným výstupem\" — protože oprava je jiná.",
    ],
    taskIntro: "Vezmi výstup z D10 nebo jakýkoli výstup, který ti nesedí, a zkus tyto kroky:",
    taskItems: [
      "Identifikuj konkrétně, co nesedí — tón, délka, obsah, nebo struktura",
      "Napiš AI instrukci opravy — konkrétně, ne obecně",
      "Porovnej původní a opravený výstup — co se změnilo?",
    ],
    taskType: "ol",
    taskPrompt: "Tento výstup nesedí, protože [konkrétní důvod]. Přepiš ho tak, aby [konkrétní požadavek na opravu].",
    taskTip: "Funguje v ChatGPT, Claude i Gemini.",
    teaser: "Zítra: Vrátíme se k promptu z D10 a výstup vylepšíme pomocí technik z dnešního dne.",
  },

  {
    day: 12,
    title: "Dobrý výstup se stane skvělým. Takto se iteruje.",
    subject: "Iterace v praxi — lepší výstup z toho, co máš.",
    preheader: "Dobrý výsledek nevznikne napoprvé. Vznikne napotřetí.",
    teze: "Skvělý výstup nevznikne napoprvé — vznikne ve třetím kole s přesnou instrukcí, co opravit.",
    concept: [
      "V D6 jsi se naučil, co je iterace a jak funguje v principu. Dnes ji použiješ na výstup, na kterém ti opravdu záleží.",
      "Máš prompt a výstup z D10. Máš techniky z D11. Teď je čas je spojit — a dotáhnout výstup na úroveň, která je opravdu použitelná. To je rozdíl oproti D6: ne cvičný výstup, ale tvoje vlastní práce, na které ti záleží.",
      "Proč je návrat k předchozímu výstupu tak cenný? Protože vidíš ho s odstupem. Co se tehdy zdálo použitelné, teď může vypadat jinak. A techniky z D11 ti dají konkrétní nápady, co zlepšit.",
      "Proces dnešního dne:",
      ["Otevři výstup z D10 — přečti ho znovu s čerstvým pohledem", "Identifikuj tři věci, které by šlo zlepšit — tón, délka, konkrétnost, struktura", "Napiš opravnou instrukci pro každou z nich", "Výsledné výstupy porovnej s originálem"],
      "Nepotřebuješ opravit vše. Zaměř se na jednu nebo dvě největší slabiny. Perfekcionismus v iteraci je past — lepší je výstup, který je z 80 % dobrý a ušetřil hodinu, než dokonalý výstup, který si vyžádal dvě hodiny iterací.",
      "Klíčový poznatek: iterace s AI není slabina. Je to způsob práce. Nejlepší pracovníci s AI nedostávají dokonalé výsledky napoprvé — dostávají je po dvou nebo třech iteracích. To je norma, ne výjimka.",
    ],
    taskIntro: "Vrať se k výstupu z D10 a proveď tři cílené iterace:",
    taskItems: [
      "Iterace 1: upřesni obsah — co přidat nebo odebrat, aby výstup lépe odpovídal skutečné situaci",
      "Iterace 2: uprav tón nebo délku — dle výstupu z D11",
      "Iterace 3: přidej konkrétní příklad nebo detail, který výstup zpřesní",
    ],
    taskType: "ol",
    taskPrompt: "Vezmi předchozí výstup a vylepši ho takto: 1. [co konkrétně přidat nebo změnit]. 2. [co zkrátit nebo odstranit]. 3. [jak upravit tón nebo strukturu].",
    taskTip: "Funguje v ChatGPT, Claude i Gemini.",
    teaser: "Zítra: Kdy AI pomáhá a kdy to celé jenom zkomplikuje — upřímný přehled.",
  },

  {
    day: 13,
    title: "Kdy AI nepoužívat — a proč to vědět je výhoda.",
    subject: "Kdy AI pomáhá a kdy přidává práci.",
    preheader: "Nejlepší nástroj pro každý úkol — to někdy není AI.",
    teze: "Vědět, kdy AI nepoužít, je stejně cenná dovednost jako vědět, jak ji použít dobře.",
    concept: [
      "Nejsofistikovanější AI uživatelé nevyužívají AI na vše. Vědí přesně, kdy AI použít — a kdy je rychlejší, lepší nebo spolehlivější udělat to bez ní.",
      "Tohle je pohled, který v tutoriálech o AI málokdy uslyšíš. Ale je to pohled, který tě posune nejvíc.",
      "Kdy AI pomáhá nejvíce:",
      ["Úkol má jasnou strukturu — email, shrnutí, agenda, analýza, vysvětlení", "Potřebuješ varianty nebo nápady rychle — brainstorming, možnosti, alternativy", "Text je dlouhý a potřebuješ ho zkrátit nebo přestrukturovat", "Děláš to opakovaně — šablona nebo prompt ti každé příští kolo ušetří čas", "Potřebuješ začít — draft, osnova, první verze, od které se odrazíš"],
      "Kdy AI přidává práci nebo komplikuje:",
      ["Potřebuješ přesná fakta, čísla nebo aktuální informace — AI může vymýšlet", "Rozhodnutí vyžaduje tvůj odborný úsudek nebo znalost konkrétního kontextu", "Výstup potřebuje být zcela osobní — AI neudrží tvůj autentický hlas bez velké práce", "Zadání je složité formulovat — pokud nevíš, co přesně chceš, AI to za tebe nevymyslí", "Krátký jednoduchý úkol — napsat jednu větu nebo odškrtnout jednu položku je rychlejší ručně"],
      "Praktický test: pokud ti trvá napsat prompt déle, než by trvalo udělat úkol ručně — přeskoč AI. Pokud se jedná o opakující se typ úkolu, investuj do dobrého promptu nyní — příště to zabere jen 30 vteřin.",
      "Tohle není kritika AI. Je to realistický pohled na to, jak ji používat s rozumem — ne z nadšení.",
    ],
    taskIntro: "Projdi svůj typický pracovní den a roztřiď úkoly do dvou skupin:",
    taskItems: [
      "Úkoly, kde AI pomáhá — strukturované, opakující se, kde potřebuješ varianty nebo drafty",
      "Úkoly, kde je lepší bez AI — krátké jednorázové věci, kde potřebuješ přesnost nebo osobní hlas",
      "Zapiš si po třech příkladech do každé skupiny",
    ],
    taskType: "ol",
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Kdy AI výstupu věřit — a kdy ho ověřit.",
  },

  {
    day: 14,
    title: "Kdy AI výstupu věřit — a kdy ne.",
    subject: "Přesvědčivý výstup ještě neznamená správný výstup.",
    preheader: "AI nikdy neřekne 'nevím'. Tady je návod, jak to poznat.",
    teze: "AI nikdy neřekne 'nevím' — vygeneruje přesvědčivý text i tehdy, kdy se mýlí.",
    concept: [
      "Tato věta rozhoduje o tom, jak dobře budeš AI používat dlouhodobě: přesvědčivý výstup ještě neznamená správný výstup.",
      "AI nikdy neřekne 'nevím'. Místo toho vygeneruje text, který zní jistě — i tehdy, kdy si jistá být nemůže. Říká se tomu halucinace, ale přesnější výraz je: přesvědčivá nepřesnost.",
      "Kde to nastává nejčastěji:",
      [
        "Fakta a čísla — statistiky, data, procentní výsledky: AI je dokáže vymyslet přesvědčivě bez varování",
        "Reference a citáty — 'expert X říká...' nebo 'studie z roku...' — bez ověření nelze věřit",
        "Aktuální informace — AI má datum cut-off a neví, co se stalo po určitém datu",
        "Tvůj specifický kontext — AI nezná tvoji firmu, klienty ani interní procesy"
      ],
      "Tři červené vlajky, které stojí za ověření:",
      [
        "Přesné číslo nebo procento bez zdroje — kde to AI vzala?",
        "Citát nebo reference na konkrétní studii nebo osobu — existuje to skutečně?",
        "Tvrzení z tvého oboru, které jsi sám dosud neslyšel — proč to nevíš, pokud je to pravda?"
      ],
      "Calibrated trust: cílem není AI nedůvěřovat. Cílem je vědět, kde ověřit a kde věřit. Texty, struktury, nápady — nízké riziko. Fakta, čísla, reference — vždy ověřit.",
    ],
    taskIntro: "Vezmi jeden výstup z předchozích dnů a proveď rychlý fact-check:",
    taskItems: [
      "Najdi jedno konkrétní tvrzení, číslo nebo referenci, které AI použila",
      "Ověř ho — Googlem, vlastní znalostí nebo zdrojem",
      "Zapiš: bylo to správně? Pokud ne — jak přesvědčivě to znělo?",
    ],
    taskType: "ol",
    taskFallback: `Pokud nemáš uložený výstup, zadej AI tento prompt a pak ověř jednu věc, kterou odpoví:
"Jaké jsou tři klíčové statistiky o využití AI v práci v roce 2024?"`,
    taskTip: "Nejde o to, že AI lže — jde o to, že si neuvědomuje, kdy si není jistá. Ty ano.",
    teaser: "Zítra: Checkpoint — polovina challenge je za tebou a zapíšeš si svůj osobní prompt checklist.",
  },

  {
    day: 15,
    title: "Polovina za tebou. Ohlédnutí, které dává směr.",
    subject: "Checkpoint — co ti z první poloviny zůstalo.",
    preheader: "Nejlepší investice 5 minut: vědět, co si vezmeš dál.",
    teze: "Polovina challenge za tebou — co si nezapíšeš dnes, zapomeneš ještě dřív, než dojdeš na konec.",
    concept: [
      "Čtrnáct dní. Čtrnáct témat. A teď přichází jeden z nejdůležitějších dnů challenge — ne kvůli nové látce, ale proto, že se zastavíš a zpracuješ, co challenge přinesla.",
      "Zapsaný poznatek funguje jinak než přečtená informace. Když si napíšeš, co ti opravdu funguje, vytvoříš si osobní checklist — přesně na míru tvé práci a tvým situacím.",
      "Tři věci, na které se zaměříme:",
      ["Co z první poloviny challenge si vezmeš a budeš aktivně používat?", "Co ti nefungovalo — a proč?", "Jaký je tvůj aktuální osobní prompt checklist?"],
      "Osobní prompt checklist je jednoduše seznam věcí, které si ověříš před tím, než prompt odešleš. Nemusí být dlouhý — tři až pět bodů stačí. Ale musí být tvůj, ne zkopírovaný. Co funguje pro tebe konkrétně.",
      "Příklad checklistu (ne šablona — příklad):",
      ["Mám roli? Je zadáno, kým má AI být?", "Mám kontext? Ví AI dost o situaci a příjemci?", "Mám formát? Ví AI, jak má výsledek vypadat?", "Mám cíl? Ví AI, čeho má výstup dosáhnout?"],
      "Druhá polovina challenge bude stavět na základech z první poloviny. Půjdeme do šablon, opakující se práce, AI nástrojů v kontextu celého pracovního dne — a nakonec k tomu, jak si vybudovat návyk, který ti zůstane i po skončení challenge.",
    ],
    taskIntro: "Zapiš si tři věci — stačí odrážky, stačí pár slov:",
    taskItems: [
      "Tři poznatky z první poloviny challenge, které ti opravdu zůstaly (konkrétní, ne obecné)",
      "Tvůj osobní prompt checklist — 3–5 věcí, které si ověříš před odesláním každého promptu",
      "Jeden konkrétní cíl pro druhou polovinu challenge",
    ],
    taskType: "ol",
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden: Opakující se práce jako signál, šablony a workflows — a jak ušetřit hodinu týdně na věcech, které děláš pořád znovu.",
  },

  // ─── TÝDEN 3: Šablony + workflow (D15–D21) ────────────────────────────────────

  {
    day: 16,
    title: "Opakující se úkoly jsou nejdražší práce, která existuje.",
    subject: "Identifikuj, co děláš každý týden znovu — to je signál.",
    preheader: "Ne každá opakující se práce je nutná. Ale každá stojí za pozornost.",
    teze: "Opakující se práce je signál — a každý signál je příležitost pro šablonu nebo workflow.",
    concept: [
      "Spousta práce nevypadá na první pohled drahá. Jeden email tady, jedno shrnutí tam, agenda schůzky ve čtvrtek. Každá věc zvlášť trvá deset minut.",
      "Ale deset věcí každý týden je hodina. A hodina každý týden je dva a půl týdne ročně. Na jedné kategorii práce.",
      "Opakující se práce je signál. Ne signál, že máš být rychlejší. Signál, že by tato práce měla mít šablonu, prompt nebo workflow — aby příště nezačínala od nuly.",
      "Tři typy opakující se práce, kde AI pomáhá nejvíc:",
      ["Dokumenty — reporty, shrnutí, zápisky, briefy, agendy, nabídky", "Komunikace — follow-upy, odpovědi na časté dotazy, potvrzení, interní updaty", "Strukturování — přepis poznámek, organizace informací, příprava podkladů pro rozhodnutí"],
      "Dnešní úkol je průzkum — bez nátlaku měnit cokoliv hned. Cílem je vidět mapu opakující se práce. Co trvá? Co se vrací? Co tě stojí nejvíc energie? To bude základ pro šablony a prompty, které si vytvoříš v dalších dnech.",
    ],
    taskIntro: "Zamysli se nad svým pracovním týdnem a zapiš si:",
    taskItems: [
      "5 věcí, které děláš opakovaně — každý týden nebo každý druhý týden",
      "U každé: přibližně jak dlouho trvá a jak moc tě to stojí energie",
      "Označ hvězdičkou tu, u které je ztráta času nebo energie největší",
    ],
    taskType: "ol",
    taskFallback: `Pokud nevíš, co si zapsat, tady jsou příklady opakující se práce z různých rolí:
— Příprava týdenního reportu pro vedení (45 min)
— Odpovědi na opakující se dotazy zákazníků (20–30 min/den)
— Přepis poznámek ze schůzky do akčního plánu (20 min)
— Příprava agendy pro pravidelné týmové meetingy (15 min)
— Drafting follow-up emailů po obchodních schůzkách (20 min)
Vyber, co se podobá tvé práci, nebo doplň vlastní.`,
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Z tohoto seznamu sestavíš svoji osobní leverage matici — kde AI může přidat nejvíc.",
  },

  {
    day: 17,
    title: "Sestav si mapu: které úkoly svěřit AI a které ne.",
    subject: "Top 5 opakujících se úkolů, kde AI může ušetřit nejvíc.",
    preheader: "Leverage matice: co předat AI, co vylepšit, co zautomatizovat.",
    teze: "Ne všechna práce má stejnou hodnotu a ne vše patří AI — mapa ukáže, kde je největší leverage.",
    concept: [
      "Včera vznikl přehled opakující se práce. Dnes ji roztřídíš — a rozhodneš, kde AI přinese nejvíc.",
      "Ne každá opakující se práce je stejný typ příležitosti. Pomáhá ji rozdělit do tří kategorií:",
      ["Předat AI: AI může udělat první verzi nebo celý výstup — ty jen zkontroluj a pošli", "Vylepšit s AI: ty máš vstup a strukturu, AI pomáhá s formulací, délkou nebo formátem", "Zautomatizovat šablonou: prompt jednou dobře nastavíš, pak ho používáš opakovaně za 30 vteřin"],
      "Jak rozlišit, do které kategorie věc patří: úkoly, které mají jasnou strukturu a výstup (email, shrnutí, report), jsou kandidáti pro \u201Epředat\" nebo \u201Ešablona\". Úkoly, kde vstup je složitý nebo osobní (koučovací rozhovor, kreativní návrh), jsou spíše pro \u201Evylepšit s AI\".",
      "Ukázka leverage matice v praxi:",
      ["Týdenní status pro vedení → předat AI (zadám data, dostanu draft)", "Odpovědi na opakující se dotazy klientů → šablona (jednou napíšu prompt, opakuji)", "Příprava agendy schůzky → vylepšit s AI (já mám témata, AI strukturuje)", "Strategická prezentace pro board → vylepšit s AI (obsah je můj, AI pomáhá s formulací)"],
      "Cílem dnešního dne není udělat vše najednou. Cílem je vybrat jeden nebo dva úkoly, kde začneš — a kde bude efekt nejviditelnější.",
    ],
    taskIntro: "Vezmi seznam z D16 a projdi ho tímto filtrem:",
    taskItems: [
      "U každého úkolu rozhodni: předat AI, vylepšit s AI, nebo zautomatizovat šablonou",
      "Vyber jeden úkol v kategorii \u201Epředat AI\" nebo \u201Ešablona\" — ten je nejjednodušší na začátek",
      "Zapiš si konkrétně, jak by tam AI pomohla — co by byl vstup a co výstup",
    ],
    taskType: "ol",
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Rozdíl mezi šablonou a workflowem — a proč na tom záleží, když chceš systém, ne jen pomůcku.",
  },

  {
    day: 18,
    title: "Šablona řeší jeden úkol. Workflow řeší celý proces.",
    subject: "Šablona vs. workflow — a kdy použít co.",
    preheader: "Šablona je odpověď. Workflow je systém.",
    teze: "Šablona ušetří čas pro jeden konkrétní krok. Workflow propojí více šablon do systému, který funguje celý proces.",
    concept: [
      "Šablona a workflow zní podobně. Ale jsou to dvě různé věci — a záměna je příčinou toho, proč někdo \u201Emá šablonu\", ale stále tráví stejně času.",
      "Šablona je předpřipravený výstup nebo prompt pro jeden opakující se úkol. Např.: mám prompt pro týdenní status — zadám data, dostanu draft. Šablona řeší jeden konkrétní krok.",
      "Workflow je posloupnost kroků, která zahrnuje více šablon a rozhodnutí. Např.: proces od schůzky k odeslání zápisku — zápis poznámek, strukturování do agendy, doplnění úkolů, odeslání. Každý krok má svoji šablonu, ale dohromady tvoří workflow.",
      "Kdy stačí šablona:",
      ["Opakující se výstup, který je vždy podobný — email, report, agenda, shrnutí", "Jednokrokový úkol, kde vstup je jasný a výstup je předvídatelný", "Začátek — první šablona je vždy nejdůležitější krok"],
      "Kdy potřebuješ workflow:",
      ["Proces má více kroků, které na sebe navazují", "Různí lidé jsou zapojeni v různých fázích", "Chybí jeden krok → celý výsledek se zhorší"],
      "Pro tuhle challenge se soustředíme hlavně na šablony — jsou rychlejší na vybudování a efekt je okamžitý. Workflow je pokročilejší téma, které si rozvedeme v Advanced verzi challenge.",
      "Důležité: dobrá šablona není dokument. Je to prompt, který je napsaný tak konkrétně, že ho můžeš zadat AI za 30 vteřin a dostat výstup, který přímo použiješ.",
    ],
    taskIntro: "Vyber si jeden opakující se úkol ze svého seznamu a rozhodni:",
    taskItems: [
      "Je to jeden krok (šablona) nebo více kroků (workflow)?",
      "Pokud šablona: napiš si, co by měl prompt obsahovat — vstup, výstup, tón, formát",
      "Pokud workflow: napiš si kroky procesu a označ, který z nich je nejdůležitější kandidát na šablonu",
    ],
    taskType: "ol",
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Vytvoříš svoji první opravdovou šablonu — prompt, který budeš opakovaně používat.",
  },

  {
    day: 19,
    title: "Jedna šablona, která od teď ušetří hodinu každý týden.",
    subject: "Vytvoř první opakovaně použitelný prompt.",
    preheader: "Jednou dobře. Pak za 30 vteřin pokaždé.",
    teze: "Jedna dobře napsaná šablona vrátí investici při každém dalším použití — a neopotřebuje se.",
    concept: [
      "Dobré šablony se nepíší na jeden zátah. Vyvíjejí se — první verze funguje na 70 %, druhá verze na 85 %, třetí je ta, kterou pak používáš roky.",
      "Ale musíš začít. A začít znamená napsat první verzi — i nedokonalou.",
      "Co dělá šablonu dobrou? Tři věci:",
      ["Je konkrétní — ne \u201Enapiš email\", ale \u201Enapiš follow-up email klientovi, který neodpověděl na nabídku po 5 dnech\"", "Má proměnné — místa, kde dosadíš konkrétní hodnoty: [jméno klienta], [typ nabídky], [datum]", "Dává konzistentní výstup — každé použití produkuje výsledek, který je na stejné kvalitativní úrovni"],
      "Jak šablonu vytvořit:",
      ["Vyber opakující se úkol — nejlépe takový, kde výstup bývá vždy podobný", "Napiš prompt, který přesně popisuje, co výstup má obsahovat, v jakém tónu a formátu", "Přidej proměnné — místa v promptu, kde dosadíš konkrétní detaily", "Otestuj šablonu na dvou různých situacích a uprav, co nesedí", "Ulož ji na místo, odkud ji příště rychle dostaneš — Notion, Google Docs, Apple Notes"],
      "Jedna šablona týdně. Za čtyři týdny máš čtyři šablony — a každá ti ušetří 20–30 minut. To je hodina a půl týdně na věcech, které dřív začínaly od nuly.",
      "Dnešní úkol není dokonalý. Je to první verze. A to je přesně, co potřebuješ.",
    ],
    taskIntro: "Postav svoji první šablonu — krok za krokem:",
    taskItems: [
      "Vyber opakující se úkol — nejlépe ten hvězdičkou označený z D16",
      "Napiš prompt: role, úkol, kontext (jako proměnné), formát výstupu",
      "Otestuj ho na jednom konkrétním příkladu — funguje? Co upravit?",
      "Ulož šablonu do Notion, Google Docs nebo Apple Notes jako \u201EMoje AI šablony\"",
    ],
    taskType: "ol",
    taskPrompt: "Jsi [role]. [Konkrétní úkol]. Kontext: [jméno/situace/specifika — dosadíš pokaždé]. Formát výstupu: [délka, tón, struktura].",
    taskTip: "Šablonu ulož jako dokument do Notion, Google Docs nebo Apple Notes — ať ji máš rychle po ruce.",
    teaser: "Zítra: Empirický pohled na čas — kde AI skutečně ušetří a kde ho paradoxně přidá.",
  },

  {
    day: 20,
    title: "Kde AI šetří čas a kde ho přidává — upřímný přehled.",
    subject: "Měření, ne pocit. Kde AI přidává hodnotu a kde ne.",
    preheader: "Nejlepší AI workflow je ten, který opravdu ušetří čas.",
    teze: "Pocit, že AI pomáhá, nestačí — konkrétní měření ukáže, kde je přínos a kde jde jen o zvyk.",
    concept: [
      "Říká se, že AI šetří čas. Ale \u201EAI mi šetří čas\" je pocit. Kde konkrétně, jak moc, a při jakém typu úkolů — to jsou data. A data jsou mnohem užitečnější.",
      "Proč na tom záleží? Protože bez měření jdeš buď do nadšení (AI pomáhá vždy) nebo do skepse (AI nepomáhá nikdy). Upřímný pohled na to, kde AI skutečně přidává hodnotu, ti pomůže ji nasadit tam, kde to dává smysl.",
      "Kde AI typicky šetří čas:",
      ["První draft textu — psaní od nuly je nejnákladnější; AI draft trvá sekundy, úprava minuty", "Strukturování — přepis poznámek nebo neuspořádaných informací do přehledné formy", "Variace — místo tvorby jedné možnosti dostaneš tři; výběr je rychlejší než tvorba", "Přeformátování — z bulletů na odstavce, z textu na tabulku, z formálního na přátelský"],
      "Kde AI čas nepřidává nebo přidává práci:",
      ["Krátké jednoduché věci — napsat jednu větu ručně je rychlejší než formulovat prompt", "Vysoce specifický kontext — pokud musíš napsat víc textu jako kontext než je výstup, nedává to smysl", "Ověřování faktů — AI výstup, který musíš doslova každou větu zkontrolovat, ušetří málo"],
      "Praktický test: pokud ti tvorba dobrého promptu trvá déle než 2 minuty a výstup bude kratší než stránka — zvaž, jestli je AI opravdu rychlejší. Pokud ano, jdi do šablony.",
      "Cílem dne není odpovědět \u201EAI mi šetří čas\". Cílem je vědět konkrétně: kde ano, jak moc a proč.",
    ],
    taskIntro: "Projdi svůj minulý týden a udělej malý experiment:",
    taskItems: [
      "Vyber 3 různé úkoly z minulého týdne — s AI nebo bez ní",
      "Odhadni: kolik minut trvaly vs. kolik by trvaly s/bez AI",
      "Zapiš si, kde byl rozdíl největší — a proč",
    ],
    taskType: "ol",
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Celý den s AI jako vedlejším nástrojem — jak to vypadá v praxi.",
  },

  {
    day: 21,
    title: "Jeden den záměrně bez AI. Pozoruj, co se změní.",
    subject: "Den bez AI — ne jako trest, ale jako experiment.",
    preheader: "Jeden den bez AI ti řekne víc než týden s ní.",
    teze: "Jeden den bez AI odhalí, kde ti skutečně pomáhá — a kde ji jen automaticky otevíráš ze zvyku.",
    concept: [
      "Dnes je den, kdy budeš záměrně bez AI. Ne jako trest nebo detox — ale jako vědomý experiment. Nejlepší způsob, jak zjistit, kde ti AI skutečně pomáhá, je zkusit jeden den bez ní.",
      "Co se může stát: některé věci budou pomalejší. Jiné překvapivě stejné. A u některých si řekneš \u201Etady mi AI opravdu chybí\" — a to je přesně ta informace, která má hodnotu.",
      "Tři otázky, které si dnes průběžně pokládej:",
      [
        "Kde mi AI chybí? — konkrétní úkol, kde bych ji normálně použil a teď ji nemám",
        "Kde funguju stejně dobře? — co zvládnu bez AI stejně rychle nebo stejně kvalitně",
        "Kde ji možná používám ze zvyku? — úkoly, kde AI zapojuji automaticky, ale není to nutné"
      ],
      "Výsledek dnešního dne není \u201Ezvládl jsem to bez AI\". Je to přesný seznam — kde AI v tvé práci skutečně patří a kde je jen zvyk.",
      "Třetí týden je za tebou. V tomhle týdnu vznikla první šablona, zmapovala se opakující se práce a zkusil sis reálný den bez AI. Teď přichází čtvrtý týden, kde se naučíš ukládat výstupy a kontext tak, aby se AI stala součástí způsobu práce — ne jen občasným nástrojem.",
    ],
    taskIntro: "Dnešní úkol je na celý den — večer si sedni a zapiš:",
    taskItems: [
      "Tři momenty, kdy ti AI chyběla — co konkrétně, proč a jak jsi to vyřešil bez ní",
      "Tři věci, které fungovaly stejně dobře nebo lépe — co to říká o tvém skutečném využití AI",
      "Jeden závěr: pro co AI ve své práci opravdu potřebuješ — konkrétně, ne obecně",
    ],
    taskType: "ol",
    taskTip: "Zapiš večer do notýsku nebo Notion — tohle je jeden z nejcennějších záznamů celé challenge.",
    teaser: "Zítra: Jaký je tvůj AI styl — a proč každý pracuje s AI jinak.",
  },

  {
    day: 22,
    title: "Každý používá AI jinak. Jaký je tvůj styl?",
    subject: "Tvůj AI styl — silné stránky, preference, způsob práce.",
    preheader: "Nejlepší AI workflow je ten, který sedí tobě.",
    teze: "Nejlepší způsob práce s AI není ten nejpopulárnější — je to ten, který sedí tobě a tvé práci.",
    concept: [
      "Dva lidé se stejnými AI nástroji mohou mít zcela odlišné výsledky. Jeden je skvělý ve psaní promptů, druhý v iteraci. Jeden používá AI pro texty, druhý pro strukturování a analýzu. Jeden preferuje krátké konverzace, druhý delší dialog.",
      "Tohle není problém. Je to realita — a čím dřív to přijmeš, tím lépe budeš vědět, jak AI nasadit.",
      "Tři dimenze AI stylu:",
      ["Typ úkolů: kde ti AI pomáhá nejvíc — texty, strukturování, brainstorming, analýza, kódování?", "Způsob iterace: preferuješ dostat jednu dobrou odpověď napoprvé, nebo rychlý draft a pak opravovat?", "Frekvence: AI jako každodenní nástroj nebo na vybrané opakující se úkoly?"],
      "Není správný nebo špatný AI styl. Jsou jen styly, které fungují lépe nebo hůř pro konkrétní práci a konkrétního člověka.",
      "Proč je tohle důležité vědět: pokud budeš AI používat způsobem, který ti nevyhovuje, přestaneš ji používat. Pokud si nastavíš AI do módu, který sedí tvé práci a tvému tempu — zůstane ti.",
      "Poznat svůj AI styl je základ pro to, co přijde v tomto týdnu. Nejde o nové techniky — jde o systém: kde ukládat výstupy, jak zachovat kontext a jak z vědomosti udělat návyk, který vydrží.",
    ],
    taskIntro: "Zapiš si svůj AI styl — tři věty, konkrétně:",
    taskItems: [
      "Kde mi AI pomáhá nejvíce — jaký typ úkolů (být konkrétní, ne obecný)",
      "Jak preferuji iterovat — jeden dobrý draft, nebo rychlý základ a pak opravuji?",
      "Jak chci AI do práce zapojit — denně na vybrané věci, nebo situačně?",
    ],
    taskType: "ol",
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden: Jak si vybudovat druhý mozek s AI — kde ukládat výstupy a jak je opakovaně používat.",
  },

  // ─── TÝDEN 4: Druhý mozek + návyk (D22–D28) ───────────────────────────────────

  {
    day: 23,
    title: "AI si nic nepamatuje. Ale ty si to zařídit můžeš.",
    subject: "Druhý mozek — kde ukládat AI výstupy, aby se neztratily.",
    preheader: "Výstup bez uložení je polovina hodnoty.",
    teze: "Výstup z AI bez systému uložení je polovina hodnoty — druhá polovina je v tom, co najdeš za měsíc.",
    concept: [
      "Každý AI výstup, který si neuložíš, je pryč. Příští konverzace s AI nezačíná tam, kde ta předchozí skončila — začíná od nuly. To je vlastnost AI, ne chyba. A lze ji kompenzovat.",
      "Druhý mozek je jednoduché místo, kde ukládáš věci, které se vrátí. AI výstupy, šablony, dobré prompty, poznatky, zápisy. Ne proto, aby to bylo hezky seřazené — ale proto, aby se šlo k tomu vrátit.",
      "Proč to nestačí pamatovat si to v hlavě? Protože mozek je špatný úložiště pro opakující se informace a dobré úložiště pro kontext a rozhodování. Druhý mozek — digitální — přebírá ukládání. Mozek zůstane na přemýšlení.",
      "Co do druhého mozku patří:",
      ["Šablony a dobré prompty — ty, které opakovaně fungují", "AI výstupy, které chceš použít nebo na ně navázat", "Zápisy ze schůzek nebo dnů — připravené AI pro rychlý přístup", "Poznatky a nápady — krátké záznamy, které ti přišly v průběhu práce"],
      "Nejdůležitější vlastnost druhého mozku: musí být rychle dostupný. Pokud se k tomu dostaneš za 10 vteřin, použiješ to. Pokud za 3 minuty hledání, nepoužiješ to nikdy.",
      "Dnes si nastavíš základ — jedno místo, kam všechno půjde. Nemusí být dokonalé. Musí existovat.",
    ],
    taskIntro: "Vyber místo pro svůj druhý mozek a nastav základ:",
    taskItems: [
      "Vyber nástroj: Notion, Google Docs, Apple Notes, Obsidian — jakýkoli, který denně otevíráš",
      "Vytvoř dokument nebo stránku nazvanou \u201EAI — šablony a výstupy\"",
      "Vlož tam tři věci z challenge: jednu šablonu, jeden dobrý prompt, jeden výstup, který chceš znovu použít",
    ],
    taskType: "ol",
    taskFallback: `Pokud nevíš, co do dokumentu vložit, tady je příklad struktury:

📁 AI — šablony a výstupy

✅ Šablona: Příprava agendy schůzky
"Napiš agendu pro 45minutovou schůzku na téma [téma]. Účastníci: [kdo]. Výstup: 4–5 bodů s časovými bloky."

✅ Oblíbený prompt: Iterace výstupu
"Přepiš předchozí výstup takto: zkrať na 3 klíčové body, formálnější tón, přidej konkrétní příklad."

✅ Uložený výstup:
[vlož výstup z challenge, který chceš znovu použít]`,
    taskTip: "Cíl: jedno místo, rychle dostupné. Není třeba složitá struktura — složitá struktura brání používání.",
    teaser: "Zítra: Postavíš základ svého mini knowledge base — tak, aby výstupy z AI nezmizely.",
  },

  {
    day: 24,
    title: "Jeden dokument, který změní, jak pracuješ s AI.",
    subject: "Mini knowledge base — kontext, který používáš znovu a znovu.",
    preheader: "Jednou napsat. Použít stokrát.",
    teze: "Jednou napsat kontext o sobě a své práci — pak ho použít stokrát, pokaždé s lepšími výsledky.",
    concept: [
      "Je jedna věc, kterou AI znovu a znovu potřebuje, a ty ji znovu a znovu opakuješ: kontext o tobě a tvé práci.",
      "Kdo jsi, co děláš, pro koho, jak komunikuješ, jaká jsou tvoje typická témata. Každý nový chat začíná od nuly — a bez kontextu dostáváš generické výstupy.",
      "Řešení je jednoduché: napiš si jednou dobře svůj pracovní kontext. Ulož ho. A příště ho jen zkopíruj na začátek konverzace. Za 10 vteřin máš AI, která \u201Ezná\" tebe.",
      "Co do pracovního kontextu patří:",
      ["Tvoje role a obor — konkrétně, ne obecně (\u201Eproduktový manažer v B2B SaaS\" ne \u201Epracuji v IT\")", "Tvoje typické úkoly — 3–5 věcí, které děláš pravidelně", "Tvoje cílová skupina — komu výstupy slouží (klienti, tým, vedení...)", "Preferovaný tón komunikace — formální, přátelský, technický, přímý", "Co AI nesmí dělat — co je v tvé práci citlivé nebo co nechceš ve výstupech"],
      "Druhá část mini knowledge base: opakující se prompty. Každý prompt, který za challenge fungoval, ulož. Příště ho dostaneš za 10 vteřin. Tak se buduje osobní nástroj, ne jen znalost.",
      "Cílem dnešního dne je mít dokument, který existuje a funguje. Ne dokonalou databázi — jen použitelný základ.",
    ],
    taskIntro: "Napiš svůj pracovní kontext — základ mini knowledge base:",
    taskItems: [
      "Role a obor: kdo jsi a v jakém kontextu pracuješ (2–3 věty)",
      "Typické úkoly: 3–5 věcí, které děláš pravidelně",
      "Tón a omezení: jak chceš, aby AI komunikovala — a co nesmí dělat",
      "Ulož jako první dokument do svého druhého mozku z D22",
    ],
    taskType: "ol",
    taskPrompt: "Pracuji jako [role] v [obor nebo typ firmy]. Moje typické úkoly jsou: [3–5 úkolů]. Výstupy tvoří pro [koho]. Preferovaný tón: [přátelský/formální/přímý]. Nechci v výstupech: [co nechceš].",
    taskTip: "Tento dokument zkopíruj vždy na začátek konverzace s AI — okamžitě dostaneš relevantnější výstupy.",
    teaser: "Zítra: Jak poznat, že AI ti skutečně pomáhá — ne pocitem, ale konkrétně.",
  },

  {
    day: 25,
    title: "Cítíš, že AI pomáhá. Ale umíš to změřit?",
    subject: "Jak poznat, že AI ti skutečně pomáhá.",
    preheader: "Ne \u201EAI mi pomáhá\". Ale proč, kde a o kolik.",
    teze: "Ne 'AI mi pomáhá' — ale kde přesně, jak moc a co by trvalo bez ní. Rozdíl je měřitelný.",
    concept: [
      "Říkat \u201EAI mi pomáhá\" je jako říkat \u201Esport mi dělá dobře\". Je to pravda — ale bez konkrétnějšího pohledu nevíš, co zopakovat a co změnit.",
      "Čtyři signály, že AI ti opravdu přidává hodnotu:",
      ["Výstup, který by bez AI vznikl těžce nebo vůbec — ne jen rychleji", "Opakující se úkol, který teď trvá výrazně méně a výsledek je stejně dobrý", "Iterace, která přinesla výsledek, co by jinak trval hodinu ručního přepisování", "Nový pohled nebo nápad, který by bez AI nevznikl rychle"],
      "Čtyři signály, že AI ti práci přidává nebo neutralizuje:",
      ["Kontrola každé věty výstupu — pokud kontroluješ 100 %, ušetříš jen psaní, ne přemýšlení", "Opravuješ výstup víc, než trvalo napsat ho ručně", "Výsledek vyžaduje tak velký kontext v promptu, že je celý proces pomalejší", "Stres ze zadávání AI místo radosti ze spolupráce"],
      "Jak měřit (jednoduše, ne složitě): jednou za týden napiš tři věci, kde AI přidala hodnotu — konkrétní výstup, konkrétní úspora, konkrétní zlepšení. Tenhle malý záznam ti za dva týdny ukáže jasný vzorec.",
      "Proč na tom záleží? Protože bez zpětné vazby se zvyk nezvyšuje — kolísá. A cílem challenge není vědět víc o AI, ale pracovat s ní líp. Zpětná vazba je klíč.",
    ],
    taskIntro: "Retrospektiva: projdi minulé tři dny a zapiš si:",
    taskItems: [
      "Jeden konkrétní případ, kde AI přidala skutečnou hodnotu — co to bylo a čím to bylo jiné",
      "Jeden případ, kde AI práci nepomohla nebo ji zkomplikovala — proč si to myslíš",
      "Co z toho by šlo příště udělat jinak",
    ],
    taskType: "ol",
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Kde jsi na AI závislý rozumně — a kde jenom ze zvyku. Mapa, která ukáže, kam dál.",
  },

  {
    day: 26,
    title: "Kde se bez AI zastavíš — a kde ne.",
    subject: "Mapa závislosti na AI: kde ti pomáhá a kde si zvykáš zbytečně.",
    preheader: "Den bez AI byl experiment. Tenhle den je závěr.",
    teze: "Jeden den bez AI ukázal, co ti chybí. Teď se podívej na celý vzorec — kde jsi na AI závislý rozumně a kde jenom ze zvyku.",
    concept: [
      "V D21 jsi zkusil jeden den záměrně bez AI a zapsal, kde ti chyběla a kde ne. Dnes ten poznatek posuneme dál.",
      "Jeden den ti řekl, co cítíš. Ale pocit se mění. Dnešní otázka je jiná: kdyby AI zmizela na celý týden — co by se opravdu zastavilo? Co bys musel dělat jinak? A kde bys zjistil, že jsi ji zapojoval ze zvyku, ne z nutnosti?",
      "Tři kategorie AI závislosti — a co s nimi dělat:",
      [
        "Zdravá závislost: úkoly, kde AI šetří tolik času nebo energie, že bez ní by to bylo znatelně horší — tady je cílem mít šablonu nebo workflow, aby tato závislost nebyla na improvizaci, ale na systému",
        "Zbytečná závislost: úkoly, kde AI zapojuješ automaticky, ale výsledek je podobný bez ní — tady je otázka: proč ji používáš? Zvyk? Nejistota? Nebo opravdu pomáhá?",
        "Nevyužitá příležitost: úkoly, kde AI nepoužíváš, ale mohla by výrazně pomoct — tady je prostor pro novou šablonu nebo nový návyk"
      ],
      "Proč je tohle jiné než D21: v D21 jsi pozoroval live. Dnes analyzuješ vzorec. Jeden den ti dal data — dnes z nich vyvodíš závěr.",
      "Čtvrtý týden se blíží ke konci. Zbývají čtyři dny — a jsou to dny, které rozhodnou o tom, jestli to, co challenge přinesla, zůstane nebo zmizí.",
    ],
    taskIntro: "Projdi svůj pracovní vzorec z posledního týdne a zapiš:",
    taskItems: [
      "Dvě místa, kde je tvá závislost na AI zdravá — a co by ji podpořilo (šablona, uložený prompt)",
      "Jedno místo, kde ji používáš ze zvyku, ne z nutnosti — co bys mohl dělat jinak",
      "Jedna příležitost, kde AI zatím nepoužíváš, ale mohla by výrazně pomoct",
    ],
    taskType: "ol",
    taskTip: "Ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Jak si vybudovat AI návyk, který přežije motivaci.",
  },

  {
    day: 27,
    title: "Vědět nestačí. Návyk je jiná věc.",
    subject: "Budování AI návyku — jak ho zabudovat do dne.",
    preheader: "Motivace přijde a odejde. Návyk zůstane.",
    teze: "Vědomost o AI přijde a odejde s motivací — návyk navázaný na den zůstane i bez ní.",
    concept: [
      "Vědomosti o AI zmizí, pokud za nimi nestojí návyk. A návyk nevznikne z motivace — motivace kolísá. Návyk vzniká z rutiny.",
      "Věda o návycích říká, že tři prvky dělají chování trvalým: spouštěč (cue), rutina (routine), a odměna (reward). To platí přesně i pro AI.",
      ["Spouštěč: konkrétní moment, který ti připomene, že AI může pomoci — ráno při otevření počítače, před schůzkou, při začátku psaní", "Rutina: konkrétní akce, ne obecný cíl — \u201Eotevřu AI a napíšu prompt pro dnešní report\" ne \u201Ebudu víc používat AI\"", "Odměna: výstup, který opravdu použiješ — konkrétní hodnota, ne jen \u201Ebyl jsem produktivní\""],
      "Nejčastější chyba: velký ambiciózní plán. \u201EBudu každý den používat AI na deset věcí\" nevydrží. \u201EKaždé pondělí ráno napíšu týdenní priority s AI\" vydrží.",
      "Dobrý AI návyk je malý, konkrétní a vázaný na věc, kterou děláš tak jako tak. Přidej AI k něčemu, co děláš každý týden — a nemusíš budovat novou rutinu od nuly.",
      "Klíčová otázka: co děláš každý týden, co se dá s AI udělat lépe? Najdi tu jednu věc. Přidej k ní AI. Opakuj čtyři týdny. Pak přidej druhou věc.",
      "Zítra se podíváme na ranní rituál — každodenní moment, který nastaví celý den. Ale i bez ranního rituálu: jeden týdenní návyk stačí k tomu, aby AI zůstala v tvém pracovním životě trvale.",
    ],
    taskIntro: "Navrhni svůj týdenní AI návyk:",
    taskItems: [
      "Vyber jednu věc, kterou děláš každý týden — a kde by AI pomohla",
      "Napiš konkrétní rutinu: v jaký den, co uděláš, jaký prompt použiješ",
      "Nastav si připomínku — kalendář, sticky note nebo cokoli, co ti připomene první měsíc",
    ],
    taskType: "ol",
    taskTip: "Týdenní návyk je konkrétní a zvládnutelný. Nezačínej od \u201Ebudu AI používat víc\u201C — začni od \u201Ekažd\u00E9 pond\u011Bl\u00ED r\u00E1no nap\u00ED\u0161u p\u0159ehled t\u00FDdne s AI\u201C.",
    teaser: "Zítra: Nastavíš si svůj denní ranní rituál — pět minut, které nastaví celý den.",
  },

  {
    day: 28,
    title: "Pět minut ráno, které změní celý den.",
    subject: "Nastav si svůj denní AI rituál.",
    preheader: "Jeden moment každý den je víc než hodina jednou za týden.",
    teze: "Pět minut ráno s AI nastaví kontext pro celý den — konzistentně, ne dramaticky.",
    concept: [
      "Nejsilnější AI návyky nejsou velké. Jsou malé, pravidelné a vázané na začátek dne.",
      "Ranní AI rituál — pět minut ráno — dokáže nastavit kontext pro celý den, identifikovat priority, a zahájit nejdůležitější práci dřív, než se roztrhne vak emailů a notifikací.",
      "Jak může vypadat pětiminutový ranní AI rituál:",
      ["Agenda dne: \u201EMám naplánováno toto. Napiš mi tři priority a co připravit pro každou schůzku.\"", "Psaní: \u201EDnes potřebuji napsat [text]. Napiš mi draft, začnu od toho.\"", "Příprava: \u201EDnes mám schůzku s [klientem] o [tématu]. Napiš mi 5 otázek.\"", "Reflexe: \u201ECo se stalo včera? [krátký přehled] Napiš mi jedno doporučení na dnešek.\""],
      "Rituál nemusí dělat vše. Stačí jedna věc — ta, která ti dává největší return na 5 minut. Za měsíc je to 20 rituálů. Za rok 240 klidných a připravených ráno.",
      "Neboj se ho upravovat. Rituál, který perfektně funguje v pondělí, nemusí fungovat ve čtvrtek. Dobrý rituál je flexibilní — má pevnou strukturu, ale proměnlivý obsah.",
      "Tohle je předposlední den challenge. Zítra bude závěr. Dnes si nastavíš věc, která ti zůstane — i po skončení challenge.",
    ],
    taskIntro: "Nastavení ranního AI rituálu — konkrétně:",
    taskItems: [
      "Vyber jednu věc, pro kterou chceš AI každé ráno použít — agenda, psaní, příprava nebo reflexe",
      "Napiš si konkrétní prompt, který budeš opakovat (ulož do svého druhého mozku z D22)",
      "Nastav si připomínku na 5–7 minut ráno po dobu příštích tří týdnů — první tři týdny jsou klíčové",
    ],
    taskType: "ol",
    taskPrompt: "Dnes mám naplánováno: [krátký přehled]. Největší priorita je: [co je nejdůležitější]. Napiš mi: 1) tři prioritní úkoly pro dnešek, 2) co připravit pro nejdůležitější schůzku nebo úkol.",
    taskTip: "Prompt si ulož do svého druhého mozku — a nastav si ho jako \u201Eranní rituál\".",
    teaser: "Zítra: Poslední den. Závěr, reflexe — a co tě čeká dál.",
  },

  // ─── D28: Závěr ───────────────────────────────────────────────────────────────

  {
    day: 29,
    title: "Třicet dní. Co ti zůstalo — a co tě čeká dál.",
    subject: "Závěr Basic challenge — tady je, co si vezmeš.",
    preheader: "Konec základů. Začátek systémů.",
    teze: "Pravidelný zvyk s AI je víc než rok příležitostného zkoušení — a tenhle challenge byl jeho základ.",
    concept: [
      "Challenge je téměř za tebou.",
      "Za sebou máš základy: AI jako leverage, ne jen rychlost. Anatomii dobrého promptu. Práci s kontextem. Iteraci. Šablony. Opakující se práci. Denní rituál. A — nejdůležitější — způsob přemýšlení o práci, který se změní, i když AI přestaneš používat.",
      "Co challenge přinesla:",
      ["Dobrý prompt = role + úkol + kontext + formát — a proč každá část záleží", "Iterace jako způsob práce — první výstup je základ, ne finální produkt", "Opakující se práce jako signál pro šablonu nebo workflow", "Kdy AI věřit a kdy ověřit — calibrated trust jako klíčová dovednost", "Druhý mozek — kde ukládat výstupy, aby nezmizely", "AI návyk jako rutina, ne motivace — malý, pravidelný, vázaný na den"],
      "Co přichází v Advanced verzi challenge:",
      ["3C framework: Capture, Clean, Connect — systém pro práci s informacemi a znalostmi", "PACT framework: Projects, Agents, Context, Tools — jak AI zapojit do projektové práce", "Pět superschopností, které AI spoluprací získáváš — Perception, Intelligence, Memory, Creation, Connection", "Leverage na úrovni systému — workflow, týmové nasazení, end-to-end procesy"],
      "Basic challenge tě postavila na nohy. Advanced challenge tě naučí běžet.",
      "Ale teď — jeden krok ještě zbývá. Zítra si odpovíš na jednu otázku, která rozhoduje o tom, jestli tohle vydrží.",
    ],
    taskIntro: "Reflexe celé challenge — tři konkrétní věci:",
    taskItems: [
      "Tři největší poznatky z celé challenge — konkrétní, ne obecné",
      "Jedno místo, kde AI změnila způsob, jak pracuješ — konkrétní výstup nebo rutina",
      "Jeden cíl pro příštích 30 dní — co budeš dělat jinak s AI, specificky",
    ],
    taskType: "ol",
    taskTip: "Reflexi ulož do svého druhého mozku — za 3 měsíce si to přečti a uvidíš, jak daleko jsi.",
    teaser: "Zítra: Poslední den. Jedna otázka, která rozhoduje o tom, jestli tohle vydrží.",
  },

  {
    day: 30,
    title: "Kdo jsi teď jako AI uživatel? Jeden výstup, který zůstane.",
    subject: "Identity statement — a nový výchozí bod.",
    preheader: "Konec challenge je začátek způsobu práce.",
    teze: "Challenge končí. Způsob práce začíná — a identity statement je kotva, která ho udrží.",
    concept: [
      "Poslední den není o učení. Je o pojmenování toho, co už víš.",
      "Výzkum říká, že jedním z největších prediktorů dlouhodobé změny chování je to, jestli si člověk dokáže říct: 'Jsem někdo, kdo tohle dělá.' Ne 'snažím se to dělat'. Ale: 'Tohle je součást toho, jak pracuju.'",
      "Dnes si napíšeš AI identity statement — jednu větu nebo krátký odstavec, který popisuje, kdo jsi teď jako AI uživatel. Konkrétně, ne obecně.",
      "Čtyři otázky, které ti pomohou ho napsat:",
      [
        "Kde AI ve své práci používám pravidelně a s dobrými výsledky?",
        "Co dělám s AI jinak než před challengí — konkrétně?",
        "Kde vím, že AI věřit — a kde jsem se naučil ověřovat?",
        "Jak bych to popsal kolegovi za 30 vteřin, pokud by se zeptal: 'Jak pracuješ s AI?'"
      ],
      "Proč na tom záleží: identity statement není sebechvála. Je to kotva. Věta, ke které se vrátíš za tři měsíce a připomeneš si, kdo jsi.",
    ],
    taskIntro: "Napiš svůj AI identity statement — jednu větu nebo krátký odstavec:",
    taskItems: [
      "Odpověz na čtyři otázky výše — nemusí být perfektní, jen konkrétní",
      "Z odpovědí napiš 2–3 věty: kdo jsi teď jako AI uživatel a jak to ovlivňuje tvou práci",
      "Ulož ho na místo, kde ho za 3 měsíce uvidíš — Notion, poznámky, calendar reminder",
    ],
    taskType: "ol",
    taskTip: "Sdílej identity statement s někým, kdo tě zná — výzkum ukazuje, že vyřčená nebo sdílená identita se drží dvakrát silněji.",
  },
];
