import type { ChallengeDay } from "./types";

export const challengeDataEN: ChallengeDay[] = [
  {
    day: 0,
    title: "This is not an AI challenge. This is an upgrade to how you work.",
    subject: "It starts today. Here is how the challenge works.",
    preheader: "28 days, 5–7 minutes a day. One real shift in how you work.",
    concept: [
      "AI is everywhere right now. New tools, new features, new promises. And that is exactly why it is easy to end up just trying more and more things without really changing how you work.",
      "This challenge was created to help you do the opposite.",
      "The goal is not to learn as many AI tools as possible. The goal is to start using AI practically, regularly, and in a way that genuinely makes your work easier.",
      "Each day should take about 5–7 minutes. Each day, you should take away something useful: a new perspective on your work, one small practical step, a concrete output, or a simple improvement to something you already do.",
      "Step by step, you are not just \"playing with AI.\" You are building better habits, less friction in your work, your own prompts, templates, and workflows — and most importantly, a new way of thinking about what really has to be done manually.",
      "The point of this challenge is not to complete everything. The point is to move a little further every day.",
    ],
    taskIntro: "Write down 3 things you do repeatedly by hand in your work or daily routine.",
    taskItems: [],
    taskType: "text",
    teaser: "Why you are not paid for work — you are paid for outcomes. And how that changes everything about working with AI.",
  },
  {
    day: 1,
    title: "You are not paid for work. You are paid for the outcome.",
    subject: "You are not paid for work. You are paid for outcomes.",
    preheader: "One shift in thinking that changes everything else.",
    concept: [
      "When work piles up, most people automatically focus on one thing: how to get everything done.",
      "But this is exactly where the difference between normal work mode and an AI-first approach starts to show.",
      "The point is not just to do things faster. First, you need to pause and ask yourself what outcome you are actually trying to achieve.",
      "Sometimes you are not really paid for writing the email, preparing the deck, creating the document, or spending an hour doing research. You are paid because someone gets the right information, a decision gets made, a project moves forward, or something gets prepared clearly and effectively.",
      "As soon as you start thinking more about the outcome than about the task itself, it becomes much easier to see what can be done more simply, can be delegated to AI, does not have to be created from scratch, or maybe does not need to be done at all.",
    ],
    taskIntro: "Pick one task you are working on today and write down:",
    taskItems: ["How the task sounds right now", "What outcome you actually want from it"],
    taskType: "ol",
    teaser: "Anything you do for the second time should not start from scratch. Here is what to do instead.",
  },
  {
    day: 2,
    title: "Anything you do for the second time should not start from scratch.",
    subject: "If you are doing it twice, stop starting from scratch.",
    preheader: "Repetition is a signal — not to go faster, but to build a template.",
    concept: [
      "A lot of work does not look difficult at first. But small repeated tasks often drain the most energy.",
      "When something repeats, it is a signal. Not a signal that you need to work faster. A signal that the task should probably have a template, a process, a prompt, or at least a better starting point.",
      "AI is strongest exactly where work repeats. Not because it will do everything perfectly. But because it helps you stop starting over every single time.",
    ],
    taskIntro: "Choose one recurring task and ask yourself:",
    taskItems: ["What repeats in this task?", "What is almost always the same?", "What could be prepared in advance?"],
    taskType: "ul",
    teaser: "Stop using AI like a search engine. It is a collaborator — and that difference changes everything.",
  },
  {
    day: 3,
    title: "AI is not a tool. AI is a collaborator.",
    subject: "Stop using AI as a search engine. Try this instead.",
    preheader: "The real shift does not come when AI answers. It comes when you assign it work.",
    concept: [
      "Most people still use AI like a slightly smarter search engine. They ask something, get an answer, and that is where it ends.",
      "But the real shift begins when you stop treating AI like a place where you type something in and start treating it like someone you assign work to.",
      "When you ask a question, you get an answer. When you assign work, you can get an outcome.",
    ],
    taskIntro: "Rewrite one normal prompt into this structure:",
    taskItems: ["Role", "Task", "Context", "Output"],
    taskType: "ul",
    teaser: "A prompt is not a question. It is a work brief — and that difference changes the quality of the output completely.",
  },
  {
    day: 4,
    title: "A prompt is not a question. It is a work brief.",
    subject: "Your prompts are questions. They should be briefs.",
    preheader: "Same principle as delegating to a person. The clearer the brief, the better the result.",
    concept: [
      "Many people think being good at AI means knowing secret formulas or complicated prompt tricks. In reality, one much simpler skill matters more: knowing how to brief work well.",
      "Just like with people. If you say only \"write something for LinkedIn,\" you will probably get something vague. But if you explain the audience, the main idea, the tone, and the desired format, the result changes completely.",
    ],
    taskIntro: "Take one old prompt and add:",
    taskItems: ["role", "goal", "context", "constraints", "output format"],
    taskType: "ul",
    teaser: "The most important question is not \"how do I do this faster?\" It is \"do I even need to be the one doing this?\"",
  },
  {
    day: 5,
    title: "Do not optimize speed. Optimize leverage.",
    subject: "Forget speed. Optimize this instead.",
    preheader: "Leverage means thinking about what you actually need to do yourself — and what you do not.",
    concept: [
      "The most important question is not: \"How can I do this faster?\" It is: \"Do I need to be the one doing this?\"",
      "Leverage means you do not do everything yourself just because you are capable of doing it. Instead, you think about what should stay with you, where AI should help, and what should no longer move manually from beginning to end.",
    ],
    taskIntro: "Take your task list for today and divide it into 3 groups:",
    taskItems: ["Only me", "Me + AI", "Mostly AI"],
    taskType: "ol",
    teaser: "Why perfection kills automation — and how to stop waiting for the \"right moment\" to start.",
  },
  {
    day: 6,
    title: "Perfection kills automation.",
    subject: "Perfection is slowing you down. Let's fix that today.",
    preheader: "You do not need a perfect system. You need a first usable version.",
    concept: [
      "You do not need a perfect system right away. You need a first usable version.",
      "Maybe it is just a simple template, one saved prompt, a short outline, a basic process, or a working draft of something you will improve later.",
      "The goal is not to make everything perfect today. The goal is to make sure that tomorrow something does not have to be created from scratch again.",
    ],
    taskIntro: "Choose one recurring thing and create the first usable version of something for it:",
    taskItems: ["a template", "a prompt", "a structure", "or a simple working process"],
    taskType: "ul",
    teaser: "Today you will build your first mini AI system. It is simpler than it sounds.",
  },
  {
    day: 7,
    title: "Your first mini AI system.",
    subject: "Day 7: Build your first mini AI system.",
    preheader: "3 steps, one output, zero chaos. This is how a mini system works.",
    concept: [
      "AI is strongest when it becomes part of a small workflow.",
      "For example: call notes → summary → follow-up email. Or: idea → outline → draft text. Or: task list → priorities → plan for the day.",
    ],
    taskIntro: "Choose one activity with at least 2–3 connected steps and write down:",
    taskItems: ["What the input is", "What AI can do with it", "What the final output is"],
    taskType: "ol",
    teaser: "Blank page? AI will write the first version of anything for you — no more staring at an empty screen.",
  },
  {
    day: 8,
    title: "AI as a copywriter.",
    subject: "Never start from a blank page again.",
    preheader: "AI writes the first version. You just refine it. That is writing with AI.",
    concept: [
      "One of the fastest types of relief AI can bring is in writing. Not because it should write everything for you without thought. But because you no longer have to start from a blank page.",
      "You bring the intention, the context, the main idea, and the tone. AI helps you generate a first version, variations, or a structure to build from.",
    ],
    taskIntro: "Take one piece of writing you need today and ask AI to prepare 3 versions:",
    taskItems: ["a shorter one", "a more persuasive one", "a more natural one"],
    taskType: "ul",
    teaser: "Research does not have to be exhausting. Here is how AI becomes your first layer of orientation.",
  },
  {
    day: 9,
    title: "AI as a research assistant.",
    subject: "Research without the rabbit hole.",
    preheader: "Too many sources, too many options, no idea where to start? AI can fix that.",
    concept: [
      "Research can be surprisingly exhausting. Often not because the problem itself is so difficult, but because there are too many sources, too many options, and you do not know where to begin.",
      "AI can help as a first layer of orientation: break a topic into important areas, suggest a comparison framework, pull out key questions, or prepare a short summary.",
    ],
    taskIntro: "Choose one topic and ask AI to prepare:",
    taskItems: ["the key areas to look at", "a comparison framework", "the questions you should ask", "what you should verify separately"],
    taskType: "ul",
    teaser: "When your head is full of noise, AI can help you structure it. Not by giving answers — by helping you think.",
  },
  {
    day: 10,
    title: "AI as a thinking partner.",
    subject: "When your head is full of noise, try this.",
    preheader: "AI as a thinking partner — not just an answer machine.",
    concept: [
      "Sometimes you are not sitting with a clear output in front of you, but with a mess in your head. That is exactly when AI can be surprisingly useful.",
      "Not as an expert who gives you the one correct answer. But as a partner that helps you sort your thoughts, name the real problem, separate the important from the less important, and suggest a reasonable next step.",
    ],
    taskIntro: "Choose one topic that still feels unclear. Dump it into AI and ask it to help you:",
    taskItems: ["split it into blocks", "name the main problem", "suggest 2–3 possible directions", "identify the best next step"],
    taskType: "ul",
    teaser: "Making decisions is hard. AI can help you see the options more clearly — without deciding for you.",
  },
  {
    day: 11,
    title: "AI as a decision partner.",
    subject: "AI as a decision partner — not just an answer machine.",
    preheader: "AI does not decide for you. It helps you see the options more clearly.",
    concept: [
      "A lot of work is not about creating something. A lot of work is about deciding.",
      "AI does not decide for you. It helps you see the options more clearly: clarify the options, name the pros and cons, show the trade-offs, highlight the risks.",
    ],
    taskIntro: "Choose one real decision. Give AI:",
    taskItems: ["the options you are choosing between", "what you want to achieve", "what is limiting you", "what you are worried about"],
    taskType: "ul",
    teaser: "What if every meeting came with automatic notes and clear next steps? That is today.",
  },
  {
    day: 12,
    title: "AI as a meeting assistant.",
    subject: "What if every meeting had automatic notes?",
    preheader: "Meetings drain energy. Missing summaries and next steps waste even more time. AI fixes both.",
    concept: [
      "Meetings do not always take the most time. But they often take the most energy. And the biggest problem is what is missing afterward: a short summary, a clear decision, and next steps.",
      "AI can quickly turn notes or a transcript into: a clear summary, an action list, open questions, and a follow-up message.",
    ],
    taskIntro: "Take the last meeting, call, or set of notes you have and ask AI to create:",
    taskItems: ["a short summary", "the key decisions", "the next steps", "a short follow-up"],
    taskType: "ul",
    teaser: "Too many tasks, not enough clarity. How AI helps you set priorities that actually work.",
  },
  {
    day: 13,
    title: "AI as a personal productivity coach.",
    subject: "Too many tasks. Here is how AI helps you prioritize.",
    preheader: "Overload is not a tool problem. It is a priority problem. And AI can help with that.",
    concept: [
      "Productivity today often looks less like a lack of tools and more like overload: too many tasks, too many things in your head, too many decisions.",
      "AI can act like an external brain that helps you: clarify priorities, reduce chaos, postpone lower-value things, and create a realistic plan.",
    ],
    taskIntro: "Take your task list for today or tomorrow and add:",
    taskItems: ["how much time you really have", "how much capacity you realistically have", "what truly matters", "what is just \"would be nice\""],
    taskType: "ul",
    teaser: "You will set up your personal AI copilot — the first version of how you will work with AI every day.",
  },
  {
    day: 14,
    title: "Your personal AI copilot.",
    subject: "Your personal AI copilot — first version.",
    preheader: "Today you design how you want to work with AI every day. Simpler than it sounds.",
    concept: [
      "Individual AI roles are useful. But the real shift comes when you start turning them into your own system.",
      "At the beginning, it is enough to clarify: what you use AI for most often, where it truly saves you time, where it helps you think better, and which prompts or processes you want to save.",
    ],
    taskIntro: "Write down the first version of your personal AI copilot setup:",
    taskItems: ["What do I use AI for most often?", "Where does it save me the most time?", "Where does it help me do better work?", "Which 3–5 prompts or workflows do I want to save?", "What do I want my default way of working with AI to be?"],
    taskType: "ul",
    teaser: "Do not automate everything — but definitely automate these. How to find the right candidates.",
  },
  {
    day: 15,
    title: "Do not automate everything. Automate what creates the biggest impact.",
    subject: "Do not automate everything. Automate the right things.",
    preheader: "The goal is not to automate as much as possible. It is to choose what gives back the most.",
    concept: [
      "The goal is not to automate as much as possible. The goal is to automate what gives you back the most time, energy, or attention.",
      "The best candidates are usually tasks that are: repetitive, predictable, slightly annoying, time-consuming, and built around a clear input and output.",
    ],
    taskIntro: "Look at the tasks that have appeared most often during this challenge so far. For each one, ask:",
    taskItems: ["How often does it happen?", "How much time does it take?", "How mentally draining is it?", "How predictable is it?"],
    taskType: "ul",
    teaser: "Forget the apps. First, understand the workflow — then choose the tools.",
  },
  {
    day: 16,
    title: "Start thinking in workflows, not tools.",
    subject: "Forget the apps. Understand the workflow first.",
    preheader: "Choosing a tool is the second step. Here is what comes first.",
    concept: [
      "Before choosing an app, you need to understand the flow of the work itself: what the trigger is, what the input is, what AI or the system should do, and what the output should be.",
      "That is the no-code mindset.",
    ],
    taskIntro: "Choose one recurring activity and describe it in this structure:",
    taskItems: ["Trigger", "Input", "Processing", "Output"],
    taskType: "ul",
    teaser: "Communication that does not start from zero every time. The AI-first approach to repetitive messages.",
  },
  {
    day: 17,
    title: "Communication does not need to start from zero every time.",
    subject: "Stop writing the same types of messages from scratch every time.",
    preheader: "Reusable structure + human finishing. That is AI-first communication.",
    concept: [
      "A big part of communication at work is repetitive: similar replies, follow-ups, confirmations, and summaries.",
      "AI-first communication is not robotic communication. It is a reusable structure plus human finishing.",
    ],
    taskIntro: "Choose one type of message you write often and create your first reusable base for it:",
    taskItems: ["an outline", "a template", "or a prompt"],
    taskType: "ul",
    teaser: "One idea, three outputs. This is what content leverage actually looks like.",
  },
  {
    day: 18,
    title: "One good idea does not need to end in just one output.",
    subject: "One idea, three outputs. This is what leverage looks like.",
    preheader: "Stop inventing new things. Start getting more out of what you already have.",
    concept: [
      "One strong idea can become a post, a short newsletter, part of a website paragraph, an FAQ, a video outline, or the basis for more content later.",
      "AI helps you stop switching into \"I need to invent something new again\" mode and instead move into \"how do I get more out of what I already have\" mode.",
    ],
    taskIntro: "Take one existing content input and ask AI to turn it into at least 3 different outputs.",
    taskItems: [],
    taskType: "text",
    teaser: "The biggest chaos does not come from the work itself. It comes between the steps. And AI can help there.",
  },
  {
    day: 19,
    title: "A lot of chaos does not come from the work itself. It comes between the steps.",
    subject: "Where the chaos that slows you down actually comes from.",
    preheader: "The problem is usually not the work itself. It is in the gaps, handoffs, and transitions.",
    concept: [
      "Inefficiency often appears not in the work itself, but between it: between a meeting and execution, between a person and a system, between an idea and an output.",
      "AI can help improve the handoff structure: what should be summarized, what should be recorded, what the next step is, and who should take it.",
    ],
    taskIntro: "Choose one place where information often gets lost and write down:",
    taskItems: ["What always needs to be passed on?", "What should be briefly summarized?", "What should be saved into the system?", "What is the clear next step?"],
    taskType: "ul",
    teaser: "Data alone is not the answer. Understanding is. And AI helps you get there faster.",
  },
  {
    day: 20,
    title: "Data alone does not help. What helps is what you understand from it.",
    subject: "How to get what you actually need from your data.",
    preheader: "Data without interpretation is just noise. AI helps you find the pattern.",
    concept: [
      "Data helps only when it turns into a pattern, an insight, a decision, or a next step.",
      "AI can help you: pull out recurring themes, identify what matters most, notice what is surprising, and suggest what to do next.",
    ],
    taskIntro: "Take one real data or text input and ask AI:",
    taskItems: ["What is repeating here?", "What is most important here?", "What should I do next based on this?"],
    taskType: "ul",
    teaser: "Connected steps change everything. Today we describe how to build them.",
  },
  {
    day: 21,
    title: "Real progress begins when the steps start connecting.",
    subject: "When the steps start connecting, everything changes.",
    preheader: "One good prompt is not enough. The real relief comes when the steps flow into each other.",
    concept: [
      "The biggest relief often does not come from one good prompt. It comes when the steps begin to connect in a way that means you no longer have to keep everything in your head and move it forward manually.",
    ],
    taskIntro: "Choose one area and describe a simple chain:",
    taskItems: ["What is the input?", "What does AI do?", "What gets stored, and where?", "Where does human control remain?", "What is the final output?"],
    taskType: "ul",
    teaser: "AI transformation at a company level does not start with a tool. It starts with work. And that is exactly where to begin.",
  },
  {
    day: 22,
    title: "AI in a company does not start with a tool. It starts with work.",
    subject: "AI at work does not start with a tool.",
    preheader: "Where to actually start AI transformation — and where most companies get it wrong.",
    concept: [
      "AI transformation does not start with technology. It starts with work itself.",
      "With the places where there is: repetitive manual work, unnecessary forwarding of information, lost know-how, slow decision-making, or work with low added value.",
    ],
    taskIntro: "Choose one team, department, or part of a company and ask:",
    taskItems: ["Where does the most repetitive manual work happen?", "Where is context or know-how getting lost?", "Where are people spending time on work that does not create the highest value?", "Where could a relatively small change create quick impact?"],
    taskType: "ul",
    teaser: "Every team needs different AI use cases. How to find them and where to start.",
  },
  {
    day: 23,
    title: "Every team needs different AI use cases.",
    subject: "Why every team needs different AI use cases.",
    preheader: "One-size-fits-all does not work. AI adoption needs to start from real work.",
    concept: [
      "Every team works differently. It has different goals, different friction, different rhythm, and different types of tasks. That is why it makes more sense to find AI use cases based on the actual role and the actual work.",
      "Use cases often fall into three categories: AI drafts something, AI summarizes something, AI becomes part of a workflow.",
    ],
    taskIntro: "Choose one specific team and write down:",
    taskItems: ["What do they do often?", "What slows them down the most?", "What keeps repeating?", "What could AI help draft, summarize, or speed up?"],
    taskType: "ul",
    teaser: "People are not convinced by technology. They are convinced by value. How to speak the language that actually works.",
  },
  {
    day: 24,
    title: "People are not convinced by technology. They are convinced by value.",
    subject: "How to convince people who are not sold on AI yet.",
    preheader: "Stop talking about AI as technology. Talk about it as work.",
    concept: [
      "Most people do not need to hear that AI is the future. They need to understand what it can concretely make easier for them right now.",
      "That is why it matters to talk about AI in the language of work, not the language of tools.",
    ],
    taskIntro: "Choose one specific role or person and ask:",
    taskItems: ["What might this person be worried about?", "What slows them down most in their work?", "Where could AI create a fast and visible benefit for them?", "What small quick win would make sense to show first?"],
    taskType: "ul",
    teaser: "A few simple governance rules that will save you problems and give people confidence.",
  },
  {
    day: 25,
    title: "Without rules, there is chaos. With too many rules, nothing happens.",
    subject: "Simple AI rules that save problems before they start.",
    preheader: "Good governance does not put people off. It gives them confidence they are doing it right.",
    concept: [
      "Good governance should not discourage people. It should help them use AI more safely, more sensibly, and with more confidence.",
      "At the beginning, a few simple rules are often enough: what is safe to use, what should be anonymized, what always needs human review, and where extra caution is needed.",
    ],
    taskIntro: "Write the first simple version of AI rules for yourself or your team:",
    taskItems: ["What is okay to put into AI?", "What should I rather anonymize or not use at all?", "Which outputs would I never leave without human review?", "What types of work require more caution?"],
    taskType: "ul",
    teaser: "How to scale AI adoption beyond a few early adopters — across the whole company.",
  },
  {
    day: 26,
    title: "AI adoption does not scale through access. It scales through what can be shared and reused.",
    subject: "How to scale AI adoption beyond early adopters.",
    preheader: "If it stays with just a few people, adoption will not move. Here is how to change that.",
    concept: [
      "If everything stays only with a few individuals, adoption will not move much further. Know-how stays scattered and results become inconsistent.",
      "Real scaling begins when success becomes shareable: a prompt library, a list of use cases, examples of what works, simple standards, a small knowledge base.",
    ],
    taskIntro: "Look at what already works and ask:",
    taskItems: ["What is worth sharing further?", "What could be saved as a prompt, template, or example?", "What would help others get started faster?", "What could become the basis of a small AI adoption kit?"],
    taskType: "ul",
    teaser: "You are no longer collecting tips. You are building a system. Second to last day.",
  },
  {
    day: 27,
    title: "You are no longer collecting tips. You are building your own AI system.",
    subject: "You are not collecting tips anymore. You are building a system.",
    preheader: "Tomorrow is the last day of the challenge. Today you write down what you are taking with you.",
    concept: [
      "A real AI system is not one tool. It is a way of working where all of these things come together: how you think about tasks, what you delegate to AI, what you save, what you reuse, how you build your knowledge base, and where human control stays in place.",
    ],
    taskIntro: "Write down the first version of your AI system:",
    taskItems: ["What I use AI for most often", "Which prompts or templates I want to save", "Which workflows already make sense to me", "Where I keep my notes, materials, and reusable assets", "Where I need human control", "What I no longer want to do from scratch manually"],
    taskType: "ul",
    teaser: "The last day of the challenge. And the beginning of everything that comes after.",
  },
  {
    day: 28,
    title: "Real change starts now.",
    subject: "28 days down. Real change starts now.",
    preheader: "Finishing the challenge is not the goal. It is the beginning. Here is what comes next.",
    concept: [
      "Finishing the challenge is not the goal. It is the beginning.",
      "The point is not to go through 28 days and try 28 things. The point is what remains in your everyday work afterward.",
    ],
    taskIntro: "Write a short plan for the next 90 days in these 4 parts:",
    taskItems: ["Keep – what I definitely want to keep", "Build – what I want to continue developing or building", "Share – what I want to share with others", "Measure – how I will know this is actually helping"],
    taskType: "ul",
    teaser: "",
  },
];
