import type { ChallengeDay } from "./types";

export const challengeDataBasicEN: ChallengeDay[] = [
  {
    day: 0,
    title: "This isn't a course. It's a new way of working.",
    subject: "Let's start. Here's how the challenge works.",
    preheader: "28 days, 5–7 minutes a day. One real shift.",
    concept: [
      "AI is everywhere today. New tools, new features, new promises every week. And that's exactly why it's easy to end up just trying things — and then closing the tab when the results aren't what you expected.",
      "This challenge was built so that doesn't happen.",
      "It's not about learning as many AI tools as possible. It's about using AI regularly and in a way that actually makes your work easier. This is the AI-first approach: a way of thinking about work that changes how you do it — regardless of which specific tool you're using.",
      "Each day takes about 5–7 minutes. Each day you'll take something concrete away:",
      ["a new way of seeing AI at work", "a small practical step", "a concrete output or small improvement to something you already do"],
      "This version of the challenge — Basic — focuses on the fundamentals. How AI thinks, what to realistically expect from it, how to write prompts that actually work, and how to bring AI into the things you do every day.",
      "Every challenge can go deeper. If you hit something you already know, that's fine — each day can be done more thoroughly. Adjust the prompt, improve the output, build it into real work. The goal isn't to get everything done. The goal is to move forward a little every day.",
      "A little is enough. Five minutes. One thing. One step. That's how real change actually happens.",
    ],
    taskIntro: "Before we start, one simple task. Think and write down:",
    taskItems: [
      "3 things you do repeatedly at work or in your day — every week or every day",
      "Even mundane things count: answering emails, prepping meetings, writing texts, reports, summaries",
      "Write them somewhere — Notion, Google Docs, Apple Notes, or paper. We'll come back to them.",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow we'll look at why AI is more than a faster Google — and why that distinction matters.",
  },
  {
    day: 1,
    title: "AI isn't a faster Google. It's leverage.",
    subject: "One mental shift that changes your results.",
    preheader: "Speed is a side effect. Leverage is the goal.",
    concept: [
      "Most people use AI like a slightly smarter search engine: they type a question, get an answer, move on. That works — but it uses a fraction of what AI is actually capable of.",
      "It's like having a Ferrari and only using it to go grocery shopping.",
      "The key mental shift: AI isn't a tool for speed. It's a tool for leverage — for dramatically better results with the same or less effort. Speed is a side effect, not the goal.",
      "What does that look like in practice? Speed means: I write an email in 5 minutes instead of 20. Leverage means: I write an email that would never have existed without AI — because with AI I thought through what the client actually needs to hear, how to frame it, and in three different variants.",
      "A good analogy: the digital camera gave people speed. But Photoshop gave photographers leverage — results the camera itself could never produce. AI is your Photoshop for working with text, thinking, and structure.",
      [
        "Speed: do the same thing, but faster",
        "Leverage: achieve a result that wouldn't otherwise be possible — or would take ten times longer",
        "Mindset: AI as a collaborator, not a shortcut",
        "Practice: ask 'how can I get a better result?' not just 'how can I do this faster?'",
      ],
      "Skipping this mental shift — the mindset part — is why most people 'try AI and then abandon it'. They don't see leverage. They just see that the first result isn't good enough. And they're right — it never is on the first try. But leverage comes in the second and third round.",
      "Today's task will make you think exactly this way.",
    ],
    taskIntro: "Take one task from yesterday's list and think about it from two angles:",
    taskItems: [
      "How could AI help me do this task faster? (speed)",
      "What result could I achieve with AI that would otherwise be completely impossible — or take way too long? (leverage)",
      "Write down both answers. They don't need to be perfect — the point is the way of thinking.",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow we'll draw a realistic map of AI: what it does well, where it fails — and why knowing this matters before you start.",
  },
  {
    day: 2,
    title: "AI is a great assistant. Not a very good magician.",
    subject: "A realistic AI map — what it can and can't do.",
    preheader: "Unrealistic expectations and excessive skepticism lead to the same place.",
    concept: [
      "One of the biggest mistakes in working with AI is unrealistic expectations. Or, on the other end, excessive skepticism. Both lead to the same result: you don't use AI effectively, because you're either waiting for miracles or convinced it won't help.",
      "A realistic map is better than no map at all.",
      "What AI genuinely does well — its strongest zones:",
      [
        "Structuring and rewriting text quickly and consistently",
        "Generating variations, ideas, and proposals — giving you five options instead of one",
        "Summarizing long documents — 10 pages down to 5 sentences",
        "Explaining complex things simply — for different audiences, different levels of detail",
        "Assisting with repetitive tasks — templates, drafts, structures",
        "Working fast with large amounts of text — what would take hours, it handles in minutes",
      ],
      "What AI can't do or does unreliably — where you need to verify:",
      [
        "Access the internet in real time (without special tools or browser integrations)",
        "Remember previous conversations unless you set it up or repeat the context",
        "Always tell the truth — AI can confidently make up facts, numbers, and references",
        "Understand your specific situation unless you provide it as context",
        "Replace expert judgment in critical decisions — medicine, law, finance",
      ],
      "The most treacherous trap: AI can't say 'I don't know' convincingly. It generates an answer that sounds great — but may be wrong. Always verify facts and specific numbers externally, especially when accuracy matters.",
      "The key principle: AI is the best collaborator when you know what you want from it — and you verify what it gives you. This principle stays true for all 28 days.",
    ],
    taskIntro: "Think of one task where you're not sure AI would help. Test it:",
    taskItems: [
      "Pick a task where you're skeptical — or where AI hasn't served you well before",
      "Write a simple prompt and see what you get",
      "Evaluate: was it useful? Where did AI fall short? What would have helped?",
    ],
    taskType: "ol",
    taskPrompt: "I need help with [task]. I have [what you have available]. The result should be [what you need].",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow it gets practical — you'll tell AI exactly what you do and let it suggest where it can help.",
  },
  {
    day: 3,
    title: "AI knows nothing about you. Change that in 5 minutes.",
    subject: "Tell AI what you do — get a proposal for how to help.",
    preheader: "Generic input = generic output. Context changes everything.",
    concept: [
      "AI without context is like a new colleague on day one. Technically capable, but doesn't yet know who they're working for, what matters, or how things work.",
      "That's exactly how AI behaves until you give it context. And that's today's task.",
      "Why does it matter so much? Try entering 'help me with my work' and see what you get. Then try 'I work as a product manager at a B2B SaaS company, my biggest daily pain point is preparing weekly status updates for leadership — they always have the same structure' — and the result will be dramatically different.",
      "Context works like a briefing for a new colleague. The better the briefing, the better they perform from the very first day. AI is no different — except you're the one doing the briefing, every time.",
      "What belongs in your context:",
      [
        "Who you are — your role or field, specifically (not generally)",
        "What you actually do — 3–5 typical tasks, not a job description",
        "Who you work for — internal team, clients, customers, leadership",
        "What your biggest recurring pain points are",
      ],
      "Today's task has two parts: first you'll tell AI about yourself, then ask it where it can help. Don't expect a perfect result — this is the first mapping. Save the output, we'll come back to it.",
      "The most common mistake: being too vague. 'I work in marketing' is too little. 'I prepare campaign reports for e-commerce clients, every week, in PowerPoint, and it always takes 3–4 hours to gather the data' is usable.",
    ],
    taskIntro: "Use this approach — it takes 5–7 minutes:",
    taskItems: [
      "Open Claude, ChatGPT, or Gemini",
      "Write an AI prompt using the template below",
      "Save the output — the specific areas where AI proposed it could help",
    ],
    taskType: "ol",
    taskPrompt: "I work as [your role or field]. My typical tasks are: [list 3–5 specific things]. My biggest recurring time-consuming task is [describe it]. Suggest 5 specific ways AI could help me — not generally, but directly for my tasks.",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow we'll look at what makes the biggest difference between a good and bad prompt — and why you can apply it right away.",
  },
  {
    day: 4,
    title: "One detail separates a great prompt from an average one.",
    subject: "What makes the biggest difference between a result and garbage.",
    preheader: "Vague input = vague output. Every single time.",
    concept: [
      "A bad result from AI usually has one cause: a bad prompt. Not bad AI. That's a liberating message — because you can improve the prompt.",
      "A prompt is essentially a work brief. And the brief you give a new colleague determines the quality of their work. 'Write me an email' is like telling a colleague 'do that thing' — neither one knows where to start.",
      "What makes a prompt bad:",
      [
        "Too vague: 'write me an email'",
        "Missing context: AI doesn't know who it's for, why, what tone to use",
        "Missing format: AI doesn't know how long or how structured the result should be",
        "Missing goal: AI doesn't know what the output should achieve — inform, persuade, book a meeting",
      ],
      "What makes a prompt good:",
      [
        "It's specific: 'write a follow-up email for a client who saw the proposal but didn't respond'",
        "Has context: 'the client is a small manufacturing company, I'm working with the owner, the offer was for a warehouse management system'",
        "Has format: 'short, max 5 sentences, friendly and direct tone'",
        "Has a goal: 'I want to get a response — positive or negative'",
      ],
      "The most common mistake: expecting AI to 'understand what you mean'. AI always interprets exactly what you wrote — not what you had in mind. Vague input, vague output. Every time.",
      "The thumb rule: the more clearly you can picture the result you want — the more precise your prompt will be. It helps to ask yourself before writing a prompt: if someone gave me this as a task from my boss, would I know exactly what to do? If not, add more.",
    ],
    taskIntro: "Compare these two prompts and try both in AI — you'll see the difference immediately:",
    taskItems: [
      "Bad: 'Write me an email.'",
      "Better: 'Write a follow-up email to a client who saw a software pricing proposal but hasn't responded. Friendly and direct tone, max 5 sentences. Goal: get a response — yes or no.'",
      "Write down how the outputs differ — quality, usability, length. This difference is exactly what we'll keep working with.",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow you'll practice rewriting bad prompts — on three real examples.",
  },
  {
    day: 5,
    title: "Rewriting prompts is a muscle. Today you'll build it.",
    subject: "Practice: from vague to concrete, three times in a row.",
    preheader: "This is a skill, not just knowledge. You have to practice it.",
    concept: [
      "Rewriting prompts is like editing text — the first version is never the best. And just like editing: you don't have to start from scratch. You need to know what to add or remove.",
      "Prompting is a skill, not just knowledge. That means reading about it isn't enough — you have to try it on your own examples. Today you have three specific prompts to rewrite. Your task: fix them so they produce better output. Then test both versions in AI and compare.",
      "What's typically missing from bad prompts:",
      [
        "Target audience or recipient — who will read or hear this?",
        "Tone or communication style — formal, friendly, technical, direct?",
        "Required format or length — bullets, paragraph, three sentences, table?",
        "Situation context or output goal — why are you writing this, and what should the recipient do?",
      ],
      "Why this exercise is so effective: you'll learn to recognize what's missing from a prompt — not as theory, but as instinct. In a few weeks, you'll be writing prompts that work on the first try, because you'll automatically ask yourself the right questions before writing.",
      "Tip for comparing: copy both the bad prompt and the rewritten one into AI and look at both outputs side by side. The difference is usually immediately visible. That's how you build intuition for good prompting — not by reading, but by comparing.",
      "Today is one of the most practical days in the entire first week. Don't read passively — go directly to AI and experiment.",
    ],
    taskIntro: "Rewrite these 3 prompts and test them in AI:",
    taskItems: [
      "'Write me a LinkedIn post.' → add: for who, on what topic, what goal, what tone, how long",
      "'Help me with my presentation.' → add: on what topic, for what audience, how many slides, what output you need",
      "'Write a reply to an email.' → add: what the email said, what you want to communicate, what tone, how long a reply",
    ],
    taskType: "ol",
    taskPrompt: "Rewrite this prompt to make it more concrete: [paste original prompt]. Add context, goal, tone, and required output format.",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: why the first result from AI is always just the beginning — and how to get much more from it.",
  },
  {
    day: 6,
    title: "The first result is a foundation. Not a finished product.",
    subject: "Iteration — how to get much more from AI.",
    preheader: "The best output comes in the second or third round.",
    concept: [
      "The biggest mistake when working with AI: write a prompt, get a result, and either accept it or throw it away. Both are wrong — and both throw away the greatest value AI offers.",
      "AI works best as an iterative collaborator. The first output is a foundation — not a final product. That's exactly how collaboration with a good colleague works: you give them the brief, they draft something, you refine it together. AI is tireless in this process — it can iterate indefinitely.",
      "Why do people skip iteration? Either they don't have time (but iteration takes 30 seconds), or they don't know what to say to AI. That's why you have specific instructions below. Or they're simply disappointed with the result — and disappointment is information. Tell AI exactly what doesn't work.",
      "How to iterate effectively — specific phrases:",
      [
        "If the result is too generic: 'add a concrete example from [your field]'",
        "If the result is too long: 'shorten it to 3 sentences, keep the key points'",
        "If the tone doesn't fit: 'rewrite it more formally' or 'make it less corporate, more human'",
        "If detail is missing: 'expand point number 2 — add a concrete example'",
        "If the structure is wrong: 'rewrite as a bullet list' or 'split into three sections with headings'",
      ],
      "The key principle: you don't need to start over. Continue the conversation — AI remembers the whole thread. Each instruction builds on the previous output. That's what makes a conversation with AI different from Google: it's a dialogue, not a series of separate searches.",
      "One warning: iteration doesn't mean rewriting everything endlessly. Three or four rounds is usually enough. If after five iterations you're still not satisfied, the problem is likely in the original prompt — go back and reframe from the start.",
    ],
    taskIntro: "Take any output from the past few days and run 3 iterations in a row:",
    taskItems: [
      "Iteration 1: shorten or lengthen the output — refine the length and information density",
      "Iteration 2: change the tone — more formal or more friendly, whichever isn't working",
      "Iteration 3: add or remove a specific piece of information — refine the content",
    ],
    taskType: "ol",
    taskPrompt: "Rewrite the previous output like this: [specific instruction — what to shorten, what to rewrite, what to add].",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow is Week 1 reflection — you'll write down what worked, what didn't, and what you'll take forward.",
  },
  {
    day: 7,
    title: "Week one is done. What did you actually learn?",
    subject: "Week 1 reflection — three things that stick.",
    preheader: "Knowledge fades. A written insight stays.",
    concept: [
      "The first week is behind us. Six topics, six short exercises. And now comes possibly the most important day of all — reflection.",
      "Why is reflection so important? Because without it, insights disappear just as quickly as they arrived. The brain remembers what it processes — not what it merely receives. Writing down three things that stuck with you is worth more than reading ten more articles about AI.",
      "Reflection isn't a test. It's not about whether you did everything 'correctly'. It's about discovering what from the first week actually stayed with you — and what you want to carry into the second week.",
      "Three questions for reflection:",
      [
        "What stuck with you most from the first week? (one concrete thing, not a list)",
        "Where did you get a result from AI that surprised you positively?",
        "What didn't work — and what would you try differently next time?",
      ],
      "The most common mistake in reflection: being too general. 'I learned about AI' is not reflection. 'I discovered that outputs dramatically improve when I specify the exact output format' is reflection — because it's a usable insight.",
      "Week two will build on what you've learned. We'll cover prompt structure, context, and how to use AI on real tasks from your work. The foundation you've built this week is about to start making sense.",
    ],
    taskIntro: "Write down three things — concretely and briefly:",
    taskItems: [
      "Your biggest insight from the first week (one sentence, concrete)",
      "One AI output that was better than expected — what about the prompt worked?",
      "One thing that didn't work — and how you'd approach it differently next time",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Next week we go deeper: prompt structure, context, and your first real AI output from your actual work.",
  },
  {
    day: 8,
    title: "Good prompts have structure. Four parts that work.",
    subject: "The anatomy of a good prompt — four parts that always work.",
    preheader: "Role, task, context, format. In that order.",
    concept: [
      "Last week we distinguished good prompts from bad ones. Now we go one step further: we'll learn exactly what a good prompt contains — and in what order.",
      "There are four parts every good prompt should have. You don't always need all of them — but the more you include, the better your output will be.",
      "The four parts of a good prompt:",
      [
        "Role: who should AI be? An experienced salesperson, coach, analyst, copywriter — the role gives AI a way of thinking",
        "Task: what exactly should it do? Write, summarize, analyze, rewrite, suggest, explain",
        "Context: what does it need to know? Information about the situation, target audience, product, constraints",
        "Format: what should the output look like? Length, structure, tone, bullets or paragraphs",
      ],
      "Why does role work? Because AI is trained on a massive amount of text from different perspectives. When you specify a role, you switch AI into the thinking mode that belongs to that role. 'You are an experienced HR manager' gives AI a different approach than 'you are a junior recruiter'.",
      "Example of a structured prompt: You are an experienced B2B sales consultant. Write a short follow-up email to a client who saw our proposal but hasn't responded in 5 days. Context: the client is a small manufacturing company, I'm the sales director, the offer was for an ERP system. Format: max 5 sentences, friendly but direct tone, no generic phrases.",
      "It doesn't always need to be this detailed. Shorter prompts work for simpler tasks. But when you want an output you'll actually use — this four-part structure gets you there much more reliably.",
      "Today you'll try this structure on your own prompt — and see the difference compared to what you were writing last week.",
    ],
    taskIntro: "Take one task from your work and write a prompt using the four-part structure:",
    taskItems: [
      "Role: who should AI be? (write a specific role or expertise)",
      "Task: what exactly should it do? (specific instruction — write, summarize, suggest...)",
      "Context: what does AI need to know about the situation, target audience, constraints",
      "Format: length, tone, output structure",
    ],
    taskType: "ol",
    taskPrompt: "You are [role]. [Specific task]. Context: [what AI needs to know]. Output format: [length, tone, structure].",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: why context is your most powerful tool — and how to use it so AI works precisely for you.",
  },
  {
    day: 9,
    title: "AI doesn't know what you know. Context is your most powerful tool.",
    subject: "Context is the key — how to give it right.",
    preheader: "The more AI knows, the more it behaves like someone who knows your work.",
    concept: [
      "Why do two people with the same prompt get completely different results? Context.",
      "AI has no access to your work, your clients, your resource constraints, or your project history. It only knows what you wrote in the current conversation. That's not a limitation — it's the rules of the game, and you can use them to your advantage.",
      "Good context isn't a paragraph of text. It's choosing the most important things AI needs to know so the output makes sense for your situation — not for an average situation.",
      "What belongs in context most:",
      [
        "Who receives the output — an experienced expert, a layperson, a customer, a manager",
        "What the situation is — what's happening, what's at stake, what came before",
        "What the constraints are — what AI shouldn't do, what's sensitive, what's fixed",
        "What your goal is — inform, persuade, get feedback, book a meeting",
      ],
      "Without context: 'Write a project summary.' AI writes a generic summary that could apply to anything — and therefore to nothing specific.",
      "With context: 'Write a project summary for the company's executive committee. The project is 3 weeks behind schedule. Leadership knows about the delay but not the reasons. Tone: calm and factual, no apologies, with a next step proposal. Max 150 words.' That's an output you'll use immediately.",
      "The key question to ask yourself before every prompt: what would a wise colleague need to know about my situation to give me good advice? That's your context.",
    ],
    taskIntro: "Take a prompt from the previous day and improve it by adding context:",
    taskItems: [
      "Choose a prompt from D8 or any one that gave you an average output",
      "Add: who the recipient is, what the situation is, what the constraints are, what the goal is",
      "Compare the output with the original — write down the concrete difference",
    ],
    taskType: "ol",
    taskPrompt: "Context: [who I am, what the situation is, what the goal is]. Recipient: [who will read this and what they know about the topic]. Constraints: [what the output should not contain or do]. Task: [specific instruction].",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow you'll write a prompt for a real task from your work — and get an output you'll actually use.",
  },
  {
    day: 10,
    title: "This one's personal. A prompt built from your actual work.",
    subject: "No exercises — a real task, a real output.",
    preheader: "This is where theory becomes practice.",
    concept: [
      "The first nine days were preparation. Today is the result.",
      "The best way to test what you've learned is to take a real task from your work and go through the whole process: context, role, task, format. Then iterate until the output is actually usable.",
      "Why is this harder than the practice exercises? Because real tasks have less-than-ideal information, the output needs to work for specific people, and the result actually matters. That's exactly why it's the best test.",
      "Tasks that work well for today:",
      [
        "Text you'll need soon — email, message, summary, post",
        "Document you prepare repeatedly — meeting agenda, weekly status, report",
        "Answer to a question you're working on — solution proposal, situation analysis, comparison of options",
        "Output you usually do manually — transcribing notes, structuring information, translating",
      ],
      "A good result today isn't a perfect output. A good result is an output that saves you time or gives you a foundation to build on. That's the goal.",
      "Remember iteration: if the first output isn't good, don't blame AI — refine the prompt. Add context, specify the format, change the role. Three rounds is usually enough.",
      "Save today's output. On day 12 we'll come back to it and improve it based on what you learn in between.",
    ],
    taskIntro: "Choose a real task from your work and go through the whole process:",
    taskItems: [
      "Write down the task and exactly what output you need",
      "Write a prompt using the four-part structure from D8 — role, task, context, format",
      "Try it in AI, review the result, and do at least one iteration",
      "Save the output — we'll come back to it on Wednesday",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: what to do when the output doesn't work — concrete techniques for fixing bad output.",
  },
  {
    day: 11,
    title: "AI output off? Three questions that fix it.",
    subject: "How to fix a bad output — without starting from scratch.",
    preheader: "Disappointment with the result is information. You know what to say next.",
    concept: [
      "A bad output from AI is frustrating. But it's also information — it tells you exactly what's missing from the prompt.",
      "The worst reaction: delete the output and start over from a blank page. Or abandon AI and do it manually. Both are unnecessary — and both throw away what AI already did for you.",
      "The right reaction: tell AI exactly what doesn't work. Not vaguely ('this is wrong'), but specifically ('this paragraph is too generic, rewrite it with a concrete example from an HR context').",
      "Five techniques for fixing a bad output:",
      [
        "Clarify the requirement: 'The result is too generic. Add a concrete example for [situation].'",
        "Change the tone: 'Rewrite it less formally, more like something a person wrote, not a corporate document.'",
        "Cut the scope: 'Shorten to 3 key points — remove everything else.'",
        "Ask for variants: 'Write it three different ways — I'm looking for a different angle.'",
        "Explain why it doesn't work: 'The reader of this message doesn't know our context — rewrite without assuming they know about the project.'",
      ],
      "One thing to watch out for: AI remembers the context of the whole conversation. If you iterate too long and results get worse, sometimes it helps to start a new conversation — with a better opening prompt that includes what you learned in the previous one.",
      "Today's exercise will teach you to distinguish between 'bad prompt' and 'bad output' — because the fix is different for each.",
    ],
    taskIntro: "Take the output from D10 or any output that isn't working, and try these steps:",
    taskItems: [
      "Identify concretely what doesn't work — tone, length, content, or structure",
      "Write an AI repair instruction — concretely, not vaguely",
      "Compare the original and the repaired output — what changed?",
    ],
    taskType: "ol",
    taskPrompt: "This output doesn't work because [specific reason]. Rewrite it so that [specific requirement for the fix].",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: we'll go back to the prompt from D10 and improve the output using today's techniques.",
  },
  {
    day: 12,
    title: "Good output becomes great. This is how you iterate.",
    subject: "Iteration in practice — better output from what you have.",
    preheader: "Good results don't come on the first try. They come on the third.",
    concept: [
      "Today is the day everything comes together.",
      "You have a prompt and output from D10. You have the techniques from D11. Now it's time to combine them — and take the output to the level you'd actually use.",
      "Why is returning to a previous output so valuable? Because you see it with fresh eyes. What seemed usable then may look different now. And what you learned in D11 gives you specific ideas for what to improve.",
      "The process for today:",
      [
        "Open the output from D10 — read it again with a fresh perspective",
        "Identify three things that could be improved — tone, length, specificity, structure",
        "Write a repair instruction for each one",
        "Compare the final outputs to the original",
      ],
      "You don't need to fix everything. Focus on one or two of the biggest weaknesses. Perfectionism in iteration is a trap — better an output that's 80% right and saved you an hour than a perfect output that took two hours of iteration.",
      "The key insight: iteration with AI isn't a weakness. It's the way of working. The best AI users don't get perfect results on the first try — they get them after two or three iterations. That's the norm, not the exception.",
    ],
    taskIntro: "Go back to the output from D10 and run three targeted iterations:",
    taskItems: [
      "Iteration 1: refine the content — what to add or remove to better match the real situation",
      "Iteration 2: adjust tone or length — based on what you learned in D11",
      "Iteration 3: add a concrete example or detail that makes the output more precise",
    ],
    taskType: "ol",
    taskPrompt: "Take the previous output and improve it like this: 1. [what specifically to add or change]. 2. [what to shorten or remove]. 3. [how to adjust tone or structure].",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: when AI helps and when it just complicates everything — an honest overview.",
  },
  {
    day: 13,
    title: "When not to use AI — and why knowing that is an advantage.",
    subject: "When AI helps and when it adds work.",
    preheader: "The best tool for every task — sometimes that isn't AI.",
    concept: [
      "The most sophisticated AI users don't use AI for everything. They know exactly when to use AI — and when it's faster, better, or more reliable to do it without.",
      "This is a perspective you rarely hear in AI tutorials. But it's the perspective that moves you forward the most.",
      "When AI helps most:",
      [
        "The task has clear structure — email, summary, agenda, analysis, explanation",
        "You need variations or ideas quickly — brainstorming, options, alternatives",
        "Text is long and you need to shorten or restructure it",
        "You do it repeatedly — a template or prompt will save you time every next round",
        "You need to start — draft, outline, first version to push off from",
      ],
      "When AI adds work or complicates things:",
      [
        "You need precise facts, numbers, or current information — AI may make things up",
        "The decision requires your expert judgment or knowledge of specific context",
        "The output needs to be completely personal — AI can't hold your authentic voice without significant effort",
        "The task is difficult to formulate — if you don't know what you want, AI won't invent it for you",
        "A short, simple task — writing one sentence or checking off one item is faster manually",
      ],
      "Practical test: if writing the prompt takes longer than doing the task manually — skip AI. If it's a recurring type of task, invest in a good prompt now so you can use it in 30 seconds next time.",
      "This isn't criticism of AI. It's a realistic view of how to use it intelligently — not just enthusiastically.",
    ],
    taskIntro: "Go through your typical workday and sort tasks into two groups:",
    taskItems: [
      "Tasks where AI helps — structured, repetitive, where you need variants or drafts",
      "Tasks where it's better without AI — short one-off things, where you need precision or a personal voice",
      "Write down three examples in each group",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow is the checkpoint — halfway through the challenge, you'll write your personal prompt checklist.",
  },
  {
    day: 14,
    title: "Halfway through. A look back that gives direction.",
    subject: "Checkpoint — what you're taking from the first half.",
    preheader: "The best 5-minute investment: knowing what you carry forward.",
    concept: [
      "Fourteen days. Fourteen topics. And now comes one of the most important days of the challenge — not because you're doing something new today, but because you'll stop and process what you've learned.",
      "A written insight works differently from information you've read. When you write down what genuinely works for you, you create a personal checklist — tailored exactly to your work and your situations.",
      "Three things we'll focus on:",
      [
        "What from the first half of the challenge will you actively use going forward?",
        "What didn't work for you — and why?",
        "What is your current personal prompt checklist?",
      ],
      "A personal prompt checklist is simply a list of things you verify before sending a prompt. It doesn't need to be long — three to five items is enough. But it needs to be yours, not copied. What specifically works for you.",
      "Example checklist (not a template — an example):",
      [
        "Do I have a role? Did I tell AI who to be?",
        "Do I have context? Does AI know enough about the situation and the recipient?",
        "Do I have a format? Does AI know what the result should look like?",
        "Do I have a goal? Does AI know what the output should achieve?",
      ],
      "The second half of the challenge will build on the foundations you've built. We'll go into templates, repetitive work, AI tools in the context of a full workday — and finally to building a habit that stays with you after the challenge ends.",
    ],
    taskIntro: "Write down three things — bullet points are fine, a few words is enough:",
    taskItems: [
      "Three insights from the first half of the challenge that genuinely stayed with you (concrete, not general)",
      "Your personal prompt checklist — 3–5 things you verify before sending every prompt",
      "One specific goal for the second half of the challenge",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Next week: repetitive work as a signal, templates and workflows — and how to save an hour a week on things you keep doing over and over.",
  },
  {
    day: 15,
    title: "Repetitive tasks are the most expensive work that exists.",
    subject: "Identify what you do every week again — that's a signal.",
    preheader: "Not every repetitive task is necessary. But every one deserves attention.",
    concept: [
      "A lot of work doesn't look expensive at first glance. One email here, one summary there, a meeting agenda every Thursday. Each thing takes ten minutes.",
      "But ten things every week is an hour. And an hour every week is two and a half weeks per year. On one category of work.",
      "Repetitive work is a signal. Not a signal to be faster. A signal that this work should have a template, a prompt, or a workflow — so it doesn't start from scratch next time.",
      "Three types of repetitive work where AI helps most:",
      [
        "Documents — reports, summaries, notes, briefs, agendas, proposals",
        "Communication — follow-ups, answers to frequent questions, confirmations, internal updates",
        "Structuring — transcribing notes, organizing information, preparing materials for decisions",
      ],
      "The most common mistake: underestimating small things. 'It only takes me ten minutes' sounds like an argument for not changing anything. But ten minutes of repetitive tasks every day is two full working weeks a year.",
      "Today's task is exploration — without pressure to change anything right now. The goal is to see the map of your repetitive work. What takes time? What keeps coming back? What costs the most energy? That will be the basis for the templates and prompts you'll build in the coming days.",
    ],
    taskIntro: "Think about your working week and write down:",
    taskItems: [
      "5 things you do repeatedly — every week or every other week",
      "For each: roughly how long it takes and how much energy it costs",
      "Mark the one where the time or energy cost is greatest with a star",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: from this list you'll build your personal leverage matrix — where AI can add the most.",
  },
  {
    day: 16,
    title: "Map it out: which tasks to hand to AI and which to keep.",
    subject: "Top 5 repetitive tasks where AI can save the most.",
    preheader: "Leverage matrix: what to hand off to AI, what to improve, what to automate.",
    concept: [
      "Yesterday you identified your repetitive work. Today you'll sort it — and decide where AI brings the most.",
      "Not every repetitive task is the same type of opportunity. It helps to divide them into three categories:",
      [
        "Hand off to AI: AI can create the first version or complete output — you just review and send",
        "Improve with AI: you have the input and structure, AI helps with phrasing, length, or format",
        "Automate with template: set up a prompt once, then use it repeatedly in 30 seconds",
      ],
      "How to tell which category something belongs to: tasks that have a clear structure and output (email, summary, report) are candidates for 'hand off' or 'template'. Tasks where the input is complex or highly personal (coaching conversation, creative proposal) are better for 'improve with AI'.",
      "Example leverage matrix in practice:",
      [
        "Weekly status for leadership → hand off to AI (I give data, I get a draft)",
        "Answers to recurring client questions → template (write the prompt once, repeat it)",
        "Meeting agenda prep → improve with AI (I have the topics, AI structures them)",
        "Strategic presentation for the board → improve with AI (content is mine, AI helps with framing)",
      ],
      "The goal today isn't to do everything at once. The goal is to pick one or two tasks to start with — where the effect will be most visible.",
    ],
    taskIntro: "Take the list from D15 and run it through this filter:",
    taskItems: [
      "For each task decide: hand off to AI, improve with AI, or automate with template",
      "Choose one task in the 'hand off to AI' or 'template' category — that's the easiest starting point",
      "Write down concretely how AI would help — what would be the input and what would be the output",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: the difference between a template and a workflow — and why it matters when you want a system, not just a tool.",
  },
  {
    day: 17,
    title: "A template solves one task. A workflow solves a whole process.",
    subject: "Template vs. workflow — and when to use which.",
    preheader: "A template is an answer. A workflow is a system.",
    concept: [
      "Template and workflow sound similar. But they're two different things — and confusing them is why someone 'has a template' but still spends the same amount of time.",
      "A template is a pre-prepared output or prompt for one repetitive task. For example: I have a prompt for weekly status — I enter data, I get a draft. A template solves one specific step.",
      "A workflow is a sequence of steps that includes multiple templates and decisions. For example: the process from a meeting to sending the minutes — taking notes, structuring into an agenda, adding action items, sending. Each step has its template, but together they form a workflow.",
      "When a template is enough:",
      [
        "Repetitive output that's always similar — email, report, agenda, summary",
        "Single-step task where the input is clear and the output is predictable",
        "Starting out — the first template is always the most important step",
      ],
      "When you need a workflow:",
      [
        "The process has multiple steps that depend on each other",
        "Different people are involved at different stages",
        "Missing one step → the whole result gets worse",
      ],
      "For this challenge we focus mainly on templates — they're faster to build and the effect is immediate. Workflow is a more advanced topic we'll develop in the Advanced version of the challenge.",
      "Important: a good template isn't a document. It's a prompt written so concretely that you can feed it to AI in 30 seconds and get an output you can use directly.",
    ],
    taskIntro: "Pick one repetitive task from your list and decide:",
    taskItems: [
      "Is it one step (template) or multiple steps (workflow)?",
      "If template: write down what the prompt should contain — input, output, tone, format",
      "If workflow: write down the steps in the process and mark which step is the best candidate for a template",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: you'll create your first real template — a prompt you'll use repeatedly.",
  },
  {
    day: 18,
    title: "One template that saves an hour every week from here on.",
    subject: "Create your first reusable prompt.",
    preheader: "Do it right once. Then 30 seconds every time after.",
    concept: [
      "Good templates aren't written in one sitting. They evolve — the first version works at 70%, the second at 85%, the third is the one you use for years.",
      "But sometimes you have to start. And starting means writing the first version — even an imperfect one.",
      "What makes a template good? Three things:",
      [
        "It's specific — not 'write an email' but 'write a follow-up email to a client who hasn't responded to a proposal in 5 days'",
        "It has variables — placeholders where you substitute specific values: [client name], [type of proposal], [date]",
        "It produces consistent output — each use produces a result at the same quality level",
      ],
      "How to create a template:",
      [
        "Choose a repetitive task — ideally one where the output is always similar",
        "Write a prompt that precisely describes what the output should contain, in what tone and format",
        "Add variables — places in the prompt where you'll substitute specific details",
        "Test the template on two different situations and adjust what doesn't fit",
        "Save it somewhere you can quickly access it — Notion, Google Docs, Apple Notes",
      ],
      "One template a week. After four weeks you have four templates — and each saves you 20–30 minutes. That's an hour and a half per week on things you used to do from scratch.",
      "Today's output doesn't need to be perfect. It's the first version. And that's exactly what you need.",
    ],
    taskIntro: "Build your first template — step by step:",
    taskItems: [
      "Choose a repetitive task — ideally the one you starred in D15",
      "Write the prompt: role, task, context (as variables), output format",
      "Test it on one concrete example — does it work? What to adjust?",
      "Save the template in Notion, Google Docs, or Apple Notes as 'My AI templates'",
    ],
    taskType: "ol",
    taskPrompt: "You are [role]. [Specific task]. Context: [name/situation/specifics — you'll fill this in each time]. Output format: [length, tone, structure].",
    taskTip: "Save the template as a document in Notion, Google Docs, or Apple Notes — so you can reach it quickly.",
    teaser: "Tomorrow: an empirical look at time — where AI actually saves time and where it paradoxically adds it.",
  },
  {
    day: 19,
    title: "Where AI saves time and where it adds it — an honest overview.",
    subject: "Measurement, not feeling. Where AI adds value and where it doesn't.",
    preheader: "The best AI workflow is one that actually saves time.",
    concept: [
      "They say AI saves time. But 'AI saves me time' is a feeling. Where specifically, how much, and with what types of tasks — that's data. And data is far more useful.",
      "Why does it matter? Because without measurement you go either into enthusiasm (AI always helps) or skepticism (AI never helps). An honest look at where AI genuinely adds value helps you deploy it where it makes sense.",
      "Where AI typically saves time:",
      [
        "First draft of text — writing from scratch is the most expensive; AI draft takes seconds, editing takes minutes",
        "Structuring — transcribing unorganized information or notes into a clear form",
        "Variations — instead of creating one option you get three; choosing is faster than creating",
        "Reformatting — from bullets to paragraphs, from text to table, from formal to friendly",
      ],
      "Where AI doesn't save time or adds work:",
      [
        "Short simple things — writing one sentence manually is faster than formulating a prompt",
        "Highly specific context — if you have to write more text as context than the output itself, it may not be worth it",
        "Fact-checking — an AI output you have to verify sentence by sentence saves very little",
      ],
      "Practical test: if creating a good prompt takes longer than 2 minutes and the output will be shorter than a page — consider whether AI is actually faster. If yes, put it into a template.",
      "The goal of today isn't to answer 'AI saves me time'. The goal is to know specifically: where yes, how much, and why.",
    ],
    taskIntro: "Look back at your last week and run a small experiment:",
    taskItems: [
      "Pick 3 different tasks you completed — with or without AI",
      "Estimate: how many minutes did they take vs. how long they would have taken with/without AI",
      "Write down where the difference was greatest — and why",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: a whole day with AI alongside you — what it looks like in practice.",
  },
  {
    day: 20,
    title: "One deliberate day without AI. See what changes.",
    subject: "A real day with AI — not an experiment, but a way of working.",
    preheader: "AI as a quiet collaborator throughout the whole day.",
    concept: [
      "The biggest shift doesn't happen with one perfect AI prompt. It happens when AI stops being 'something I sometimes try' and becomes a quiet tool that's present throughout the day.",
      "That doesn't mean involving AI in every task. It means being alert during the day to moments where AI could help — and actually using it in the ones you choose.",
      "What a day with AI alongside might look like:",
      [
        "Morning: quick summary of today's agenda or priorities — I tell AI what I have planned, I get an overview",
        "Before a meeting: draft agenda or prepared questions — 2 minutes instead of 10",
        "After a meeting: notes turned into meeting minutes — paste what I wrote, get a clean record",
        "Mid-day: an email that's taking long — instead of 20 minutes, I iterate with AI's draft in 5",
        "End of day: short record of what happened — basis for a report or personal review",
      ],
      "Most important thing: don't force it. If on one day you don't use AI at all, nothing is wrong. If you use it for three things and one of them works great — that's a result.",
      "This is the goal: not a habit of always using AI, but a reflex — 'AI could help here' — and the ability to test it in 30 seconds.",
    ],
    taskIntro: "Today's task spans the whole day, not just 5 minutes:",
    taskItems: [
      "Choose 2–3 specific tasks you'll use AI for today — write them down beforehand",
      "For each, write: prompt, result, what you adjusted",
      "At end of day write three sentences: what worked, what didn't, what you'll change next time",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: what's your AI style — and why everyone works with AI differently.",
  },
  {
    day: 21,
    title: "Everyone uses AI differently. What's your style?",
    subject: "Your AI style — strengths, preferences, way of working.",
    preheader: "The best AI workflow is the one that fits you.",
    concept: [
      "Two people with the same AI tools can have completely different results. One is great at writing prompts, another at iteration. One uses AI for text, another for structuring and analysis. One prefers short conversations, another longer dialogues.",
      "This isn't a problem. It's reality — and the sooner you accept it, the better you'll know how to deploy AI.",
      "Three dimensions of AI style:",
      [
        "Type of tasks: where AI helps you most — text, structuring, brainstorming, analysis?",
        "Iteration approach: do you prefer getting one good answer the first time, or a quick draft and then refining?",
        "Frequency: AI as an everyday tool or for specific repetitive tasks?",
      ],
      "There's no right or wrong AI style. There are only styles that work better or worse for specific work and specific people.",
      "Why knowing this matters: if you use AI in a way that doesn't suit you, you'll stop using it. If you configure AI to fit your work and your pace — it'll stick.",
      "Week three is behind us. This week you built your first template, identified repetitive work, and went through a first real day with AI. Now comes week four — and it's about making this lasting.",
    ],
    taskIntro: "Write down your AI style — three sentences, concretely:",
    taskItems: [
      "Where AI helps me most — what type of tasks (be specific, not general)",
      "How I prefer to iterate — one good draft, or quick foundation and then I refine?",
      "How I want to integrate AI into my work — daily on selected things, or situationally?",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Next week: how to build a second brain with AI — where to store outputs and how to reuse them.",
  },
  {
    day: 22,
    title: "AI remembers nothing. But you can set it up to.",
    subject: "Second brain — where to store AI outputs so they don't disappear.",
    preheader: "An output without storage is half the value.",
    concept: [
      "Every AI output you don't save is gone. The next conversation with AI doesn't start where you left off — it starts from zero. That's a feature of AI, not a bug. And it can be compensated for.",
      "A second brain is simply a place where you store things you'll come back to. AI outputs, templates, good prompts, insights, notes. Not because it needs to be beautifully organized — but so you can return to it.",
      "Why isn't it enough to remember it in your head? Because your brain is a poor storage system for repetitive information but a great system for context and decision-making. The second brain — digital — takes over storage. Your brain stays free for thinking.",
      "What belongs in the second brain:",
      [
        "Templates and good prompts — the ones that repeatedly work",
        "AI outputs you want to use again or build on",
        "Meeting or day notes — prepared by AI for quick access",
        "Insights and ideas — short records that came to you during work",
      ],
      "The most important property of a second brain: it needs to be quickly accessible. If you can reach it in 10 seconds, you'll use it. If it takes 3 minutes of searching, you'll never use it.",
      "Today you'll set up the foundation — one place where everything goes. It doesn't need to be perfect. It needs to exist.",
    ],
    taskIntro: "Choose a place for your second brain and set up the foundation:",
    taskItems: [
      "Choose a tool: Notion, Google Docs, Apple Notes, Obsidian — whichever you open daily",
      "Create a document or page called 'AI — templates and outputs'",
      "Add three things from the challenge: one template, one good prompt, one output you want to use again",
    ],
    taskType: "ol",
    taskTip: "Goal: one place, quickly accessible. No need for a complex structure — complex structure prevents usage.",
    teaser: "Tomorrow: you'll build the foundation of your mini knowledge base — so AI outputs don't disappear.",
  },
  {
    day: 23,
    title: "One document that changes how you work with AI.",
    subject: "Mini knowledge base — context you use again and again.",
    preheader: "Write it once. Use it a hundred times.",
    concept: [
      "There's one thing AI needs again and again — and you keep repeating it: context about you and your work.",
      "Who you are, what you do, who you do it for, how you communicate, what your typical topics are. Every new chat starts from zero — and without context you get generic outputs.",
      "The solution is simple: write your working context once, properly. Save it. Next time, just paste it at the start of a conversation. In 10 seconds you have an AI that 'knows' you.",
      "What belongs in your working context:",
      [
        "Your role and field — specifically, not generally ('product manager at a B2B SaaS company' not 'I work in IT')",
        "Your typical tasks — 3–5 things you do regularly",
        "Who you work for — who outputs serve (clients, team, leadership...)",
        "Preferred communication tone — formal, friendly, technical, direct",
        "What AI shouldn't do — what's sensitive in your work or what you don't want in outputs",
      ],
      "The second part of your mini knowledge base: recurring prompts. Every prompt you wrote during the challenge that worked — save it. You'll have it in 10 seconds next time. That's how you build a personal tool, not just knowledge.",
      "The goal of today is to have a document that exists and works. Not a perfect database — just a usable foundation.",
    ],
    taskIntro: "Write your working context — the foundation of your mini knowledge base:",
    taskItems: [
      "Role and field: who you are and what context you work in (2–3 sentences)",
      "Typical tasks: 3–5 things you do regularly",
      "Tone and constraints: how you want AI to communicate — and what it shouldn't do",
      "Save it as the first document in your second brain from D22",
    ],
    taskType: "ol",
    taskPrompt: "I work as [role] at [field or type of company]. My typical tasks are: [3–5 tasks]. Outputs are created for [who]. Preferred tone: [friendly/formal/direct]. I don't want in outputs: [what you don't want].",
    taskTip: "Copy this document to the start of every AI conversation — you'll immediately get more relevant outputs.",
    teaser: "Tomorrow: how to know AI is actually helping — not by feeling, but concretely.",
  },
  {
    day: 24,
    title: "You can feel AI is helping. But can you measure it?",
    subject: "How to know AI is actually helping you.",
    preheader: "Not 'AI helps me'. But why, where, and by how much.",
    concept: [
      "Saying 'AI helps me' is like saying 'exercise is good for me'. It's true — but without more specific insight you don't know what to repeat and what to change.",
      "Four signals that AI is genuinely adding value:",
      [
        "An output that would have been difficult or impossible without AI — not just faster",
        "A repetitive task that now takes significantly less time and the result is just as good",
        "An iteration that produced a result that would have otherwise taken an hour of manual rewriting",
        "A new perspective or idea you wouldn't have reached quickly on your own",
      ],
      "Four signals that AI is adding work or going neutral:",
      [
        "Checking every sentence of the output — if you verify 100%, you only saved 'writing, not thinking'",
        "Fixing the output takes longer than writing it manually would have",
        "The result requires so much context in the prompt that the whole process is slower",
        "Stress from giving AI instructions instead of enjoyment from the collaboration",
      ],
      "How to measure (simply, not complexly): once a week write three things where AI added value — specific output, specific saving, specific improvement. This small record will show you a clear pattern after two weeks.",
      "Why does it matter? Because without feedback, habits don't improve — they fluctuate. And the goal of the challenge isn't to know more about AI, but to work with it better. Feedback is the key.",
    ],
    taskIntro: "Retrospective: look back at the last three days and write down:",
    taskItems: [
      "One concrete case where AI added real value — what it was and what made it different",
      "One case where AI didn't help or made things harder — why do you think that was?",
      "What you'd do differently next time based on this",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: you'll compare last week with AI vs. a hypothetical week without it — and see what changed.",
  },
  {
    day: 25,
    title: "What would this week have looked like without AI?",
    subject: "Side-by-side comparison — with AI vs. without AI.",
    preheader: "The best way to see progress: an imaginary comparison.",
    concept: [
      "You don't need to live a whole week without AI to know what it changed. It's enough to imagine it.",
      "The retrospective comparison is a thought experiment: take one specific output or process from the past week and think — what would it have looked like without AI? How long would it have taken? What would the result have looked like? How much energy would it have cost?",
      "Why this exercise is so powerful: the brain remembers changes better when comparing them to an alternative. Not 'what got better', but 'how would it have been otherwise'.",
      "Three types of comparison:",
      [
        "Time: this output took 15 minutes with AI. Without AI it would have been 45 minutes — or I wouldn't have done it at all.",
        "Quality: the output I got after 2 iterations would have taken an hour manually or would have been worse.",
        "Energy: this week I didn't get stressed about repetitive things — because I knew I could handle them quickly.",
      ],
      "This isn't bragging about AI. It's a way to build motivation for continuing — based on real data, not random enthusiasm.",
      "Week four is nearing its end. Three days left — and they're the days that determine whether what you've learned sticks or disappears.",
    ],
    taskIntro: "Choose three things from last week and for each write:",
    taskItems: [
      "What you did with AI — specific output or saving",
      "How it would have looked without AI — time, quality, or energy",
      "One insight: what will you take forward from this comparison",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: how to build an AI habit that outlasts motivation.",
  },
  {
    day: 26,
    title: "Knowing isn't enough. A habit is a different thing.",
    subject: "Building an AI habit — how to embed it into your day.",
    preheader: "Motivation comes and goes. A habit stays.",
    concept: [
      "After 25 days you know more about AI than most people know after months of experimenting. But knowledge disappears if there's no habit behind it. And a habit doesn't come from motivation — motivation fluctuates. A habit comes from routine.",
      "The science of habits says three elements make behavior lasting: a cue, a routine, and a reward. That applies exactly to AI too.",
      [
        "Cue: a specific moment that reminds you AI could help — opening your computer in the morning, before a meeting, when starting to write",
        "Routine: a specific action, not a general goal — 'I'll open AI and write a prompt for today's report' not 'I'll use AI more'",
        "Reward: an output you'll actually use — concrete value, not just 'I was productive'",
      ],
      "The most common mistake: a big ambitious plan. 'I'll use AI for ten things every day' won't last. 'Every Monday morning I'll write my weekly priorities with AI' will last.",
      "A good AI habit is small, specific, and attached to something you already do anyway. Add AI to something you already do every week — and you don't have to build a new routine from scratch.",
      "The key question: what do you do every week that could be done better with AI? Find that one thing. Add AI to it. Repeat for four weeks. Then add a second thing.",
    ],
    taskIntro: "Design your AI habit for next month:",
    taskItems: [
      "Choose one thing you do every week — where AI would help",
      "Write a concrete routine: when, what you'll do, what prompt you'll use",
      "Set a reminder — calendar, sticky note, or anything that reminds you for the first three weeks",
    ],
    taskType: "ol",
    taskTip: "Write it down by hand in a notebook, or open Notion, Google Docs, or Apple Notes.",
    teaser: "Second-to-last day: you'll set up your daily AI ritual — five minutes in the morning that change the whole day.",
  },
  {
    day: 27,
    title: "Five minutes in the morning that change the whole day.",
    subject: "Set up your daily AI ritual.",
    preheader: "One moment every day is more than an hour once a week.",
    concept: [
      "The strongest AI habits aren't big. They're small, regular, and attached to the start of the day.",
      "A morning AI ritual — five minutes in the morning — can set the context for the whole day, identify priorities, and start the most important work before the flood of emails and notifications begins.",
      "What a five-minute morning AI ritual might look like:",
      [
        "Agenda: 'I have this planned today. Write me three priorities and what to prepare for each meeting.'",
        "Writing: 'Today I need to write [text]. Write me a draft, I'll start from that.'",
        "Prep: 'Today I have a meeting with [client] about [topic]. Write me 5 questions.'",
        "Reflection: 'What did I do yesterday? [short overview] Write me one recommendation for today.'",
      ],
      "The ritual doesn't need to do everything. Just one thing — the one that gives you the greatest return for 5 minutes. Over a month that's 20 rituals. Over a year, 240 calm and prepared mornings.",
      "Don't be afraid to adjust it. A ritual that works perfectly on Monday may not work on Thursday. A good ritual is flexible — it has a fixed structure but variable content.",
      "This is the second-to-last day of the challenge. Tomorrow is the wrap-up. Today you'll set up the thing that stays — even after the challenge ends.",
    ],
    taskIntro: "Set up your morning AI ritual — concretely:",
    taskItems: [
      "Choose one thing you want to use AI for every morning — agenda, writing, prep, or reflection",
      "Write the specific prompt you'll repeat (save it in your second brain from D22)",
      "Set a reminder for 5–7 minutes in the morning for the next two weeks — the first three weeks are critical",
    ],
    taskType: "ol",
    taskPrompt: "Today I have planned: [short overview]. My biggest priority is: [what's most important]. Write me: 1) three priority tasks for today, 2) what to prepare for the most important meeting or task.",
    taskTip: "Save the prompt in your second brain — and set it up as your 'morning ritual'.",
    teaser: "Tomorrow is the last day. Wrap-up, reflection — and what comes next.",
  },
  {
    day: 28,
    title: "28 days. What you learned — and what comes next.",
    subject: "Basic challenge wrap-up. Here's what you take away.",
    preheader: "End of the basics. Beginning of systems.",
    concept: [
      "Twenty-eight days are behind us.",
      "You went through the fundamentals: AI as leverage, not just speed. The anatomy of a good prompt. Working with context. Iteration. Templates. Repetitive work. A daily ritual. And — most importantly — a way of thinking about work that changes even if you stop using AI.",
      "What you learned in the Basic challenge:",
      [
        "Good prompt = role + task + context + format — and why each part matters",
        "Iteration as a way of working — the first output is a foundation, not a final product",
        "Repetitive work as a signal for a template or workflow",
        "Second brain — where to store outputs so they don't disappear",
        "AI habit as routine, not motivation — small, regular, attached to the day",
      ],
      "What comes in the Advanced version of the challenge:",
      [
        "3C framework: Capture, Clean, Connect — a system for working with information and knowledge",
        "PACT framework: Projects, Agents, Context, Tools — how to involve AI in project work",
        "Five superpowers you gain through AI collaboration — Perception, Intelligence, Memory, Creation, Connection",
        "Leverage at the system level — workflow, team deployment, end-to-end processes",
      ],
      "The Basic challenge got you on your feet. The Advanced challenge will teach you to run.",
      "But right now — celebrate what you learned. 28 days, 5–7 minutes a day. That's not nothing. Most people never finish.",
    ],
    taskIntro: "The last challenge task — final reflection:",
    taskItems: [
      "Three biggest insights from the whole challenge — concrete, not general",
      "One place where AI changed how you work — specific output or routine",
      "One goal for the next 30 days — what you'll do differently with AI, specifically",
    ],
    taskType: "ol",
    taskTip: "Save the final reflection in your second brain — read it in 3 months and see how far you've come.",
    teaser: "Advanced challenge: 3C, PACT, Superpowers — and systems that work for you.",
  },
];
