import type { ChallengeDay } from "./types";

export const challengeDataAdvancedEN: ChallengeDay[] = [
  {
    day: 0,
    title: "You have the basics. Now comes the system.",
    subject: "Advanced start: 3C, PACT, Superpowers.",
    preheader: "For those who have the fundamentals. Now it's time to go further.",
    teze: "The basics of AI aren't enough — a system decides whether progress lasts or disappears within a month.",
    concept: [
      "You're here because you already have the basics. You know how to give AI a task. You may even use it every day. And still you feel there's more — that you're getting a fraction of what AI could offer.",
      "That's exactly why this version of the challenge exists.",
      "We're not starting with what AI is and how to use it. We're starting with the question: how do you build a system that works — even when you're not actively managing it?",
      "This challenge has three layers:",
      [
        "3C framework — Capture, Clean, Connect: how to turn knowledge chaos into something you can actually use",
        "PACT framework — Projects, Agents, Context, Tools: how to think about AI as a system, not a collection of tricks",
        "Superpowers — five capabilities you genuinely develop through AI collaboration: Perception, Intelligence, Memory, Creation, Connection",
      ],
      "And a fourth layer that closes everything: Scale — how to turn what you've built into a system that works for you.",
      "Each day takes 5–10 minutes. The theory is shorter and more concrete. The practice focuses on things you can use immediately.",
      "First step: think about where AI falls short for you. Not generally — but specifically. Where do you have to rewrite the output? Where do you lose time with AI instead of saving it? Where does it hit a wall?",
      "This is your starting point. It's not self-criticism — it's mapping the terrain. The next 30 days will be more concrete when you know where you're starting from.",
    ],
    taskIntro: "Write 3 things where AI falls short for you or where you want to go significantly deeper. Be specific:",
    taskItems: [],
    taskType: "text",
    taskFallback: `If you're not sure where to start, answer these three questions:
– Where do I always have to significantly rewrite AI's output?
– What do I do repeatedly where AI doesn't help the way I'd like?
– Where do I feel others are getting more from AI than I am?

Examples from practice:
→ Outputs for clients are too generic — I always have to rewrite them into project context.
→ I don't know how to involve AI in strategic planning without getting shallow results.
→ I use AI for content, but I'm missing a system for keeping what works.`,
    taskExample: `Input: "Where does AI fall short for me?"

Three concrete records:
1. Proposal writing: AI suggests a structure but doesn't know the client context — I always rewrite 60% of it.
2. Project retrospectives: I don't know how to systematically capture insights and give them to AI as context.
3. Team delegation: I use AI myself, but I don't know how to introduce a system for the whole team.`,
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow we'll look at the 3C framework — and why knowledge chaos slows down even good prompts.",
  },
  {
    day: 1,
    title: "3C framework: Capture, Clean, Connect as one system.",
    subject: "Why knowledge chaos slows down even good prompts.",
    preheader: "Knowledge without a system isn't knowledge. It's just data.",
    teze: "Knowledge without a system isn't knowledge — it's data you won't be able to retrieve when you need it.",
    concept: [
      "One of the most common reasons AI outputs are mediocre has nothing to do with the prompt itself.",
      "It has everything to do with the input. With what you give AI to work with.",
      "If you're working with chaos — notes everywhere, ideas unwritten, lessons from projects lost in emails — then even the best prompt produces mediocre results. Garbage in, garbage out applies to AI doubly so.",
      "The 3C framework is a system for working with knowledge in the context of AI. Three steps, one system:",
      [
        "Capture — saving things worth keeping: what's worth retaining and what isn't. Filtering is a skill, not just a habit.",
        "Clean — processing raw material into usable knowledge. This is the step most people skip.",
        "Connect — linking old knowledge to current work. An old insight can unlock a new solution.",
      ],
      "Three steps that only work as a whole:",
      [
        "Capture without Clean = a pile of notes you never use",
        "Clean without Connect = isolated knowledge without context",
        "Connect without Capture = linking things you never actually captured",
      ],
      "In the days ahead we'll break each step into theory and practice. But today the most important insight is this: the highest quality outputs from AI don't come from the cleverest prompts. They come from the best context. And context comes from a system.",
    ],
    taskIntro: "Think about how you currently work with knowledge from your work. Answer three questions:",
    taskItems: [
      "Where do you capture insights, ideas, and important information from work? (one place, or chaos?)",
      "How do you process raw material — notes, transcripts, rough drafts — into something usable?",
      "How do you return to old knowledge and insights when you're solving a new problem?",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow we'll look at the first step — Capture: what's worth saving and what isn't.",
  },
  {
    day: 2,
    title: "Capture: not everything is worth saving.",
    subject: "Filtering is a skill, not just a habit.",
    preheader: "Capturing everything is just as bad as capturing nothing.",
    teze: "Capturing everything is just as bad as capturing nothing — filtering is a skill, not just a habit.",
    concept: [
      "The first step of the 3C system is Capture — saving valuable information from your work.",
      "But here's the problem most people fall into: they try to capture everything. And the result is a pile of notes they never pull anything useful from.",
      "Capture isn't about maximum retention. It's about filtering. A good filter teaches you to see what has lasting value — and what's just momentary noise.",
      "Filter principles — what's worth capturing:",
      [
        "Practical insights: what worked, what didn't, what you'd decide differently next time",
        "Recurring patterns: what happens regularly — in projects, communication, decisions",
        "Context for AI: information you'll want to give AI as context — about a client, project, yourself",
        "Decisions and their reasons: not just what was decided, but why",
      ],
      "What you don't need to capture:",
      [
        "General information that's easily searchable at any time",
        "Facts without context or without connection to your specific work",
        "Things that probably won't come back and aren't transferable",
      ],
      "Practical test: if you read a captured note three weeks from now — will it still be relevant? If yes, capture it. If not, skip it.",
      "Today's goal: understand your filter and capture five things from the current week that genuinely have lasting value.",
    ],
    taskIntro: "Capture 5 things from this working week that are worth keeping. For each, write one sentence: why you captured it.",
    taskItems: [],
    taskType: "text",
    taskFallback: `If you're not sure what to capture, use this prompt:

"Help me capture the key things from this working week. Ask me 5 questions focused on: what worked, what didn't, what decision I made and why, what surprised me, and what I'd do differently next time."

Answer the questions — you have the basis for 5 captured things.`,
    taskExample: `Input (raw material from the week, given to AI):
"This week: meeting with client about contract renewal, report draft, internal project retrospective, new vendor — first call, Q2 budget rejected."

AI output — 5 things worth capturing:
1. Client — meeting: what specific objections came up and how I responded. (Why: prepare answers next time)
2. Retrospective: three things the team would do differently. (Why: patterns that repeat)
3. New vendor: first impression, key collaboration parameters. (Why: context for future negotiations)
4. Rejected budget: what the real reason for rejection was. (Why: pattern for future requests)
5. Report draft: what worked in the structure, what was unclear. (Why: foundation for a template)`,
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Capture in practice — how to build capturing into your workday without being overwhelmed.",
  },
  {
    day: 3,
    title: "Capture in practice: a system that takes no more than 2 minutes.",
    subject: "How to build capturing into work without being overwhelmed.",
    preheader: "The best system is the one you actually use.",
    teze: "The best Capture system isn't the most thorough — it's the one you actually use even in demanding weeks.",
    concept: [
      "The theory of Capture is clear. The practice is another thing — because most people start capturing, keep it up for two weeks, and then stop. Not because they don't want to. But because the system was too complex.",
      "The rule: the best Capture system is the simplest one that genuinely works for you. One inbox. One place. Two minutes.",
      "Three Capture patterns that work in practice:",
      [
        "End-of-day note: 3 sentences at the end of the workday — what happened, what you learned, what to do differently",
        "Meeting capture: right after a meeting — two minutes, three things: what was decided, what I need to do, what surprised me",
        "Inbox first: one place for everything — Notion, Apple Notes, or paper — and once a week you process it",
      ],
      "How AI helps with Capture: you don't need to write clean notes right away. Dump rough notes into AI — fragmented sentences, abbreviations, stream of thought. AI structures it. That makes Capture faster and less painful.",
      "Example Capture prompt: I have these rough notes from a meeting: [paste notes]. Extract: 1) what was decided, 2) what I need to do and by when, 3) the most important insight.",
      "The key mistake: having too many places for Capture. Every extra place is a place where information disappears. One place, consistently. A week is enough to find out if it works.",
    ],
    taskIntro: "Set up your Capture system — concretely, not generally:",
    taskItems: [
      "Choose one place to capture — Notion, Apple Notes, Google Docs, paper (one, not several)",
      "Choose your pattern: end-of-day note, meeting capture, or weekly inbox — which fits you better?",
      "Right now, capture 3 things from today or yesterday — test your system today",
    ],
    taskType: "ol",
    taskPrompt: "I have these rough notes from a meeting or day: [paste notes]. Extract: 1) what was decided or what is the key conclusion, 2) what I need to do and by when, 3) the most important insight worth keeping.",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Clean — why saving a note and processing a note are two different things.",
  },
  {
    day: 4,
    title: "Clean: processing is not the same as storing.",
    subject: "Clean — raw material becomes knowledge only after processing.",
    preheader: "A pile of notes isn't a knowledge system. It's just a pile.",
    teze: "A pile of notes isn't a knowledge system — raw material only becomes knowledge after processing.",
    concept: [
      "The second step of the 3C system is Clean — processing raw material into usable knowledge.",
      "Here's the biggest gap in most systems: people capture but don't clean. And the result is a pile of raw material you can't efficiently extract anything from.",
      "The difference between storing and processing:",
      [
        "Storing: I copied the meeting transcript into Notion",
        "Processing: from the transcript I extracted three key decisions, two tasks with deadlines, and one strategic insight — and tagged each one for easy searching",
      ],
      "Why Clean is critical: AI needs structured context, not raw chaos. The better the input material is processed, the more relevant the output.",
      "How Clean works in practice:",
      [
        "Extraction: pull the key points from a long piece of material — decisions, tasks, insights",
        "Formatting: rewrite raw material into a consistent structure you can quickly read next time",
        "Tagging: add a category or keyword — so it's easy to find later",
        "Compression: from an hour of notes, make five bullets — what you actually need",
      ],
      "AI as Clean assistant: paste raw material, give a Clean instruction, get structured output. Then verify and save. Clean with AI takes 3 minutes instead of 20.",
      "Today's goal: take raw material from D2 or D3 and run it through the entire Clean process.",
    ],
    taskIntro: "Take raw material from your Capture system and run Clean:",
    taskItems: [
      "Open raw material — meeting notes, day record, or anything from D2/D3",
      "Give AI the Clean instruction (see prompt below) or do it manually: extract key points, format, add context",
      "Save the result as a clean record — so that in a month you can read it and immediately understand",
    ],
    taskType: "ol",
    taskPrompt: "Here is this raw material: [paste notes or transcript]. Run Clean: 1) extract key decisions and conclusions, 2) list tasks with deadlines, 3) identify the most important insight or pattern, 4) write a one-sentence summary. Output in structured format.",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Clean in practice — how to build it into your routine so it works even in busy weeks.",
  },
  {
    day: 5,
    title: "Clean in practice: a routine that works even under pressure.",
    subject: "How to process regularly — without being overwhelmed.",
    preheader: "Clean as a habit: once a week, structured, 20 minutes.",
    teze: "Clean as a weekly routine saves more than an hour of searching — and only works if you actually repeat it.",
    concept: [
      "The theory of Clean is clear. The practice is about when and how you fit it into your working week — not as extra work, but as part of a routine.",
      "The most common mistake: trying to Clean in real time. Cleaning every record immediately after capturing is too demanding. The result is overwhelm, and then abandoning the whole system.",
      "Better approach: batch Clean. Once a week, thirty minutes, everything at once. Or a daily mini Clean: five minutes at the end of the day for three records from today.",
      "Two functional routines:",
      [
        "Weekly Clean (Friday, 20–30 min): go through the entire inbox from the week, process everything at once, archive",
        "Daily mini Clean (end of day, 5 min): three most important things from today, quick extraction",
      ],
      "How AI speeds up weekly Clean: paste all your raw records from the week into one AI conversation and give it: 'Process these records from the week. For each: extract key points, identify recurring patterns across multiple records, and suggest a processing priority.' In 10 minutes you have structure that would otherwise take an hour.",
      "Key insight: regular Clean is more valuable than perfect Clean. A perfect system that doesn't run regularly brings nothing. An imperfect system that runs every week brings a lot.",
      "After today's practice you'll have both Capture and Clean built in. Tomorrow we add the third step: Connect.",
    ],
    taskIntro: "Set your Clean rhythm and run your first weekly Clean:",
    taskItems: [
      "Decide: weekly Clean or daily mini Clean — which better fits your work?",
      "Set a recurring slot in your calendar — specific day and time",
      "Run your first Clean right now: take everything from your Capture inbox and process it using the AI prompt",
    ],
    taskType: "ol",
    taskPrompt: "Here are my raw records from this working week: [paste records]. Process them: 1) for each record extract key points, 2) identify recurring patterns or themes across multiple records, 3) suggest what is priority for future work.",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Connect — how to link an old insight to a new problem so a real solution emerges.",
  },
  {
    day: 6,
    title: "Connect: old insight, new solution.",
    subject: "Connect — linking knowledge is the most valuable part of 3C.",
    preheader: "The most valuable knowledge you have is the knowledge that leads you to a new solution.",
    teze: "The most valuable knowledge isn't new — it's what you already have, waiting to be linked to today's problem.",
    concept: [
      "The third step of the 3C system is Connect — linking your captured and processed knowledge to current work.",
      "Capture and Clean are preparation. Connect is where the value actually shows up.",
      "What Connect means in practice: when you're solving a new problem, project, or decision, you're not creating knowledge from scratch. You go back to what you captured and processed — and link it to the current situation.",
      "Three ways Connect works:",
      [
        "Analogy: 'I'm now solving X. I solved a similar situation Y before. What worked then?'",
        "Patterns: 'This project has a recurring problem Z. I've seen it in three previous projects. What was the common denominator?'",
        "Contextual input: 'I need to create a proposal for Client A. I have records on a similar Client B — I'll give them to AI as context.'",
      ],
      "How AI helps with Connect: paste your processed records from Capture/Clean as context and tell AI: 'I'm currently dealing with this situation: [description]. From my previous records, this is relevant: [records]. What patterns do you see? What from previous experience is applicable?'",
      "Key insight: people who get the best outputs from AI don't write the best prompts. They have the best context. And context comes from a working Capture, Clean, Connect system.",
      "After today you have the entire 3C system — at least as theory. Tomorrow we'll do a review: where the system works, where there are gaps, and what you'll take forward.",
    ],
    taskIntro: "Take a current problem or project you're working on and run Connect:",
    taskItems: [
      "Choose a current problem or decision you're dealing with",
      "Go through your Capture/Clean system: what from previous records is relevant?",
      "Give AI the current problem + relevant records as context and ask for pattern analysis and recommendations",
    ],
    taskType: "ol",
    taskPrompt: "I'm currently dealing with this situation: [description of situation or problem]. From my previous records, this is relevant: [paste records]. What patterns do you see? What from previous experience or insights can be applied to the current situation?",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Connect in practice — link an old insight to today's problem.",
  },

  {
    day: 7,
    title: "Connect in practice: link an old insight to today's problem.",
    subject: "Connect isn't a metaphor — it's a concrete work step.",
    preheader: "The most valuable knowledge isn't new. It's what you already have.",
    teze: "Three words that change the way you work: 'Do I have anything on this?'",
    concept: [
      "The theory of Connect is clear: you return to old captured and processed knowledge and link it to a current problem. The practice is harder — because it requires one transition most people skip: deliberately asking before you start from scratch.",
      "The Connect prompt — three words that change the way you work: 'Do I have anything on this?'",
      "Three situations where Connect works most powerfully:",
      [
        "A new project in a similar area — notes from a previous project can save days of work",
        "A recurring decision — if you've dealt with a similar decision before, what did you find out?",
        "A challenge that seems new — check whether it's actually new or just phrased differently"
      ],
      "How AI helps with Connect: you don't need to go through your notes yourself. Paste relevant notes into AI and ask: 'How does this relate to this new problem?' or 'What from these records is relevant to [situation]?'",
      "The key Connect skill: not telling yourself 'this is different'. Looking for similar patterns before declaring a situation entirely new.",
    ],
    taskIntro: "Do your first conscious Connect on a real example today:",
    taskItems: [
      "Choose one current problem or project you're working on",
      "Go through your records from the last 3–6 months — Notion, notes, emails — and look for anything relevant",
      "Give AI: 'I have these records: [paste]. I'm now dealing with: [description]. What's relevant and how to connect it?'",
      "Write down one concrete insight that would otherwise be lost",
    ],
    taskType: "ol",
    taskPrompt: "I have these older records or notes: [paste records]. I'm currently dealing with: [description of situation or problem]. What from these records is relevant? How to connect it to the current situation? What key insight would be a shame to miss?",
    taskTip: "Even if Connect brings just one usable thing — that's a result. Connect improves as your archive grows.",
    teaser: "Tomorrow: 3C reflection — where the system works, where there are gaps, and what you take forward from week one.",
  },

  {
    day: 8,
    title: "3C reflection: where the system works and where the gaps are.",
    subject: "Week one is done — what you're taking from 3C.",
    preheader: "A system only works when you actually use it.",
    teze: "A system without reflection is theory — reflection is the moment you discover what you actually use.",
    concept: [
      "The entire first week was about the 3C framework. Today is time to pause and evaluate — not as theory, but as practice.",
      "Reflection isn't an assessment of whether you did everything 'right'. It's mapping reality: where the system works and where it hits friction. This is the most valuable information for keeping the system alive and improving it.",
      "Three questions for 3C reflection:",
      [
        "Capture: are you capturing regularly? Is the inbox overflowing or empty? What's the biggest obstacle?",
        "Clean: are you processing records or are they piling up? Is AI helping you with Clean or have you not used it yet?",
        "Connect: did you go back to an old record this week and use it? Why or why not?",
      ],
      "What to do with the reflection results: if Capture isn't working — simplify the system (one place, one pattern). If Clean is overwhelming — switch to weekly Clean. If Connect is missing — start every project or problem by first connecting it to your archive.",
      "Key insight from week one: 3C isn't about perfection. It's about consistency. An imperfect system you use every week is more valuable than a perfect system you abandon after two weeks.",
      "Next week we move to the PACT framework — and we start thinking about AI as a system for project work.",
    ],
    taskIntro: "Run a 3C reflection — briefly and concretely:",
    taskItems: [
      "Capture: is it working? What's the biggest friction point?",
      "Clean: are you processing regularly or is material piling up?",
      "Connect: did you use an old record this week? What did it bring you, or what are you missing?",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Next week: PACT framework — Projects, Agents, Context, Tools. A systematic approach to AI in project work.",
  },
  {
    day: 9,
    title: "PACT framework: Projects, Agents, Context, Tools.",
    subject: "Why a framework beats a random selection of tools.",
    preheader: "Without structure, AI becomes another tool that adds confusion.",
    teze: "Without structure, AI becomes another ad hoc tool — PACT makes it part of how you work.",
    concept: [
      "Week two of the challenge is about the PACT framework — a way to think about AI in a work context systematically.",
      "PACT stands on four elements. Each is a different layer, a different question:",
      [
        "Projects — how to involve AI in real projects with clear structure and outputs",
        "Agents — when AI agents and multi-step workflows make sense, and when they're unnecessarily complex",
        "Context — why context determines output quality more than the prompt itself",
        "Tools — how to choose tools functionally, not based on hype",
      ],
      "Why a framework instead of random tool selection: without structure, AI becomes another tool you come to ad hoc. With a framework, it becomes part of how you work.",
      "The difference in practice: without PACT you ask 'What AI tool should I try?' or 'How do I write a better prompt?'. With PACT you ask 'What result do I want to achieve and how can AI systematically help me?' — and that's a different question.",
      "PACT isn't a rigid methodology. It's a way of thinking — four questions you ask when thinking about involving AI:",
      [
        "Is this a project with a clear structure, or a one-off task?",
        "Is this a recurring complex task where an agent or workflow would help?",
        "Do I have enough context for the output to be high quality?",
        "What tool is genuinely appropriate for this situation?",
      ],
      "This week we'll break down each PACT element. The goal: by the end of the week, have clarity on how to involve AI systematically in your work context.",
    ],
    taskIntro: "Think about your current work and answer the four PACT questions:",
    taskItems: [
      "Projects: Which current project could have a clear AI-assisted structure?",
      "Agents: Do you have a complex recurring task where a multi-step workflow could work?",
      "Context: What context about yourself, your role, or your work does AI not have — that would significantly improve outputs?",
      "Tools: Which AI tools do you use and why — or do you use them randomly without a clear reason?",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Projects — how to plan a real project with AI using WBS.",
  },
  {
    day: 10,
    title: "Projects: plan a real project with AI using WBS.",
    subject: "AI as a collaborator on project structure.",
    preheader: "AI doesn't know your project. But if you describe it, it can help you break it down.",
    teze: "AI doesn't know your project — but describe it in structure and it will help break it into manageable parts.",
    concept: [
      "The first element of the PACT framework is Projects — how to involve AI in real project work.",
      "The most common mistake: AI is used on individual parts of a project (write an email, summarize a document) but not on the project as a whole. The result is fragmented help without added value at the level of the whole.",
      "Work Breakdown Structure (WBS) is a technique that breaks a project down into clear layers of outputs and steps. With AI it can be created quickly — and the result serves as the foundation for the whole project, stakeholder communication, and delegation.",
      "How WBS with AI works: you describe the project — goal, scope, key constraints — and AI helps you:",
      [
        "Identify major phases and outputs in each phase",
        "Break phases down into specific steps and responsibilities",
        "Flag dependencies and risks",
        "Suggest a rough time estimate",
      ],
      "When AI genuinely helps with Projects: when you have a project that is complex or new, when you're unclear on scope, or when you need a structure quickly for communicating with stakeholders.",
      "WBS with AI isn't the final plan — it's a starting point. A quick overview you then adjust to reality. But creating it takes 10 minutes instead of 3 hours.",
    ],
    taskIntro: "Choose one current project and have AI create a WBS for it:",
    taskItems: [
      "Write a project description: what is the goal, what is in scope, who is involved, what is the rough timeline",
      "Give AI the WBS instruction (see prompt below)",
      "Go through the result and adjust to reality — add what AI missed, remove what doesn't make sense",
    ],
    taskType: "ol",
    taskPrompt: "Create a WBS for this project: [project description — goal, scope, people involved, timeline]. Break it down into: 1) major phases with outputs, 2) specific steps in each phase, 3) dependencies between phases, 4) potential risks. Output in structured format.",
    taskFallback: `If you don't have a suitable project, use this practice task:
"Project: Implementing a new onboarding process for new employees. Goal: reduce time to full productivity from 3 months to 6 weeks. Involved: HR, direct manager, IT. Timeline: Q3."`,
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Agents — what are AI agents, when do they make sense, and when are they overkill.",
  },
  {
    day: 11,
    title: "Agents: when they make sense and when they're overkill.",
    subject: "What are AI agents and how to think about them.",
    preheader: "An agent isn't magic. It's a workflow. And a workflow has to make sense.",
    teze: "An agent isn't magic — it's a workflow, and every workflow must make sense before you put it on autopilot.",
    concept: [
      "The second element of the PACT framework is Agents — AI agents and automated workflows.",
      "What is an AI agent: simplified, it's an AI that doesn't just perform one task but a series of steps — it reacts to the result of the previous step, decides what to do next, and can call tools or other models.",
      "When agents make sense:",
      [
        "A recurring complex task where there's a clear sequence of steps and each depends on the output of the previous",
        "Processing a large volume of inputs — an agent goes through data, categorizes, filters",
        "Parallel processing — an agent runs multiple tasks simultaneously and combines outputs",
        "Monitoring or alerting — an agent watches a state and notifies when a condition is met",
      ],
      "When agents don't help or add complexity:",
      [
        "One-off or simple tasks — they add complexity without value",
        "Creative work with a high degree of human judgment — agents don't replace decision-making",
        "Tasks where input is very different each time — agents need consistent input structure",
      ],
      "Practical test for agents: does this task have a clear trigger, clear steps, and a clear output? Does it repeat regularly? If yes to both — it's a candidate for an agent. If not — a good prompt is enough.",
      "For this challenge we focus on simpler multi-step workflows — a series of prompts where the output of one step is the input of the next. Agents in the technical sense are a more advanced topic.",
    ],
    taskIntro: "Identify one recurring complex task from your work and evaluate:",
    taskItems: [
      "Does it have a clear trigger and predictable steps? (condition for a workflow)",
      "Does it repeat regularly in the same or similar structure?",
      "Sketch: what would a three-step workflow look like — what is the input, what are the steps, what is the output",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Agents in practice — you'll build a multi-step workflow for one real task.",
  },
  {
    day: 12,
    title: "Agents in practice: a multi-step workflow for a complex task.",
    subject: "Build a workflow where each step builds on the previous.",
    preheader: "One complex task. Three steps. Each depends on the last.",
    teze: "A complex task broken into three sequential steps performs better with AI than one massive prompt.",
    concept: [
      "The theory of agents is behind us. Today it's practice: you'll build a multi-step workflow for one recurring task.",
      "A multi-step workflow with AI is a sequence of prompts where the output of one step is the input of the next. You're not using an automation tool — you're working in one conversation or a series of conversations, but with clear structure.",
      "Example multi-step workflow for preparing a client proposal:",
      [
        "Step 1 — Context analysis: 'Here is information about the client and their situation. Identify key needs and potential objections.'",
        "Step 2 — Proposal structure: 'Based on the analysis from step 1, suggest a proposal structure — sections, key arguments for each section, what to emphasize first.'",
        "Step 3 — Draft: 'Write a draft proposal based on the structure from step 2. Tone: professional but friendly. Length: max 1 A4 page.'",
      ],
      "Why this structure is stronger than one prompt: each step refines the input for the next. The result is relevant to the specific situation, not generic.",
      "Where multi-step workflows add value: complex outputs (proposals, reports, strategies) where you need to analyze first and then create. A simple email or summary doesn't need a workflow.",
      "Today's goal: take the task from D10 and build a concrete three-step workflow. Then test it.",
    ],
    taskIntro: "Take the task from D10 and build a three-step workflow:",
    taskItems: [
      "Step 1: What is the input and what should AI analyze or discover?",
      "Step 2: What builds on the output of step 1 and what should AI suggest or structure?",
      "Step 3: What is the final output and what should it look like?",
    ],
    taskType: "ol",
    taskPrompt: "Step 1: [instruction for input analysis]. \nStep 2: Based on the output of step 1, [instruction for structure or proposal]. \nStep 3: Based on the output of step 2, [instruction for final output — format, tone, length].",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: how to evaluate whether an AI output in a project is worth trusting — calibrated trust checklist.",
  },

  {
    day: 13,
    title: "How to evaluate AI output quality — not by feel, but by criteria.",
    subject: "Calibrated trust: when to trust output and when to verify it.",
    preheader: "A convincing output and a correct output aren't the same thing.",
    teze: "AI optimizes for persuasiveness, not correctness — a calibrated trust checklist closes that gap.",
    concept: [
      "In project work with AI, one specific problem arises: the output looks good. The structure works, the language is convincing, the logic makes sense. And yet it may be wrong — because AI optimizes for persuasiveness, not correctness.",
      "Three types of errors that occur most often in projects:",
      [
        "Factual errors — numbers, dates, references: AI can invent them convincingly with no warning",
        "Context errors — output is generally correct but doesn't account for the specifics of your project, client, or market",
        "Assumption errors — AI assumes the situation is standard, but your case isn't standard"
      ],
      "Calibrated trust checklist — four questions for every important project output:",
      [
        "Does the output contain specific numbers or facts? → verify at least one",
        "Does the output match the specific project context or is it generic? → if generic, iterate with context",
        "Does the output assume something you didn't tell AI? → identify and explicitly verify",
        "Does the output surprise you in a good way? → that's a signal to verify, not just accept"
      ],
      "When to iterate vs. when to start over: if the output fails more than one checklist point — start over with better context. Iteration fixes output. Better context fixes the source of the problem.",
      "Rule for projects: the greater the impact of a decision, the more it's worth verifying AI output externally — with your own knowledge, a colleague, or a source.",
    ],
    taskIntro: "Take one AI output from this week's PACT work and run a quality check:",
    taskItems: [
      "Go through it using the calibrated trust checklist — answer all four questions",
      "Identify one place where AI assumed more than you told it",
      "Adjust the prompt or add context and compare the new output with the old one",
    ],
    taskType: "ol",
    taskPrompt: "This is my AI output: [paste output]. Run a quality check: 1) What facts or numbers in the output are worth verifying? 2) Where does the output assume context that wasn't provided? 3) Where is the output too generic for real use in the project?",
    taskTip: "A quality check doesn't need to be extensive — two minutes and four questions. It builds calibrated trust, not paranoia.",
    teaser: "Tomorrow: Context — why context decides more than the prompt itself.",
  },

  {
    day: 14,
    title: "Context: why context decides more than the prompt.",
    subject: "The most important part of the PACT framework — and why most people overlook it.",
    preheader: "Same prompt, different context — completely different result.",
    teze: "The same prompt with different context gives a completely different result — context is the secret weapon most people overlook.",
    concept: [
      "The third element of the PACT framework is Context — and it's probably the most important of the four.",
      "Experiment: take any prompt and give it twice — once without context and once with detailed context. The results will be as different as if they came from a different AI.",
      "Why context decides: AI processes your input and generates a probabilistic output based on what it knows. Without context, it knows general things. With context, it knows your situation. And the output matches what it knows.",
      "Three types of context that have the biggest impact:",
      [
        "Role and person context: who you are, what you do, for whom, and with what constraints — this sets the entire tone and relevance",
        "Situation context: what specifically is happening, what's at stake, what is the goal, what are the facts",
        "Output context: who the result is for, what they know about the topic, what their perspective is",
      ],
      "The biggest mistake in working with context: thinking it's about length. Context can be one sentence — if it's the right sentence. 'I'm writing a proposal for a conservative financial audience' changes the output more dramatically than three paragraphs of irrelevant context.",
      "System prompt as a context tool: a system prompt is a way to give AI persistent context for a whole conversation or for repeated use. It's like onboarding a new employee — brief them once well, and you don't have to repeat it.",
      "Tomorrow you'll write your own system prompt — context you'll use repeatedly.",
    ],
    taskIntro: "Run a context experiment — you'll see the difference immediately:",
    taskItems: [
      "Take any prompt you plan to use or regularly use",
      "First give it without context — save the result",
      "Add detailed context (who you are, what the situation is, who the output is for) and give it again",
      "Compare both outputs — write down the concrete difference",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: you'll write your working system prompt — context you'll use again and again.",
  },
  {
    day: 15,
    title: "Context in practice: write your working system prompt.",
    subject: "Write it once. Use it a hundred times.",
    preheader: "Your system prompt is your standing briefing for AI.",
    teze: "Write your working system prompt once — then use it a hundred times as a permanent briefing for AI.",
    concept: [
      "Context theory is behind us. Today you create: you'll write your working system prompt.",
      "A system prompt is a document or passage that immediately gives AI context about you, your role, and your preferred ways of working together. You add it to the beginning of every new conversation — or set it in Custom Instructions in ChatGPT or Project Settings in Claude.",
      "What a good system prompt contains:",
      [
        "Who you are: role, field, type of organization, years of experience",
        "What you do: 3–5 typical tasks, who you create outputs for",
        "How you work: preferred tone, output length, what you don't want",
        "Context about your organization or field: what's specific to your context — terminology, culture, constraints",
        "Preferred format: bullets or paragraphs, structured or free",
      ],
      "How to use a system prompt: paste it at the beginning of every new AI conversation. Or save to Custom Instructions / Project Settings. AI then immediately 'knows' who it's talking to — and outputs will be more relevant without repeated briefing.",
      "Most important property of a system prompt: it's not perfect the first time. Write the first version today, test it this week, and adjust what doesn't fit. A system prompt is a living document.",
    ],
    taskIntro: "Write your working system prompt — in 5 sections:",
    taskItems: [
      "Who I am and what I do: role, field, typical outputs",
      "Who I work for: internal team, clients, leadership — and what they know about my work",
      "How I prefer to communicate: tone, length, format",
      "What AI must not do or assume: constraints, sensitive areas",
      "Context about my organization or field: what's specific, what AI won't know without explanation",
    ],
    taskType: "ol",
    taskPrompt: "I work as [role] at [type of organization/field]. My typical tasks are: [3–5 specific things]. Outputs are created for [who]. Preferred tone: [friendly/formal/direct]. Preferred output length: [short/medium/detailed]. Format: [bullets/paragraphs]. What I don't want: [what AI shouldn't do]. Specific context: [what's important to know about my work or field].",
    taskTip: "Save the system prompt in your knowledge base — and add it as Custom Instructions in ChatGPT or Project Instructions in Claude.",
    teaser: "Tomorrow: PACT checkpoint — what from the framework you're actually using and what's bringing you value.",
  },
  {
    day: 16,
    title: "PACT checkpoint: what from the framework you're actually using.",
    subject: "Halfway through Advanced challenge — time to map where you are.",
    preheader: "A framework without reflection is just theory.",
    teze: "Halfway through Advanced — a framework without reflection stays just theory in your notes.",
    concept: [
      "Fourteen days are behind us. You've been through the entire 3C framework and the entire PACT framework. Today is reflection — not a test, but mapping reality.",
      "The most useful question of the day: which parts of 3C and PACT am I actually using and which stayed as theory?",
      [
        "3C — Capture: am I capturing regularly? Does my filter work? Am I still capturing too much or too little?",
        "3C — Clean: am I processing records or are they piling up? Is AI helping me with Clean?",
        "3C — Connect: do I go back to old knowledge or do I ignore it?",
        "PACT — Projects: did I use WBS or a structured approach on a project?",
        "PACT — Agents: do I have any workflow that runs repeatedly?",
        "PACT — Context: did I set up a system prompt and am I using it?",
        "PACT — Tools: do I know clearly why I use which tools?",
      ],
      "Key insight: it's not a problem if you're not using part of the framework. The problem is if you don't know. Reflection shows you where the opportunity is.",
      "The second half of the Advanced challenge will focus on Superpowers — five capabilities you genuinely develop through AI collaboration. And then on Scale — how to convert everything you've built into a system that works for you.",
    ],
    taskIntro: "PACT checkpoint — go through each element and evaluate:",
    taskItems: [
      "Capture, Clean, Connect: for each write one sentence — working, or where are the gaps?",
      "Projects, Agents, Context, Tools: for each write one sentence — are you using it, or did it stay as theory?",
      "One concrete improvement: what from the above do you want to actively improve over the next 14 days?",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Next week: Superpowers — five capabilities you develop through AI collaboration.",
  },
  {
    day: 17,
    title: "Five superpowers you gain through AI collaboration.",
    subject: "Perception, Intelligence, Memory, Creation, Connection.",
    preheader: "The most valuable things AI collaboration brings aren't outputs. They're capabilities.",
    teze: "The most valuable result of AI collaboration isn't output — it's new capabilities that stay even if AI disappears.",
    concept: [
      "Week three of the challenge is about Superpowers — five capabilities you genuinely develop through AI collaboration.",
      "This view is different from what most people hear about AI. Most discussion is about what AI will do for you. But even more valuable is what AI collaboration teaches you — capabilities you carry with you even without AI.",
      "The five superpowers:",
      [
        "Perception — the ability to see patterns and structure where others see chaos",
        "Intelligence — the ability to make better decisions through structured dialogue with AI as a thinking partner",
        "Memory — the ability to work with information and knowledge systematically, not relying only on your memory",
        "Creation — the ability to quickly create quality first versions and iterate — without blank page paralysis",
        "Connection — the ability to link ideas, people, and resources in ways that would take much longer without AI",
      ],
      "Why are these superpowers, not just AI features: if AI stopped existing tomorrow, these capabilities would stay with you. Pattern awareness, systematic memory work, iterative creation — these are ways of thinking that AI practice strengthens.",
      "This week we'll break each superpower into theory and practice. Today is the overview — tomorrow we go deep with the first one: Perception.",
    ],
    taskIntro: "Think about the five superpowers and answer:",
    taskItems: [
      "Which of the five comes most naturally to you — where does AI collaboration feel most natural?",
      "Which is your biggest opportunity — where do you feel AI collaboration could add the most?",
      "Write down one concrete situation from your work where each superpower could help",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Perception — how AI collaboration trains your ability to see patterns and structure.",
  },
  {
    day: 18,
    title: "Perception: you see patterns that would otherwise escape you.",
    subject: "How AI collaboration trains your ability to see structure in chaos.",
    preheader: "The most valuable thing isn't a faster output. It's a different way of seeing.",
    teze: "AI collaboration trains the ability to see patterns and signals that would stay below the surface without it.",
    concept: [
      "The first superpower is Perception — the ability to see patterns, structure, and connections where others see chaos or unrelated information.",
      "How AI collaboration trains Perception: AI very quickly finds structure in large amounts of text or data. If you work with AI regularly, you start to adopt this way of looking — you look for patterns before you start creating. You see structure before you name it.",
      "Three exercises that strengthen Perception:",
      [
        "Pattern recognition: give AI a large volume of material and ask — 'What patterns do you see? What repeats? What looks unusual?' Then try this perspective yourself next time without AI.",
        "Structure first: before every new task ask — 'What is the fundamental structure of this problem? What are the key variables?' Before you start creating.",
        "Anomaly detection: in any data input (reports, feedback, customer responses) ask AI — 'What looks unusual or unexpected here?' It trains you to see exceptions.",
      ],
      "Perception in the context of 3C: the Clean process strengthens Perception — processing raw material forces you to look for key points and patterns. After a month of Clean routine this way of looking starts to come automatically.",
      "Key insight: Perception can't be trained by reading. It's trained through practice — repeatedly looking for patterns in your own work. AI is your training partner.",
    ],
    taskIntro: "Perception exercise — take a large piece of material from your work:",
    taskItems: [
      "Choose material: meeting transcripts, customer feedback, project notes, or data from a report",
      "Give it to AI and ask: 'What patterns do you see? What repeats? What is unusual or surprising?'",
      "Compare the output with what you'd have noticed yourself — what did AI see that surprised you?",
    ],
    taskType: "ol",
    taskPrompt: "Here is [type of material]: [paste material]. Run a Perception analysis: 1) What patterns or recurring themes do you see? 2) What seems unusual or surprising? 3) What is the underlying structure or logic of this material?",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Intelligence — how AI collaboration trains your ability to make better decisions.",
  },
  {
    day: 19,
    title: "Intelligence: better decisions with AI as a thinking partner.",
    subject: "How AI collaboration trains your ability to decide better.",
    preheader: "AI won't decide for you. But it will help you make a better decision.",
    teze: "AI won't decide for you — but structured dialogue with it reveals assumptions and blind spots you'd otherwise miss.",
    concept: [
      "The second superpower is Intelligence — the ability to make better decisions through structured dialogue with AI as a thinking partner.",
      "AI doesn't decide for you. But it can help you structure a decision in a way that reveals blind spots, challenges assumptions, and shows alternatives.",
      "Four ways AI helps with decision-making:",
      [
        "Devil's advocate: 'Here is my decision. Play devil's advocate — what are the strongest arguments against it?'",
        "Assumptions: 'Here is my reasoning. What assumptions does this decision require? Which are the riskiest?'",
        "Pre-mortem: 'Imagine this decision fails in a year. What most likely caused the failure?'",
        "Alternatives: 'What are three alternative approaches to this problem that I haven't mentioned?'",
      ],
      "Why this trains Intelligence: each of these exercises forces you to break a decision into parts and examine it structurally. If you repeat this method, you start applying it automatically — even without AI.",
      "Important boundary: AI is a thinking partner, not a decision-making tool. The final decision is always yours. AI gives you breadth of view — you bring expert judgment and responsibility.",
      "Key mistake: asking AI 'what should I do?' instead of 'help me think through this situation'. The first question turns off your thinking. The second turns it on.",
    ],
    taskIntro: "Choose one decision you're currently working on and go through it with these four steps:",
    taskItems: [
      "Write your current reasoning — why you lean toward the option you currently prefer",
      "Ask AI for devil's advocate — the strongest arguments against your preferred choice",
      "Ask AI for a pre-mortem — what could cause failure in a year",
      "Incorporate the outputs into your decision-making — what did it change or confirm?",
    ],
    taskType: "ol",
    taskPrompt: "I'm working through this decision: [description of situation and your current reasoning]. \n1) Play devil's advocate — what are the strongest arguments against my preferred choice? \n2) What assumptions does my reasoning require? Which are the riskiest? \n3) Pre-mortem: if this decision fails in a year, what most likely caused the failure?",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Intelligence in practice — you'll analyze a real decision you're currently facing.",
  },
  {
    day: 20,
    title: "Intelligence in practice: analyze a real decision you're facing.",
    subject: "Structured decision-making with AI — from reasoning to action.",
    preheader: "Decision theory is one thing. Practice is another.",
    teze: "The best test of AI as a thinking partner is a real decision you're facing right now — today.",
    concept: [
      "Intelligence theory is behind us. Today it's practice — you'll take a real decision from your work context and run it through the whole process.",
      "Why practice is harder than theory: real decisions have uncertainty, an emotional component, and political context. AI helps with the analytical component — but the emotional and political component is on you.",
      "Three types of decisions where AI Intelligence adds the most:",
      [
        "Strategic decisions with unclear outcomes: where choice depends on assumptions about the future",
        "Cross-domain decisions: where you need to integrate multiple perspectives at once",
        "Decisions under time pressure: where AI quickly structures what would otherwise take hours of deliberation",
      ],
      "How to handle a decision with high emotional charge: first write to AI how you feel about the situation — without filters. Then ask for structured analysis. Separating emotion and analysis gives you clarity that's hard to reach in direct discussion.",
      "Key insight: AI sees your situation without emotion and without politics. That's both an advantage and a limitation. Advantage: clarity and breadth of view. Limitation: AI doesn't know context you never write down.",
    ],
    taskIntro: "Take a real decision from your work context and run it through the structured decision-making process:",
    taskItems: [
      "Write the situation: what you're deciding, what the options are, what's keeping you undecided",
      "Run through the four Intelligence steps from D17: devil's advocate, assumptions, pre-mortem, alternatives",
      "Write: what surprised you about the AI output or what changed? What did it confirm? What will you do differently because of this process?",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: the remaining three superpowers — Memory, Creation, Connection.",
  },
  {
    day: 21,
    title: "Memory, Creation, Connection: the remaining three superpowers.",
    subject: "Three superpowers that complete the picture.",
    preheader: "Memory, creation, connection — and how AI collaboration develops them.",
    teze: "Memory, creation, connection — three capabilities you develop through AI collaboration that lift results above average.",
    concept: [
      "Perception and Intelligence are behind us. Today we add the remaining three superpowers — and tie everything together.",
      "Memory — the ability to work with information systematically, without relying on natural memory:",
      [
        "AI collaboration forces you to capture and process (see 3C) — and this strengthens the ability to work with an external memory system",
        "In practice: system prompt, knowledge base, recurring context — these are tools of externalized memory",
        "Superpower: you stop relying on what you remember — and start building a system that works even without you",
      ],
      "Creation — the ability to quickly create first versions and iterate without paralysis:",
      [
        "AI collaboration trains you in iterative creation — the first draft is a foundation, not a final product",
        "Superpower: overcoming blank page paralysis. Whenever you don't know how to start, you have a way — ask AI for a first version",
        "In practice: complex outputs (proposals, strategies, presentations) come together faster and at higher quality",
      ],
      "Connection — the ability to link ideas, people, and resources:",
      [
        "AI collaboration exposes you to broader context — AI sees connections that would take years of experience to identify",
        "In practice: cross-disciplinary thinking, connecting seemingly unrelated things, identifying experts or resources",
        "Superpower: you learn to ask 'who or what else is solving this?' — and look for inspiration outside your own field",
      ],
      "All five superpowers together: Perception sees patterns. Intelligence structures decisions. Memory retains and retrieves. Creation realizes. Connection links. AI collaboration strengthens all of them — but they're yours.",
    ],
    taskIntro: "For each of the three remaining superpowers, write one concrete example from your work:",
    taskItems: [
      "Memory: where do you rely on your head but a system would work better? Where would externalized memory add value?",
      "Creation: where does the blank page or getting started block you? Where would an AI draft help overcome the beginning?",
      "Connection: where would connecting with another domain, field, or person bring a new perspective?",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Creation in practice — building a complex output from scratch, with iteration.",
  },
  {
    day: 22,
    title: "Creation: complex output from scratch with iteration.",
    subject: "Build a complex output in six steps.",
    preheader: "Blank page paralysis stops when you have a process.",
    teze: "Blank page paralysis stops existing once you have a process — and Creation gives you an exact process.",
    concept: [
      "The Creation superpower is today's practice. You'll take a complex output — one that would normally take hours — and run it through the full iterative process with AI.",
      "What a complex output is: not one email or short summary. But a strategy, presentation, proposal, analysis, consulting recommendation, or any output where the blank page is the biggest obstacle.",
      "Six steps for Creation with AI:",
      [
        "Define: write exactly what you want to create — for whom, why, in what format, what is the goal",
        "Structure: ask AI for a structure — overview of sections and flow logic, not the content itself",
        "Draft sections: for each section separately write a prompt — this gives more relevant content than one big prompt",
        "Synthesize: combine sections, go through the whole output — what's missing, what's excessive, what doesn't fit",
        "Refine: iterate — specific instructions for each weak part",
        "Final review: go through from the reader's perspective — is it understandable, convincing, usable?",
      ],
      "Why sections separately work better than one big prompt: each section has a different goal, different tone, different constraints. One prompt for the whole output generates the average. Prompts for sections generate the optimum.",
      "Today you'll work longer than the usual 5–10 minutes. Creation work deserves 20–30 minutes. But the output you get will be worth it.",
    ],
    taskIntro: "Choose a complex output from your work and run it through the six-step Creation process:",
    taskItems: [
      "Define: what you're creating, for whom, why, and in what format",
      "Structure: let AI suggest a structure — then adjust to reality",
      "Draft: run each section as a separate prompt, combine",
      "Refine: iterate the weak parts, finalize",
    ],
    taskType: "ol",
    taskPrompt: "We're creating a [type of output] for [recipient/audience]. Goal: [what the output should achieve]. Context: [relevant info]. \nStep 1: Suggest a structure — overview of sections with a one-sentence description of each. \nStep 2 (for each section separately): Write the [section name] section at [length] in [tone] tone.",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: Superpowers reflection — which comes naturally to you and which do you want to develop further.",
  },
  {
    day: 23,
    title: "Your AI superpowers: which comes naturally, which to develop further.",
    subject: "Superpowers week reflection — and your personal profile.",
    preheader: "The best development system is the one that starts from you.",
    teze: "Five superpowers, one priority — the fastest development comes from what naturally fits you.",
    concept: [
      "Week three is behind us. You've been through all five superpowers — Perception, Intelligence, Memory, Creation, Connection — in theory and practice.",
      "Today is reflection: not what you did, but what you're taking forward.",
      "Why Superpowers reflection matters: everyone works with AI differently. Everyone has different natural strengths. And everyone has different areas where AI collaboration is the biggest opportunity. Knowing your profile helps you invest energy where the effect will be greatest.",
      "Five questions for Superpowers reflection:",
      [
        "Perception: are you using AI for finding patterns regularly? Or is it still occasional experiments?",
        "Intelligence: did you run AI structured decision-making in a real situation? What did it bring?",
        "Memory: is your 3C system working as externalized memory? Or do you still rely mainly on your head?",
        "Creation: has AI collaboration overcome blank page paralysis? Are you iterating or still waiting for a perfect first draft?",
        "Connection: are you actively looking for connections and analogies from other fields? Or staying in a narrow context?",
      ],
      "Your Superpowers profile isn't a perfect picture — it's a starting point for further development. Week four will focus on Scale: how to convert what you've built into a system that works for you.",
    ],
    taskIntro: "Write your Superpowers profile — briefly and concretely:",
    taskItems: [
      "Your naturally stronger superpowers (1–2): where does AI collaboration feel most natural",
      "Your biggest opportunity (1): where is the greatest potential for improvement",
      "One concrete step for week four: what you'll actively do differently",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Next week: Scale — Human-in-the-loop, workflow with checkpoints, AI adoption in a team, and a system that works for you.",
  },
  {
    day: 24,
    title: "Human-in-the-loop: where you must be in the AI process.",
    subject: "How to design a system where AI works but you control.",
    preheader: "The best AI system isn't one where AI does everything. It's one that knows where you're needed.",
    teze: "The best AI system isn't the one where AI does everything — it's the one where you know exactly where you're irreplaceable.",
    concept: [
      "Week four is about Scale — converting what you've built into systems that work for you. And the first question you need to answer: where are you in the process?",
      "Human-in-the-loop (HITL) is a principle of AI system design: AI does what it does well, but humans are involved at key decision points.",
      "Why HITL matters: a fully automated system without human oversight works great — until it fails. And then it fails catastrophically. HITL systems are more robust because humans catch errors that AI doesn't see.",
      "Three types of human involvement:",
      [
        "Human-before: you define the input, context, and goal — AI then executes",
        "Human-in: you approve or correct at key steps of the workflow",
        "Human-after: AI runs the entire task, you review and approve the result",
      ],
      "How to decide where to be in the process:",
      [
        "High failure risk or large impact: human-before or human-in",
        "Low risk and a recurring structured task: human-after",
        "Creative or highly personalized output: human-before, strong context",
      ],
      "Today's goal: map one of your recurring tasks and decide where the right place for human input is.",
    ],
    taskIntro: "Take one recurring task from your work context and design its HITL structure:",
    taskItems: [
      "Describe the task: what is the input, what are the steps, what is the output",
      "Decide: human-before, human-in, or human-after — where is your added value?",
      "Write concretely: what does AI do and exactly where do you enter — what do you review, what do you approve, what do you adjust",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: map your workflow — where you are, where AI works, where the checkpoints are.",
  },
  {
    day: 25,
    title: "Map your workflow: where you are, where AI works.",
    subject: "Workflow with checkpoints — visualizing the system.",
    preheader: "A system you can't see, you can't optimize.",
    teze: "A system you can't see, you can't optimize — visualizing the workflow reveals both gaps and opportunities.",
    concept: [
      "Yesterday you decided where you are in the process. Today you visualize it — you'll draw (or write) your workflow.",
      "Why visualization matters: a workflow you only have in your head is a workflow you can't share, optimize, or delegate. Once you draw it or describe it, you see it differently.",
      "How to describe a workflow — four elements:",
      [
        "Trigger: what starts the process? (new client request, weekly rhythm, a specific event)",
        "Steps: what happens in what order? (who or what — you or AI)",
        "Checkpoints: where are the human control points?",
        "Output: what is the final result and who does it serve?",
      ],
      "How AI helps with workflow design: give AI a description of your current process and ask: 'Identify steps where AI could help, and suggest where the right checkpoints for human oversight are.' AI gives you a structured view you then adjust.",
      "Today's goal: have one recurring process described — so that someone else could read it and understand how to run it. That's the foundation for delegation or improvement.",
    ],
    taskIntro: "Write or draw a workflow for one of your recurring processes:",
    taskItems: [
      "Trigger: what starts this process?",
      "Steps in order: what happens, who does it (you or AI), what is the output of each step",
      "Checkpoints: where do you enter — what do you review or approve",
      "Final output: what is created and who does it serve",
    ],
    taskType: "ol",
    taskPrompt: "Here is a description of my process for [process name]: [description of current process]. Identify: 1) where AI could take over or assist, 2) where the right checkpoints for human oversight are, 3) what the optimized workflow would look like. Output as a structured step-by-step overview.",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: AI adoption in a team — sharing knowledge without hype or resistance.",
  },
  {
    day: 26,
    title: "AI adoption in a team: sharing knowledge without hype or resistance.",
    subject: "How to bring AI to colleagues without pressure and without technology for technology's sake.",
    preheader: "The best AI champion on a team is the one who shows results, not evangelizes.",
    teze: "The best AI champion in a team is the one who shows results quietly — not the one who evangelizes loudly.",
    concept: [
      "One of the biggest AI opportunities isn't what you can do with AI on your own. It's what a team can do when knowledge, prompts, and workflows are shared.",
      "But AI adoption in a team is a different challenge than personal AI adoption. People have different technical backgrounds, different openness to new tools, and different concerns. The 'just try it, it's great' approach isn't enough.",
      "Three AI adoption approaches for teams that work:",
      [
        "Show, don't tell: show a concrete result from your work — time saved, quality, a simpler process. Results convince more than arguments.",
        "Start small: one prompt for one recurring task the team does regularly. No big project, no new tool on top.",
        "Build a shared library: start a shared collection of prompts, templates, and workflows. Everyone contributes what works for them. The system grows organically.",
      ],
      "What slows adoption:",
      [
        "Too much hype: 'AI will change everything' creates resistance in skeptics and disappointment in enthusiasts, because reality never matches hype",
        "Technical complexity: if adoption requires a new tool or big investment, most people will put it off",
        "No clear benefit: if it's not clear what it specifically lightens for you, you have no reason to try",
      ],
      "Your role in adoption: you're not an AI evangelist. You're someone who has results — and is willing to share them. That's a powerful enough contribution.",
    ],
    taskIntro: "Prepare an adoption contribution for your team:",
    taskItems: [
      "Choose one concrete result or workflow that's working for you from the challenge",
      "Write a one-sentence description: what it is, how long it takes, what it will bring a colleague",
      "Share it with one colleague — verbally, in chat, or as a document",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: teach a colleague one AI trick — or write it as a mini guide.",
  },
  {
    day: 27,
    title: "Teach a colleague one AI trick — or write it as a mini guide.",
    subject: "Knowledge shared is knowledge doubled.",
    preheader: "The best test of whether you understand something: can you explain it simply?",
    teze: "The best test of understanding: can you explain it simply enough that a colleague uses it immediately?",
    concept: [
      "One of the best ways to deepen your own knowledge is to teach others. If you can explain how an AI prompt works, simply and without jargon — you genuinely understand it.",
      "Today's task has two variants: teach a colleague one trick in person, or write it as a mini guide.",
      "Personal teaching (5–10 minutes): choose one concrete AI trick from your repertoire, walk through one real example with a colleague, and let them try it themselves. Goal: the colleague walks away with one usable prompt.",
      "Mini guide (alternative): write a document explaining one AI trick or workflow. Contents:",
      [
        "What it is: a one-sentence description",
        "Why it works: the basic principle (simply, without theory)",
        "How to do it: step by step, with a concrete prompt",
        "Example output: what you get if you do it right",
      ],
      "Why a mini guide works better than sharing a link or tooltip: a guide is contextualized for your team and your work. A generic tutorial covers generic situations. Your guide covers your context.",
      "Bonus: if a colleague uses the mini guide and gives you feedback — what was unclear, what works differently — you'll learn more from that than from an hour of another tutorial.",
    ],
    taskIntro: "Choose a variant and do it today:",
    taskItems: [
      "Variant A: Teach a colleague one trick in person — specific prompt, real example, let them try it",
      "Variant B: Write a mini guide for one AI trick or workflow from your practice",
      "After completing: write down what surprised you — either in the colleague's responses or in the writing process",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: leverage at the system level — tool vs. way of working.",
  },
  {
    day: 28,
    title: "Leverage at the system level: tool vs. way of working.",
    subject: "The difference between 'I use AI' and 'AI is part of how I work'.",
    preheader: "The biggest leverage isn't in one great prompt. It's in the system.",
    teze: "The biggest leverage isn't in one great prompt — it's in a system where AI is part of every step of your work.",
    concept: [
      "The second-to-last topic of the Advanced challenge comes back to the beginning — but differently.",
      "At the start of the challenge, leverage was defined as: achieving a result that wouldn't otherwise be possible. Or would take ten times longer. Leverage at the individual level.",
      "Leverage at the system level is different: AI is embedded in how you work so it functions for you — even when you're not actively thinking 'how do I use AI'. It becomes part of the process, not a tool you consciously pull out.",
      "What it looks like in practice:",
      [
        "Every project kickoff automatically includes a WBS with AI — not as an extra step, but as part of how a project starts",
        "Every week the Clean routine is built in — Friday, 20 minutes, Capture inbox processed",
        "The system prompt is set and adds automatically — no manual briefing",
        "The shared prompt library in the team grows organically — everyone adds what works",
      ],
      "System leverage comes from habits and processes, not motivation. If every Monday you have to remind yourself 'today I'll use AI', you don't yet have system leverage. If AI is simply part of how you do things — you have it.",
      "Today's question: what from what you've built over 26 days has become part of your system? And what hasn't yet?",
    ],
    taskIntro: "Map your current system leverage:",
    taskItems: [
      "What from the challenge has become a routine or part of how you work? (specific things, not general)",
      "What still requires conscious effort or reminders?",
      "One concrete decision: what will you embed into your system as a regular step — with a specific timeline",
    ],
    taskType: "ol",
    taskTip: "Work directly in Claude, ChatGPT, or Gemini – save the result to Notion, Google Docs, or Apple Notes.",
    teaser: "Tomorrow: you'll build an end-to-end mini AI system — for one of your key processes.",
  },
  {
    day: 29,
    title: "Build an end-to-end mini AI system.",
    subject: "One key process — from input to output — with AI at every step.",
    preheader: "A system that works for you starts as one well-designed process.",
    teze: "A system that works for you starts as one well-designed process — and today you'll build it.",
    concept: [
      "Second-to-last day of the challenge. Today you create — and you're creating the biggest thing in the entire challenge.",
      "An end-to-end mini AI system is one concrete process from your work — from input to output — designed with AI at every relevant step, with a clear HITL structure, and documented so that someone else could follow it or use it.",
      "Five elements of a good mini AI system:",
      [
        "Trigger: what starts the process and how do I know it's time to run it",
        "Input: what I feed in — data, context, material",
        "AI steps: what AI does at each step and with what prompt",
        "HITL checkpoints: where I enter — what I review, approve, or adjust",
        "Output: what is created and who it serves",
      ],
      "Examples of mini AI systems from the world of work:",
      [
        "Weekly reporting: Trigger: Friday 2pm. Input: week's data. AI: structures summary, suggests key numbers. HITL: I verify accuracy of numbers, add context. Output: report for leadership.",
        "Client onboarding: Trigger: new client signed. Input: client info. AI: draft onboarding email sequence. HITL: I review tone, personalize. Output: sent emails.",
        "Project retrospective: Trigger: end of project. Input: notes, feedback, data. AI: structures retrospective. HITL: I add context, decide on priorities. Output: retrospective record in Capture system.",
      ],
      "Today's goal is to have one working mini AI system documented so a colleague could read it and understand how to run it.",
    ],
    taskIntro: "Build your end-to-end mini AI system — documented in five elements:",
    taskItems: [
      "Choose a process: recurring, complex, and valuable — where AI adds the most",
      "Document the five elements: trigger, input, AI steps with prompts, HITL checkpoints, output",
      "Test it once — run the whole system on a real example and write down what to adjust",
    ],
    taskType: "ol",
    taskTip: "Save the system in your knowledge base — so it's accessible to you and to colleagues.",
    teaser: "Tomorrow is the wrap-up. 30 days. What you've built — and what comes next.",
  },
  {
    day: 30,
    title: "The system is built. And now it works for you.",
    subject: "Advanced challenge wrap-up — and what comes next.",
    preheader: "End of the challenge. Beginning of the system.",
    teze: "Thirty days of systematic AI work built something lasting — a system, not just a habit.",
    concept: [
      "Twenty-eight days are behind us.",
      "You've been through the 3C framework — Capture, Clean, Connect — and built the foundation for working with knowledge in the context of AI. You've been through the PACT framework — Projects, Agents, Context, Tools — and started thinking about AI systematically, not as a collection of tricks. You've been through Superpowers — five capabilities you develop through AI collaboration. And you finished with Scale — Human-in-the-loop, workflow design, AI adoption in a team, system leverage.",
      "What you take from the Advanced challenge:",
      [
        "3C system as the foundation of knowledge work — Capture, Clean, Connect as a routine",
        "PACT as a way of thinking about AI in project and work context",
        "Five superpowers as a conscious development goal — what to train, where is the opportunity",
        "HITL as a principle of AI workflow design — where you are, where AI works",
        "At least one documented end-to-end mini AI system",
      ],
      "What comes next: this challenge is the end of a course, not the end of the journey. The systems you've built improve with every week of use. The 3C system will be better in a month than it is today. The workflow you designed will dial in after the first month of operation.",
      "One last question: what is one concrete decision you'll make in the next 30 days — one that moves your AI system forward?",
      "Take that with you.",
    ],
    taskIntro: "Final Advanced challenge reflection:",
    taskItems: [
      "Three biggest insights from the whole challenge — concrete, not general",
      "One place where AI changed how you work — systemically, not just once",
      "One concrete decision for the next 30 days — what you'll embed or improve",
    ],
    taskType: "ol",
    taskTip: "Save the final reflection in your knowledge base — read it in 3 months and see how far you've come.",
    teaser: "You built the system. Now use it. Results come — not from motivation, but from consistency.",
  },
];
