import type { ChallengeDay } from "./types";

export const challengeDataBasicCZ: ChallengeDay[] = [
  // ─── TÝDEN 1: Mindset + leverage + základ (D0–D6 z originálu) ───────────────

  {
    day: 0,
    title: "Tohle není kurz. Je to nový způsob práce.",
    subject: "Začínáme. Takhle funguje challenge.",
    preheader: "28 dní, 5–7 minut denně. Jeden opravdový posun.",
    concept: [
      "AI je dnes všude. Nové nástroje, nové funkce, nové sliby. A právě proto je snadné skončit u toho, že člověk jen zkouší další a další věci — ale ve skutečnosti se jeho práce moc nemění.",
      "Tahle challenge vznikla proto, aby pomohla udělat pravý opak.",
      "Nejde o to naučit se co nejvíc AI nástrojů. Jde o to začít AI používat prakticky, pravidelně a tak, aby opravdu ulehčovala práci. Tohle je AI-first přístup: způsob přemýšlení je důležitější než jakýkoliv konkrétní nástroj.",
      "Každý den ti zabere přibližně 5–7 minut. Každý den si odneseš něco použitelného:",
      ["nový pohled na práci", "malý praktický krok", "konkrétní výstup nebo drobné zlepšení něčeho, co už děláš"],
      "Tato verze challenge — Basic — se soustředí na základy. Na to, jak AI přemýšlí, co od ní realisticky čekat, jak psát zadání, která fungují, a jak ji zapojit do věcí, které děláš každý den.",
      "A ještě jedna důležitá věc: když narazíš na něco, co už znáš, nevadí to. Každou výzvu lze prohloubit — upravit prompt, vylepšit šablonu, zabudovat do reálné práce.",
      "Smyslem téhle challenge není stihnout všechno. Smyslem je posouvat se každý den o kousek dál. Stačí málo. Pět minut. Jedna myšlenka. Jeden krok.",
    ],
    taskIntro: "Sepiš si 3 věci, které ve své práci nebo běžném dni děláš opakovaně ručně. Nemusí to být nic velkého — stačí drobnosti, které se vracejí znovu a znovu. Budeme se k nim v challenge vracet.",
    taskItems: [],
    taskType: "text",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: proč se v práci neplatí za práci, ale za výsledek — a jak tohle mění zadávání úkolů AI.",
  },

  {
    day: 1,
    title: "V práci se neplatí za práci. Platí se za výsledek.",
    subject: "Jeden posun v myšlení, který mění výsledky.",
    preheader: "Aktivita vs. výsledek — klíčový rozdíl pro AI-first přístup.",
    concept: [
      "Když je toho hodně, většinou automaticky řešíme jednu věc: jak všechno stihnout.",
      "Jenže právě tady se láme rozdíl mezi běžným fungováním a AI-first přístupem.",
      "Nejde totiž jen o to udělat věci rychleji. Nejdřív je potřeba se zastavit a podívat se, co je vlastně skutečný výsledek, kterého chceme dosáhnout.",
      "Ne vždy se platí za to, že:",
      ["napíšeš email", "připravíš prezentaci", "vytvoříš dokument", "nebo strávíš hodinu rešerší"],
      "Platí se za to, že:",
      ["někdo dostane jasnou informaci", "vznikne rozhodnutí", "posune se projekt", "nebo se něco kvalitně připraví"],
      "Jakmile začneš víc přemýšlet o výsledku než o samotném úkolu, začneš mnohem snáz vidět, co lze zjednodušit, co zadat AI, co nemusí začínat od nuly — nebo co možná vůbec nemusíš dělat.",
      "Neptat se jen: Jak to udělám? Ale nejdřív: Čeho tím vlastně chci dosáhnout? Tento rozdíl — aktivita vs. výsledek — mění způsob, jak s AI pracuješ. Bez tohoto posunu je AI jen rychlejší způsob dělat totéž. S tímto posunem je nástrojem pro správné věci.",
    ],
    taskIntro: "Vyber si jeden úkol, který dnes řešíš, a napiš si k němu dvě věci:",
    taskItems: ["Jak ten úkol zní teď (aktivita)", "Jaký je skutečný výsledek, kterého chceš dosáhnout"],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: cokoliv děláš podruhé, by nemělo začínat od nuly — princip OHIO a jak ti ušetří energii.",
  },

  {
    day: 2,
    title: "Cokoliv děláš podruhé, už by to nemělo začínat od nuly.",
    subject: "Co děláš podruhé, přestaň psát od nuly.",
    preheader: "Opakování je signál — ne výzva pracovat rychleji, ale postavit šablonu.",
    concept: [
      "Spousta práce nevypadá na první pohled složitě. Ale právě ty malé opakující se věci často berou nejvíc energie.",
      "Když něco děláš opakovaně, je to signál. Ne signál, že máš být rychlejší. Ale signál, že by to mělo mít šablonu, postup, prompt nebo aspoň jednodušší výchozí bod.",
      "Tady přichází na řadu princip OHIO: Only Handle It Once. Pokud děláš něco podruhé, nastav to hned teď jednou dobře — šablonu, prompt, strukturu — a příště začínáš z výchozí pozice, ne od nuly.",
      "Existují tři typy věcí, které se v práci opakují a kde OHIO dává největší smysl:",
      ["Dokumenty — zprávy, nabídky, briefy, zápisky, souhrny", "Komunikace — follow-upy, potvrzení, odpovědi na časté otázky, úvodní emaily", "Rozhodnutí — opakující se volby, kde vždy zvažuješ stejná kritéria"],
      "AI je nejsilnější právě tam, kde se něco opakuje. Ne proto, že všechno udělá dokonale. Ale proto, že pomůže přestat začínat pokaždé znovu.",
      "Smyslem dne není vymyslet dokonalý systém. Smyslem je najít jednu věc, která se opakuje, a udělat první krok k tomu, aby se příště dělala snadněji.",
    ],
    taskIntro: "Vyber si jednu opakující se činnost a zkus si k ní napsat prompt pro tvorbu šablony ve formátu:",
    taskItems: [
      "Vytvor mi sablonu pro [dopiš typ dokumentu nebo zprávy]",
      "Sablona ma obsahovat tyto sekce: [dopiš sekce, které se vždy opakují]",
      "Vystup ve formatu [dopiš — seznam, tabulka, odstavce...]",
    ],
    taskType: "ul",
    taskPrompt: "Vytvor mi sablonu pro [typ dokumentu]. Sablona ma obsahovat: [sekce]. Vystup v [formatu].",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: AI není jen vyhledávač — největší posun nastane, když ji přestaneš ptát a začneš jí zadávat práci.",
  },

  {
    day: 3,
    title: "Kvalita zadání = kvalita výstupu.",
    subject: "Přestaň AI používat jako vyhledávač.",
    preheader: "Největší posun nastane, když přestaneš AI ptát a začneš jí zadávat práci.",
    concept: [
      "Většina lidí pořád používá AI tak, jako by to byl trochu chytřejší vyhledávač. Něco se zeptají, dostanou odpověď a tím to skončí.",
      "Jenže největší posun nastane ve chvíli, kdy AI přestaneš brát jako místo, kam něco napíšeš, a začneš ji brát jako někoho, komu zadáváš práci.",
      "Klíčový princip: kvalita zadání = kvalita výstupu. Tato rovnice platí absolutně. Vágní otázka = vágní výstup. Konkrétní zadání s kontextem = použitelný výsledek.",
      "Dobré zadání má čtyři části, které AI opravdu potřebuje znát:",
      ["Kým má být — jakou roli nebo expertízu má zaujmout (zkušený obchodník, kouč, analytik...)", "Co přesně má udělat — napsat, shrnout, analyzovat, navrhnout, přepsat...", "Co potřebuje vědět — kontext o situaci, produktu, cílové skupině, tónu a omezení", "Jak má vypadat výsledek — délka, formát, tón, struktura"],
      "Ukázka rozdílu v praxi. Vágní: Napis mi email. Konkrétní: Jsi zkušený obchodní komunikátor. Napis follow-up email klientovi, ktery videl nabidku na software pro HR, ale neodpovedel. Cilem je dostat schuzku. Ton je pratelsky a konkretni, maximalne 5 vet.",
      "Tohle je změna, která nejvíc mění kvalitu výstupů. A je to změna, kterou lze udělat hned — bez učení se nových nástrojů.",
    ],
    taskIntro: "Vezmi si jeden konkrétní prompt, který jsi napsal dříve nebo plánuješ napsat dnes, a přepracuj ho tak, aby obsahoval všechny čtyři části:",
    taskItems: [
      "Kým má AI být — napiš roli (příklad: Jsi zkušený projektový manažer s praxí v IT)",
      "Co přesně má udělat — konkrétní úkol (příklad: Napis strucny souhrn stavu projektu pro klienta)",
      "Co potřebuje vědět — kontext (příklad: Projekt je v prodlení 2 týdny, klient zatím neví proč)",
      "Jak má vypadat výsledek — formát a rozsah (příklad: Max 5 vět, profesionální tón)",
    ],
    taskType: "ul",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: Prompt Generator přístup — místo okamžité tvorby se nejdřív zeptat a pak teprve vytvořit.",
  },

  {
    day: 4,
    title: "Nejdřív se zeptej. Pak vytvoř.",
    subject: "Tvůj prompt je příliš vágní. Tady je jak ho opravit.",
    preheader: "Prompt Generator přístup: AI si doplní kontext, pak teprve tvoří.",
    concept: [
      "Spousta lidí má pocit, že umět AI znamená znát nějaké tajné formulky nebo složité triky. Ve skutečnosti velmi často stačí jedna věc: nejdřív dát AI prostor doplnit si kontext — a pak teprve tvořit.",
      "Tohle se jmenuje Prompt Generator přístup. Místo toho, abys hned zadával finální prompt, řekneš AI: nejdřív se mě zeptej na klíčové detaily, které potřebuješ vědět, a pak vytvoř výsledek.",
      "Proč to funguje? Protože AI nemá intuici ani zkušenost s tebou a tvou situací. Ptaní se nahrazuje to, co by zkušený kolega zjistil přes neformální rozhovor.",
      "Dobrý prompt má zpravidla pět složek:",
      [
        "Role — kým má AI být (expert, kouč, copywriter, analytik...)",
        "Cíl — co má přesně udělat (napsat, analyzovat, přepsat, navrhnout, shrnout)",
        "Kontext — co potřebuje vědět o projektu, situaci, cílové skupině nebo požadavcích",
        "Omezení — co nemá dělat, jak má psát, jaký je maximální rozsah",
        "Formát výstupu — odstavce, číslovaný seznam, tabulka, nadpisy, krátký text",
      ],
      "A je tu ještě jeden přístup, který funguje skvěle: přidej na konec promptu větu: Nez zacnes, poloz mi 3 doplnujici otazky, ktere zlepsit vystup. AI se sama zeptá na to, co jí chybí. A tím, že odpovíš, dáš jí lepší kontext. Výsledek bude znatelně lepší.",
      "Nejdůležitější věc je začít. Vezmi si jeden starý prompt — takový, kde výstup nebyl ideální — a aplikuj pět složek plus větu o doplňujících otázkách. Uvidíš rozdíl okamžitě.",
    ],
    taskIntro: "Vezmi si jeden prompt, kde výstup nebyl ideální, a přepiš ho s pěti složkami. Pak ho doplň větou o doplňujících otázkách.",
    taskItems: [
      "Role — kým má AI být",
      "Cíl — co přesně má udělat",
      "Kontext — co potřebuje vědět",
      "Omezení — co nemá dělat nebo jak omezit rozsah",
      "Formát výstupu — jak má výsledek vypadat",
    ],
    taskType: "ul",
    taskPrompt: "Nez zacnes, poloz mi 3 doplnujici otazky, ktere zlepsit vystup.",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: nejdůležitější otázka není jak to udělám rychleji — ale musí tohle být uděláno ručně?",
  },

  {
    day: 5,
    title: "Neřeš rychlost. Řeš leverage.",
    subject: "Zapomeň na rychlost. Řeš tohle místo toho.",
    preheader: "Leverage matice: co musíš dělat ty, co je lepší s AI, co může dělat hlavně AI.",
    concept: [
      "Nejdůležitější otázka není: Jak to udělám rychleji? Ale: Musí tohle být uděláno ručně?",
      "Leverage znamená přemýšlet o tom, co má zůstat na tobě, kde má pomáhat AI a co by vůbec nemělo projít ručně od začátku do konce.",
      "Existuje jednoduchá Leverage matice, která pomůže třídit práci do tří skupin:",
      [
        "Jen ty — práce, která vyžaduje tvoje zkušenosti, vztahy, hodnoty nebo rozhodovací pravomoc",
        "Ty + AI — spolupráce, kde říkáš směr a AI pomáhá s exekucí",
        "Hlavně AI — opakující se nebo předvídatelné úkoly, které AI zvládne s minimálním dohledem",
      ],
      "Do kategorie Jen ty patří vedení lidí, strategická rozhodnutí, osobní vztahy nebo etické úsudky. Do Ty + AI patří psaní zpráv, příprava prezentací, analýza nebo research. Do Hlavně AI patří formátování, sumarizace, přepisy, opakující se emaily nebo generování variant.",
      "Klíčová otázka, která změní způsob, jak se díváš na práci: Musím tohle dělat já, nebo musím jen dohlédnout na to, aby to bylo hotové?",
      "Tohle není o lenosti. Je to o tom být chytřejší v tom, kam se investuje pozornost. Nejcennější věc, kterou máš, je soustředěný čas — a ten stojí za to šetřit pro práci, kde opravdu záleží na tom, kdo to dělá.",
    ],
    taskIntro: "Vezmi si dnešní nebo zítřejší seznam úkolů a rozděl každý do jedné ze tří skupin podle Leverage matice:",
    taskItems: [
      "Jen já — tady musím být osobně, nedá se delegovat (napiš alespoň 2 příklady)",
      "Já + AI — zadám směr a kontext, AI pomůže s exekucí (napiš alespoň 2 příklady)",
      "Hlavně AI — předvídatelné, AI to zvládne s minimálním dohledem (napiš alespoň 2 příklady)",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: proč dokonalost zabíjí automatizaci — a jak první verze mění všechno.",
  },

  {
    day: 6,
    title: "V1 je vždy lepší než žádná verze.",
    subject: "Dokonalost tě brzdí. Dnes to změníme.",
    preheader: "Nepotřebuješ dokonalý systém. Potřebuješ první použitelnou verzi.",
    concept: [
      "Čekání na dokonalý moment je jedna z nejčastějších příčin, proč automatizace v praxi nikdy nezačne.",
      "Vždy je něco málo nedodělané. Vždy by to šlo udělat lépe. Vždy chybí jeden krok, jedna šablona, jeden nástroj. A tak se nic nezačne.",
      "Klíčový princip, který tohle mění: V1 > 0. První verze je vždy lepší než žádná verze. Tato rovnice je základ iterace s AI.",
      "Jak iterovat s AI — čtyři kroky:",
      [
        "Napiš draft — řekni AI záměr a nech ji napsat první verzi, i kdyby nebyla dokonalá",
        "Nech AI zlepšit — dej jí konkrétní feedback: co je dlouhé, co chybí, co změnit v tónu",
        "Uprav — přidej svůj pohled, zkušenost nebo kontext, který AI nemá",
        "Finalizuj — krátká kontrola, malé úpravy, hotovo",
      ],
      "Konkrétní workflow pro vytvoření šablony pro opakující se dokument: Krok 1 — dej AI jeden příklad dokumentu, který jsi napsal ručně. Krok 2 — požádej ji, aby z něj vytáhla strukturu a proměnné části. Krok 3 — nech ji vytvořit šablonu s prázdnými místy pro doplnění. Krok 4 — otestuj šablonu na dalším dokumentu.",
      "Tohle celé zabere méně než 15 minut. A výsledkem je šablona, která existuje — ne dokonalá šablona, která ještě nevznikla.",
      "Cílem není mít dnes všechno perfektní. Cílem je, aby zítra něco nemuselo vznikat znovu od nuly.",
    ],
    taskIntro: "Vyber si jednu opakující se věc — dokument, email nebo proces — a projdi 4krokový iterační workflow:",
    taskItems: [
      "Napiš AI záměr a nech ji napsat první verzi (neupravuj zatím nic)",
      "Dej AI konkrétní feedback: co zlepšit, co zkrátit, co změnit",
      "Přidej svůj kontext nebo pohled, který AI nemůže vědět",
      "Ulož výsledek jako šablonu nebo základ pro příště",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra je reflexe prvního týdne — čas zastavit se a zapsat si, co ti z prvního týdne zůstalo.",
  },

  // ─── D7: Shrnutí týdne 1 — reflexe (nový) ────────────────────────────────────

  {
    day: 7,
    title: "Týden za tebou. Co ti z něj zůstalo?",
    subject: "Reflexe prvního týdne — tři věci, které zůstávají.",
    preheader: "Znalost zapomeneš. Zapsaný poznatek ti zůstane.",
    concept: [
      "První týden je za tebou. Šest témat, šest krátkých cvičení. A teď přichází možná nejdůležitější den ze všech — reflexe.",
      "Proč je reflexe tak důležitá? Protože bez ní mizí poznatky stejně rychle, jak přišly. Mozek si pamatuje to, co zpracuje — ne to, co jen přijme. Napsat si tři věci, které ti utkvěly, je víc než přečíst deset dalších článků o AI.",
      "Reflexe není test. Nejde o to, jestli jsi všechno udělal správně. Jde o to přijít na to, co ti z prvního týdne opravdu zůstalo — a co z toho chceš vzít do týdne druhého.",
      "Tři otázky pro reflexi:",
      [
        "Co ti z prvního týdne utkvělo nejvíc? (jedna konkrétní věc, ne seznam)",
        "Kde si s AI dostal výsledek, který tě překvapil pozitivně?",
        "Co ti nefungovalo — a co bys příště zkusil jinak?",
      ],
      "Nejčastější chyba při reflexi: být příliš obecný. 'Naučil jsem se o AI' není reflexe. 'Zjistil jsem, že výsledky se zásadně zlepší, když zadám konkrétní formát výstupu' je reflexe — protože to je použitelný poznatek.",
      "Týden druhý bude stavět na tom, co ti zůstalo. Zaměříme se na strukturu promptu, kontext a první opravdový AI výstup z tvé práce.",
    ],
    taskIntro: "Zapiš si tři věci — konkrétně a stručně:",
    taskItems: [
      "Jedno největší zjištění z prvního týdne (jedna věta, konkrétní)",
      "Jeden výstup z AI, který byl lepší, než jsi čekal — co na promptu fungovalo?",
      "Jedna věc, která nefungovala — a jak bys k ní příště přistoupil jinak",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden: anatomie dobrého promptu, kontext jako nejsilnější nástroj — a první opravdový výstup z tvé práce.",
  },

  // ─── TÝDEN 2: Struktura promptu + iterace (D4+D9 a D6+D7 z originálu) ────────

  {
    day: 8,
    title: "Dobré prompty mají strukturu. Tady je ta tvoje.",
    subject: "Anatomie dobrého promptu — pět složek, které vždy fungují.",
    preheader: "Role, cíl, kontext, omezení, formát. V tomhle pořadí.",
    concept: [
      "Minulý týden jsme rozlišili dobré a špatné zadání. Teď jdeme o krok dál: naučíme se, co přesně dobrý prompt obsahuje — a v jakém pořadí to dát.",
      "Dobrý prompt má pět složek. Nemusíš je použít vždy všechny — ale čím víc z nich zadáš, tím lepší výstup dostaneš.",
      "Pět složek dobrého promptu:",
      [
        "Role — kým má AI být? Zkušený obchodník, kouč, analytik, copywriter — role dává AI způsob uvažování",
        "Cíl — co přesně má udělat? Napsat, shrnout, analyzovat, přepsat, navrhnout, vysvětlit",
        "Kontext — co potřebuje vědět? Informace o situaci, cílové skupině, produktu, omezeních",
        "Omezení — co nemá dělat? Délka, tón, tabu témata, co se nemá opakovat",
        "Formát výstupu — jak má výsledek vypadat? Délka, struktura, tón, odrážky nebo odstavce",
      ],
      "A je tu ještě jeden přístup, který funguje výborně — přidej na konec promptu větu: Nez zacnes, poloz mi 3 doplnujici otazky, ktere zlepsit vystup. AI se sama zeptá na to, co jí chybí. Výsledek bude znatelně lepší.",
      "Proč role funguje? Protože AI je trénovaná na obrovském množství textu z různých perspektiv. Když zadáš roli, přepneš AI do způsobu uvažování, který k té roli patří.",
      "Ukázka strukturovaného promptu: Jsi zkušený obchodní konzultant s praxí v B2B. Napis kratky follow-up email klientovi, ktery videl nasi nabidku ale neodpovedel 5 dni. Kontext: klient je mala vyrobni firma, ja jsem obchodni reditel, nabidka byla na ERP system. Format: max 5 vet, pratelsky ale primy ton, bez obecnych frazi.",
      "Dnes si tuto strukturu zkusíš na vlastním promptu — a uvidíš rozdíl oproti tomu, co jsi psal minulý týden.",
    ],
    taskIntro: "Vezmi jeden úkol z tvé práce a napiš prompt podle pětisložkové struktury:",
    taskItems: [
      "Role: kým má AI být? (dopiš konkrétní roli nebo odbornost)",
      "Cíl: co přesně má udělat? (konkrétní instrukce — napsat, shrnout, navrhnout...)",
      "Kontext: co AI potřebuje vědět o situaci, cílové skupině, omezeních",
      "Omezení: co nemá dělat, jak má psát, jaký je maximální rozsah",
      "Formát: délka, tón, struktura výstupu",
    ],
    taskType: "ol",
    taskPrompt: "Jsi [role]. [Konkrétní cíl]. Kontext: [co AI potřebuje vědět]. Omezení: [co nemá dělat]. Formát výstupu: [délka, tón, struktura].",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: AI mluví tvojí řečí — pokud ji to naučíš. Nastavíš si vlastní Tone of voice.",
  },

  {
    day: 9,
    title: "AI mluví tvojí řečí — pokud ji to naučíš.",
    subject: "Nastav AI svůj styl. Tady je jak.",
    preheader: "Tone of voice: jak AI přestat psát genericky a začít psát jako ty.",
    concept: [
      "Výstupy z AI mají jednu společnou slabinu: zpočátku znějí genericky. Přesně, ale bez osobitosti. Správně, ale bez tónu.",
      "Řešením je nastavit AI svůj Tone of voice — svůj styl komunikace, který pak AI reflektuje ve výstupech.",
      "Tone of voice není jen formálnost nebo neformálnost. Je to kombinace několika věcí:",
      ["Jak mluvíš s lidmi — přátelsky, přímě, odborně, konverzačně", "Co nesmí být ve výstupech — korporátní fráze, klišé, prázdná adjektiva", "Jaká slova nebo obraty jsou typicky tvoje", "Jakou délku a strukturu preferuješ"],
      "Jak AI naučit tvůj styl: nejjednodušší způsob je dát jí vzorový text, který jsi napsal sám. Může to být email, LinkedIn post, zpráva kolegovi nebo kus dokumentu. A pak říct: Analyzuj muj styl psani a popiste ho. Co je pro muj styl typicke?",
      "Prompt pro nastavení Tone of voice: Tady je vzor textu, ktery jsem napsal: [vloz text]. Analyzuj muj styl: 1) Jak pisu — ton, rytmus, delka vet. 2) Co je pro muj styl typicke. 3) Co v mem stylu neni — fraze ktere nepouzivam. Uloz si tento styl a pouzij ho pri dalsich zadanich.",
      "Jakmile AI zná tvůj styl, výstupy přestanou znít genericky. Budou bližší tomu, co bys napsal sám — jen rychleji.",
      "Toto nastavení se vyplatí udělat jednou pořádně. A pak ho přidávat jako součást promptů tam, kde záleží na tónu — emaily, LinkedIn, texty pro zákazníky.",
    ],
    taskIntro: "Napiš si svůj první Tone of voice prompt. Postup:",
    taskItems: [
      "Vezmi jeden text, který jsi napsal a který ti přijde typický pro tvůj styl",
      "Vlož ho do AI s promptem pro analýzu stylu z dnešního dne",
      "Nech AI popsat tvůj styl — co je typické, co tam není, jaký je tón",
      "Ulož si výsledný popis jako základ pro budoucí prompty",
    ],
    taskType: "ol",
    taskPrompt: "Tady je vzor textu, ktery jsem napsal: [vloz text]. Analyzuj muj styl psani: 1) Jak pisu — ton, rytmus, delka vet. 2) Co je pro muj styl typicke. 3) Co v mem stylu neni — fraze nebo pruhce ktere nepouzivam. Uloz si tento styl a pouzij ho pri dalsich zadanich.",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra si napíšeš prompt pro opravdový úkol ze své práce — a dostaneš výstup, který okamžitě použiješ.",
  },

  {
    day: 10,
    title: "Dnes tvoříš pro sebe. Prompt z tvé reálné práce.",
    subject: "Žádné cvičení — opravdový úkol, opravdový výstup.",
    preheader: "Tady se teorie mění na praxi.",
    concept: [
      "Prvních devět dní bylo příprava. Dnes je výsledek.",
      "Nejlepší způsob, jak otestovat, co ti z challenge zůstalo, je vzít opravdový úkol z tvé práce a projít celým procesem: role, cíl, kontext, omezení, formát. A pak iterovat, dokud výstup není použitelný.",
      "Proč je tohle důležité? Protože reálný úkol je vždy těžší než cvičný příklad. Máš méně ideální informace, výstup musí sedět konkrétním lidem, a záleží ti na výsledku. Právě proto je to nejlepší test.",
      "Úkoly, které na dnešní den fungují dobře:",
      [
        "Text, který budeš brzy potřebovat — email, zpráva, shrnutí, post",
        "Dokument, který připravuješ opakovaně — agenda schůzky, týdenní status, report",
        "Odpověď na otázku, kterou řešíš — návrh řešení, analýza situace, porovnání možností",
        "Výstup, který jinak děláš manuálně — přepis poznámek, strukturování informací",
      ],
      "Dobrý výsledek dnes není dokonalý výstup. Dobrý výsledek je výstup, který ti ušetří čas nebo dá základ, který dál dopracuješ.",
      "Pamatuj na iteraci: pokud první výstup není dobrý, nereklamuj to u AI — upřesni prompt. Přidej kontext, upřesni formát, změň roli. Tři kola zpravidla stačí.",
      "Výstup dnešního dne si ulož. Ve středu se k němu vrátíme a společně ho dotáhneme.",
    ],
    taskIntro: "Vyber reálný úkol ze své práce a projdi celým procesem:",
    taskItems: [
      "Zapiš si úkol a co přesně potřebuješ jako výstup",
      "Napiš prompt podle pětisložkové struktury z D8 — role, cíl, kontext, omezení, formát",
      "Zkus ho v AI, výsledek zkontroluj a udělej aspoň jednu iteraci",
      "Výstup ulož — vrátíme se k němu ve středu",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: co dělat, když výstup nesedí — konkrétní techniky pro opravu bez začínání od nuly.",
  },

  {
    day: 11,
    title: "Výstup nesedí? Tady jak ho zachránit.",
    subject: "Jak opravit špatný výstup — bez začínání od nuly.",
    preheader: "Zklamání z výsledku je informace. Víš přesně, co říct dál.",
    concept: [
      "Špatný výstup z AI je frustrace. Ale je to také informace — říká ti přesně, co chybí v zadání.",
      "Nejhorší reakce: smazat výstup a začít znovu od prázdné stránky. Nebo AI opustit a dělat to ručně. Obojí je zbytečné — a tím vyhodíš to, co AI pro tebe udělala.",
      "Správná reakce: napiš AI přesně, co nesedí. Ne vágně ('toto je špatně'), ale konkrétně ('tento odstavec je příliš obecný, přepiš ho s konkrétním příkladem z HR prostředí').",
      "Pět technik pro opravu špatného výstupu:",
      [
        "Upřesni požadavek: 'Výsledek je příliš obecný. Přidej konkrétní příklad pro [situaci].'",
        "Změň tón: 'Přepiš to méně formálně, více jako by to psal člověk, ne korporátní dokument.'",
        "Omeč rozsah: 'Zkrať na 3 klíčové body — zbytek odstraň.'",
        "Požádej o varianty: 'Napis to este tremi ruznymi zpusoby — hledám jiný úhel pohledu.'",
        "Vysvětli, proč to nefunguje: 'Příjemce zprávy nezná náš kontext — přepiš bez předpokladu, že čtenář ví o projektu.'",
      ],
      "Jedna věc, na kterou si dát pozor: AI si pamatuje kontext celé konverzace. Pokud iteruješ moc dlouho a výsledky se zhoršují, někdy pomůže začít novou konverzaci — s lepším výchozím promptem, který zahrnuje, co ses v předchozí konverzaci dozvěděl.",
    ],
    taskIntro: "Vezmi výstup z D10 nebo jakýkoli výstup, který ti nesedí, a zkus tyto kroky:",
    taskItems: [
      "Identifikuj konkrétně, co nesedí — tón, délka, obsah, nebo struktura",
      "Napiš AI instrukci opravy — konkrétně, ne obecně",
      "Porovnej původní a opravený výstup — co se změnilo?",
    ],
    taskType: "ol",
    taskPrompt: "Tento výstup nesedí, protože [konkrétní důvod]. Přepiš ho tak, aby [konkrétní požadavek na opravu].",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: vrátíme se k výstupu z pondělí a dotáhneme ho pomocí technik z dnešního dne.",
  },

  {
    day: 12,
    title: "Vrátíme se k pondělnímu výstupu. Teď ho dotáhneme.",
    subject: "Iterace v praxi — lepší výstup z toho, co máš.",
    preheader: "Dobrý výsledek nevznikne napoprvé. Vznikne napotřetí.",
    concept: [
      "Dnes je den, kdy se vše dá dohromady.",
      "Máš prompt a výstup z D10. Máš techniky z D11. Teď je čas je spojit — a dotáhnout výstup na úroveň, kterou bys opravdu použil.",
      "Proč je návrat k předchozímu výstupu tak cenný? Protože vidíš ho s odstupem. Co se ti tehdy zdálo použitelné, teď může vypadat jinak.",
      "Proces dnešního dne:",
      [
        "Otevři výstup z D10 — přečti ho znovu s čerstvým pohledem",
        "Identifikuj tři věci, které by šlo zlepšit — tón, délka, konkrétnost, struktura",
        "Napiš opravnou instrukci pro každou z nich",
        "Výsledné výstupy porovnej s originálem",
      ],
      "Nepotřebuješ opravit vše. Zaměř se na jednu nebo dvě největší slabiny. Perfekcionismus v iteraci je past — lepší je výstup, který je o 80 % dobrý a ušetřil hodinu, než dokonalý výstup, na který jsi strávil dvě hodiny iterací.",
      "Klíčový poznatek: iterace s AI není slabina. Je to způsob práce. Nejlepší pracovníci s AI nedostávají dokonalé výsledky napoprvé — dostávají je po dvou nebo třech iteracích. To je norma, ne výjimka.",
    ],
    taskIntro: "Vrať se k výstupu z D10 a proveď tři cílené iterace:",
    taskItems: [
      "Iterace 1: upřesni obsah — co přidat nebo odebrat, aby výstup lépe odpovídal skutečné situaci",
      "Iterace 2: uprav tón nebo délku — dle technik z D11",
      "Iterace 3: přidej konkrétní příklad nebo detail, který výstup zpřesní",
    ],
    taskType: "ol",
    taskPrompt: "Vezmi předchozí výstup a vylepši ho takto: 1. [co konkrétně přidat nebo změnit]. 2. [co zkrátit nebo odstranit]. 3. [jak upravit tón nebo strukturu].",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: kdy AI pomáhá a kdy to celé jenom zkomplikuje — upřímný přehled.",
  },

  // ─── D13: Kdy AI pomáhá a kdy ne (nový) ──────────────────────────────────────

  {
    day: 13,
    title: "AI není správná volba vždy. Tady kdy.",
    subject: "Kdy AI pomáhá a kdy přidává práci.",
    preheader: "Nejlepší nástroj pro každý úkol — to někdy není AI.",
    concept: [
      "Nejsofistikovanější uživatelé AI nevyužívají AI na vše. Vědí přesně, kdy ji použít — a kdy je rychlejší, lepší nebo spolehlivější udělat to bez ní.",
      "Tohle je pohled, který v tutoriálech o AI málokdy uslyšíš. Ale je to pohled, který ti přinese nejvíc.",
      "Kdy AI pomáhá nejvíce:",
      [
        "Úkol má jasnou strukturu — email, shrnutí, agenda, analýza, vysvětlení",
        "Potřebuješ varianty nebo nápady rychle — brainstorming, možnosti, alternativy",
        "Text je dlouhý a potřebuješ ho zkrátit nebo přestrukturovat",
        "Děláš to opakovaně — šablona nebo prompt ti každé příští kolo ušetří čas",
        "Potřebuješ začít — draft, osnova, první verze, od které se odrazíš",
      ],
      "Kdy AI přidává práci nebo komplikuje:",
      [
        "Potřebuješ přesná fakta, čísla nebo aktuální informace — AI může vymýšlet",
        "Rozhodnutí vyžaduje odborný úsudek nebo znalost konkrétního kontextu",
        "Výstup potřebuje být zcela osobní — AI neudrží autentický hlas bez velké práce",
        "Zadání je složité formulovat — pokud nevíš, co přesně chceš, AI to za tebe nevymyslí",
        "Krátký jednoduchý úkol — napsat jednu větu je rychlejší ručně",
      ],
      "Praktický test: pokud ti trvá napsat prompt déle, než by trvalo udělat úkol ručně — přeskoč AI. Pokud se jedná o opakující se typ úkolu, investuj do dobrého promptu teď, abys ho příště použil za 30 vteřin.",
      "Tohle není kritika AI. Je to realistický pohled na to, jak ji používat s rozumem — ne z nadšení.",
    ],
    taskIntro: "Projdi svůj typický pracovní den a roztřiď úkoly do dvou skupin:",
    taskItems: [
      "Úkoly, kde AI pomáhá — strukturované, opakující se, kde potřebuješ varianty nebo drafty",
      "Úkoly, kde je lepší bez AI — krátké jednorázové věci, kde potřebuješ přesnost nebo osobní hlas",
      "Zapiš si po třech příkladech do každé skupiny",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra je checkpoint — polovina challenge je za tebou a zapíšeš si svůj osobní prompt checklist.",
  },

  // ─── D14: Polovina — checkpoint (D14 z originálu adaptovaný) ────────────────

  {
    day: 14,
    title: "Polovina za tebou. Čas se zastavit a podívat dozadu.",
    subject: "Halfway checkpoint — co máš a co stavíš dál.",
    preheader: "Den 14 ze 28. Čas se zastavit, zhodnotit a nastavit kurz na druhou polovinu.",
    concept: [
      "Čtrnáct dní za tebou, čtrnáct dní před tebou. Čas se zastavit a podívat se, co vlastně máš.",
      "Prvních 14 dní bylo o základech: AI-first přístup, výsledek vs. aktivita, OHIO princip, kvalita zadání, Prompt Generator přístup, V1 a iterace, Tone of voice, Leverage matice — a první opravdový výstup z tvé práce.",
      "Tohle nejsou jen koncepty. Jsou to nástroje, které lze používat hned — a většina z nich se stane silnější, čím víc se propojí dohromady.",
      "Zastavení má tři účely:",
      ["Zhodnotit, co se opravdu zabudovalo do práce — co používáš, co jen znáš", "Pojmenovat, co má smysl dál rozvíjet — kde je největší potenciál pro zbytek challenge", "Připravit se na druhou polovinu — která bude o šablonách, opakující se práci a návyku"],
      "Osobní prompt checklist je jednoduše seznam věcí, které si ověříš před tím, než prompt odešleš. Nemusí být dlouhý — tři až pět bodů stačí. Ale musí být tvůj, ne zkopírovaný.",
      "Příklad checklistu (ne šablona — příklad):",
      ["Mám roli? Zadal jsem AI, kým má být?", "Mám kontext? Ví AI dost o situaci a příjemci?", "Mám formát? Ví AI, jak má výsledek vypadat?", "Mám cíl? Ví AI, čeho má výstup dosáhnout?"],
      "Checkpoint není hodnocení. Je to příležitost vědomě vybrat, na co se soustředit dál — a co z prvních 14 dní si opravdu vzít s sebou.",
    ],
    taskIntro: "Zapiš si tři věci — stačí odrážky, stačí pár slov:",
    taskItems: [
      "Tři poznatky z první poloviny challenge, které ti opravdu zůstaly (konkrétní, ne obecné)",
      "Tvůj osobní prompt checklist — 3–5 věcí, které si ověříš před odesláním každého promptu",
      "Jeden konkrétní cíl pro druhou polovinu challenge",
    ],
    taskType: "ul",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden: opakující se práce jako signál, šablony a workflows — jak ušetřit hodinu týdně.",
  },

  // ─── TÝDEN 3: Šablony + workflow (D2+D5 a D6+D7 z originálu, rozvinuté) ──────

  {
    day: 15,
    title: "Opakující se práce je nejdražší práce, co máš.",
    subject: "Identifikuj, co děláš každý týden znovu — to je signál.",
    preheader: "Ne každá opakující se práce je nutná. Ale každá stojí za pozornost.",
    concept: [
      "Spousta práce nevypadá na první pohled drahá. Jeden email tady, jedno shrnutí tam, agenda schůzky ve čtvrtek. Každá věc zvlášť trvá deset minut.",
      "Ale deset věcí každý týden je hodina. A hodina každý týden je dva a půl týdne ročně. Na jedné kategorii práce.",
      "Opakující se práce je signál. Ne signál, že máš být rychlejší. Signál, že by tato práce měla mít šablonu, prompt nebo workflow — aby příště nezačínala od nuly.",
      "Tři typy opakující se práce, kde AI pomáhá nejvíc:",
      ["Dokumenty — reporty, shrnutí, zápisky, briefy, agendy, nabídky", "Komunikace — follow-upy, odpovědi na časté dotazy, potvrzení, interní updaty", "Strukturování — přepis poznámek, organizace informací, příprava podkladů pro rozhodnutí"],
      "Nejčastější chyba: podceňovat drobnosti. 'Trvá mi to jen deset minut' zní jako argument pro to, nic neměnit. Ale deset minut opakujících se úkolů každý den je za rok dva plné pracovní týdny.",
      "Dnešní úkol je průzkum — bez nátlaku měnit cokoliv hned. Cílem je vidět mapu opakující se práce. Co trvá? Co se vrací? Co tě stojí nejvíc energie?",
    ],
    taskIntro: "Zamysli se nad svým pracovním týdnem a zapiš si:",
    taskItems: [
      "5 věcí, které děláš opakovaně — každý týden nebo každý druhý týden",
      "U každé: přibližně jak dlouho trvá a jak moc tě to stojí energie",
      "Označ hvězdičkou tu, u které je ztráta času nebo energie největší",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: z tohoto seznamu sestavíš svůj osobní seznam AI kandidátů — kde AI přinese nejvíc.",
  },

  {
    day: 16,
    title: "Sestavíš svůj osobní seznam AI kandidátů.",
    subject: "Top 5 opakujících se úkolů, kde AI může ušetřit nejvíc.",
    preheader: "Leverage matice v praxi: co předat AI, co vylepšit, co zautomatizovat.",
    concept: [
      "Včera jsi identifikoval opakující se práci. Dnes ji roztřídíš — a rozhodneš, kde AI přinese nejvíc.",
      "Ne každá opakující se práce je stejný typ příležitosti. Pomáhá ji rozdělit do tří kategorií:",
      [
        "Předat AI: AI může udělat první verzi nebo celý výstup — ty jen zkontroluj a pošli",
        "Vylepšit s AI: ty máš vstup a strukturu, AI pomáhá s formulací, délkou nebo formátem",
        "Zautomatizovat šablonou: prompt jednou dobře nastavíš, pak ho používáš opakovaně za 30 vteřin",
      ],
      "Jak rozlišit, do které kategorie věc patří: úkoly, které mají jasnou strukturu a výstup (email, shrnutí, report), jsou kandidáti pro předat nebo šablona. Úkoly, kde vstup je složitý nebo osobní (koučovací rozhovor, kreativní návrh), jsou spíše pro vylepšit s AI.",
      "Ukázka leverage matice v praxi:",
      [
        "Týdenní status pro vedení → předat AI (zadám data, dostanu draft)",
        "Odpovědi na opakující se dotazy klientů → šablona (jednou napíšu prompt, opakuji)",
        "Příprava agendy schůzky → vylepšit s AI (já mám témata, AI strukturuje)",
        "Strategická prezentace pro board → vylepšit s AI (obsah je můj, AI pomáhá s formulací)",
      ],
      "Cílem dnešního dne není udělat vše najednou. Cílem je vybrat jeden nebo dva úkoly, kde začneš — a kde bude efekt nejviditelnější.",
    ],
    taskIntro: "Vezmi seznam z D15 a projdi ho tímto filtrem:",
    taskItems: [
      "U každého úkolu rozhodni: předat AI, vylepšit s AI, nebo zautomatizovat šablonou",
      "Vyber jeden úkol v kategorii 'předat AI' nebo 'šablona' — ten je nejjednodušší na začátek",
      "Zapiš si konkrétně, jak by tam AI pomohla — co by byl vstup a co výstup",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: rozdíl mezi šablonou a workflowem — a proč na tom záleží, když chceš systém, ne jen pomůcku.",
  },

  {
    day: 17,
    title: "Šablona řeší jeden úkol. Workflow řeší celý proces.",
    subject: "Šablona vs. workflow — a kdy použít co.",
    preheader: "Šablona je odpověď. Workflow je systém.",
    concept: [
      "Šablona a workflow zní podobně. Ale jsou to dvě různé věci — a záměna je příčinou toho, proč někdo 'má šablonu', ale stále tráví stejně času.",
      "Šablona je předpřipravený výstup nebo prompt pro jeden opakující se úkol. Mám prompt pro týdenní status — zadám data, dostanu draft. Šablona řeší jeden konkrétní krok.",
      "Workflow je posloupnost kroků, která zahrnuje více šablon a rozhodnutí. Proces od schůzky k odeslání zápisku — zápis poznámek, strukturování do agendy, doplnění úkolů, odeslání. Každý krok má svoji šablonu, ale dohromady tvoří workflow.",
      "Kdy stačí šablona:",
      ["Opakující se výstup, který je vždy podobný — email, report, agenda, shrnutí", "Jednokrokový úkol, kde vstup je jasný a výstup je předvídatelný", "Začátek — první šablona je vždy nejdůležitější krok"],
      "Kdy potřebuješ workflow:",
      ["Proces má více kroků, které na sebe navazují", "Různí lidé jsou zapojeni v různých fázích", "Chybí jeden krok → celý výsledek se zhorší"],
      "Důležité: dobrá šablona není dokument. Je to prompt, který je napsaný tak konkrétně, že ho můžeš zadat AI za 30 vteřin a dostat výstup, který přímo použiješ.",
    ],
    taskIntro: "Vyber si jeden opakující se úkol ze svého seznamu a rozhodni:",
    taskItems: [
      "Je to jeden krok (šablona) nebo více kroků (workflow)?",
      "Pokud šablona: napiš si, co by měl prompt obsahovat — vstup, výstup, tón, formát",
      "Pokud workflow: napiš si kroky procesu a označ, který z nich je nejdůležitější kandidát na šablonu",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: postavíš svoji první šablonu — prompt, který budeš opakovaně používat.",
  },

  {
    day: 18,
    title: "Dnes postavíš šablonu, která ti ušetří hodinu týdně.",
    subject: "Vytvoř první opakovaně použitelný prompt.",
    preheader: "Jednou dobře. Pak za 30 vteřin pokaždé.",
    concept: [
      "Dobré šablony se nepíší na jeden zátah. Vyvíjejí se — první verze funguje na 70 %, druhá na 85 %, třetí je ta, kterou pak používáš roky.",
      "Ale někdy začít. A začít znamená napsat první verzi — i nedokonalou.",
      "Co dělá šablonu dobrou? Tři věci:",
      [
        "Je konkrétní — ne 'napiš email', ale 'napiš follow-up email klientovi, který neodpověděl na nabídku po 5 dnech'",
        "Má proměnné — místa, kde dosadíš konkrétní hodnoty: [jméno klienta], [typ nabídky], [datum]",
        "Dává konzistentní výstup — každé použití produkuje výsledek na stejné kvalitativní úrovni",
      ],
      "Jak šablonu vytvořit:",
      [
        "Vyber opakující se úkol — nejlépe takový, kde výstup bývá vždy podobný",
        "Napiš prompt, který přesně popisuje, co výstup má obsahovat, v jakém tónu a formátu",
        "Přidej proměnné — místa v promptu, kde dosadíš konkrétní detaily",
        "Otestuj šablonu na dvou různých situacích a uprav, co nesedí",
        "Ulož ji na místo, odkud ji příště rychle dostaneš — Notion, Google Docs, Apple Notes",
      ],
      "Jedna šablona týdně. Za čtyři týdny máš čtyři šablony — a každá ti ušetří 20–30 minut. To je hodina a půl týdně na věcech, které jsi dřív dělal od nuly.",
    ],
    taskIntro: "Postav svoji první šablonu — krok za krokem:",
    taskItems: [
      "Vyber opakující se úkol — nejlépe ten, který jsi označil hvězdičkou v D15",
      "Napiš prompt: role, cíl, kontext (jako proměnné), formát výstupu",
      "Otestuj ho na jednom konkrétním příkladu — funguje? Co upravit?",
      "Ulož šablonu do Notion, Google Docs nebo Apple Notes jako 'Moje AI šablony'",
    ],
    taskType: "ol",
    taskPrompt: "Jsi [role]. [Konkrétní úkol]. Kontext: [jméno/situace/specifika — dosadíš pokaždé]. Formát výstupu: [délka, tón, struktura].",
    taskTip: "Šablonu ulož jako dokument — ať ji máš rychle po ruce.",
    teaser: "Zítra: první mini AI workflow — jednoduchý systém, kde kroky navazují.",
  },

  // ─── D19–D20: Mini AI workflow + vědomý den s AI (D7 z originálu) ────────────

  {
    day: 19,
    title: "Tvůj první mini AI workflow.",
    subject: "3 kroky, jeden výstup, nulový chaos. Takhle to funguje.",
    preheader: "Workflow není složitý systém. Je to řetězec kroků, kde AI pomáhá aspoň v jednom.",
    concept: [
      "AI je nejsilnější ve chvíli, kdy se stane součástí malého workflow — ne jen nástrojem pro jednorázové použití.",
      "Mini AI workflow není složitý. Je to řetězec 2–3 kroků, kde každý krok navazuje na předchozí a AI pomáhá s alespoň jedním z nich.",
      "Tři příklady funkčních mini AI workflow:",
      [
        "Poznámky z hovoru → AI shrnutí → follow-up email: Napiš hrubé poznámky, nech AI vytvořit strukturované shrnutí s action items, z toho vygeneruj follow-up email pro klienta",
        "Nápad → osnova → draft: Napiš 2–3 větný záměr, nech AI vytvořit osnovu s hlavními body, z osnovy nech AI napsat první draft textu",
        "Briefing → zadání → followup: Vlož briefing nebo zadání od klienta, nech AI vytáhnout klíčové požadavky a otázky, vytvoř strukturované zadání pro tým",
      ],
      "Každý z těchto řetězců nahrazuje 20–40 minut ruční práce. A jakmile ho jednou nastavíš, funguje pořád.",
      "Klíč je v tom, že nepřemýšlíš o jednotlivých krocích zvlášť. Přemýšlíš o celém toku: co je vstup, co s tím udělá AI, co je výstup. I trojkrokový řetězec, který ušetří pět minut denně, má za měsíc velkou hodnotu.",
    ],
    taskIntro: "Vyber si jednu činnost, která má 2–3 navazující kroky, a popiš svůj první mini AI workflow:",
    taskItems: [
      "Co je vstup — co dostaneš nebo co vznikne jako startovní materiál",
      "Co s tím udělá AI — co jí zadáš a co má připravit",
      "Co je finální výstup — co pošleš, uložíš nebo předáš dál",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: celý den s AI vedlejší — jak to vypadá v praxi.",
  },

  {
    day: 20,
    title: "Jeden vědomý den s AI vedlejší.",
    subject: "Reálný den s AI — ne experiment, ale způsob práce.",
    preheader: "AI jako tichý spolupracovník po celý den.",
    concept: [
      "Největší posun nenastane v jednom dokonalém AI promptu. Nastane ve chvíli, kdy AI přestane být 'věc, kterou někdy zkouším', a stane se tichým nástrojem, který je přítomný celý den.",
      "To neznamená AI zapojit do každého úkolu. Znamená to být v průběhu dne pozorný na chvíle, kde by AI mohla pomoci — a ve vybraných z nich ji opravdu použít.",
      "Jak může vypadat den s AI vedlejší:",
      [
        "Ráno: rychlé shrnutí agendy nebo priorit pro dnešek — zadám AI, co mám naplánováno, dostanu přehled",
        "Před schůzkou: draft agendy nebo připravené otázky — za 2 minuty namísto 10",
        "Po schůzce: zápis z poznámek — vložím, co jsem si zapsal, dostanu čistý zápis",
        "Uprostřed dne: email, který trvá — místo 20 minut iteruju s AI draft za 5",
        "Na konci dne: krátký zápis toho, co se stalo — základ pro report nebo osobní přehled",
      ],
      "Nejdůležitější věc: nevynucovat. Pokud v jeden den AI nepoužiješ vůbec, nic se neděje. Pokud ji použiješ na tři věci a jedna z nich funguje skvěle — to je výsledek.",
      "Tohle je cíl: ne zvyk používat AI vždy, ale reflex — 'tady by AI mohla pomoci' — a schopnost to za 30 vteřin otestovat.",
    ],
    taskIntro: "Dnešní úkol je na celý den, ne jen na 5 minut:",
    taskItems: [
      "Vyber 2–3 konkrétní úkoly, u kterých dnes AI použiješ — předem si je zapiš",
      "U každého zapiš: prompt, výsledek, co jsi upravil",
      "Na konci dne napiš tři věty: co fungovalo, co ne, co příště změníš",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: každý pracuje s AI jinak — jaký je tvůj styl?",
  },

  // ─── D21: Tvůj AI styl (nový) ─────────────────────────────────────────────────

  {
    day: 21,
    title: "Každý pracuje s AI jinak. Jaký je tvůj styl?",
    subject: "Tvůj AI styl — silné stránky, preference, způsob práce.",
    preheader: "Nejlepší AI workflow je ten, který sedí tobě.",
    concept: [
      "Dva lidé se stejnými AI nástroji mohou mít zcela odlišné výsledky. Jeden je skvělý ve psaní promptů, druhý v iteraci. Jeden používá AI pro texty, druhý pro strukturování a analýzu.",
      "Tohle není problém. Je to realita — a čím dřív to přijmeš, tím lépe budeš vědět, jak AI nasadit.",
      "Tři dimenze AI stylu:",
      [
        "Typ úkolů: kde ti AI pomáhá nejvíc — texty, strukturování, brainstorming, analýza?",
        "Způsob iterace: preferuješ dostat jednu dobrou odpověď napoprvé, nebo rychlý draft a pak opravovat?",
        "Frekvence: AI jako každodenní nástroj nebo na vybrané opakující se úkoly?",
      ],
      "Není správný nebo špatný AI styl. Jsou jen styly, které fungují lépe nebo hůř pro konkrétní práci a konkrétního člověka.",
      "Proč je tohle důležité vědět: pokud budeš AI používat způsobem, který ti nevyhovuje, přestaneš ji používat. Pokud si nastavíš AI do módu, který sedí tvé práci a tvému tempu — zůstane ti.",
      "Třetí týden je za tebou. Byl o šablonách, opakující se práci a prvním mini workflow. Teď přichází čtvrtý týden — a jde o to, jak to udělat trvalým.",
    ],
    taskIntro: "Zapiš si svůj AI styl — tři věty, konkrétně:",
    taskItems: [
      "Kde ti AI pomáhá nejvíce — jaký typ úkolů (být konkrétní, ne obecný)",
      "Jak preferuješ iterovat — jeden dobrý draft, nebo rychlý základ a pak opravuješ?",
      "Jak chceš AI do práce zapojit — denně na vybrané věci, nebo situačně?",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Příští týden: jak si vybudovat druhý mozek s AI — kde ukládat výstupy a jak je opakovaně používat.",
  },

  // ─── TÝDEN 4: Druhý mozek + návyk (D10 z originálu + nové) ───────────────────

  {
    day: 22,
    title: "AI si nic nepamatuje. Ale ty si to zařídit můžeš.",
    subject: "Druhý mozek — kde ukládat AI výstupy, aby se neztratily.",
    preheader: "Výstup bez uložení je polovina hodnoty.",
    concept: [
      "Informace se dnes valí ze všech stran. Artikly, poznámky, emaily, nápady, zpětná vazba. A většina z toho zmizí dřív, než ji stihneme zpracovat.",
      "Každý AI výstup, který si neuložíš, je pryč. Příští konverzace s AI nezačíná tam, kde jsi skončil — začíná od nuly. To je vlastnost AI, ne chyba. A lze ji kompenzovat.",
      "Druhý mozek je systém pro ukládání znalostí — místo, kde se zachycují výstupy, šablony, dobré prompty a poznatky tak, aby byly použitelné i za týden, měsíc nebo rok.",
      "Proč to funguje s AI? Protože AI je nejsilnější, když má co zpracovat. Čím víc uložených podkladů a kontextu, tím přesnější výstupy AI produkuje.",
      "Co do druhého mozku patří:",
      ["Šablony a dobré prompty — ty, které opakovaně fungují", "AI výstupy, které chceš použít nebo na ně navázat", "Zápisy ze schůzek nebo dnů — připravené AI pro rychlý přístup", "Poznatky a nápady — krátké záznamy, které ti přišly v průběhu práce"],
      "Nejdůležitější vlastnost druhého mozku: musí být rychle dostupný. Pokud se k tomu dostaneš za 10 vteřin, použiješ to. Pokud za 3 minuty hledání, nepoužiješ to nikdy.",
      "Dnes si nastavíš základ — jedno místo, kam všechno půjde. Nemusí být dokonalé. Musí existovat.",
    ],
    taskIntro: "Zamysli se nad tím, kde teď informace a znalosti ukládáš. Napiš si odpovědi na tři otázky a pak nastav základ druhého mozku:",
    taskItems: [
      "Kde teď zachycuješ nápady, poznámky a zdroje (nic, hlava, appka, notebook...)",
      "Co se ti nejčastěji ztrácí — jaký typ informací bys potřeboval mít po ruce",
      "Vyber nástroj a vytvoř dokument nazvaný 'AI — šablony a výstupy' — vlož tam tři věci z challenge",
    ],
    taskType: "ol",
    taskTip: "Cíl: jedno místo, rychle dostupné. Není třeba složitá struktura — složitá struktura brání používání.",
    teaser: "Zítra: jeden dokument, který změní, jak pracuješ s AI — tvůj pracovní kontext.",
  },

  {
    day: 23,
    title: "Jeden dokument, který změní, jak pracuješ s AI.",
    subject: "Mini knowledge base — kontext, který používáš znovu a znovu.",
    preheader: "Jednou napsat. Použít stokrát.",
    concept: [
      "Je jedna věc, kterou AI znovu a znovu potřebuje, a ty ji znovu a znovu opakuješ: kontext o tobě a tvé práci.",
      "Kdo jsi, co děláš, pro koho, jak komunikuješ, jaká jsou tvoje typická témata. Každý nový chat začíná od nuly — a bez kontextu dostáváš generické výstupy.",
      "Řešení je jednoduché: napiš si jednou dobře svůj pracovní kontext. Ulož ho. A příště ho jen zkopíruj na začátek konverzace. Za 10 vteřin máš AI, která 'zná' tebe.",
      "Co do pracovního kontextu patří:",
      [
        "Tvoje role a obor — konkrétně, ne obecně ('produktový manažer v B2B SaaS' ne 'pracuji v IT')",
        "Tvoje typické úkoly — 3–5 věcí, které děláš pravidelně",
        "Tvoje cílová skupina — komu výstupy slouží (klienti, tým, vedení...)",
        "Preferovaný tón komunikace — formální, přátelský, technický, přímý",
        "Co AI nesmí dělat — co je v tvé práci citlivé nebo co nechceš v výstupech",
      ],
      "Druhá část mini knowledge base: opakující se prompty. Každý prompt, který ti za challenge fungoval, ulož. Příště ho dostaneš za 10 vteřin. Tak se buduje osobní nástroj, ne jen znalost.",
      "Cílem dnešního dne je mít dokument, který existuje a funguje. Ne dokonalou databázi — jen použitelný základ.",
    ],
    taskIntro: "Napiš svůj pracovní kontext — základ mini knowledge base:",
    taskItems: [
      "Role a obor: kdo jsi a v jakém kontextu pracuješ (2–3 věty)",
      "Typické úkoly: 3–5 věcí, které děláš pravidelně",
      "Tón a omezení: jak chceš, aby AI komunikovala — a co nesmí dělat",
      "Ulož jako první dokument do svého druhého mozku z D22",
    ],
    taskType: "ol",
    taskPrompt: "Pracuji jako [role] v [obor nebo typ firmy]. Moje typické úkoly jsou: [3–5 úkolů]. Výstupy tvoří pro [koho]. Preferovaný tón: [přátelský/formální/přímý]. Nechci v výstupech: [co nechceš].",
    taskTip: "Tento dokument zkopíruj vždy na začátek konverzace s AI — okamžitě dostaneš relevantnější výstupy.",
    teaser: "Zítra: jak poznat, že AI ti skutečně pomáhá — ne pocitem, ale konkrétně.",
  },

  // ─── D24–D25: Měření hodnoty AI + porovnání (nový) ───────────────────────────

  {
    day: 24,
    title: "Cítíš to, ale neumíš to změřit. Tady jak.",
    subject: "Jak poznat, že AI ti skutečně pomáhá.",
    preheader: "Ne 'AI mi pomáhá'. Ale proč, kde a o kolik.",
    concept: [
      "Říkat 'AI mi pomáhá' je jako říkat 'sport mi dělá dobře'. Je to pravda — ale bez konkrétnějšího pohledu nevíš, co zopakovat a co změnit.",
      "Čtyři signály, že AI ti opravdu přidává hodnotu:",
      [
        "Výstup, který by bez AI vznikl těžce nebo vůbec — ne jen rychleji",
        "Opakující se úkol, který teď trvá výrazně méně a výsledek je stejně dobrý",
        "Iterace, která přinesla výsledek, co by jinak trval hodinu ručního přepisování",
        "Nový pohled nebo nápad, ke kterému by ses sám nedostal rychle",
      ],
      "Čtyři signály, že AI práci přidává nebo neutralizuje:",
      [
        "Kontroluješ každou větu výstupu — pokud kontroluješ 100 %, ušetříš jen psaní, ne přemýšlení",
        "Opravuješ výstup víc, než trvalo napsat ho ručně",
        "Výsledek vyžaduje tak velký kontext v promptu, že je celý proces pomalejší",
        "Stres ze zadávání AI místo radosti ze spolupráce",
      ],
      "Jak měřit (jednoduše, ne složitě): jednou za týden napiš tři věci, kde AI přidala hodnotu — konkrétní výstup, konkrétní úspora, konkrétní zlepšení. Tenhle malý záznam ti za dva týdny ukáže jasný vzorec.",
      "Cílem challenge není vědět víc o AI, ale pracovat s ní lépe. Zpětná vazba je klíč.",
    ],
    taskIntro: "Retrospektiva: projdi minulé tři dny a zapiš si:",
    taskItems: [
      "Jeden konkrétní případ, kde AI přidala skutečnou hodnotu — co to bylo a čím to bylo jiné",
      "Jeden případ, kde AI práci nepomohla nebo ji zkomplikovala — proč si to myslíš",
      "Co z toho bys příště udělal jinak",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: porovnáš minulý týden s AI s hypotetickým týdnem bez ní — a uvidíš, co se změnilo.",
  },

  {
    day: 25,
    title: "Jak vypadal tento týden bez AI?",
    subject: "Zpětné srovnání — s AI vs. bez AI.",
    preheader: "Nejlepší způsob vidět pokrok: imaginární porovnání.",
    concept: [
      "Nemusíš celý týden žít bez AI, abys věděl, co změnila. Stačí si ho představit.",
      "Zpětné porovnání je myšlenkový experiment: vezmi jeden konkrétní výstup nebo proces z minulého týdne a přemýšlej — jak by vypadal, kdybys AI nepoužil? Jak dlouho by trvalo? Jak by vypadal výsledek? Kolik energie by stál?",
      "Proč je tohle cvičení tak silné: mozek si lépe pamatuje změny, pokud je porovnává s alternativou. Ne 'co se zlepšilo', ale 'jak by to bylo jinak'.",
      "Tři typy porovnání:",
      [
        "Čas: tento výstup trval 15 minut s AI. Bez AI by byl 45 minut — nebo by nevznikl vůbec.",
        "Kvalita: výstup po 2 iteracích by ručně trval hodinu nebo by byl horší.",
        "Energie: tento týden jsem se na opakující se věci nedostal do stresu — protože jsem věděl, že je zvládnu rychle.",
      ],
      "Tohle není o oslavování AI. Je to způsob, jak vybudovat motivaci pro pokračování — na základě skutečných dat, ne náhodného nadšení.",
      "Zbývají tři dny — a jsou to dny, které rozhodnou o tom, jestli to, cos se naučil, zůstane nebo zmizí.",
    ],
    taskIntro: "Vyber tři věci z minulého týdne a pro každou si napiš:",
    taskItems: [
      "Co jsi udělal s AI — konkrétní výstup nebo úspora",
      "Jak by to vypadalo bez AI — čas, kvalita nebo energie",
      "Jeden poznatek: co z tohoto porovnání si vezmeš dál",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Zítra: jak si vybudovat AI návyk, který přežije motivaci.",
  },

  // ─── D26–D27: Budování návyku + ranní rituál (nový) ─────────────────────────

  {
    day: 26,
    title: "Vědět nestačí. Návyk je jiná věc.",
    subject: "Budování AI návyku — jak ho zabudovat do dne.",
    preheader: "Motivace přijde a odejde. Návyk zůstane.",
    concept: [
      "Po 25 dnech víš o AI víc, než věděla většina lidí po měsících zkoušení. Ale vědomosti zmizí, pokud za nimi nestojí návyk. A návyk nevznikne z motivace — motivace kolísá. Návyk vzniká z rutiny.",
      "Věda o návycích říká, že tři prvky dělají chování trvalým: spouštěč (cue), rutina (routine), a odměna (reward). To platí přesně i pro AI.",
      [
        "Spouštěč: konkrétní moment, který ti připomene, že AI může pomoci — ráno při otevření počítače, před schůzkou, při začátku psaní",
        "Rutina: konkrétní akce, ne obecný cíl — 'otevřu AI a napíšu prompt pro dnešní report' ne 'budu víc používat AI'",
        "Odměna: výstup, který opravdu použiješ — konkrétní hodnota, ne jen 'byl jsem produktivní'",
      ],
      "Nejčastější chyba: velký ambiciózní plán. 'Budu každý den používat AI na deset věcí' nevydrží. 'Každé pondělí ráno napíšu týdenní priority s AI' vydrží.",
      "Dobrý AI návyk je malý, konkrétní a vázaný na věc, kterou děláš tak jako tak. Přidej AI k něčemu, co děláš každý týden — a nemusíš budovat novou rutinu od nuly.",
      "Klíčová otázka: co děláš každý týden, co se dá s AI udělat lépe? Najdi tu jednu věc. Přidej k ní AI. Opakuj čtyři týdny. Pak přidej druhou věc.",
    ],
    taskIntro: "Navrhni svůj AI návyk pro příští měsíc:",
    taskItems: [
      "Vyber jednu věc, kterou děláš každý týden — a kde by AI pomohla",
      "Napiš konkrétní rutinu: kdy, co uděláš, jaký prompt použiješ",
      "Nastav si připomínku — kalendář, sticky note nebo cokoli, co ti připomene první tři týdny",
    ],
    taskType: "ol",
    taskTip: "Zapiš si to ručně do notýsku, nebo otevři Notion, Google Docs nebo Apple Notes.",
    teaser: "Předposlední den: nastavíš si svůj denní AI rituál — pět minut ráno, které změní celý den.",
  },

  {
    day: 27,
    title: "Pět minut ráno, které změní celý den.",
    subject: "Nastav si svůj denní AI rituál.",
    preheader: "Jeden moment každý den je víc než hodina jednou za týden.",
    concept: [
      "Nejsilnější AI návyky nejsou velké. Jsou malé, pravidelné a vázané na začátek dne.",
      "Ranní AI rituál — pět minut ráno — dokáže nastavit kontext pro celý den, identifikovat priority, a zahájit nejdůležitější práci dřív, než se roztrhne vak emailů a notifikací.",
      "Jak může vypadat pětiminutový ranní AI rituál:",
      [
        "Agenda dne: 'Mám naplánováno toto. Napiš mi tři priority a co připravit pro každou schůzku.'",
        "Psaní: 'Dnes potřebuji napsat [text]. Napiš mi draft, začnu od toho.'",
        "Příprava: 'Dnes mám schůzku s [klientem] o [tématu]. Napiš mi 5 otázek.'",
        "Reflexe: 'Co jsem udělal včera? [krátký přehled] Napiš mi jedno doporučení na dnešek.'",
      ],
      "Rituál nemusí dělat vše. Stačí jedna věc — ta, která ti dává největší return na 5 minut. Za měsíc je to 20 rituálů. Za rok 240 připravených ráno.",
      "Neboj se ho upravovat. Rituál, který perfektně funguje v pondělí, nemusí fungovat ve čtvrtek. Dobrý rituál je flexibilní — má pevnou strukturu, ale proměnlivý obsah.",
      "Tohle je předposlední den challenge. Zítra bude závěr. Dnes si nastavíš věc, která ti zůstane — i po skončení challenge.",
    ],
    taskIntro: "Nastavení ranního AI rituálu — konkrétně:",
    taskItems: [
      "Vyber jednu věc, pro které chceš AI každé ráno použít — agenda, psaní, příprava nebo reflexe",
      "Napiš si konkrétní prompt, který budeš opakovat (ulož do svého druhého mozku z D22)",
      "Nastav si připomínku na 5–7 minut ráno po dobu příštích dvou týdnů",
    ],
    taskType: "ol",
    taskPrompt: "Dnes mám naplánováno: [krátký přehled]. Největší priorita je: [co je nejdůležitější]. Napiš mi: 1) tři prioritní úkoly pro dnešek, 2) co připravit pro nejdůležitější schůzku nebo úkol.",
    taskTip: "Prompt si ulož do svého druhého mozku — a nastav si ho jako 'ranní rituál'.",
    teaser: "Zítra je poslední den. Závěr, reflexe — a co tě čeká dál.",
  },

  // ─── D28: Závěr + teaser na Advanced (nový) ──────────────────────────────────

  {
    day: 28,
    title: "28 dní. Co ti zůstalo — a co tě čeká dál.",
    subject: "Závěr Basic challenge. Co si odneseš.",
    preheader: "Konec základů. Začátek systémů.",
    concept: [
      "Dvacet osm dní je za tebou.",
      "Prošel/a jsi základy: AI-first přístup, výsledek vs. aktivita, OHIO princip, kvalita zadání, Prompt Generator, V1 a iterace, Tone of voice, Leverage matice, šablony, opakující se práci, druhý mozek a ranní rituál. A — nejdůležitější — způsob přemýšlení o práci, který ti zůstane, i když AI přestaneš používat.",
      "Co si odneseš z Basic challenge:",
      [
        "Dobrý prompt = role + cíl + kontext + omezení + formát — a proč každá část záleží",
        "Iterace jako způsob práce — první výstup je základ, ne finální produkt",
        "Opakující se práce jako signál pro šablonu nebo workflow",
        "Druhý mozek — kde ukládat výstupy, aby nezmizely",
        "AI návyk jako rutina, ne motivace — malý, pravidelný, vázaný na den",
      ],
      "Co přichází v Advanced verzi challenge:",
      [
        "3C framework: Capture, Clean, Connect — systém pro práci s informacemi a znalostmi",
        "PACT framework: Projects, Agents, Context, Tools — jak AI zapojit do projektové práce",
        "Pět superschopností, které AI spoluprací získáváš — Perception, Intelligence, Memory, Creation, Connection",
        "Leverage na úrovni systému — workflow, týmové nasazení, end-to-end procesy",
      ],
      "Basic challenge tě postavila na nohy. Advanced challenge tě naučí běžet.",
      "Ale teď — zastav se a oslav, co je za tebou. 28 dní, 5–7 minut denně. To není samozřejmost. Většina lidí to nikdy nedodělá.",
    ],
    taskIntro: "Poslední úkol challenge — závěrečná reflexe:",
    taskItems: [
      "Tři největší poznatky z celé challenge — konkrétní, ne obecné",
      "Jedno místo, kde AI změnila způsob, jak pracuješ — konkrétní výstup nebo rutina",
      "Jeden cíl pro příštích 30 dní — co budeš dělat jinak s AI, specificky",
    ],
    taskType: "ol",
    taskTip: "Závěrečnou reflexi ulož do svého druhého mozku — za 3 měsíce si to přečti a uvidíš, jak daleko jsi.",
    teaser: "Advanced challenge: 3C, PACT, Superschopnosti — a systémy, které pracují za tebe.",
  },
];
